### ISSUE TITLE
Translations not display properly in modifier-type.ts 

### ISSUE THREAD

**Issue by Adri1** [pagefaultgames/pokerogue#1003]
The text related to TempBattleStatBoosterModifierType in modifier-type.ts doesn't display tranlsated stats (Should be "Atq. Spé." here in French)
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/4685e99b-2cb2-46f9-b84f-00e6300c8ef7)

Also about AttackTypeBoosterModifierType still in modifier-type.ts, types are not translated either (Should be "Fée" here in French)
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/0cc562aa-918f-46d9-aea3-f47f0478f1bb)

**Comment by CodeTappert** [comment]
This was fixed in [#2264](https://github.com/pagefaultgames/pokerogue/pull/2264)
