### ISSUE TITLE
Can't finish daily run

### ISSUE THREAD

**Issue by LouBtl** [pagefaultgames/pokerogue#1018]
Hi,
I never had this issue before today (2024-05-17): when I last hit the boss from the daily run at level 50, I get the fading screen, the victory music and... I get stuck on the black screen. I tried refreshing the page, I don't get the rewards, and I have the game in my save files as if I didn't finish it. I can beat the boss again and get the same black screen. I tried on both my Chrome browser on my phone and on my laptop, same issue. I didn't have any issue through my run.
Any idea how I could fix it?

**Comment by LouBtl** [comment]
![Screenshot_20240517_090908](https://github.com/pagefaultgames/pokerogue/assets/44314766/5a4eea5a-f77f-4e6b-be5c-93734877cf00)
Here's the screen on my phone.

**Comment by Vowow** [comment]
I have exactly the same issue

**Comment by TempsRay** [comment]
Should have been fixed with https://github.com/pagefaultgames/pokerogue/commit/10437142b60b1049b4abd65f6d6d6b06afb1210c try clearing your cache and refreshing
