### ISSUE TITLE
Intimidate not working after page refresh

### ISSUE THREAD

**Issue by hightowernl** [pagefaultgames/pokerogue#1024]
If you go from a single battle to a double battle and your 2nd Pokemon has Intimidate it will trigger the Intimidate (before the game asks you to switch or scan IVs, which is probably the problem)
But anyway, this way Intimidate works, but....
If you refresh your browser, the game probably didn't save the information that you just sent out your 2nd Pokemon after a single battle. So Intimidate no longer triggers. 
This gives the player a bigger disadvantage as usually you refresh because the battle didn't work out and you failed. But without that Intimidate on the next try the battle will be even harder.

Also because Intimidate triggers before the game asks you to switch or scan IV's it's possible to Intimidate the opponent and switch out while the battle didn't even start. Giving the player an advantage.

**Comment by 0zuzu** [comment]
I have a detailed explanation of this bug in #1005
