### ISSUE TITLE
Translation in modifiers for moveType is missing something

### ISSUE THREAD

**Issue by karl-police** [pagefaultgames/pokerogue#1032]
https://github.com/pagefaultgames/pokerogue/blob/main/src/locales/de/modifier-type.ts#L58

![image](https://github.com/pagefaultgames/pokerogue/assets/12023782/83befd56-0ae0-4043-affa-ea4a06b49dca)

See
> Fireattacken

**Comment by CodeTappert** [comment]
Yes because for whatever reason in this commit https://github.com/pagefaultgames/pokerogue/commit/3cc9c93643a496f35e9333a43b5776e4f4d27531 the guy changed where the moves are without updating all references to it... I wil fix it

**Comment by CodeTappert** [comment]
![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/8177b6dc-26fe-46ba-8d78-9a2f5640222a)

![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/8f0aa5d7-d63f-4a3f-a090-c84365fb5efd)


It works fine with the current version on main...

**Comment by CodeTappert** [comment]
Maybe it should be `Feuer-Attacken` but right now it translated the entry as it should
