### ISSUE TITLE
Shell Bell bugged, fixed on reload

### ISSUE THREAD

**Issue by pedwards95** [pagefaultgames/pokerogue#1045]
Currently shell bell has a bug for me where it barely heals anything, and then when I reload the page, suddenly the health is higher. I *think* this is an interaction with multilens, but I do not know this for sure.

1 HP after 1 shotting the enemy:
![abb4b731045ef7a98bea4005f556aad2](https://github.com/pagefaultgames/pokerogue/assets/61423556/23db3b7d-2bce-4719-a68f-af4cae4b7847)

After shell bell and 2 berries proc (sitrus and enigma) (no leftovers):
![6cf2b265dd036dcc20b1b685bfe2bcd7](https://github.com/pagefaultgames/pokerogue/assets/61423556/7f1e7755-9d0b-4666-93b7-cf184e90b757)

Start of next battle:
![0a462ca4d60f0902d3255fffefcdbf69](https://github.com/pagefaultgames/pokerogue/assets/61423556/3b0c0955-a5c7-4fd1-9bd4-26f045720111)

After refreshing the page:
![ff78dd520d457ab6fd377c800caa1a14](https://github.com/pagefaultgames/pokerogue/assets/61423556/6fa0ab85-08de-42d5-ad6c-500e90c8e5fd)

**Comment by pedwards95** [comment]
Extra, next battle. This bug is consistent, and the difference in full hp vs hurt effects the shop item pool.

![efcd3f645bf74f4c0b3309603ca7cd6f](https://github.com/pagefaultgames/pokerogue/assets/61423556/c2b1348a-1645-4c9b-8a10-696248f66a54)
![7977f2f828cf6991075e6660a0d227e5](https://github.com/pagefaultgames/pokerogue/assets/61423556/7893064b-f1bf-4fa6-9761-30807dc355fb)
![7b20a9f4b37442f29cabfb2fb1fcc827](https://github.com/pagefaultgames/pokerogue/assets/61423556/f39386be-8f37-40b2-a827-c760f353e262)

**Comment by VictorGiraud** [comment]
Looks broken to me too - on my tail glow lanturn, barely heals anything after set up.

**Comment by ArcaneWeasel** [comment]
I am encountering this bug as well.

**Comment by innerthunder** [comment]
Closing this as it seems to be fixed now, likely due to changes to multi-hit logic from a while back (e.g. #1420 )

https://github.com/user-attachments/assets/c3d975d3-96e2-4aa0-8a36-a5282c074808
