### ISSUE TITLE
Full Restore does not heal confusion

### ISSUE THREAD

**Issue by stendler** [pagefaultgames/pokerogue#1054]
Full Restore, and by the looks of the code Full Heal as well, do not heal confusion, but they should - at least to my memory of the games and Bulbapedia:

https://bulbapedia.bulbagarden.net/wiki/Full_Heal
https://bulbapedia.bulbagarden.net/wiki/Full_Restore

**Comment by CodeTappert** [comment]
Yes it should also cure confusion. Only in first gen it didnt

**Comment by EvasiveAce** [comment]
I think I have a fix, I'll make the PR here in a second with video proof of testing.
