### ISSUE TITLE
Vital throw hits Pokemon that are Digging

### ISSUE THREAD

**Issue by danmikhail** [pagefaultgames/pokerogue#1058]
1. Excedrill Digs [is underground]
2. Machamp plays Vital Throw
3. Vital Throw hits

Intended behavior:
3. Vital Throw misses

**Comment by rayanzmn** [comment]
https://github.com/pagefaultgames/pokerogue/assets/129906641/3667ce17-9168-4291-8b0f-047387dd7ca9

I seem to be unable to recreate the bug. Do you believe there's something more specific that's triggering it?

**Comment by TempsRay** [comment]
Machamp has no guard which hits even if the opponent is underground.
