### ISSUE TITLE
HOW TO DELAY CommandPhase

### ISSUE THREAD

**Issue by karl-police** [pagefaultgames/pokerogue#1062]
I am in 100 Discord servers and I need to leave one, so I am just gonna ask my question here, also it's on a freaking lockdown, for whatever reason, idk.

I tried to join with my alt, but the dev channel was locked to a role and I couldn't be bothered.

&nbsp;

How can I **interrupt** a **CommandPhase** properly?

If I do it wrong, I get this.

![image](https://github.com/pagefaultgames/pokerogue/assets/12023782/60b2d575-d71a-43cd-bc1a-9fdee57cbaeb)

&nbsp;

I just want to push a Phase above the CommandPhase.

But if I use ``end()`` on the CommandPhase or ``scene.shiftPhase()`` it will trigger the ``EnemyCommandPhase``...

so far I was able to push a phase above the **CommandPhase**. But the thing is it breaks the CommandPhase.

&nbsp;

If I use ``.start()`` it starts the phase I pushed above the CommandPhase, but then quickly also starts the CommandPhase again for some reason.

**Comment by karl-police** [comment]
I think the reason on why I am getting this issue is, because it's tied to **``TurnStartPhase``**... 🤔 

I didn't want to share what I am trying to do. Put I am trying to force put ScanIv Phase.

Otherwise, I am just gonna leave it as a prompt, to toggle it, without the option to force trigger it. That's what I am trying to do, but I didn't want to mention it until I'd have made the pull request for it tbh.

**Comment by karl-police** [comment]
I believe pushing that Phaser scene back just will cause issues regardless of what you do, because it was intended to work in a specific way.

**Comment by Tempo-anon** [comment]
Did you end up getting your answer? Cleaning up open issues so if you still have any questions please hop back into dev-corner to ask about it
