### ISSUE TITLE
Quick Claw with Galarica Cuff sprite

### ISSUE THREAD

**Issue by Adri1** [pagefaultgames/pokerogue#1065]
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/417ea471-771a-43f2-9200-b5e52c11825a)
"Vive Griffe" meaning "Quick Claw", but with Galarica Cuff sprite.
I checked the translation in the French locale **modifier-type.ts** file and the issue doesn't come from here

As I saw this on a French live Twitch, I got no more precisions about this. So idk if it's a Quick Claw with a wrong sprite, or a Galarica Cuff with the wrong name

**Comment by Dakurei** [comment]
When I tested adding a ball to the game, I had a similar display when the image atlas wasn't up to date, so I guess the item image was added, but the atlas wasn't redone 🤔

**Comment by Madmadness65** [comment]
It's an issue with an outdated image cache. Reloading it with something like Ctrl-F5 should fix it.
