### ISSUE TITLE
https://lichess.org/fXEamFVZ

### ISSUE THREAD

**Issue by pokerogue** [pagefaultgames/pokerogue#1067]
Join up please.

**Comment by Lisianthus1228** [comment]
Can we golf instead

**Comment by Madmadness65** [comment]
Please don't post spam in the game's GitHub Issues.

**Comment by f-raZ0R** [comment]
y'all if you want to do something in these github issues why not contribute to the game that would be cool and swag

go all out and make a pr
implement master ball tier item that transes your pokemon's gender or something

**Comment by f-raZ0R** [comment]
(okay but actually it'd be better to do something thats good for the game please don't actually write that pr unless you can come up with a way to make it actually fit and not be a dead draw. in which case thatd be kinda cool honestly)
