### ISSUE TITLE
 [Bug] Missing an AoE move on one of the two targets makes Multi Lens only apply 1 hit on the other one

### ISSUE THREAD

**Issue by jaimefd** [pagefaultgames/pokerogue#1071]
Using Kyurem with Blizzard in my endless run I consistently noticed that if I hit Blizzard in double battles against only 1 target, the miss stops the extra 3 hits multi lens should give me (he has max multi lens and max wide lens)

**Comment by innerthunder** [comment]
This was fixed a while ago with #2648
