### ISSUE TITLE
If a pokemon fussion beats classic, only base species gets the ribbon.

### ISSUE THREAD

**Issue by ReneGV** [pagefaultgames/pokerogue#1072]
Desired behavior:
- Both species should get the ribbon.
- You should get 2 5x tickets if you complete classic for first time with both species.
- You should get 1 5x tickets if you complete classic for first time with only one of both species.
- You should get 0 5x tickets if you have already completed classic with both species

**Comment by TempsRay** [comment]
This is not a bug since the current behavior is intentional. This is a suggestion.
