### ISSUE TITLE
Fell Stinger is not working correctly

### ISSUE THREAD

**Issue by GabRipriel** [pagefaultgames/pokerogue#1077]
The move fell stinger isn't increasing the attack stat after using it. I had this problem in a classic run with beedrill. I believe is a move problem but i didn't try it with another pokemon to confirm it.

**Comment by bennybroseph** [comment]
It only does so if you knock out a Pokemon with the resulting damage.

[source](https://bulbapedia.bulbagarden.net/wiki/Fell_Stinger_(move))
