### ISSUE TITLE
Locally Hosted Configuration has CORS conflict with API

### ISSUE THREAD

**Issue by athias** [pagefaultgames/pokerogue#1078]
Locally Hosted in this context refers to running from source, using `npm run start:dev`

It's been reported already in discord that the game fails to run the `GameOverPhase`, although the source of the issue was unknown.  I ran into this issue and identified the source/conflict preventing it from loading properly.

Essentially the game is attempting to run the `api.pokerogue.net`, specifically: `Access to fetch at 'https://api.pokerogue.net/savedata/newclear?slot=0' `

The source of this is caused when the individual connects via the Network option instead of localhost.  This causes the `utils.ts` to not recognize it as being run locally, specifically `localhost`

To resolve this issue locally I modified the `src/utils.ts` line 218 to include my hosted IP address in the secondary option of the `window.location.hostname`

This example uses `10.10.10.10` as my hosted IP
```
export const sessionIdKey = 'pokerogue_sessionId';
export const isLocal = window.location.hostname === 'localhost' || window.location.hostname === '10.10.10.10';
export const serverUrl = isLocal ? 'http://localhost:8001' : 'http://10.10.10.10:8001';
export const apiUrl = isLocal ? serverUrl : 'https://api.pokerogue.net';
```

**Comment by IceFire03** [comment]
Would it make more sense to check if the hostname != pokerogue and set the serverUrl based on the hostname, then?

**Comment by athias** [comment]
Initially I tried to add in some overrides to define locally hosted server configs and have `utils.ts` simply update accordingly.  Unfortunately I probably don't know enough JS to get it working properly because I ran into some clear formatting issue.

**Comment by CodeTappert** [comment]
Wouldnt 

```ts
// Check if the current hostname is 'localhost' or an IP address, and ensure a port is specified
export const isLocal = (window.location.hostname === 'localhost' || 
    /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/.test(window.location.hostname)) && 
    window.location.port !== '';

// Set the server URL based on whether it's local or not
export const serverUrl = isLocal ? `${window.location.hostname}:${window.location.port}` : '';
```

not be enough?

So it is local if run on localhost or some IP with a port no matter what. And this should also fix the serverURL as far as i know

**Comment by IceFire03** [comment]
Yeah that makes sense to me

**Comment by athias** [comment]
> Wouldnt
> 
> ```ts
> // Check if the current hostname is 'localhost' or an IP address, and ensure a port is specified
> export const isLocal = (window.location.hostname === 'localhost' || 
>     /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/.test(window.location.hostname)) && 
>     window.location.port !== '';
> 
> // Set the server URL based on whether it's local or not
> export const serverUrl = isLocal ? `${window.location.hostname}:${window.location.port}` : '';
> ```
> 
> not be enough?
> 
> So it is local if run on localhost or some IP with a port no matter what. And this should also fix the serverURL as far as i know

I tested this fix on my setup and had no issues using the network address and completing the area where it previously failed:

![Screenshot from 2024-05-18 16-20-35](https://github.com/pagefaultgames/pokerogue/assets/18584449/260318dc-1c47-4b10-b4eb-f77f09524462)

**Comment by CodeTappert** [comment]
Then please create a Pull Request with this change! 
(And maybe give some credit to me by linking my comment with the suggestion in it)

**Comment by IceFire03** [comment]
@CodeTappert I think it would be best for you to make the pull request and link it to this issue seeing as it's your code :)

**Comment by CodeTappert** [comment]
Well then i will do that in like 9h or so. After i slept

**Comment by CodeTappert** [comment]
@IceFire03 See https://github.com/pagefaultgames/pokerogue/pull/1122
