### ISSUE TITLE
[BUG] Protect doesn't count throwing a pokeball as a turn

### ISSUE THREAD

**Issue by pedwards95** [pagefaultgames/pokerogue#1079]
Steps to reproduce:
- Turn 1: Use protect
- Turn 2: Throw a pokeball (any)
- Turn 3: Use protect

Expected: Protect works
Actual: Protect has a high chance to fail

**Comment by TempsRay** [comment]
That's an intentional feature so you can't just alternate between throwing pokeballs and using protect

**Comment by pedwards95** [comment]
... what? Why? You can do that in any other pokemon game.

**Comment by IceFire03** [comment]
Yeah, i'm also confused -- it's not like the Pokemon can't attack if you throw a ball, so I'm not sure why it would be neccessary

**Comment by bennybroseph** [comment]
Not only has this been posted before, but it's how the mainline games already behave. I booted up S/V just to test it the last time and this was the result.

https://github.com/pagefaultgames/pokerogue/assets/13838608/85060aab-0df2-4efb-abb5-58b7255ff915

In the future, please provide a source of some kind before posting an issue.

**Comment by bennybroseph** [comment]
For reference https://github.com/pagefaultgames/pokerogue/issues/803

**Comment by pedwards95** [comment]
Alright then. Sorry.

**Comment by bennybroseph** [comment]
No worries, it's not something you'd really do in a regular playthrough so I understand the confusion. Just don't want the first thought be posting issues here before searching is all.
