### ISSUE TITLE
Save Data for one full day missing

### ISSUE THREAD

**Issue by Vedviing77** [pagefaultgames/pokerogue#1098]
Save data for the entirety of May 17, 2024 seems to be missing. I don't know what may have happened. I left work, closed my computer out, and pulled up Pokerogue on my phone this morning only for everything I achieved yesterday to not appear. Any help would be appreciated.

**Comment by XGSleepWalker** [comment]
Have you checked your computer to see what save loads in there?

**Comment by Vedviing77** [comment]
I’m going to sound not so smart but how would I do this? Just go to export —> save?

**Comment by Vedviing77** [comment]
> Have you checked your computer to see what save loads in there?

I’m not going tk sound smart here but how do I do this? I assume I go to export —> save??

**Comment by Vedviing77** [comment]
> Have you checked your computer to see what save loads in there?

Would also like to say I came into the office this morning (its a small town) and decided to fire it up and see if anything happened to have been retained and there's NOTHING from yesterday either on the PC or the phone

**Comment by espen1004** [comment]
I'm also missing data, a lot of starters are suddenly not available to start with anymore, even ones I just used in my previous run. Account name is Borealiz save file attached if it helps.

[data_Borealiz.txt](https://github.com/pagefaultgames/pokerogue/files/15367017/data_Borealiz.txt)

**Comment by Tempo-anon** [comment]
Data loss should no longer be an issue with the changes made to the server, as well as upcoming oauth. Please open another issue in the future if you get any data loss.
