### ISSUE TITLE
Epic Shiny Spewpa evolving soft locks the game

### ISSUE THREAD

**Issue by PhantomCrystal** [pagefaultgames/pokerogue#1099]
Whenever I try to evolve my Epic Shiny Spewpa the game is forever stuck on "What? Spewpa is evolving!" screen. Regular Spewpa evolves just fine. Kind of sucks that my Epic Shiny is one I can't even use.

**Comment by karl-police** [comment]
Are you on Browser, where you can access the Developer Console through SHIFT + I + F12, and then go to Console. But only screenshot errors.

**Comment by PhantomCrystal** [comment]
I am on Browser but Shift + I + F12 doesn't work, do you mean F12?
![Bugged](https://github.com/pagefaultgames/pokerogue/assets/169913158/3076a7fb-95d2-4019-bdda-dd58742ad9ba)

**Comment by PhantomCrystal** [comment]
Better picture
![Console](https://github.com/pagefaultgames/pokerogue/assets/169913158/d5b6a7e6-9dac-42de-bb63-7b0769dde9fe)

**Comment by geefuoco** [comment]
> Whenever I try to evolve my Epic Shiny Spewpa the game is forever stuck on "What? Spewpa is evolving!" screen. Regular Spewpa evolves just fine. Kind of sucks that my Epic Shiny is one I can't even use.

Is there any more information you can provide about your game ? I was not able to reproduce the issue

https://github.com/pagefaultgames/pokerogue/assets/87877876/f4b379c6-0851-4d95-92b9-8c4b3226f21f

**Comment by PhantomCrystal** [comment]
> > Whenever I try to evolve my Epic Shiny Spewpa the game is forever stuck on "What? Spewpa is evolving!" screen. Regular Spewpa evolves just fine. Kind of sucks that my Epic Shiny is one I can't even use.
> 
> Is there any more information you can provide about your game ? I was not able to reproduce the issue
> 
>  pokerogue_spewpa_evolution.mp4

It's not a browser problem because it also soft locks the game on my phone as well. Maybe it's my account that's bugged?

**Comment by chacolah** [comment]
Known issue, we have a few PRs awaiting merge that will fix this.
