### ISSUE TITLE
My Kirlia didn't evolve into a Gardevoir?

### ISSUE THREAD

**Issue by Thesgtkirby** [pagefaultgames/pokerogue#1100]
My male Kirlia didn't evolve into a Gardevoir, instead they were just evolved into a Gallade. I don't know how this happened, but I'm sure it's just a mistake because I know something this silly wouldn't be intentionally made.

**Comment by ShinyZoroark** [comment]
Kirlia evolution is gender-based in Pokerogue

**Comment by Xavion3** [comment]
Duplicate of #1101
