### ISSUE TITLE
Shiny sprites are not appearing shiny

### ISSUE THREAD

**Issue by Nbertelsen** [pagefaultgames/pokerogue#1120]
Shiny Pokémon are not appearing as their shiny sprites and are instead appearing with their regular sprites. I've tried logging out, clearing my browsing history, I even tried using a different browser on a different device but nothing seems to fix this bug. 

In the attached picture you can see my shiny conkeldurr has it's regular sprites but still shows the shiny symbol by the name. Any insight would be helpful.
![Screenshot_20240518_204659_Chrome](https://github.com/pagefaultgames/pokerogue/assets/46724789/935128ed-b583-47b3-8cbb-aeb9d52161ea)

**Comment by j-diefenbach** [comment]
There was a recent pull request merged that shows default sprites for malfunctioning / missing shiny sprites. Could have something to do with that, i’m guessing since this is endless this was working fine before that

**Comment by chacolah** [comment]
my PR #1116 should fix this since we lacked jsons for some mons sprites and I generated a bunch we needed, just waiting on review/ approval.

**Comment by washedszn** [comment]
Happened on Conkeldurr too, @chacolah in case he's missing from the ones you generated 

![image](https://github.com/pagefaultgames/pokerogue/assets/48860738/6398dcb7-44e4-45a6-97dc-e37a2af20c16)

**Comment by jaimefd** [comment]
Can confirm, was about to post an issue on this too. My shiny lokix who was perfectly working before now doesn't look shiny
