### ISSUE TITLE
Linux executable for retro handhelds

### ISSUE THREAD

**Issue by shim80** [pagefaultgames/pokerogue#1127]
Hello
Yout game is awesome !
Don't you think it's would be even more awesome to play it on handheld retro console ?! (aka anbernic devices, see [here](https://anbernic.com/collections/handheld-game-console?gad_source=1&gclid=Cj0KCQjwxqayBhDFARIsAANWRnSETyMTQSsK2DWg6aXdFuqCnAH_HggNx1VOx8UgtrzXkJr-3sM7nO8aAvdVEALw_wcB) )
This game look like it would be perfect for this kind of size, with physical control !

For now, this game is currently only accessible via a web browser. But most of retro handhelds (the ones that ship with linux) doesn't have web browser, although they can connect to the Internet via Wi-Fi.

Do you think there would be a way to port your game as linux executable?
Theses devices run on 4 core aarch64 soc, 1gb ram and OpenGL ES 3.2 compatible GPU

There's a team called Portmaster that work on porting PC games for these devices, they've already ported a lot of indies (mostly low end 2D games), you can see the full list here: https://portmaster.games/games.html

Thanks in advance ;)

**Comment by bennybroseph** [comment]
No current plans for something like this. We don't have a Windows executable either for the same reason.

**Comment by shim80** [comment]
> We don't have a Windows executable either for the same reason.
Well, Windows doesn't need it since Windows alway ship with web browser...

I'm not talking about doing a full game executable, just a sh file that launch the necessary files with required libraries.
I don't know, maybe using Electron or Nativefier (I'm not developer)... 
We just need to make sure that this will work on aarch64

**Comment by bennybroseph** [comment]
well, the project is open source. feel free to develop this feature and make a Pull Request so that we can get this in

**Comment by bennybroseph** [comment]
https://github.com/Odizinne/Pokerogue-Standalone

**Comment by shim80** [comment]
Nice !
There's no aarch64 support yet, but it's a start
