### ISSUE TITLE
Soul Dew max stacks is too high

### ISSUE THREAD

**Issue by zizibaloob** [pagefaultgames/pokerogue#1132]
Soul Dew currently has a max held item count of 10. Because it is additive with the existing +/- 0.1 from the pokemon's nature, this means that at 10 stacks the pokemon gets +110% to the beneficial stat but only -100% (then rounded up to 1) to the sacrificial stat.

With a max held item count of 9, they would both be +/- 100%.

**Comment by bennybroseph** [comment]
Logistically, there's less issue with giving the player a free +10% stat boost rather than:

- Reducing the stack size to a non-even number
or
- Making each stack worth 9%

I don't see any reason to do either of these at the moment. The +10% for free seems fine.
