### ISSUE TITLE
Cannot actually start first run.

### ISSUE THREAD

**Issue by LazerKN** [pagefaultgames/pokerogue#1133]
![Screenshot (30)](https://github.com/pagefaultgames/pokerogue/assets/170269386/3ff24b57-001e-43b5-a04d-bda1754c0932)

So anytime I try to open the game it first comes up with a black screen that doesn't change and after refreshing the page it will finally start and let me choose my starters and begin the game.  The second issue arises when I try to actually play the game.  Whether I choose to hit or switch Pokemon, as soon as I make a move the game soft freezes.  It doesn't physically freeze but neither the move or the pokemon switches in.  Wondering if there is any fix I can do and the attached photo is in reference to what happens after I make a move.  Nothing happens it just sits on that screen doing nothing.  Thank you for your time.

**Comment by TempsRay** [comment]
Open the console with F12 and post the error logs

**Comment by LazerKN** [comment]
> Open the console with F12 and post the error logs

![Uploading Screenshot (31).png…]()

**Comment by LazerKN** [comment]
> Open the console with F12 and post the error logs

![Screenshot (31)](https://github.com/pagefaultgames/pokerogue/assets/170269386/e56c6945-c6f6-4a68-b661-7b95ebdc0680)

**Comment by Tempo-anon** [comment]
It has been 3 weeks so closing this. Let us know if issue persists.
