### ISSUE TITLE
bypassFaint flag of abilities appears non-functional

### ISSUE THREAD

**Issue by Xavion3** [pagefaultgames/pokerogue#114]
Discovered while implementing the ability changing abilities. Rough Skin, Iron Barbs, Mummy, and so on don't appear to actually trigger when the pokemon with the ability is KO'd, even though they should.

**Comment by mattrossdev** [comment]
https://github.com/pagefaultgames/pokerogue/pull/134

**Comment by Flashfyre** [comment]
@Xavion3 Can you confirm this is fixed?

**Comment by Procyonae** [comment]
It worked during testing of #199
