### ISSUE TITLE
[Suggestion] Unlocking Egg Moves with Candy

### ISSUE THREAD

**Issue by lloyd-delacroix** [pagefaultgames/pokerogue#1146]
Wanted to open a discussion on the possibility of expanding the candy options to include unlocking a new egg move. The cost would have to be high enough to not negate Move Up Egg Gatcha, but provide a way to target favorite 'mons. As a starting point, using the passive unlock costs per unlocked egg might be reasonable, though it might need to be higher for the epic / legendary tiers or have some sort of increasing cost scaling per move unlocked.

**Comment by lloyd-delacroix** [comment]
Added PR with sample implementation. #1147

**Comment by jsalts** [comment]
As an avid player, I cannot wait to unlock egg moves with candy.

**Comment by JoannaFalkowska** [comment]
IIRC Discord is a better place for a suggestion/balancing discussion, if you didn't start a thread there already.
