### ISSUE TITLE
[Contribution] I made a custom cursor 

### ISSUE THREAD

**Issue by Odizinne** [pagefaultgames/pokerogue#1154]
I made a custom cursor for my Pokerogue electron app<br/>
I'm not sure this is something you would like to add, but i can share it to you.

![PR_cursor](https://github.com/pagefaultgames/pokerogue/assets/102679854/876a10c0-adc2-425b-bdeb-ffc52c340978)

I tried to respect logo color palette.<br/>
The cursor is 64x64, i found 32x32 is a bit too tiny for this game.

If you like it and want to use it for pokerogue.net, feel free to do so!

**Comment by torranx** [comment]
This is nice @Odizinne ! I tried to place this cursor but the size is a bit too large for my liking, for reference:

https://github.com/pagefaultgames/pokerogue/assets/68144167/100f1bb2-7acc-4aa2-894a-dde8b6027f28

If you'd like, I can make a PR for this, otherwise go for it!

**Comment by Odizinne** [comment]
![PR_cursor](https://github.com/pagefaultgames/pokerogue/assets/102679854/dbd43a56-b986-4b9d-80c3-8527060553fc)

Here is the 32x32 version if you prefer

**Comment by torranx** [comment]
Here's the 32x32 in action:
My opinion is that the 64x64 is giving out too much attention, that's just me tho. Let me know what you think.

https://github.com/pagefaultgames/pokerogue/assets/68144167/7ed58e65-b250-4014-9341-13ccc2a17556

**Comment by Odizinne** [comment]
Your go is my go. In my app i hide cursor on idle, so size is not a real problem, but i think you're right, 32x32 is more appropriate for a website!

**Comment by torranx** [comment]
PR opened, let's see if others like it. Added attribution for you in commit message @Odizinne

**Comment by torranx** [comment]
Actually let me add it to the readme

**Comment by torranx** [comment]
PR closed, please refer to my [comment](https://github.com/pagefaultgames/pokerogue/pull/1157#issuecomment-2120109400).

**Comment by Tempo-anon** [comment]
The PR is closed but we really appreciate your effort and contribution!
