### ISSUE TITLE
Disable on 2 turn attacks

### ISSUE THREAD

**Issue by hightowernl** [pagefaultgames/pokerogue#1158]
Disable is working on 2 turn attacks. I've done it on Sky Attack, probably works on the others as well.

Instead of the game saying something like "Pokemon X is glowing" it says "Pokemon X is using Sky Attack," then it's possible to Disable and the Pokemon can't finish their move.

I think in the regular games Disable doesn't work while charging as It's not recognised as move yet.

**Comment by bennybroseph** [comment]
Do you have a source on that?

**Comment by jatinkohli** [comment]
I just checked in showdown, using disable against a 2 turn attack seems to work the same as using disable against any other move. 

https://replay.pokemonshowdown.com/gen9anythinggoes-2135916708
