### ISSUE TITLE
The move Dive doesn’t work properly

### ISSUE THREAD

**Issue by Veenstra888** [pagefaultgames/pokerogue#1159]
I just noticed the move Dive doesn't have a (P) yet when used, you're still vulnerable when you should be semi-vulnerable (only vulnerable to Surf and Whirlpool). Currently my Dewgong gets hit by fighting-type moves while under water.

**Comment by bennybroseph** [comment]
[No Guard](https://bulbapedia.bulbagarden.net/wiki/No_Guard_(Ability))

**Comment by Veenstra888** [comment]
That explains it. Thanks!
