### ISSUE TITLE
Abilities that prevent sleep don't show the pop-up banner

### ISSUE THREAD

**Issue by Eridanus91** [pagefaultgames/pokerogue#1160]
When an ability is relevant, it will pop up on screen, like Fur Coat reducing damage or Early Bird reducing amount of sleep turns.

Except things like Insomnia or Vital Spirit preventing target from falling asleep. The move will just silently fail.

**Comment by Snailman11** [comment]
Should be Fixed by https://github.com/pagefaultgames/pokerogue/pull/3265 (Add missing changes from sweet veil PR)
