### ISSUE TITLE
Cloudflare is buggy

### ISSUE THREAD

**Issue by FuecocoBoi09** [pagefaultgames/pokerogue#1166]
I cannot access PokeRogue as the Cloudflare login stays without resolving. Please try to fix this or remove Cloudflare.

https://github.com/pagefaultgames/pokerogue/assets/169853299/c3236714-71ae-44ef-a8c0-1808d4ef34ab

**Comment by chacolah** [comment]
This is most likely an issue with cloudflare itself which we can't really fix on our end, and we aren't going to open the game up to ddos and other similar attacks by removing it.

**Comment by danieland** [comment]
Are you by any chance using Telekom as your ISP @FuecocoBoi09  ?

**Comment by FuecocoBoi09** [comment]
I have securly on my ipad
