### ISSUE TITLE
Missing Shinys/Data

### ISSUE THREAD

**Issue by duck90hunter** [pagefaultgames/pokerogue#1167]
Ran into an issue on 5/19 when switching between my phone and my laptop. Spent the evening of 5/18 catching shinys (and a few legendries) on an endless run during the shiny weekend on my phone. I performed multiple save and quits and reloads of the page and had no issues. Around 11 PST on 5/19, I switched from my phone back to my laptop. My save file had my current wave and I thought nothing of it. However, at around 5 PM PST (when shiny event ended) I went to start a new classic run and discovered that none of the shinys I'd caught the night before were available as starters, including nearly all the ones still on my endless team. I think what happened is the laptop re-hatched some eggs that had hatched on my phone the night before and it somehow reset my catches to the last time the laptop had been used but still saved the endless wave progression?

Can the catch data lost be recovered? Would unsplicing fusuions I still have in the endless party add them as starters and get the candies due for them? I sent a bunch of screenshots to my brother and while I know there were other things caught, I am currently missing the following at minimum.

Lvl 3 Shiny Ninjask (currently on team)
Candies for 3 Lvl 1 Machamps (caught them in a row, caught one later which unlocked but missing candies)
Lvl 1 Kingambit w/ HA (Currently on team)
Lvl 1 Fearow
Lvl 1 Hypno w/ HA
Lvl 3 Breloom (Currently on Team)
Lvl 1 Beedrill
Lvl 2 Ursaluna (Currently on Team)
Lvl 2 Ursaluna (Currently on Team)
Lvl 1 Sigilyph
Lvl 1 Mawile
Lvl 2 Lilligant
Lvl 1 Malamar w/ HA
Registeel (Currently on Team)
I know I also caught several tink-a-tinks and garnacyls as I had caught few in the past, including a tink w/ HA (already had unlocked). Would like the candies on these but less concerned here.

My account name is Duck90hunter. I caught some great things after the incident (lvl 1 Guzzlord) but losing all of these (especially the lvl 3 red shinys) has been a bitter pill to swallow. Appreciate any help in possibly getting those catches re-added.

**Comment by duck90hunter** [comment]
Here is the snapshots I have that I sent my brother. Didn't send Registeel but you can see him fused to Xearneas in the images. 

![Screenshot_20240520_082511_Messages](https://github.com/pagefaultgames/pokerogue/assets/170334704/9ee9a2aa-0543-49b6-bcd9-8e8290d74832)
![Resized_Screenshot_20240518_212419_Chrome_1716092888678](https://github.com/pagefaultgames/pokerogue/assets/170334704/4f2b38e2-a716-4c23-b980-0a1143116224)
![Resized_Screenshot_20240518_214546_Chrome_1716096758080](https://github.com/pagefaultgames/pokerogue/assets/170334704/75ae13d8-fbec-47fd-b961-229632efc738)
![Resized_Screenshot_20240518_220857_Chrome_1716096763181](https://github.com/pagefaultgames/pokerogue/assets/170334704/466ef51d-d436-422c-8e75-a7395cdd8d49)
![Resized_Screenshot_20240518_220857_Chrome_1716096763181](https://github.com/pagefaultgames/pokerogue/assets/170334704/4509f064-2f45-44c2-9c78-0416fbea2df6)
![Resized_Screenshot_20240518_221307_Chrome_1716096763709](https://github.com/pagefaultgames/pokerogue/assets/170334704/97d25b6d-cafb-4da6-9242-30feba9c1798)
![Resized_Screenshot_20240518_221437_Chrome_1716096764163](https://github.com/pagefaultgames/pokerogue/assets/170334704/371e3949-f768-468a-8e75-1286f5aa771f)
![Resized_Screenshot_20240518_221803_Chrome_1716096766084](https://github.com/pagefaultgames/pokerogue/assets/170334704/6a041644-12a7-4d2c-af82-60ce8236ddb0)
![Resized_Screenshot_20240518_222305_Chrome_1716096766549](https://github.com/pagefaultgames/pokerogue/assets/170334704/f0d60ad5-494b-46d6-ba88-732a11f9413a)
![Resized_Screenshot_20240519_110319_Chrome_1716141929407](https://github.com/pagefaultgames/pokerogue/assets/170334704/c8fbcdd2-37b7-4f4d-90e1-bc094b74b9e2)
![Resized_Screenshot_20240519_084708_Chrome_1716141953378](https://github.com/pagefaultgames/pokerogue/assets/170334704/158cda65-9863-4760-bcf8-4711b3fb2a77)
![Resized_Screenshot_20240519_082824_Chrome_1716141954452](https://github.com/pagefaultgames/pokerogue/assets/170334704/257cab92-6650-4714-bce0-d6457fb3edfb)
![Resized_Screenshot_20240519_111147_Chrome_172851446977809_1716142315974](https://github.com/pagefaultgames/pokerogue/assets/170334704/9db59549-1dcd-4790-b429-4f070f342380)
![Resized_Screenshot_20240519_112720_Chrome_1716144091843](https://github.com/pagefaultgames/pokerogue/assets/170334704/34882759-95fe-4474-969d-25a294c25878)

**Comment by Tempo-anon** [comment]
Data loss in between devices should hopefully no longer be a thing. Open another issue if this problem persists.
