### ISSUE TITLE
Request for adjusting text shadow

### ISSUE THREAD

**Issue by Adri1** [pagefaultgames/pokerogue#1168]
Currently, the text shadow looks like this, with a simple drop shadow to the bottom right:
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/ccdbcf75-68e1-4875-a4b6-8c44a7a361d7)
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/c463aeb2-2770-4e17-99c7-2dd366fd9b3f)

But it should looks like this, to increase lisibility, like it is in Pokémon Emerlald, from where this font comes from:
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/b62ba72c-0f32-40be-9644-052b421255ad)
_(image made manually)_
The shadow should be casted **below**, on the **left** and from the **bottom right** vertex of each pixel. (and also apply it to pkmnems font, not only to this one)

Image from Emerald :
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/77dc50b3-3bfd-468a-ae9b-c6cd4965f093)

So if anyone knows where to edit / knows how / can do it

**Comment by danieland** [comment]
Definitely agree the blurriness isn't helping visibility at the moment - the code for it is here:
https://github.com/pagefaultgames/pokerogue/blob/d2e455cdadbe250bf02ab44b4b885f2cc750429e/src/ui/text.ts#L56

These "setShadow" methods also have slightly misnamed variables attached to them as you're not really setting "shadowSize" but rather the x and y positions:
https://newdocs.phaser.io/docs/3.80.0/focus/Phaser.GameObjects.TextStyle-setShadow

It's pretty simple to edit, I'd rather point you towards it though since I don't have designer-eyes sadly - but even setting "shadowSize" to 3 here instead of 6 is a massive improvement I think personally:
https://github.com/pagefaultgames/pokerogue/blob/d2e455cdadbe250bf02ab44b4b885f2cc750429e/src/ui/text.ts#L89

Probably requires a little tinkering by someone who's good at design and such!

**Comment by Adri1** [comment]
Thanks! I'll try to dig myself then, but if anyone is passing by and know how, feel free to submit your solution

**Comment by Adri1** [comment]
I guess I'll wait until somebody with more skill than me can take over
Blur option, well, blurs the shadow, but noting else and I can't find any way to have something shrap like in the edited image I made.

**Comment by zaccie** [comment]
Current code only used a single value for both x,y co-ordinates so I modified the code to support x,y co-ordinates having separate values if we wanted them, some examples shown:
![dropshadow](https://github.com/pagefaultgames/pokerogue/assets/17427370/9905457f-f39d-46c2-918f-451927cbfd75)

**Comment by zaccie** [comment]
If it looks good to others ( i think anything is better than current) I can PR what I have for others to take a look

**Comment by bennybroseph** [comment]
Yes, a PR would be good. I'll say though as I knew this was the only coding solution that could be done, this could technically affect performance on devices that are already struggling since we are rendering text a third time to achieve this. Definitely like the look of it though. The best solution performance-wise is probably a whole new font that already looks like this though.

**Comment by zaccie** [comment]
> ~Yes, a PR would be good. I'll say though as I knew this was the only coding solution that could be done, this could technically affect performance on devices that are already struggling since we are rendering text a third time to achieve this. Definitely like the look of it though. The best solution performance-wise is probably a whole new font that already looks like this though.~
> 
> I misread. I would still like to see the PR with these changes, though I will admit I'm less excited lol. If someone also wants to add a second drop shadow, that will achieve the effect of this image and is the desired end effect.
> 
> ![image](https://private-user-images.githubusercontent.com/13838608/332358150-086f1a6a-6359-42e3-b55c-d4f10320c70d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODI1MDEsIm5iZiI6MTcxNjI4MjIwMSwicGF0aCI6Ii8xMzgzODYwOC8zMzIzNTgxNTAtMDg2ZjFhNmEtNjM1OS00MmUzLWI1NWMtZDRmMTAzMjBjNzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA5MDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYjlmNzgyMzA4NWQ3NDZlN2ZlMTFmZmYwNTQyMzZlYWI5OWYyMzQzZjNjMWU0N2I0NGUyMmIyNWJjYWVjNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wnXY654otFOeZYJqEVkNxbYDwOJRR4l5-7ZGdwnFOLY)

made a PR here: https://github.com/pagefaultgames/pokerogue/pull/1197
making the text look more like emeralds is hard because the font renderer doesnt seem to support making the drop shadow thicker

**Comment by Adri1** [comment]
> ~Yes, a PR would be good. I'll say though as I knew this was the only coding solution that could be done, this could technically affect performance on devices that are already struggling since we are rendering text a third time to achieve this. Definitely like the look of it though. The best solution performance-wise is probably a whole new font that already looks like this though.~
> 
> I misread. I would still like to see the PR with these changes, though I will admit I'm less excited lol. If someone also wants to add a second drop shadow, that will achieve the effect of this image and is the desired end effect.
> 
> ![image](https://private-user-images.githubusercontent.com/13838608/332358150-086f1a6a-6359-42e3-b55c-d4f10320c70d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODQyMTMsIm5iZiI6MTcxNjI4MzkxMywicGF0aCI6Ii8xMzgzODYwOC8zMzIzNTgxNTAtMDg2ZjFhNmEtNjM1OS00MmUzLWI1NWMtZDRmMTAzMjBjNzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA5MzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NDNlODk1NTM4YzA5ODQ4ZDkxNmQxOThmZGY2ZjI4ODJkZmQwNjVkMDRkZjhjNzM0NGM3ZmYzNjBmYjgwMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.psmwVLAU_et89XeqZbEe_-_1HjR0YPl9iuKZZsCxrbk)

Actually, 3 shadow would be needed. The current one, one to compete the right side and one to compete the bottom side

I tried to add these shadows yesterday, either nothing at all is displayed or only one is considered.

I tried to check for solutions, and one seem to consist in create a new shader to phaser3 that would allow to cast multiple shadows. But this is beyond my skills

**Comment by torranx** [comment]
Resolved in https://github.com/pagefaultgames/pokerogue/pull/1197
