### ISSUE TITLE
Achievements don't reward the vouchers

### ISSUE THREAD

**Issue by Fir3Soul** [pagefaultgames/pokerogue#1171]
I just got a few achievements and on the first one I was like "I think I might be bugged" 
Second acchevement same thing , now on the third I decided to check for the vouchers and they are not rewarded. 

Can I provide Logs or some sort of thing ? I tried checking the network tab for anything but for some reason It's empty ?
Would my Export Data help ?

![image](https://github.com/pagefaultgames/pokerogue/assets/90197053/882e609a-ac31-4d12-9846-d2a8793cbdc2) 

Cheers

**Comment by lockadox** [comment]
The Achievements tab is not supposed to give vouchers, only the Vouchers tab.

**Comment by TempsRay** [comment]
The voucher is only the icon for the achievement. Achievements do not give voucher rewards.
