### ISSUE TITLE
Hide your encryption keys 

### ISSUE THREAD

**Issue by Skorono** [pagefaultgames/pokerogue#1173]
Hi! i`m Listik. 
Now, using your open encryption key, i can change game saves.
Fix this :)

**Comment by CodeTappert** [comment]
But can you also inject them to the online version of the game? If not then this isnt relevant

**Comment by rusHater** [comment]
Weaboo ruski kid didnt realize he’s out of the leaderboard after 5 mins lmao

**Comment by Skorono** [comment]
Game reads session data from local storage, then changing it i can manipulate data

**Comment by CodeTappert** [comment]
> Game reads session data from local storage, then changing it i can manipulate data

Still you only ruin your own fun when doing so. This game has no PVP only PVE.

But you are right. Coding Standard wise its bad practice

**Comment by Skorono** [comment]
By doing this, I have clearly shown that you have specific problems. A few hours after me, there were people who could do exactly the same thing. 
What's the point of a rating if it's so easy to break?

**Comment by Skorono** [comment]
And, yes, it`s no hard to fix

**Comment by CodeTappert** [comment]
> And, yes, it`s no hard to fix

Then create a pr with a fix

**Comment by Skorono** [comment]
Hmm, change env conf on server side, no?

**Comment by bennybroseph** [comment]
@Skorono feel free to ping me once you've created the Pull Request for this, appreciate you agreeing to do this

**Comment by Kiriox94** [comment]
> Hmm, change env conf on server side, no?
> 

If you do this, it will no longer be possible to import the saves to your local version of pokerogue, because the keys will not be the same

**Comment by JoannaFalkowska** [comment]
> But can you also inject them to the online version of the game? If not then this isnt relevant

Yes, you can. I tested this like a week ago.

**Comment by Skorono** [comment]
This is a rather difficult way to reproduce a glitch. The script did all the work for me, but its action can be described something like this: start a gaming session -> read saves from localstorage -> decrypt and modify -> write back -> exit to the main menu. 

Question: if you do not store data on the client side, then do you suggest constantly contacting the server for data? I don't think this is the best solution...
Or did I misunderstand you?

**Comment by Nexllon** [comment]
Here's my 2 cents
You don't prevent any cheating by hiding the encryption keys, you can just debug the code later to intercept it or even edit the information before it's even used, it's pretty futile. The only thing it'll do is break offline mode right now.
Cheat prevention in a client-side game needs a large amount of focus and time to counteract it, as of right now I don't think this change is either necessary (due to metrics that already deal with cheaters) or worth it.

**Comment by JoannaFalkowska** [comment]
I do agree it's not worth it. Players currently don't have a way of interacting between them, besides the leaderboards. Perhaps if cheaters in the leaderboard are too frustrating for some small part of the playerbase, and we don't really even try to prevent this, it would be better to close down leaderboards for now?

**Comment by flx-sta** [comment]
Since this is a client sided game and the only person you are cheating is yourself I don’t see the issue right now. Which doesn’t mean we might come back another time to it
