### ISSUE TITLE
Perish Song persists after forced switch out going from wild double to single battle

### ISSUE THREAD

**Issue by HyperRes** [pagefaultgames/pokerogue#1185]
Scenario:
Wild double battle:
Opposing Flutter Mane uses perish song on Suicune and Terapagos.
Both opposing mons are knocked out and floor is cleared.
The next floor is a single battle, so Terapagos is automatically switched out and a single battle with Suicune and an opposing mon occurs.
Suicune's perish count persists, but if Terapagos is switched in, Terapagos' perish count also persists, despite it being switched out at the start of the battle.

**Comment by JoannaFalkowska** [comment]
I can confirm something very similar happened to me with Perish Song counter getting carried over to another mon.

**Comment by Tempo-anon** [comment]
Should be fixed with #3119
