### ISSUE TITLE
Study Passive on Burmy does not work

### ISSUE THREAD

**Issue by ExcaliburgerDL** [pagefaultgames/pokerogue#1191]
I intentionally unlocked the passive on Burmy, evolved it to Wormadam (Trash Cloak), to bring to endless, to fuse with Purifying Salt Nacli. The Summary screen shows that my fused Wormadam still has the Sturdy passive, however the Sturdy passive ability can never activate.
![Snipaste_2024-05-20_22-18-55](https://github.com/pagefaultgames/pokerogue/assets/170391575/259ffb6d-b63e-414e-98a9-a8933aded2eb)

**Comment by Tempo-anon** [comment]
Cannot replicate. Maybe the ability was suppressed or neutralized? Open another issue with more details if this persists.
