### ISSUE TITLE
Screen freeze at wave 182

### ISSUE THREAD

**Issue by Cheveninho** [pagefaultgames/pokerogue#1196]
When i won the wave 181 my pokemon is gonna switch out and then the screen freeze and i can't do anything. I try to change the way to win the wave 181 but the final is the same.

**Comment by JoannaFalkowska** [comment]
Hey @Cheveninho, do you have some more info? Was this online or offline? What were you doing? Do you still have this problem?

**Comment by Tempo-anon** [comment]
Closing since it has been a while with no update. Let us know if you get frozen in the future with more details so we can debug it.
