### ISSUE TITLE
Tail Glow is not part a of Xurkitree's Level 1 move set when it should be

### ISSUE THREAD

**Issue by Wolfram0305** [pagefaultgames/pokerogue#1199]
A while ago, a lot of moves were added back to level 1 move sets when they were removed from said move set due to the move being cut from gen 8/9. The one edge case that was missed here that I noticed was Xurkitree's access to Tail Glow.

In Gen 7, Xurkitree has access to Tail Glow as a part of its level 1 move set. In gen 8, Tail Glow does not exist in Sword and Shield, presumably due to Manaphy not being available in Sword and Shield, which lead to Tail Glow being cut from Xurkitree's level 1 move set. In gen 9, Tail Glow once again exists, probably due to Manaphy being available in Scarlet and Violet, but Xurkitree did not make it into those games. This means that the final version of Xurkitree's move set from gen 8 does not include Tail Glow, and PokéRogue currently matches the most recent move set it has available to it.

Following the logic of the level 1 moves being restored when the move was cut in the generation the Pokémon features in, I believe Xurkitree should have access to Tail Glow as a part of its level 1 move set.

**Comment by pedwards95** [comment]
This comes from serebii.net, the place where the latest move sets are pulled from. Serabii does not have an entry for Xurkitree past gen 8. That said, gen 8 is the latest generation where Xurkitree can be acquired, so if you revert the moveset back to gen 7, you would have to do that for a lot of different pokemon.

**Comment by jaimefd** [comment]
> This comes from serebii.net, the place where the latest move sets are pulled from. Serabii does not have an entry for Xurkitree past gen 8. That said, gen 8 is the latest generation where Xurkitree can be acquired, so if you revert the moveset back to gen 7, you would have to do that for a lot of different pokemon.

I see this more like combining gen 7 and 8 movesets, which is good, as gen 8 removed a lot of moves that we do have in pokerogue. As op mentioned in the first paragraph this has already been done with some pokemon so it should indeed be done with other pokemon, and starting with Xurkitree is good as it's one case where it makes a great difference

**Comment by EvasiveAce** [comment]
Ill take a look if its not fixed

**Comment by Tempo-anon** [comment]
Part of a larger design question but Tail Glow is currently part of Xurkitree's egg moves
