### ISSUE TITLE
Sparkling Aria not recognized as sound based move

### ISSUE THREAD

**Issue by shim80** [pagefaultgames/pokerogue#1204]
Hello
I'm using Primarina with Punk Rock ability, that's supposed to boost all sound based moves.
However, her signature move Sparkling Aria (that is sound based move) doesn't seem to work with this ability

**Comment by Shadowth117** [comment]
Are you sure on this one? It does look at least look like the ability and move are configured correctly already.
https://github.com/pagefaultgames/pokerogue/blob/33f8365192f49d8ad3448e54afa1b76d48ef3910/src/data/ability.ts#L3733
https://github.com/pagefaultgames/pokerogue/blob/33f8365192f49d8ad3448e54afa1b76d48ef3910/src/data/move.ts#L6585

**Comment by EvasiveAce** [comment]
It procs for me, is this what you were meaning? @shim80 

[Video](https://github.com/pagefaultgames/pokerogue/assets/71776311/e4b2980c-9f06-4382-a80c-84fbe7d1c403)

**Comment by TempsRay** [comment]
Can't seem to reproduce
