### ISSUE TITLE
Revieved Pokemon has to be replaced

### ISSUE THREAD

**Issue by Zabosch** [pagefaultgames/pokerogue#1207]
After a trainer encounter i revieved my first Pokemon, but had to send out an other one after battle.

- Trainerbattle using first Pokemon.
- Win, but gets defeated by psn.
- use revieve

result: game wants me to send out an other Pokemon but the first one
expected: game proceedes as normal sending out first Pokemon

**Comment by kenzo251** [comment]
can i add to this bug report (with a similar flow of events) that if this happens before a trainer battle your player and pokemon sprite overlap 
![image](https://github.com/pagefaultgames/pokerogue/assets/41966600/cf6c1700-ac2d-42a4-8480-c16f57ddf707)

**Comment by Zabosch** [comment]
My Mon was just killed by sandstorm after defeating wild Mon and revived at rewardscreen. same issue as described above.

**Comment by Zabosch** [comment]
I tried looking into this issue and the question came into my mind, if there a way i can manipulate my team to not recreate it manually.

**Comment by flx-sta** [comment]
Related to #222
