### ISSUE TITLE
Enemy's Last Respects scales from players fainted pokemon

### ISSUE THREAD

**Issue by LaukkaE** [pagefaultgames/pokerogue#1208]
The check for Last Respect's power always checks players side. (scene.getParty())
This causes AI's side to scale from players fainted pokemon.

![lastrespects](https://github.com/pagefaultgames/pokerogue/assets/73663099/9e5f8619-a9d3-42b0-8e54-3b92e4c50348)

Wild Opponents pokemon is hitting here for 150 bp with two fainted allies.

**Comment by Shadowth117** [comment]
I verified and went ahead and made a pull request for this. 
https://github.com/pagefaultgames/pokerogue/pull/1233

**Comment by Shadowth117** [comment]
Someone did more of an overhaul to that setup for supreme overlord and so this is probably the go forward pr from here:
https://github.com/pagefaultgames/pokerogue/pull/1219

**Comment by Tempo-anon** [comment]
Fixed
