### ISSUE TITLE
[Ui Bug] Weird border only with chromium based browser when below 1080p

### ISSUE THREAD

**Issue by Odizinne** [pagefaultgames/pokerogue#1213]
![image](https://github.com/pagefaultgames/pokerogue/assets/102679854/72bf5f29-8c00-4874-93cd-89f6550290bd)

This occurs only when running Pokerogue in fullscreen **below 1080p resolution in chromium based browser**.

exiting / entering fullscreen again fixes it

I cannot reproduce when above 1080p / at any resolution with firefox

Steps to reproduce:

- Lower your resolution below 1080p
- With chrome, start pokerogue in fullscreen / start pokerogue, enter fullscreen, refresh

**Comment by Odizinne** [comment]
I'll do more testing but for now i cannot replicate this anymore. I need to have a look at recent commits.

Will close this issue after more investigation if i still cannot replicate.

**Comment by flx-sta** [comment]
Cannot reproduce on `beta` (29a5dd006868e14c80f9a5fbef6f6335a182bc89)
