### ISSUE TITLE
black screen + nothing loads

### ISSUE THREAD

**Issue by Saviolbn** [pagefaultgames/pokerogue#1221]
My game only loads a blakc screen, I asked my friend if he could see, his game didnt even load
![image](https://github.com/pagefaultgames/pokerogue/assets/125612304/53e2b017-3609-478a-a6b2-49f9ef5bee59)

**Comment by JoannaFalkowska** [comment]
Is this in the offline or online app? If it's online, probably it would be better to ask for help on Discord: https://discord.com/channels/1125469663833370665/1125894949020381285/

**Comment by Saviolbn** [comment]
online, ill go there
