### ISSUE TITLE
Colored text in starter screen is doubled

### ISSUE THREAD

**Issue by josericardo-fo** [pagefaultgames/pokerogue#1230]
Growth and passive ability
I dont't know if that's intentional

![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/a214f756-4266-4071-bb34-78b332582c00)

![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/3a0820d2-85b4-4622-940b-22f46ec55adc)

![image](https://github.com/pagefaultgames/pokerogue/assets/79599290/1cc94f89-7387-4dbd-a5fc-1c48ee9daf1e)

**Comment by EvasiveAce** [comment]
Is this on the main branch?

![image](https://github.com/pagefaultgames/pokerogue/assets/71776311/af7bdf4e-86ed-4d1f-9e35-c4c8e9cc2fe8)
![image](https://github.com/pagefaultgames/pokerogue/assets/71776311/aa622830-b8f4-4a3b-8ceb-562fca7f9970)


This is what I'm seeing, am I missing something?

**Comment by TempsRay** [comment]
Should be fixed with https://github.com/pagefaultgames/pokerogue/pull/1220. Clear your cache and refresh to make sure you're on the latest version
