### ISSUE TITLE
No Guard hits Pokemon underground/vanished/fly etc

### ISSUE THREAD

**Issue by hightowernl** [pagefaultgames/pokerogue#1244]
Just came across this Machamp hitting my Hoopa while Hoopa was in the shadow realm.

https://github.com/pagefaultgames/pokerogue/assets/57909502/371f3fe5-e7e4-4067-9fed-767a930298c8

**Comment by TempsRay** [comment]
That's how it works in the vanilla games

**Comment by hightowernl** [comment]
> That's how it works in the vanilla games

Ah my bad then, thought otherwise
