### ISSUE TITLE
[BUG] Golden Punch does not give $$ for damage over time

### ISSUE THREAD

**Issue by pedwards95** [pagefaultgames/pokerogue#1258]
This might be intended behavior, but as the title says, the golden punch item does not give money for damage over time abilities. 
Examples would include but not limited to Salt Cure, Fire Spin, Sand Tomb, Bind. Only the initial hit gives money, not the extended per turn damage.

If this is supposed to give money, where should the line be drawn?
Should Toxic, Will-O-Wisp, ect also give money?

Sorry if this is intended behavior. 
![44f85ba5c3e2ad3a158eb71cfebc9ac6](https://github.com/pagefaultgames/pokerogue/assets/61423556/259eda60-3d27-41ae-b72b-6d2dd9a3c3bd)

**Comment by TempsRay** [comment]
Intentional since it refers to direct damage only but would require correcting all localizations of it

**Comment by TempsRay** [comment]
Updated desc for english. Not sure if the wording is ambiguous in other languages
