### ISSUE TITLE
Lighting Rod/Storm Drain vs multi-target moves

### ISSUE THREAD

**Issue by TrainerX493** [pagefaultgames/pokerogue#1264]
Lightning Rod against Discharge in doubles should fully neutralizethe move and protect the ally from taking damage, but currently Lightning Rod only protects the user.

I did not see if Discharge still hit the foe's partner or not, I was too busy being distracted by Gyarados being fried.

**Comment by FrijDom** [comment]
This is intended behaviour; This is how it works in the games. It's part of why spread moves are powerful.

**Comment by Tempo-anon** [comment]
Not a bug
