### ISSUE TITLE
The webpage is extremely slow, making the experience very unpleasant

### ISSUE THREAD

**Issue by timmyLan** [pagefaultgames/pokerogue#1267]
I can't enjoy browsing with Chrome. Although the webpage loads successfully, the text appears very slowly, making the whole experience feel painfully sluggish.

https://github.com/pagefaultgames/pokerogue/assets/17721482/df7f6bf7-62c7-45dd-a15e-581507b4e01d

**Comment by ElliottInnit** [comment]
Highly likely this is a local performance issue. 

1. Do you get the same issue in a non-chromium browser? FF, Arc, Opera etc., anything but Chrome/Edge
2. Do you have hardware accel enabled?

**Comment by CodeTappert** [comment]
Are you a user of Deutsche Telekom? 
Please provide more info

**Comment by Tempo-anon** [comment]
Closing due to lack of information
