### ISSUE TITLE
[QoL] Show field effects when pressing C (weather, screens, hazards)

### ISSUE THREAD

**Issue by jaimefd** [pagefaultgames/pokerogue#1277]
I've noticed it's hard to tell when weather effects are going on, or to check if your stealth rocks/spikes/screens are still in effect between waves.

It would be great to have some way to check what field effects are active, and if limited see the remaining turns, as a toggle mid battle similar to how we can view stat boosts with C.

**Comment by bennybroseph** [comment]
Already being worked on #1096

**Comment by jaimefd** [comment]
Oh awesome, my bad, missed it

**Comment by CodeTappert** [comment]
Fixed in https://github.com/pagefaultgames/pokerogue/pull/1377
