### ISSUE TITLE
Typo about using translator to translate  zh_ch into zh_tw

### ISSUE THREAD

**Issue by h44451890** [pagefaultgames/pokerogue#1282]
Mutiple characters in traditional Chinese are simplified to a character in simplified chinese. For example,"巖"and"岩"  both exist in zh_tw and they are a little different. But in zh_cn,"巖" is simplified into "岩". When using a translator to translate "岩", you might got the wrong character.
![image](https://github.com/pagefaultgames/pokerogue/assets/139263319/124c6a67-09ef-4cf4-a914-83f932da29b6)
大岩蛇 is the correct name for onix for both zh_cn and zh_tw.
There are a lot of typos like this in zh_tw localization

**Comment by zjl88858** [comment]
https://github.com/pagefaultgames/pokerogue/pull/1297

**Comment by h44451890** [comment]
I think that there are still some typos in elsewhere like move and ability descriptions.

**Comment by zjl88858** [comment]
> I think that there are still some typos elsewhere like move and ability descriptions. Could you please check them out?

Yep. I'll check it soon. But not now.
If you have free time, you can join in the fun together.

**Comment by zjl88858** [comment]
https://github.com/pagefaultgames/pokerogue/pull/1359
Gen1-6 move name has been fixed.
I'll fix later for Gen7+ move and ability.
