### ISSUE TITLE
Optionally increase challenge difficulty after each win

### ISSUE THREAD

**Issue by andytaylor823** [pagefaultgames/pokerogue#1283]
Most rogue-likes have some mechanism for advancing in difficulty after each win (e.g. Ascensions 1-20 in Slay the Spire, or Heat in Hades). There should be an option to add small penalties/challenges after each win in Classic mode with all previous penalties enabled.

-----------------

Some ideas for possible challenges, in no particular order:

- Start with fewer points for starter pokemon
- Pokemon cannot start with egg moves
- Luck is always set at lowest
- More frequent trainer battles
- Trainers are harder
- Rival is harder
- Wild pokemon are harder (higher levels)
- The shop is 10% more expensive
- Earn 10% less money
- Bosses have an extra shield
- Only 5 team slots instead of 6 (e.g. start with an un-releasable, un-hatchable egg)
- Extra rival fight?
- Second boss at the end? Maybe Arceus himself comes down?

Obviously, some of these are greater penalties than others, and some can be used multiple times. Here is an example of what a challenge ladder could look like:

```
Level 1: Start with 9 points for starter pokemon
Level 2: ^ and wild pokemon are harder
Level 3: ^ and trainers are harder
Level 4: ^ and rival is harder
Level 5: ^ and the shop is 10% more expensive
...and so on
```

Apologies if this has been suggested before -- I didn't see anything similar in the last 4 pages of git issues.

**Comment by jaimefd** [comment]
Many games also have something called "Prestige" where you reset your levels to start again, but with increased difficulty, strength and/or rewards. Maybe your idea could be implemented like that, after certain waves of endless you can choose to reset and unlock 1 higher level of endless

**Comment by JonStudders** [comment]
Please join the discussion here:
https://discord.com/channels/1125469663833370665/1243737542638043167

**Comment by Tempo-anon** [comment]
Challenges are planned https://github.com/pagefaultgames/pokerogue/pull/1459
