### ISSUE TITLE
To many server requests

### ISSUE THREAD

**Issue by arin-prashar** [pagefaultgames/pokerogue#1285]
Poke-rouge on launch makes a lot of server requests.
A way to mitigate them is to change some file types such as mp3 to a lighter version
PNG to WebP or JPEG as they are lighter or SVG as they can directly be rendered

the excessive server requests from a single device can be handled but with given rate of increasing popularity
there is a need of load balancer that handles only one type of request at a time 
such as setting up a load balancer with 4 network adapter
it sets one for images
second for mp3 and similar ones
third one for player data
fourth as a backup

![image](https://github.com/pagefaultgames/pokerogue/assets/112185917/91fa6576-d9df-457d-9b93-c76f89187daa)
![image](https://github.com/pagefaultgames/pokerogue/assets/112185917/5c41c9d6-9323-451d-a956-15c29c1c1a2a)
![image](https://github.com/pagefaultgames/pokerogue/assets/112185917/e6450940-a32e-43e7-8b28-a0642bcb3dfb)
![image](https://github.com/pagefaultgames/pokerogue/assets/112185917/cc1f90ee-dfb4-427c-b0ee-c3c4d46b18d4)
![image](https://github.com/pagefaultgames/pokerogue/assets/112185917/48669371-cc11-4fcb-9dd9-f027ef36adfb)
![image](https://github.com/pagefaultgames/pokerogue/assets/112185917/0e25395b-93d3-4208-8b26-cd358c7b21e2)
![image](https://github.com/pagefaultgames/pokerogue/assets/112185917/a5d285ff-0572-4af9-9f04-f6e0a4462cde)

# The game has become a lot more popular so the server response will lead to a 500+ error so a way to mitigate is to make it multi port and spread among different servers so as to reduce overall load

**Comment by arin-prashar** [comment]
Hope its taken into consideration

**Comment by flx-sta** [comment]
@arin-prashar Thanks for your input.
We will be taking it into account looking forward
