### ISSUE TITLE
Missing Pokemon name

### ISSUE THREAD

**Issue by drzeeb** [pagefaultgames/pokerogue#1296]
Today i discoverd a missing label of a pokemon from an egg.
I don't know which pokemon it is, could be a Ting-Lu which has a translation in the german locales.
![Screenshot_2024-05-23-17-03-22-67_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/pagefaultgames/pokerogue/assets/11742001/c53dda88-c10f-4f62-847f-8d05c566357c)

**Comment by TempsRay** [comment]
That is its actual name.
