### ISSUE TITLE
Login Error: dial unix /run/mysqld/mysqld.sock: connect: connection refused

### ISSUE THREAD

**Issue by Nydragon** [pagefaultgames/pokerogue#1302]
I get the following error on login: 

`dial unix /run/mysqld/mysqld.sock: connect: connection refused`

POST
https://api.pokerogue.net/account/login
[HTTP/2 500  294ms]

**Comment by Nydragon** [comment]
#1305

**Comment by Greenlamp2** [comment]
![image](https://github.com/pagefaultgames/pokerogue/assets/44787002/84852b48-290f-4c64-b2f2-b1985303e1ff)
