### ISSUE TITLE
195 Breaks the Game.

### ISSUE THREAD

**Issue by PabloTwigman21** [pagefaultgames/pokerogue#1303]
So I was playing Pokerogue and I finally beat floor 195(Rival Fight). After claiming all my money, eggs, items, etc, The game froze with my side having my Meowscarada still out and Ivy just standing there(menacingly). I closed the game and reopened and when I try to log back in it says dial unix /run/mysqld/mysqld.sock     What does that mean?
<img width="393" alt="Screenshot 2024-05-23 180252" src="https://github.com/pagefaultgames/pokerogue/assets/170681726/457d9c0f-0978-4aa5-97f8-af50d8cb8b83">

Here's a screenshot of what it looks like.

**Comment by Madmadness65** [comment]
This is unrelated, that error is from server downtime, and in this case, from a DDoS attack. Hopefully it will be resolved soon.

**Comment by Greenlamp2** [comment]
![image](https://github.com/pagefaultgames/pokerogue/assets/44787002/58934c3c-1df2-48c8-9be0-cc2b80d84321)
