### ISSUE TITLE
dial unix /run/mysqld/mysqld.sock

### ISSUE THREAD

**Issue by giulomy** [pagefaultgames/pokerogue#1305]
i just discovered a new issue and i didn't see anything about it, it says dial unix /run/mysqld/mysqld.sock and i can't log my account, if anyone knows something about this pls help me i don't want to lose 15+ hours on this.

**Comment by virmaus** [comment]
probably the database is corrupted for the attacks of DDOS

**Comment by Chuiantw1212** [comment]
I guess it was not DDOS attacks, but tons of users.

**Comment by Greenlamp2** [comment]
![image](https://github.com/pagefaultgames/pokerogue/assets/44787002/9390047b-62dd-4cef-9ec6-f80b6d879717)
