### ISSUE TITLE
[SUGGESTION] Add Settings Option in the Index Page

### ISSUE THREAD

**Issue by SnowCharmQ** [pagefaultgames/pokerogue#1312]
In the index page, as shown below, it is best to add a settings option on this page, where users can view the current game key bindings and customize them. These are global system settings and should not only be accessible within the game. Other settings, such as volume and page size, should also be considered.
![image](https://github.com/pagefaultgames/pokerogue/assets/82224175/3346252e-84ee-4e0f-8bdd-7d8215fbcc6c)

**Comment by torranx** [comment]
You can access the settings immediately by pressing Esc

**Comment by SnowCharmQ** [comment]
> You can access the settings immediately by pressing Esc, keybinds are still under development #1205

Good! But adding a hint in the page would be more user-friendly or sometimes users will miss it :)

**Comment by torranx** [comment]
I agree, I had a bit of struggle too when I first opened up the game. Another example is when selecting pokemon before your run, didn't know you'd do it with Space key, I was spamming Enter.
