### ISSUE TITLE
[Missing animation] Muddy Water has no move animation

### ISSUE THREAD

**Issue by hayuna** [pagefaultgames/pokerogue#1319]

**Comment by c0nsy** [comment]
Surf is missing too, missing the animations in the muddy-water.json and surf.json files

**Comment by pom-eranian** [comment]
backgrounds for Muddy Water, Surf and Sludge Wave. 
Also here I made all three moves have the same length.  (not sure if that's ok. surf was shorter than the other 2)


https://github.com/pagefaultgames/pokerogue/assets/174080725/3008c4f5-06c9-46ba-9629-32915c024854
