### ISSUE TITLE
Poison damage from Toxic Spikes incorrectly occurs immediately upon switch in

### ISSUE THREAD

**Issue by DayKev** [pagefaultgames/pokerogue#1320]
When a Pokemon is sent out (such as after a KO), Toxic Spikes will trigger to poison the Pokemon as normal but it will also immediately take a tick of poison damage which is incorrect.

https://github.com/pagefaultgames/pokerogue/assets/34855794/d503a80b-fe84-4a1c-8b7b-2d8aec85a936

Had trouble recording the SV footage but screenshot shows the Cyndaquil at full health still (and poisoned) in the same scenario as the PokeRogue footage.

![image](https://github.com/pagefaultgames/pokerogue/assets/34855794/4ffa405a-d1f1-4eb8-a8db-422762ef73d6)

**Comment by j-diefenbach** [comment]
Relevant to #895
