### ISSUE TITLE
Unlocked Passive, cost reduction and egg moves are not showing up when starting Classic run; UI elements are missing

### ISSUE THREAD

**Issue by JoannaFalkowska** [pagefaultgames/pokerogue#1324]
I had enough candies on Azumarill to unlock its Passive and reduce cost by 1. I did that in a menu before starting a Classic run. I had non-shiny Registeel with Pokerus in the party before Azumarill. Then I added a third pokemon to the party, shiny Wormadam. I remember also changing some natures and moves. But wventually I changed my mind and X-ed out of the Classic run start menu.

Now, when I try to start a Classic run with Azumarill, it shows its passive as "not unlocked", cost as the base 4 cost, and 2 egg moves that I had (Jet Punch and Swords Dance) are gone. 

Also the number of remaining candies is missing in the upper left corner, and "Use Candies" is not visible anymore in this specific species menu.

My account name is "Senthe", if that helps. It would be nice to get those unlocks back on it.

Here are parts about Azumarill that I'm getting back from the `/savedata/system?clientSessionId=...` JSON. Note that it also claims that I hatched 0 Azumarill, which is not true, as I had egg moves unlocked on it already. Also "seenCount: 1, caughtCount: 6" AFAIR should mean that at least 5 of them were hatched. And obviously it shouldn't be possible to catch 6 of them, including red shiny, and also have 0 candies and no unlocks.

```
{
    "trainerId": 59687,
    ...
        "183": {
            "seenAttr": 149,
            "caughtAttr": 223,
            "natureAttr": 4259944,
            "seenCount": 1,
            "caughtCount": 6,
            "hatchedCount": 0,
            "ivs": [
                15,
                23,
                20,
                22,
                28,
                26
            ]
        },
    ...
        "183": {
            "moveset": null,
            "eggMoves": 0,
            "candyCount": 0,
            "friendship": 0,
            "abilityAttr": 7,
            "passiveAttr": 0,
            "valueReduction": 0,
            "classicWinCount": 0
        }
```

Screenshot:
![image](https://github.com/pagefaultgames/pokerogue/assets/14551750/3bdae209-6dd0-48dc-9ea8-c8e59a608849)

**Comment by Madmadness65** [comment]
This is not a bug, evolved Pokémon like Marill cannot have candies used on it and egg moves selected on it. In order to use them, you need to use Azurill instead.

**Comment by JoannaFalkowska** [comment]
Thank you, clearly I am freaking stupid 😅
