### ISSUE TITLE
Accidental zoom on IOS (D-PAD)

### ISSUE THREAD

**Issue by flx-sta** [pagefaultgames/pokerogue#1326]
I am using Pokerogue on my IOS device and sometimes when I use the D-Pad my device thinks I want to zoom into the page. 
Which results in this perspective:
![IMG_BC492384B299-1](https://github.com/pagefaultgames/pokerogue/assets/50131232/6c54a577-9842-4343-a8a7-8b34d97723e4)

The only way to fix it is to restart the app.

I didn't observe this bug before so it might have been added recently..

**Comment by felix-staud** [comment]
@Madmadness65 this might be an easy fix. see PR

**Comment by lost-RD** [comment]
I experienced this bug once yesterday. Only the once so far since the fix was merged
