### ISSUE TITLE
Using Lum Berry on Poke that just fainted causes infinite loop 

### ISSUE THREAD

**Issue by keebarber** [pagefaultgames/pokerogue#1327]
There is a bug with how the Lum Berry affects status in that it can 'heal' FNT, which the game doesn't like. Below is a step by step of what occurred.

1. Completed Double Battle in which P1 fainted and P2 was still alive at the end of the battle. 
2. Picked Lum Berry and applied it to P1 who was fainted. 
3. At the start of the next battle (which was a single battle), both P1 and P2 had their names show up, but P1 (who was fainted) had no health bar, and the sprites were slightly overlapping. 
4. I was not prompted to make a move, but the wild Poke used Focus Energy (which failed), and the text box got stuck looping until Stack size was exceeded and it froze. 
5. Upon selecting continue, P2 was sent out, P1 was in the second spot, and was still holding the Lum Berry. 
6. Game continued as expected from there.

**Comment by flx-sta** [comment]
Wasn't able to reproduce it on `beta` (4a04ef50c35b668f21a6fc627d30c064dce933eb)
