### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by thom-sim** [pagefaultgames/pokerogue#1339]
Hello,

I've been playing for a while now, everything worked great until yesterday. I can play and load with my other devices, but on my newly acquired PC it won't pass the loading screen anymore.

So far I tried : 
- Clearing data site and cookies
- Uninstalling Chrome
- Edge don't work either
- Register a new account
- Unable auto-proxy
- Obviously my PC is up-to-date at every level

**Anyone as a clue of what I can do ?**

Thanks in advance

**Comment by LiasEster** [comment]
i have the same problem, i can't play with pc anymore only mobile cuz stuck in loading screen

**Comment by thom-sim** [comment]
After many tries, account created and clears of browser data, game seem to work again
