### ISSUE TITLE
Name & Gender mismatch

### ISSUE THREAD

**Issue by GodkarmachineOBabaghanoush** [pagefaultgames/pokerogue#135]
Breeder Bethany is given the male sprite & male symbol despite the female name. If this is intentional, disregard.

[Screenshot from the daily.](https://media.discordapp.net/attachments/827086183619362868/1229257381440000081/image.png?ex=662f0626&is=661c9126&hm=02231f97bb288704e866b47f998f91ecc91fec0fae2bae28c517938734bb2189&=&format=webp&quality=lossless&width=828&height=455)

**Comment by Flashfyre** [comment]
Not intentional, thanks for catching this

**Comment by Flashfyre** [comment]
Fixed
