### ISSUE TITLE
Missing hatched pokemons

### ISSUE THREAD

**Issue by arin-prashar** [pagefaultgames/pokerogue#1355]
I hatched 2 legendary pokemons on 24/5/24(DD/MM/YY) 
but when I checked today (25/5/24) both of them were missing
I would like to get it confirmed that is it a bug or something else as they were one of my strongest mons,
U can check the logs for hatched eggs
in game Username -> DKGamer02AI 

Thanks for the support

**Comment by arin-prashar** [comment]
![image](https://github.com/pagefaultgames/pokerogue/assets/112185917/fe127de4-d0ca-4ba7-afaf-d405b9bf375f)
The one selected and the tapu koko at the end of above line
the tapu koko had fairy wind as the egg move and pretty good IV

**Comment by Shadowth117** [comment]
I've had this happen too where it deletes the egg, but doesn't save the Pokemon. I think you have to actually get to the next wave or something for it to save properly. It would be good if we could make sure that eggs hatching and all the starter updates for said egg are tied more intimately.

**Comment by arin-prashar** [comment]
> I've had this happen too where it deletes the egg, but doesn't save the Pokemon. I think you have to actually get to the next wave or something for it to save properly so if there's something that causes an error or disconnect, it leaves you without your egg mons. It would be good if we could make sure that eggs hatching and all the starter updates for said egg are tied more intimately.


I used the hatched mons till round 60 
but still next day missing
