### ISSUE TITLE
Enforce space around curly braces

### ISSUE THREAD

**Issue by JakubHanko** [pagefaultgames/pokerogue#1356]
In my opinion, we use the spaces around curly braces fairly inconsistently, see for example imports in `trainer.ts`, `battle-message-ui-handler.ts:122` (the definition of `levelUpStatsValuesContent` variable), just to name a few.

Do we want to add a new rule to ESLint?

https://eslint.style/rules/js/object-curly-spacing

If yes, I can just add one more commit to #1323 .

**Comment by j-diefenbach** [comment]
Might aswell imo
