### ISSUE TITLE
Does offline mode update automatically

### ISSUE THREAD

**Issue by 2664165718** [pagefaultgames/pokerogue#1371]
Does offline mode update automatically, or do we need to manually update it ourselves, and if the latter how should you do it?

**Comment by Upos1997** [comment]
You have to do it manually.
![image](https://github.com/pagefaultgames/pokerogue/assets/37412723/19163f3f-fa52-417c-843c-a4b932e08c30)

**Comment by JoannaFalkowska** [comment]
@Upos1997 I think that's a screenshot from some PokeRogue wrapper, possibly https://github.com/Admiral-Billy/Pokerogue-App, i.e. irrelevant to this repo.

@2664165718 In the online PokeRogue app, you'll find options to Export Data and Export Session. First is for your data like hatched starters and statistics, second is for exporting specific save slots. You can do only one of those exports or both, whichever you prefer. Then in the offline version from this repo, you'll find that in this menu there are options to Import Data and Import Session, which let you make use of those exported files.

![image](https://github.com/pagefaultgames/pokerogue/assets/14551750/5d5cb6dc-d63c-4348-9607-b06e39457d12)
![image](https://github.com/pagefaultgames/pokerogue/assets/14551750/0bfe8ebf-7eae-4a02-8815-935fc40ec15c)

Offline data does not synchronize automatically, you need to do it manually on your own. Also note that if you keep playing both versions, another import from online won't magically "merge" with your offline data - it'll completely override it.
