### ISSUE TITLE
Punk Rock ability does not fully convert move types

### ISSUE THREAD

**Issue by ExcaliburgerDL** [pagefaultgames/pokerogue#1385]
Primarina with Punk Rock ability, converting a fire move such as Torch Song to water move, this situation does not prevent flash fire and well-baked body from negating Torch Song, those abilities still treats the move as a fire move.

**Comment by lockadox** [comment]
Wrong ability, the one that converts sound moves to Water type is Liquid Voice.

**Comment by Madmadness65** [comment]
As stated above, you seem to have mistaken two different abilities.
