### ISSUE TITLE
Classic mode stuck after completing level 200, retry invalid

### ISSUE THREAD

**Issue by zjuHong** [pagefaultgames/pokerogue#1387]
Excuse me, I downloaded it from GitHub and deployed it locally myself, NPM version 6.14.18. After completing level 200 in Classic Mode, I got stuck and tried a few times, but it didn't work. May I ask if there is any special code logic in this area? Not very familiar with the front-end, seeking answers.

**Comment by keoy7am** [comment]
I think it's related to [How to switch to server-side saving for privately hosted?](https://github.com/pagefaultgames/rogueserver/issues/22)

In the debugging mode of the browser, you will see a 404 error at 

>  http:// api-server /savedata/newclear?slot=0

It seems that in the current version, some functions linked to the backend server are invalid.

In my environment, some API functions of the backend server are functioning normally.

eg.
> http:// api-server /game/titlestats
> Returns 200 status, but always displays

```json
{"playerCount":0,"battleCount":0}
```

**Comment by JoannaFalkowska** [comment]
I can confirm that when I used the front-end version standalone, I had to disable some API calls to avoid errors. `/titlestats` were definitely among them. I think this is a bug tbh, the frontend should be able to work without backend out-of-the-box. There are already checks for whether API calls should be made or not, but some calls seem to be attempted anyway.

**Comment by zjuHong** [comment]
> I think it's related to [How to switch to server-side saving for privately hosted?](https://github.com/pagefaultgames/rogueserver/issues/22)
> 
> In the debugging mode of the browser, you will see a 404 error at
> 
> > http:// api-server /savedata/newclear?slot=0
> 
> It seems that in the current version, some functions linked to the backend server are invalid.
> 
> In my environment, some API functions of the backend server are functioning normally.
> 
> eg.
> 
> > http:// api-server /game/titlestats
> > Returns 200 status, but always displays
> 
> ```json
> {"playerCount":0,"battleCount":0}
> ```

Understood, thank you. I didn't notice that there is also a backend code repository orz

**Comment by CodeTappert** [comment]
Ö.

L,eaw
