### ISSUE TITLE
Liquid Voice ability bug

### ISSUE THREAD

**Issue by ExcaliburgerDL** [pagefaultgames/pokerogue#1390]
Primarina with Liquid Voice ability, converting a fire move such as Torch Song to water move, this situation does not prevent abilities such as flash fire and well-baked body from negating Torch Song, those abilities still treat the move as a fire move.

**Comment by td76099** [comment]
Going to add this in to #1384 to get this taken care of!

**Comment by td76099** [comment]
With any luck #1440 will fix it now :)

**Comment by ExcaliburgerDL** [comment]
fixed
