### ISSUE TITLE
[Bug] Repeatble freeze when switching in Zacian after a double battle

### ISSUE THREAD

**Issue by Terrorforge** [pagefaultgames/pokerogue#1395]
[sessionData_Terrorforge_zacian_consistent_freeze.zip](https://github.com/pagefaultgames/pokerogue/files/15447103/sessionData_Terrorforge_zacian_consistent_freeze.zip)

Fought a double battle. Right-side pokemon was taken out on the same turn I won, and I got the prompt to select a new right-side pokemon. I chose Zacian-crowned. When Zacian entered the field, the Intrepid Sword pop-up showed up behind the item select screen, and after selecting an item the game would not progress.

**Comment by flx-sta** [comment]
Duplicate of #222
