### ISSUE TITLE
Game won't start in Firefox due to "Uncaught TypeError: G.requestVideoFrameCallback is not a function"

### ISSUE THREAD

**Issue by tstephenson888** [pagefaultgames/pokerogue#141]
Hello! The game won't render on my display due to a recent update. The game was working just fine a few days ago, but the game now only displays a black screen. I've tried forcing a browser cache reset, and disabling my ad blocker. I don't believe I have any other extensions that would interfere with the game launching.
![Here's what the dev console in my browser says](https://github.com/pagefaultgames/pokerogue/assets/22721076/29b4c542-5981-47f3-b6e5-b93ec1cf72de)

I am using Firefox 124.0.2 on Windows 11

**Comment by Flashfyre** [comment]
You can fix this by using any other browser as it's a Firefox-specific issue. It doesn't happen to me on Firefox oddly enough, so not sure what causes it to break.

**Comment by samme** [comment]
If you're comfortable running code in the console, you can run

> 'requestVideoFrameCallback' in HTMLVideoElement.prototype

> 'getVideoPlaybackQuality' in HTMLVideoElement.prototype

and see what values it shows.

**Comment by Flashfyre** [comment]
This function is actually not supported in Firefox, but the engine should have a polyfill to resolve that missing function. For me it works, but for some others it doesn't seem to.

**Comment by Gammer0909** [comment]
> This function is actually not supported in Firefox, but the engine should have a polyfill to resolve that missing function. For me it works, but for some others it doesn't seem to.

What FireFox version are you using?

**Comment by bennybroseph** [comment]
Closing this issue as no other reports have popped up or been added here
