### ISSUE TITLE
[Bug] Game froze in abyss when encounter a new wave with Umbreon  

### ISSUE THREAD

**Issue by FrankHZ** [pagefaultgames/pokerogue#1419]
![image](https://github.com/pagefaultgames/pokerogue/assets/19247479/1e85f0d5-c0a4-4295-8698-bdd091cfd8e2)
![image4](https://github.com/pagefaultgames/pokerogue/assets/19247479/0b2aaeb0-bbc4-4da8-8cc6-6902cd8b6d26)
![image2](https://github.com/pagefaultgames/pokerogue/assets/19247479/24e62575-e9a7-4997-8a03-2cd70413dd80)
![image3](https://github.com/pagefaultgames/pokerogue/assets/19247479/56d265a7-7e5d-479e-a4f4-907ea8fbe5e0)
It looks like the evolution chain cannot be correctly evaluated for Umbreon

**Comment by TempsRay** [comment]
Sounds like a bug introduced from some Eevee evolution code but that should have been fixed. Does Umbreon still crash the game?

**Comment by FrankHZ** [comment]
> Sounds like a bug introduced from some Eevee evolution code but that should have been fixed. Does Umbreon still crash the game?

Yes, I just tried and it worked fine

**Comment by Richter28** [comment]
Hey, i have the same issue, if i ennconter Umbreon in abyss, my game crash. I see i little pokedoll where there should be Umbreon, than my game freeze. Any Ideas how i could save my run? 

thanks your help <3

**Comment by Tempo-anon** [comment]
Can you share your console for error logs? Seeing a substitute is usually indicative that you need to clear your cache
