### ISSUE TITLE
[Suggestion] Remember the entire starter configuration, not just moves

### ISSUE THREAD

**Issue by Terrorforge** [pagefaultgames/pokerogue#1446]
Please make it so the game permanently remembers the full setup of a starter as last used; ability, nature, form, passive on/off, gender, shiny, anything else I forgot.

This should be remembered between runs, but it currently isn't even remembered if you move the cursor off the pokemon in the selection screen. So not only is it annoying to have to input all the options whenever you start a run, it's super easy to accidentally erase what you've already put in while you're building a team. Just today I've restarted two runs on wave 40+ because I juggled my team around a bit on the selection screen and forgot to re-re-re-input that I wanted my Mudbray to have Stamina. The other day I did the same thing with Battle Bond Greninja. The more options I unlock, the worse it gets.

**Comment by JakubHanko** [comment]
I implemented ability and nature persistence as part of #1400 . Should be fairly simple to extend, if needed, once accepted.

**Comment by Terrorforge** [comment]
That's great, thank you. Form and gender are also important and would be the natural next step, tho obviously it only matters for a handful of pokemon.

And since you're storing the settings locally, at that point might as well persist passive and shiny settings just for consistency

**Comment by JakubHanko** [comment]
Sure, makes sense. I just don't want to get too much work in before I get a green light from the leads.

**Comment by Terrorforge** [comment]
Yeah, don't sweat it. Just work out the basic implementation and the rest can come later.

**Comment by wesleyschlenker** [comment]
Boosting engagement on this with a comment. This is a very simple and much needed QoL improvement IMO. Thank you @JakubHanko for the original work on ability and nature persistence. I hope a lead dev responds on your PR soon with a a big green flag so that you can implement the rest of the starter configuration into local storage.
