### ISSUE TITLE
Implement Ice Face

### ISSUE THREAD

**Issue by Tempo-anon** [pagefaultgames/pokerogue#1456]
Can probably just be a battlertag. The battlertag will block the first physical move and then disappear.

When hail/snow begins it should check if there are any Pokemon that are Eiscue with Ice face and without the tag, applying it if they do not have it. 

When an eiscue with ice face is sent out into snow/hail it should gain the battlertag.

**Comment by torranx** [comment]
Looking to implement this as my first take on abilities.

**Comment by torranx** [comment]
in progress!

**Comment by Tempo-anon** [comment]
Done in https://github.com/pagefaultgames/pokerogue/pull/1755
