### ISSUE TITLE
Trainers can use unevolved mons late-game if those mons have alternate evolution requirements

### ISSUE THREAD

**Issue by DayKev** [pagefaultgames/pokerogue#1475]
I just fought the rival battle on floor 95 and he had a Feebas (so effectively -1 Pokémon). There should probably be some arbitrary level set for Pokémon with alternate evolution requirements so that if a trainer is given one of them at or above that level they'll be given the evolved form instead.

![image](https://github.com/pagefaultgames/pokerogue/assets/34855794/cb0fd749-b76b-4e4f-a517-efb982a00bd9)

**Comment by Tempo-anon** [comment]
This should have been fixed. If it has not, please let us know.
