### ISSUE TITLE
[Refactor idea] Splitting phases.ts

### ISSUE THREAD

**Issue by hayuna** [pagefaultgames/pokerogue#1483]
As far as we can see, this file start to be growing and right now has like 5k lines. Could we start thinking about splitting this huge file into smaller phases?

Example of this:

<img width="500" alt="Screenshot 2024-05-28 at 11 55 25" src="https://github.com/pagefaultgames/pokerogue/assets/19636010/99490edf-234d-44f4-b0d5-f8909e3c0946">

**Comment by torranx** [comment]
Upvoting this!

**Comment by flx-sta** [comment]
I'd support this but agree with @torranx that it should be small incremental changes

**Comment by hayuna** [comment]
I will do the research which of the phases are not inside existing pull requests and then try to make a PR with 3-4 files. Lets try from the small pieces

**Comment by flx-sta** [comment]
@hayuna I wouldn't dig too much into the PRs.
The idea is to keep the PRs small thus people can catch up on their PRs.

If peoples PRs are obliberated because they didn't keep up with merges that's on them.

I'd just start slowly and with small incremented changes

**Comment by flx-sta** [comment]
Incremental improvements like such are being consistently applied
