### ISSUE TITLE
Item is invisible

### ISSUE THREAD

**Issue by spixi** [pagefaultgames/pokerogue#1486]
![a](https://github.com/pagefaultgames/pokerogue/assets/3192596/727f0aa7-ebad-4f3d-a886-a85b04b2cdfa)
I have a Golden Poké Ball and play in German. The item "X Accuracy" is invisible in the reward screen as seen in the attached image.

**Comment by Madmadness65** [comment]
This is a known issue, primarily to do with the game speed. It doesn't have anything to do with any specific items, just that the game is going fast enough to rarely skip visually spawning an item, but it can still be selected as normal.

**Comment by Smewkie** [comment]
I have also heard through bug reports in the discord that turning off either Graphics Acceleration or Hardware acceleration in your browser can stop this from happening.

**Comment by flx-sta** [comment]
Closing this as it has nothing to do with our code
