### ISSUE TITLE
Grassy Terrain does not recover first health bar of boss monsters

### ISSUE THREAD

**Issue by spixi** [pagefaultgames/pokerogue#1488]
![a](https://github.com/pagefaultgames/pokerogue/assets/3192596/cd07722f-5693-4c07-87e7-968eb14b100a)
Grassy Terrain is active and the heal animation is shown, but no health is recovered. When the second health bar is full, health from the first health bar should be recovered as well.

**Comment by Snailman11** [comment]
This would be bosses not being able to heal past the bar

**Comment by Snailman11** [comment]
Position By Balance
![Screenshot_20241107-184116](https://github.com/user-attachments/assets/fee37fd6-79d5-4caf-9843-8b2e709fae9c)

Conversation in #dev-corner, reported by ImperialSympathizer
https://discord.com/channels/1125469663833370665/1176874654015684739/1283072498723721257
