### ISSUE TITLE
[Feat] Replace key hint with controller icons when using a controller

### ISSUE THREAD

**Issue by Odizinne** [pagefaultgames/pokerogue#1493]
It would be nice to replace the hint for nature, variant etc. by controller button icons when using one.

Ideally, there would be a generic icon set, and some customized ones depending on the controller (Sony, Microsoft, Nintendo etc.)

If someone show interest into implementing this, please let me know so i can try to create some icons in accordance with the game design!

**Comment by Greenlamp2** [comment]
i'll work on that once https://github.com/pagefaultgames/pokerogue/pull/1205 is merged

**Comment by flx-sta** [comment]
Icons are now displayed
