### ISSUE TITLE
[Feature] Implement Magnet RIse

### ISSUE THREAD

**Issue by Tempo-anon** [pagefaultgames/pokerogue#1505]
**Is your feature request related to a problem? Please describe.**
Magnet Rise (and the associated levitation mechanics) need to be implemented

**Describe the Feature**
We currently have a battlertag already for Magnet Rise but all the intricacies of being off the ground need to be implemented

**Additional context**
* Fails if user is ingrained (does ingrain remove the tag?)
* Removed if gravity is in play and fails if gravity is already in play
* Removed if user is smacked down or thousand arrow'd and cannot use it again

**Comment by GrantMickle21** [comment]
I would love to have this implemented since I use Magnezone a lot. It was my first shiny.

**Comment by abhinav-selvaraj** [comment]
im looking at the src code and im struggling to follow the hierarchy and see how its not implemented

**Comment by Dakurei** [comment]
Implement in https://github.com/pagefaultgames/pokerogue/commit/89eba349c9f77985b10a0befadae7b5caf8edd0b
