### ISSUE TITLE
[Feature] Starting Party Limit based on Player Progress

### ISSUE THREAD

**Issue by frutescens** [pagefaultgames/pokerogue#1513]
Current Situation:
Right now, when they start a new game, players have to make sure that their chosen starters are worth 10 points (in Classic Mode) or 15 points (in Endless Mode). I believe that there should be milestones in the game where players are able to increase this starting limit. I still believe a maximum is necessary so I set an arbitrary maximum of 20 points for a starting party. 

Suggestions for Classic Mode:
- Beating Classic for the first time: +1
- Beating all special trainers: +2
- Completing the Pokedex: +3
- 100 Pokemon with Classic Mode Ribbons: +2 
- +2 points for future challenges like monotype runs, etc.

Suggestions for Endless Mode:
- Every 1000 Waves: +1
After 5000 waves, players can have a maximum party limit of 20.

**Comment by molker** [comment]
This is why candy and cost reduction exists, 20 or even 15 limit in classic would make it probably too easy when you have a lot of high cost pokemon unlocked.
