### ISSUE TITLE
Supercell Slam's Line 63994 in tms.ts is missing a space towards the end.

### ISSUE THREAD

**Issue by H-A-R-V** [pagefaultgames/pokerogue#1528]
https://github.com/pagefaultgames/pokerogue/blob/0780211901c2cfa67f5eb1735f3446a68d45dcf4/src/data/tms.ts

Line 63994

"  [Moves.SUPERCELL_SLAM]:["

to

 " [Moves.SUPERCELL_SLAM]: ["

**Comment by JakubHanko** [comment]
Quite possibly solved with the addition of this rule to the linter?

https://eslint.style/rules/js/key-spacing

**Comment by H-A-R-V** [comment]
Does this mean adding a space wouldn't fix it? I just noticed it was inconsistent with the other TM's when I went to pull data for the wiki.

**Comment by JakubHanko** [comment]
It definitely would fix it. However, I think it would be great if this was caught by the linter instead of a human.

**Comment by Tempo-anon** [comment]
Going to close this issue out since we have lots of linting improvements that can be done
