### ISSUE TITLE
[BUG] Red Shiny Not Available in Selection

### ISSUE THREAD

**Issue by Buttkicker420** [pagefaultgames/pokerogue#1529]
**Describe the bug**
I caught a red rarity excadrill and it is not appearing in my available selection. This is a bug as I caught it on a different run, selected it from the pokemon selection in a different run, and was going to play a classic run but it is not available. 

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Device**

**Additional context**
![image2](https://github.com/pagefaultgames/pokerogue/assets/171105846/5e9e988e-3c7a-4712-8074-96dbcf796df3)
![image](https://github.com/pagefaultgames/pokerogue/assets/171105846/3e969194-f0e9-4edc-97a9-2e256acb2642)

**Comment by Buttkicker420** [comment]
In addition to losing my shiny I’m also now noticing that I lost the passive ability I unlocked with drillbur.

**Comment by Nohbody** [comment]
I tried to recreate this bug by catching an Epic Shiny Excadrill on a new Classic save, but could not recreate the issue. I was able to select the new variant as expected on a new Classic run. Perhaps one of the devs with access to the prod db can just flag your account with the expected catch.

**Comment by Tempo-anon** [comment]
Can't reproduce this issue. Let us know in the future if you experience any more account data loss
