### ISSUE TITLE
[BUG] Rogue Ball is still available in post-battle shop even at max stacks

### ISSUE THREAD

**Issue by zizibaloob** [pagefaultgames/pokerogue#1530]
**Describe the bug**
I have 99 Rogue Balls in my inventory. Unlike with other items that hit max stacks, the shop still offers me Rogue Balls. I can select them and receive functionally no item.

**To Reproduce**
1. Obtain 99x Rogue Ball
2. Reroll items in post-battle shop
3. Eventually Rogue Ball appears
4. Selecting it results in no Rogue Balls being added to inventory

**Expected behavior**
Items owned at maximum stacks do not appear in the shop

**Screenshots / Videos**
![rogue-balls](https://github.com/pagefaultgames/pokerogue/assets/4566292/28d99af9-5a5f-4e85-8891-cc0c35a723cd)

**Device**
M1 MacBook Pro, Mac OS Sonoma 14.4.1, Firefox 125.0.2 (64-bit)

**Comment by Tempo-anon** [comment]
Not a bug, that's just how all balls work currently

**Comment by Smewkie** [comment]
This is also how held items such as type boosting items, baton, black hole, etc work currently, even if you have no pokemon available that can hold them they can still appear in the shop.

I do agree however that having 99 of them means you shouldn't be able to pick them with 0 benefit, perhaps a message stating that you can't carry more of them would be better.
