### ISSUE TITLE
[Feature] Indicator for Perfect IVs

### ISSUE THREAD

**Issue by frutescens** [pagefaultgames/pokerogue#1546]
I think it would be nice to have a visual indicator when hatching eggs that shows the player that they have already achieved perfect IVs regarding the hatched starter. Otherwise, the player has to go through multiple windows to see their starter's IVs. 

I also think that if a player got all 3 IV Viewers, it would be nice to have this visual indicator on the enemy Pokemon. This way, if a player is catching Pokemon to improve their starters' IVs, they do not have to exit the game, go to 'New Game', and then toggle the 'View IV' option over and over again to check if the starter already has perfect IVs. 

This indicator can also be deployed on the starter select UI as well.

I am open to other icons for the indicator, but I thought this mark would be a cute stand-in for now: https://bulbapedia.bulbagarden.net/wiki/File:Absent-Minded_Mark.png

**Comment by InuKami16** [comment]
The indicator would be nice on the starter screen, but not necessary in battle. The IV scanner will display a green text if that stat is an improvement over your current IVs and a white text otherwise. There's no need to go back to the New Game screen to toggle IVs since if the pokemon is already perfect, then all of the IVs will display white.

**Comment by frutescens** [comment]
I agree! I'll focus on the starter screen instead.

**Comment by dooont** [comment]
Is this still being worked on? would be very interested in helping out with this!

**Comment by Dynamixus** [comment]
Yep came to suggest this too.

**Comment by CodeTappert** [comment]
It was added here https://github.com/pagefaultgames/pokerogue/pull/2019

Is this enough?
