### ISSUE TITLE
[BUG] In store soft-lock with PC keyboard

### ISSUE THREAD

**Issue by BlastCom** [pagefaultgames/pokerogue#1547]
<ins>**Describe the bug**</ins>
- When in-store, pressing the backspace key will prompt the following message: "Are you sure you don't want to take any items?" with the following "Yes" and "No" option. Then pressing the escape key makes the "Yes" and "No" box disappear, but the message prompt still showing. At this stage, the game is locked. Any keystroke can't fix this issue. Only refreshing and starting the game again fixes the issue, but you'll need to defeat the earlier foe again.
    
<ins>**To Reproduce**</ins>
1. Kill a foe
2. Wait for the store to show up.
3. Press the "Backspace" key
4. Press the "ESC" key
5. Know the game is locked.

<ins>**Expected behavior**</ins>
- Pressing the escape key should give the same function as selecting the option "No".

<ins>**Screenshots / Videos**</ins>
- No need for a screenshot, can be easily reproduced.

<ins>**Device**</ins>
- Windows 10, Chrome

<ins>**Additional context**</ins>
- None

**Comment by torranx** [comment]
I think all prompts asking Yes or No like when switching pokemon have this kind of bug.
