### ISSUE TITLE
[BUG] Multi Hit - Multi target moves not working if...

### ISSUE THREAD

**Issue by hightowernl** [pagefaultgames/pokerogue#1558]
**Describe the bug**
So I got thrown into a double battle, my Darkrai knows Fiery Wrath which hits both targets. It holds 3x multiple hit lenses so every time it attacks those attacks will hit 4 times. 1 of the opponent used Fly, Fiery Wrath missed that target, then only hit the other opponent 1x and then stopped. I think it should hit the other opponent 4x as that Pokemon wasn't using Fly/Dig or anything.

**To Reproduce**

1. Have a Pokemon hold at least 1 lens to hit multiple times
2. Get into a double battle
3. Pray 1 of the opposing Pokemon knows Fly/Dig/anything that would make your attack miss, and that they move first.
4. Use a move that hits both opponents.

**Expected behavior**

Miss the flying opponent and hit the other multiple times.

**Screenshots / Videos**

**Device**

PC

**Additional context**

**Comment by hayuna** [comment]
@hightowernl I've added recording how it looks like to bugfix would be addressed faster. 
- Both pokemons hold 3 multi lens.
- Its double battle
- Bulbasaur is using Dig
- Pidgey is using Fiery Wrath which attacks both foes

To the author: If something is wrong in my example, please comment it.

https://github.com/pagefaultgames/pokerogue/assets/19636010/c541b76e-113e-495c-8503-1abb541fea19

**Comment by Smewkie** [comment]
Can confirm this is also the behavior if you have a move that hits both pokemon and is less than 100% accuracy + multilens, hitting one pokemon but missing the other will result in the extra hits that should go to the pokemon you did hit to just not happen.

**Comment by innerthunder** [comment]
Fixed by https://github.com/pagefaultgames/pokerogue/pull/2648
