### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by whozhi** [pagefaultgames/pokerogue#1563]
**Describe the bug**
When I was playing this game, I found that when I used the DNA Splicers item to fuse a Pokémon with the Wonder Guard ability, which is a characteristic of Shedinja and Necrozma, sometimes the Wonder Guard ability does not work properly. That is, the effect of the Wonder Guard ability, which should make damage from non-restraining attributes ineffective, failed to activate. Here is the relevant video.

In this video, the Poison type is not super effective against Psychic and Ghost types. The weather condition on the field is rain, which should theoretically prevent damage to our side. However, damage is still being inflicted. Even after multiple refreshes, there is still no effect. I hope this issue can be resolved. At the same time, I wish this project will continue to grow and bring the joy of Pokémon to more people.

https://github.com/pagefaultgames/pokerogue/assets/145985199/07d7dac9-2ed5-4b75-b498-eae93b3b37e0

**Comment by molker** [comment]
please add a title describing the bug after [BUG]

**Comment by Fasin78** [comment]
Did you get gastro acid by a wild mon before this wave? Some of the gastro acid users are located in swamp and could have suppressed the wonder guard.

**Comment by hayuna** [comment]
Cannot reproduce this issue

I have fusion of Species.NECROZMA and Species.SHEDINJA with Abilities.WONDER_GUARD, fighting with Species.TOXAPEX and his attack Move.POISON_JAB has no effect

**Comment by Tempo-anon** [comment]
Cannot reproduce, but was probably gastro acid'd
