### ISSUE TITLE
[BUG] Softlock - maybe related to Giga Impact?

### ISSUE THREAD

**Issue by nbasu02** [pagefaultgames/pokerogue#1572]
**Describe the bug**

Softlocked each time I try and progress to a boss on my current run.  Happens each time I progress from 89 to 90.  My pokemon is recalled and then the game softlocks.

Based on the error message, possibly related to a missing image or sound effect for Giga Impact?

**To Reproduce**

Unsure, but maybe load an opponent or boss that uses Giga Impact?  This might be unrelated, but the message in the screenshot does come up when I try and progress to round 90.

**Expected behavior**

It at least shouldn't softlock

**Screenshots / Videos**

![Screenshot from 2024-05-29 15-28-13](https://github.com/pagefaultgames/pokerogue/assets/1032044/5b800d2f-1917-4368-b9f5-092f5574a409)

**Device**
Linux, Firefox

**Additional context**

**Comment by geefuoco** [comment]
Doesn't look like that image actually exists in the repo. Going to look a bit further and open a PR up

**Comment by Tempo-anon** [comment]
Please don't play on other websites. The official url is https://pokerogue.net/

**Comment by nbasu02** [comment]
> Please don't play on other websites. The official url is https://pokerogue.net/

Oh wild, didn't know - thanks

**Comment by Tempo-anon** [comment]
Closing since the fix to giga impact has been merged in
