### ISSUE TITLE
When resizing the browser to mobile and then back to desktop the mobile controls stay on screen and also don't anything

### ISSUE THREAD

**Issue by thomaswijers** [pagefaultgames/pokerogue#158]
Not really a big or important bug but just something I noticed.
![image_2024-04-16_192614754](https://github.com/pagefaultgames/pokerogue/assets/81619890/c10edcfd-f8ba-4ed3-98fa-4144f9b6f939)

**Comment by bennybroseph** [comment]
Cannot Reproduce
