### ISSUE TITLE
[BUG] Shiny sprite (Mareanie) not displaying in battle

### ISSUE THREAD

**Issue by GITitdoneboi** [pagefaultgames/pokerogue#1589]
![438095030_473808455050984_4372293791182063958_n](https://github.com/pagefaultgames/pokerogue/assets/51449288/db8eb457-c1b0-4fcd-82f8-a16672b3c760)
![438060646_418441464287297_6446592488643044029_n](https://github.com/pagefaultgames/pokerogue/assets/51449288/d57f622b-4435-4483-ac65-0327a9dc2e41)
![438069862_807349021327189_667546654044392249_n](https://github.com/pagefaultgames/pokerogue/assets/51449288/4429d20d-8a46-40be-b8c2-1be4d1df8116)

Shiny sprite (Mareanie) **not** displaying in battle

Shiny sprite **is** displayed in Pokémon List and Summary

**Comment by flx-sta** [comment]
If I remember correctly those missing back sprites were added
