### ISSUE TITLE
[BUG] Incoming pokemon burned by flame body after flip turn

### ISSUE THREAD

**Issue by travbp** [pagefaultgames/pokerogue#1599]
**Describe the bug**
Pelipper used flip turn on a Flame Body Talonflame. The incoming Pokémon that replaced Pelipper (Barraskewda) got burned by flame body.

**Expected behavior**
Pelipper burned by Flame Body

**Comment by torranx** [comment]
please provide title

**Comment by flx-sta** [comment]
Cant repro
