### ISSUE TITLE
[BUG] Missing descriptions in locales/en/modifier-type.ts

### ISSUE THREAD

**Issue by InnocentGameDev** [pagefaultgames/pokerogue#1603]
**Describe the bug**
Some items seem to have missing descriptions in locales/en/modifier-type.ts

These include:

- Grip Claw
- Wide Lens 
- Multi lens 
- DNA splicers
- Mini Black Hole

**To Reproduce**
I was just doing some localization and came across this.

**Comment by Madmadness65** [comment]
They are there, under `ContactHeldItemTransferChanceModifierType`, `PokemonMoveAccuracyBoosterModifierType`, `PokemonMultiHitModifierType`, `FusePokemonModifierType`, and `TurnHeldItemTransferModifierType`, respectively. I agree that it is a bit confusing that they aren't marked as a "description" next to the item names, though.
