### ISSUE TITLE
[BUG] Fused Normal/Ghost type not immune to Fighting moves

### ISSUE THREAD

**Issue by aJaardvark** [pagefaultgames/pokerogue#1604]
**Describe the bug**
A fused Spiritomb and Raticate (Spicate) will take damage from Superpower. Spiritomb's Ghost typing should provide immunity to Fighting type moves.

**To Reproduce**

1. Fuse a Spiritomb and a Raticate
2. Be attacked in a battle by Superpower (possibly other fighting type move)

**Expected behavior**

A fused Pokemon with Ghost typing should not receive any damage from Fighting type moves.

**Comment by Tempo-anon** [comment]
Are you sure the opponent didn't have scrappy

**Comment by Smewkie** [comment]
or no guard, no guard as it's currently implemented bypasses type restrictions

**Comment by aJaardvark** [comment]
Ahhh, I'd checked for Scrappy, but not for No Guard. It was either a Machoke or Machamp so that is most likely it. Thank you!
