### ISSUE TITLE
[BUG] Roar Self target and animation

### ISSUE THREAD

**Issue by DustinLin** [pagefaultgames/pokerogue#1614]
**Describe the bug**

Opponent can target itself with roar, which shouldn't be possible. Additionally sprites become clear

**To Reproduce**

`overrides.ts` allow doubles, and set all opponents moves to roar

**Expected behavior**

Both of the above shouldn't happen

**Screenshots / Videos**

https://github.com/pagefaultgames/pokerogue/assets/39450497/3847ec5f-9091-4566-8799-fee12ff2296d

**Device**

**Additional context**

**Comment by DustinLin** [comment]
Just realized this is also referenced in issue #481

**Comment by flx-sta** [comment]
Related to #481
