### ISSUE TITLE
[Balance] Base Hidden Ability chance is extremely low

### ISSUE THREAD

**Issue by jaimefd** [pagefaultgames/pokerogue#1623]
**Short version**
- Increase Hidden Ability chance from eggs to 1/32
- Increase Ability Charm multiplier per stack from x2 to x4
- Decrease Ability Charm max stacks from 4 to 2
- Multiplier at max stacks remains unchanged

**Is your feature request related to a problem? Please describe.**

The current base hidden ability chance (I believe 1/128) is way too low, considering it's such a crucial aspect for many Pokémon, who can only shine and are balanced around it. A low rate like this works in the main line games, as there's ability patches and many other elements that massively increase the odds. However, the only currently "viable" way to get them is with long Endless runs, where getting all 4 Ability Charms is realistic.

However, unless I'm mistaken, it has been stated multiple times that the game is mostly balanced around Classic. And you will rarely ever get more than 1 Ability Charm per Classic run, if any. The situation gets even worse for Eggs, since there's no way to reduce the odds for them. 1/128 is VERY low for eggs, there's already so much RNG involved in getting the species you want, and even shinies have a higher chance, which makes no sense, and looks like a forgotten feature.

**Describe the Feature**

Eggs are the biggest losers here. I would, at least, increase the base odds by 4 or 8. If we compare hidden abilities to shines, they should be more common. If we compare them to egg moves, they offer a similar upgrade value to Rare Egg Moves. That is why I believe that a **1/32 chance** would be ideal for eggs. Hidden Abilities are essentially a third ability, often worse than base abilities, there's no reason to be rarer than this.

To balance it for wild encounters, I would **double the effectiveness of each Ability Charm, while halving the max stacks**. So each stack would quadruple the odds, but the maximum possible chance will remain the same since the maximum stacks is 2 now instead of 4. This would keep Endless at the same rate, while allowing Classic players to opt for HA hunting if that's what they wish.

**Additional context**

That's all I had to say, I assume the team may have good reasons to keep HA chances low, but hopefully my ideas could be considered, as they will keep hidden abilities as a rarer and valuable ability, while not being virtually non-existent outside of lategame Endless.

**Comment by Tempo-anon** [comment]
HA rates from species eggs have been increased. Closing this out for now.
