### ISSUE TITLE
[BUG] HP Recovery seems to be bugged at higher HP values

### ISSUE THREAD

**Issue by Smewkie** [pagefaultgames/pokerogue#1626]
As seen in multiple bug reports on the discord:

https://discord.com/channels/1125469663833370665/1245880756987887696

https://discord.com/channels/1125469663833370665/1242294328613671073

https://discord.com/channels/1125469663833370665/1241732423788789833

https://discord.com/channels/1125469663833370665/1240787947855548418

From gathering data it seems to be specifically a leftovers problem, but I'm hesitant to say it's -only- leftovers, they would just be the most likely place to start.

**To Reproduce**
1: have a high HP value, I believe I've seen this happen as low as 50k
2: Get knocked down to 1 HP as usually happens in late game endless
3: Heal to almost full with a combination of enigma, sitrus berries, shell bell, and leftovers, with max healing charms.
4: should have a few hundred HP short of full health.
5: Subsequent turns with Protect will not heal those few hundred HP.

**Additional context**
This bug got introduced semi-recently, I believe in the last few weeks.

**Comment by minyukim** [comment]
This issue is under discussion here: https://github.com/pagefaultgames/pokerogue/pull/1877
