### ISSUE TITLE
Lost data from several runs [BUG]

### ISSUE THREAD

**Issue by DaMan246** [pagefaultgames/pokerogue#1632]
**Describe the bug**

I was using my Windows Laptop and Windows gaming device throughout the night and got several new shinies and legendaries.  I ended the night playing on my iPhone and then the next morning all the data from these runs were lost.  My shinies and legendaries caught, along with other new starters, were lost. It is like I never did any of the runs over the roughly 6 hour span. The mons were saved while playing but were seemingly lost over night.

**To Reproduce**

1. Play a few runs
2. Swap devices
3. Possibly wait a certain time or server reset

**Expected behavior**

The data from runs is saved and shared across devices.

**Screenshots / Videos**

Data file is attached

**Device**

Initially, 2 different windows laptops, then iPhone, still no issue, next day was the same windows laptop as the night before.

**Additional context**

[N/A]
[data_DaMan246.zip](https://github.com/user-attachments/files/15507682/data_DaMan246.zip)

**Comment by flx-sta** [comment]
We are not able to recover lost user data. We put security measure in place for such now to mitigate the issue
