### ISSUE TITLE
[BUG] Aegislash not reverting stance on fainting

### ISSUE THREAD

**Issue by RNGezeus** [pagefaultgames/pokerogue#1659]
Searches for similar reports?
Searched "Aegislash" "Stance change" "Blade form" "Shield form" and I didn't see it mentioned.

**Describe the bug**
Upon fainting Aegislash doesn't revert to shield stance stance forcing you to send it in as blade stance after revival.

**To Reproduce**
1: Turn Aegislash to sword form
2: Let it faint
3: Revive it
4: Switch it in

**Expected behavior**
Expect it to always start in shield stance, relevant if it doesn't know kings shield due to being caught in wild or intentionally deleted for a full coverage set.

**Screenshots / Videos**
https://github.com/pagefaultgames/pokerogue/assets/46976469/9bea9b98-a303-418a-94f3-acd7770991e4

**Comment by Tempo-anon** [comment]
This should have been fixed now
