### ISSUE TITLE
[BUG]Bombirdier  The screen gets stuck after the Bombirdier using the big cleaning

### ISSUE THREAD

**Issue by XDD0524** [pagefaultgames/pokerogue#1680]
**Describe the bug**
1.classic model 188
2.The Four Heavenly Kings Kahiri
3.The screen gets stuck after the Bombirdier used the tidy up

**Screenshots / Videos**
![1](https://github.com/pagefaultgames/pokerogue/assets/102139579/02f3d056-e6d7-4056-93ca-9d913574a3d5)

**Comment by Tempo-anon** [comment]
大扫除 is [Tidy Up](https://bulbapedia.bulbagarden.net/wiki/Tidy_Up_(move))

**Comment by XDD0524** [comment]
> 大扫除 is [Tidy Up](https://bulbapedia.bulbagarden.net/wiki/Tidy_Up_(move))

感谢纠正
