### ISSUE TITLE
[BUG] Aegislash always has a greyed-out pokeball

### ISSUE THREAD

**Issue by Terrorforge** [pagefaultgames/pokerogue#1687]
**Describe the bug**
The pokeball indicator for non-shiny Aegislash always shows as greyed-out to indicate you're missing a gender, ability or form, even if you have both genders and Aegislash's only ability and out-of-combat form.

**To Reproduce**
Capture a male and female Aegislash, then find a non-shiny Aegislash.

**Expected behavior**
Pokeball only shows as greyed-out if the player is missing that pokemon's gender, ability, form or Shiny tier.

**Screenshots / Videos**
![image](https://github.com/pagefaultgames/pokerogue/assets/5107449/e28d6b0d-f020-46d4-b20b-bb1071cc9c0c)
Wild Aegislash has greyed-out pokeball

![image](https://github.com/pagefaultgames/pokerogue/assets/5107449/d74d215c-8f99-483b-ac29-6558e1df336d)
![image](https://github.com/pagefaultgames/pokerogue/assets/5107449/e630d5bf-f291-46b7-8bd2-f0e880b4ab7a)
But I have both genders already.

**Device**
Chrome on PC.

**Additional context**
Session and profile data. I have just encountered a wild Aegislash with a greyed-out pokeball despite owning both genders of Honedge.
[Terrorforge_Aegislash.zip](https://github.com/user-attachments/files/15521504/Terrorforge_Aegislash.zip)

Presumably this has something to do with how the game treats Aegislash's form change gimmick, like it thinks you still need to catch Blade Forme or something. The indicator doesn't change when it changes form, though.

**Comment by RNGezeus** [comment]
I get Aegislash to show as litup, and given it enters battle as shield forme I'm gonna quickly guess the issue appears if you only catch it in bladeforme. which is very likely since Aegislash likely wont use Kingsshield to return to shieldform.

And unless you are in a deep endless run the chance you catch it before it changes form feel rather low.

**Comment by Terrorforge** [comment]
Can confirm. Caught one on the first turn before it transformed and the ball isn't greyed out any more.
