### ISSUE TITLE
Game frozen on level 25 trainer battle

### ISSUE THREAD

**Issue by anikoiau** [pagefaultgames/pokerogue#1689]
**Describe the bug**
At level 25, there is a rival battle. In it the rival brings out Throh which uses circle throw causing my pokemon to switch out. After switching in the next pokemon, the game freezes afterwards. I have tried clearing browser cache and cookies and also tried in Chrome, Edge and Firefox. But still nothing works

Error log:
```
TypeError: Cannot read properties of undefined (reading 'damage')
    at Ak.applyPostDefend (index-4637969b.js:14852:3011)
    at index-4637969b.js:14874:5092
    at applyAbAttr (index-4637969b.js:14874:4582)
    at applyNextAbAttr (index-4637969b.js:14874:4092)
    at index-4637969b.js:14874:4663
    at new Promise (<anonymous>)
    at applyAbAttrsInternal (index-4637969b.js:14874:3804)
    at applyPostDefendAbAttrs (index-4637969b.js:14874:5076)
    at index-4637969b.js:14985:1174
    at executeIf (index-4637969b.js:6363:75932)
```

**To Reproduce**
1. Reach level 25 in classic mode
2. Start the battle and defeat the first pokemon
3. Trainer brings out the second pokemon, Throh and it uses Circle Throw as its first move
4. User's pokemon switches out. User sends out the next pokemon
5. Thee game freezes and the following error log is visible on the browser console

**Expected behavior**
Game shouldn't freeze

**Screenshots / Videos**
![image](https://github.com/pagefaultgames/pokerogue/assets/53526184/175fa25d-510f-4e3c-bc73-e3b73df297b2)

https://github.com/pagefaultgames/pokerogue/assets/53526184/cf2d0580-4325-4c15-a162-0054f733d8ca

**Device**
Playing on PC. Issue happens in Chrome, Firefox and edge

**Additional context**
Possibly the error is on [this line](https://github.com/pagefaultgames/pokerogue/blob/060b1b2cccf7a8b2f7451c684f8a9e0dadcffde2/src/data/ability.ts#L643)

**Comment by torranx** [comment]
can we get your session data please?

**Comment by Jonasillo92** [comment]
i also get an error while playing and its not the first tim, i tried different thing but the game get frozen and with the time its says the game is corrup while trying to enter the save 
![image](https://github.com/pagefaultgames/pokerogue/assets/169928565/13e87569-8f4c-4aa8-8e94-1772825729b6)

**Comment by torranx** [comment]
> i also get an error while playing and its not the first tim, i tried different thing but the game get frozen and with the time its says the game is corrup while trying to enter the save ![image](https://private-user-images.githubusercontent.com/169928565/335818984-13e87569-8f4c-4aa8-8e94-1772825729b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjU0MzEsIm5iZiI6MTcxNzI2NTEzMSwicGF0aCI6Ii8xNjk5Mjg1NjUvMzM1ODE4OTg0LTEzZTg3NTY5LThmNGMtNGFhOC04ZTk0LTE3NzI4MjU3MjliNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxODA1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODczNTM2NjliZWVhMThlY2EyYzgwOTZjOGE4Zjk0NzM3YmZiNjU2ZWJiZGM0MDUyZWIwNzM4NzAyZDIwNmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.898swy6zT8CI8kfJbeCzENHpjTyJOiXwL4DtZ-_O_e4)

please provide session data so we can assess further

**Comment by anikoiau** [comment]
> can we get your session data please?

Can you please tell how to get that data?

**Comment by torranx** [comment]
<img width="1306" alt="Screenshot 2024-06-02 at 2 07 16 AM" src="https://github.com/pagefaultgames/pokerogue/assets/68144167/62515ce7-581a-4e14-9a16-229aee786d33">

i think you cant post it on github tho, please create a bug report on discord and @ me > @Swain

thanks!

**Comment by anikoiau** [comment]
@torranx Thanks for the info. 
[Session Data.zip](https://github.com/user-attachments/files/15522895/Session.Data.zip)
Attached my session data psrv file inside a zipped folder to comply with Github's restrictions. Also I was unsure about which channel to use for the bug report, so just followed what other people are doing are doing and posted on the game-feedback channel.
