### ISSUE TITLE
[BUG] using candies not available on new shiny marill

### ISSUE THREAD

**Issue by leodad11** [pagefaultgames/pokerogue#1691]
![캡처](https://github.com/pagefaultgames/pokerogue/assets/171432736/aa4a3630-f33f-4b90-b1a1-3e65a500a19e)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Device**

**Additional context**

**Comment by hightowernl** [comment]
I think giving candies is only allowed on baby Pokemon so I think Azurill should work

**Comment by leodad11** [comment]
> I think giving candies is only allowed on baby Pokemon so I think Azurill should work

do you know how to close this?

**Comment by hightowernl** [comment]
> > I think giving candies is only allowed on baby Pokemon so I think Azurill should work
> 
> do you know how to close this?

No idea haha, just wait for a mod I guess
