### ISSUE TITLE
Killing a wild Pokémon with Jaw lock still leaves the user trapped in the next battle

### ISSUE THREAD

**Issue by PulitoDelgado** [pagefaultgames/pokerogue#170]
What the title says. I haven't used Jaw Lock again to further investigate because it's too expensive to watch Dreadnaw be chipped away to death lol. I figure this only occurs during waves of wild Pokémon and should be working properly during trainer battles.

**Comment by BillyZ33** [comment]
It additionally doesn't work correctly during trainer battles. If you use Jaw Lock in a trainer battle, it traps your Pokémon for the entire battle as well. The only way to switch a Pokémon that has used Jaw Lock is in between battles.
