### ISSUE TITLE
[BUG] Fire types can give Flame Orb and Poison/Steel types can give Toxic orb

### ISSUE THREAD

**Issue by AsdarDevelops** [pagefaultgames/pokerogue#1706]
**Describe the bug**
Fire types put Flame Orb in the pool and Poison/Steel types do the same with Toxic orb.

Unimplemented moves activate the odds for the orbs as well.

**To Reproduce**
Get Chimchar line and level it up to lvl 31 so it learns Facade
Roll a lot
Find Flame Orb because you have Facade and be sad because you lost an ultra roll. 

**This did not happen previously**
I'd like to add that while the earlier implementation might've had some bugs in niche cases, this should not warrant discarding all the coding that went in place to avoid these cases, which would've not happened with the earlier version of the implementation.

I don't even think a conditional argument for the Flame Orb on a Fire type can be made. The most niche argument that can be made is that you may somehow need your fire type Pokémon to give you flame orb so you can "status block" in endless on a __different__ Pokémon that doesn't have Facade.

Toxic Orb is in a some spot, but with Toxic orb having even less of an argument to work as a "status block". Again this is only for Endless, no one is going to want to pre-burn PKMNs without the key abilities/moves in Classic. It also affects more Pokémons.

Fusions might be affected by this typing issue, but I have not checked that far.

Unimplemented moves can't be used but some like Fling will give you the Orbs as well. Should be considered for new players and for the cases where you catch the Pokémon with the unimplemented move and need to wait until it learns a different move to kick that one out. These moves should have been commented out. We can add them after implementation.

**Expected behavior**
One would expect running Facade on a fire/poison/steel type not to punish unnecesarily.

**Screenshots / Videos**
![image](https://github.com/pagefaultgames/pokerogue/assets/170796740/c1bde707-1425-4d15-879c-af1b2d084d04)

**Additional context**

**Comment by InnocentGameDev** [comment]
Also as a personal note, it takes forever to find these items when you want them, which I think should not be the case. I think it's pretty clear you want a Toxic Orb when running a Poison Heal mon, else you're running one less ability until you hit that. This is not an issue in core games where you can just have your fight with the item already selected.

But these are just my views on balance and are aside the point of the bug submission.

**Comment by Snailman11** [comment]
I don't this is a bug necessarily. (Ponyta enabling flame orb drops.)
https://discord.com/channels/1125469663833370665/1265037848227348662

https://discord.com/channels/1125469663833370665/1251317886547398668/1261011296753680485 (This would probably all under enhancement)
