### ISSUE TITLE
[BUG] Money cap at Number.MAX_SAFE_INTEGER means everything eventually costs the maximum money you can hold

### ISSUE THREAD

**Issue by Mattadore** [pagefaultgames/pokerogue#1714]
**Describe the bug**
Money and cost are currently capped at Number.MAX_SAFE_INTEGER but in endless that is very reachable, and at some point it's not possible to gain more money and everything just costs the max amount of money it is possible to hold.

**To Reproduce**
Reach 5000s in endless

**Expected behavior**
Uncapped money and cost

**Screenshots / Videos**
![image](https://github.com/pagefaultgames/pokerogue/assets/10523441/d43c1c2e-1f26-43f9-82e5-9751b84e7302)

**Device**
Browser

**Additional context**
It seems like you'd need to replace money and cost variables with Javascript BigInt or string to allow uncapped integer size.

**Comment by YounesM** [comment]
Since every cost is relative to the floor your at anyway would'nt be be easier to have a smaller cap (1M for example) and fixed item costs at some point? 
I don't see the point of having big money numbers when you have to pay x% of it to get an item anyway.

**Comment by Mattadore** [comment]
Big numbers make dopamine go brrr.

I mean, if they want to rework the entire pricing system to avoid reaching the double precision floating point integer cap that's fine but this seems more straightforward. Either way, it's currently broken

**Comment by flx-sta** [comment]
Idk if I would call this a bug but rather a given limitation due to types

**Comment by Tempo-anon** [comment]
Late game endless gets pretty degenerate. It's been a common occurrence that eventually rerolling and hoping for what you want is the strat.
