### ISSUE TITLE
[BUG] Toxic doesn't reset damage scaling

### ISSUE THREAD

**Issue by RNGezeus** [pagefaultgames/pokerogue#1723]
Did I find similar topics?
I cleared filter and searched "Toxic" and none of the results mentioned anything in their title.

**Describe the bug**
Toxic keeps ramping until its cured and can't be reset by switching.

**To Reproduce**
Get Badly poisoned, I have tested by Orb and Move:Toxic
Play normally to let damage ramp
recall pokemon, manually or forced with trainers / biome change

**Expected behavior**
Toxic to reset the ramping damage counter back to minimum

**Screenshots / Videos**
Still ramping during constant switching
https://github.com/pagefaultgames/pokerogue/assets/46976469/779b3188-e7cf-430f-b794-c0054bb0a387

**Additional context**
https://bulbapedia.bulbagarden.net/wiki/Poison_(status_condition)
"A badly poisoned Pokémon will remain badly poisoned even if switched out or the battle ends, although the counter is reset."

**Comment by Dakurei** [comment]
Fixed in https://github.com/pagefaultgames/pokerogue/commit/942c1198149011f6c4077d4103a6024a28112685
