### ISSUE TITLE
Password not working [BUG]

### ISSUE THREAD

**Issue by OceaneMion** [pagefaultgames/pokerogue#1725]
There is some user including myself that have some problem with the login saying that the password is wrong.What is strange is that I'm quite sure it is the good password.
Do you now how can I get back my password from my username ?

**Comment by CodeTappert** [comment]
This isnt the place for that. 

See the #password-reset  in the discord. 

And close this issue

**Comment by OceaneMion** [comment]
Thanks for your help did not mean to bother
