### ISSUE TITLE
[BUG] Sleep talk Damages own teamates

### ISSUE THREAD

**Issue by Heroaki341** [pagefaultgames/pokerogue#1727]
When using sleep talk in double battles, if there are no enemies on the field it will choose to target it's team mate and roll one of the moves to use. (in this case hammer arm) 

It shouldn't be too hard to reproduce, just enter any double battle and defeat all the opponent pokemon before sleep talk is used and it'll choose to attack it's team mate.

I had expected it to fail like other moves that are used after all opponents are defeated.  

Here are the screenshots
![Screenshot (4)](https://github.com/pagefaultgames/pokerogue/assets/141649405/c2a35cf7-2245-4b9e-b1c8-c3751427ae40)
![Screenshot (5)](https://github.com/pagefaultgames/pokerogue/assets/141649405/6ef33a4e-be97-47cc-a519-0ac9decfcf0d)
![Screenshot (6)](https://github.com/pagefaultgames/pokerogue/assets/141649405/a32bbf79-326c-465d-9f67-23cbf2627959)

I'm currently playing on a PC.

Sorry if this is a bad report, first time using Github as anything other than a download source.  P.S Loving the game!

**Comment by DustinLin** [comment]
able to reproduce:

https://github.com/pagefaultgames/pokerogue/assets/39450497/0a339b18-31b5-4925-9e48-7dbf96b323ff

**Comment by DustinLin** [comment]
I'll take a look into fixing this

**Comment by DustinLin** [comment]
should be closed/fixed from the above PR being merged
