### ISSUE TITLE
No-Guard ability doesn't work as in this example, my Machamp failed Dynamic Punch while having No-Guard ability

### ISSUE THREAD

**Issue by Sharp8** [pagefaultgames/pokerogue#173]
![machampFailedDynamicPunchPokeRogue](https://github.com/pagefaultgames/pokerogue/assets/63881741/adc7577b-77d8-4538-ba78-70cf86104745)

As you can see I used one PP of Dynamic Punch and that Gyarados still full HP (believe me I used this move with him).

I do not know whether I have to provide any files, more evidence or proof for this matter to be taken into account.

**Comment by Flashfyre** [comment]
(N) means not implemented

**Comment by Sharp8** [comment]
> (N) means not implemented

Oh I see now thanks, but it means if this implements I can still be where I left the battle? Or it must reset the run?

**Comment by Flashfyre** [comment]
It will automatically update when added.
