### ISSUE TITLE
Implement TMs/HMs Move Preview

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [pagefaultgames/pokerogue#1731]
**Is your feature request related to a problem? Please describe.**
It is frustrating that you cannot see what the move of a TM/HM does until you try teaching it to a Pokémon. I always end up having to consult an outside resource like Bulbapedia or PokemonDB to see the effects of a move, in order to not waste an item by discarding a TM/HM.
Currently, you can choose to not learn the move after trying to teach it to the Pokémon, but that discards the TM/HM and prevents you from selecting a different item.

**Describe the Feature**
It would be greatly appreciated if there were a way to view what the TM/HM move does and compare it to a Pokémon's existing moves (as seen in the third screenshot), without having to commit to selecting the TM/HM as your after-battle item of choice.

**Additional context**
![image](https://github.com/pagefaultgames/pokerogue/assets/142738275/20a616c0-3faf-4e09-aa09-07c032ec268e)
![image](https://github.com/pagefaultgames/pokerogue/assets/142738275/a0ecdad4-1d01-437b-a878-f79732bf7947)
![image](https://github.com/pagefaultgames/pokerogue/assets/142738275/c79e0c16-09c0-47d4-b372-36d241ce337a)

**Comment by torranx** [comment]
if im not mistaken, i think someone is already working on this

**Comment by Tempo-anon** [comment]
Yes done in https://github.com/pagefaultgames/pokerogue/pull/1585

**Comment by FruityGumGuiltyFruit** [comment]
My bad, thank you very much. I tried to search if something similar was already in the works, but couldn't find anything.
