### ISSUE TITLE
[BUG] Softlock attempting to open menu when asked to switch pokemon

### ISSUE THREAD

**Issue by rbmclean** [pagefaultgames/pokerogue#1736]
**Describe the bug**
Attempting to open the menu when asked if you want to switch pokemon softlocks. The menu doesn't open, you are still asked if you want to switch, but the yes/no options are gone and the accept/cancel buttons do nothing.

**To Reproduce**
1. Play until asked "do you want to switch pokemon".
2. Press "m"
3. Note softlock

**Expected behavior**
Either open the menu on pressing M, or do nothing and keep the switch options on screen

**Screenshots / Videos**
![image](https://github.com/pagefaultgames/pokerogue/assets/6756519/2ccab603-4294-48ff-af4b-9cce4943a9cb)

**Device**
PC - firefox

**Comment by NekodNekod** [comment]
happens too using admiral's app when pressing esc, softlocked.

**Comment by RNGezeus** [comment]
I think this a pretty wide issue, I feel I've softlocked every single yes/no option at least once in this manner by pressing ESC on browser. But it doesn't consistently happen every time. I'm gonna take a bit to actually explore the phenomenon.
