### ISSUE TITLE
Protect does not fail when it is supposed to

### ISSUE THREAD

**Issue by HyperRes** [pagefaultgames/pokerogue#1746]
**Describe the bug**
Protect should fail if the user goes last in the turn. In a single battle this means if both mons protect, the one that goes last should fail; if one mon uses protect and one uses helping hand, protect should fail; and if one mon switches and one uses protect, protect should fail. This works similarly in double battles. This is not implemented properly in PokeRogue. 

**To Reproduce**
Use protect.
The opponent switches.
Protect should fail but does not.

**Comment by frutescens** [comment]
Should be fixed in the next beta. Thank you for reporting.
