### ISSUE TITLE
[BUG] Money items fail when money puts you past 9 quadrillion

### ISSUE THREAD

**Issue by sambienvenu** [pagefaultgames/pokerogue#1748]
**Describe the bug**
On taking nugget, small nugget, or relic gold you get no money if it would put you over 9 quadrillion (9q) money. 

**To Reproduce**

1. Get to floor 4000+ on endless mode
2. Take nugget, big nugget, or relic gold at an amount that goes over 9q
3. See that your money has not changed
4. Also see that your Stats show as 9.007q for highest money

**Expected behavior**
Gain money. Alternatively, gain money up to some cap.

**Screenshots / Videos**
![image](https://github.com/pagefaultgames/pokerogue/assets/62450537/94050e2b-c06a-41af-a399-44a825d57052)

![image](https://github.com/pagefaultgames/pokerogue/assets/62450537/510dc601-33ef-4f86-b766-8ca2ee1fb526)

**Device**
Windows PC, Google Chrome

**Additional context**
This means I will run out of money for rerolls as I cannot gain money from items any longer, and there are no trainers in endless mode.

**Comment by Mattadore** [comment]
+1, have also encountered this issue and I'm not sure what to do

**Comment by HighMans** [comment]
The max money you can get is 9,007,199,254,740,991, once you drop down below that, you can get money to get back to the limit.

**Comment by sambienvenu** [comment]
> The max money you can get is 9,007,199,254,740,991, once you drop down below that, you can get money to get back to the limit.

This has never been the case for me. If I would go above a certain amount (I assume this value), I instead stay at my old value. For example if I am at 8q and I take a 20q nugget, I stay at 8q.

**Comment by hayuna** [comment]
Cannot reproduce

Initial money 8q
Nugget is adding 20q


https://github.com/pagefaultgames/pokerogue/assets/19636010/bc3d99e8-4018-4bf2-b38f-d4caa0cea0cc

**Comment by sambienvenu** [comment]
I think you (Highmans and hayuna) and are both are correct, and I must have already been at 9q the first few times I encountered this. I am seeing similar behavior with nugget right now. I will retest big nugget and relic gold to make sure.

**Comment by flx-sta** [comment]
Feel free to re-open if the bug appears again
