### ISSUE TITLE
[BUG] Game unrecoverable after error during Daily Run level-up

### ISSUE THREAD

**Issue by aptitudex** [pagefaultgames/pokerogue#1751]
Played daily run today-- leveled up Gholdengo. I have no memory of its level, the floor I was on, etc... but I think it received its XP via EXP share. The level-up animation rapidly repeated ad infinitum.

Now, I am completely unable to start the game. localhost loads with the default purple background color with no game instance Cache clear, server restart, etc have no impact.

Some added context from the browser logs:
`
http://localhost:8000/manifest.json
Error: Cannot create WebGL context, aborting.
    CreateRenderer phaser.js:16517
    boot phaser.js:17106
    DOMContentLoaded phaser.js:30952
    Game2 phaser.js:17078
    startGame main.ts:157
    <anonymous> main.ts:168
    promise callback* main.ts:166
`
`
[main.ts:24:10](http://localhost:8000/src/main.ts)
    <anonymous> main.ts:24
    (Async: EventListener.handleEvent)
    <anonymous> main.ts:22
`
`
Uncaught (in promise) Error: Cannot create WebGL context, aborting.
    CreateRenderer phaser.js:16517
    boot phaser.js:17106
    DOMContentLoaded phaser.js:30952
    Game2 phaser.js:17078
    startGame main.ts:157
    <anonymous> main.ts:168
    promise callback* main.ts:166
`
`
[phaser.js:16517:41](http://localhost:8000/node_modules/phaser/dist/phaser.js)
​`

Have been having a lot of fun so would love a point in the right direction on recovering my save file at least if possible.

**Comment by Tempo-anon** [comment]
Can't reproduce. Please open up another issue if this persists.
