### ISSUE TITLE
[Feature] (Localization to Korean) Trainer dialogue

### ISSUE THREAD

**Issue by sodaMelon** [pagefaultgames/pokerogue#1761]
Hello everyone,

I thought it might be helpful to create a dedicated thread for discussing all aspects of our Korean localization project. This will give us a centralized place to share updates, ask questions, and collaborate more effectively.

🎶담당자: @returntoice @Ohmry @sodaMelon  - (NEW participants are also welcome. Tagging here or metion me)

---------------------------------
---------------------------------
---------------------------------
**Is your feature request related to a problem? Please describe.**

When I play the game in Korean mode, the trainer's dialogue are still printed out in English.

**Describe the Feature**

We are now going to translate them into Korean as well.

**Additional context**

- 이 작업에 대한 논의는 [PokéRogue wiki Discord](https://discord.gg/hJQX8jNf)에서 진행하고 있습니다.  (on translation korean channel)
- If you have any problem or new suggestion, comment to this issue.
Or contact me on Discord& my email(sodamlee315@gmail.com)

Let's use this space to:
Share progress updates
Discuss any challenges or roadblocks
Share resources and tips
Collaborate on specific tasks
Looking forward to our continued work together!

**Comment by sodaMelon** [comment]
1. (번역해야하는 대사들이 담긴 파일은) pokerogue\src\locales\ko\dialogue.ts 에 있습니다.
2.  일반트레이너 - 관장 - 사천왕 - 더블순으로 대사가 배치되어있습니다.
3.  최신 버전 대사는 defeat 부분 말고는 전부 본가에 있는 대사를 그대로 가져온 것으로 추정됩니다. 

## 트레이너 종류
- [ ] 일반 트레이너 : @Ohmry 님이 해주시고 있는 듯? (새벽이라 천천히 확인할게요!)
- [ ] 체육관 관장: (양이 많아 세대별로 나눌 필요있어보임)
- [ ] 사천왕
- [ ] 더블배틀 트레이너


##작업방식
PR을 일일히 넣기는 파일이 1개이고, 작업량이 많으므로
 **GOOGLE Docs나 Sheet**같은 "동시편집도구"로 진행예정에 있습니다.

**Comment by sodaMelon** [comment]
@MrWaterT 안녕하세요~ 어제 디코로 메시지를 드리긴했는데 너무 시간이 늦어서 못보신거같아가지고 여기에도 멘션 드립니다.
최초 번역 감사드려요!! 덕분에 게임 너무 재밌게 잘하고있습니다 ㅎㅎ😁😁

이 이슈는 트레이너 대화 스크립트가 한국어 번역이 안된 것 같아서 생성했습니다. PokéRogue Community Discord의 dev_corner 채널에 여쭤보니 Tempo-anon님이 스레드 세워서 기존사람들&다른사람들이랑 같이 진행하라고 하셔서요~.  (디코메시지는 그래서 드리게됐습니다.)
그래서 기존 번역자을 찾다가 returntoice님이 PokéRogue wiki Discord에 사람들 모여있다길래, 거기에서 의견 나누고 번역 협업 진행중입니다. 


※※※혹시 @MrWaterT 님이 기존에 계획하고 있으셨던 게 있으면 알려주세요! 도와드리고 싶습니다.

**Comment by sodaMelon** [comment]
# 진척사항 (Progress)
https://docs.google.com/spreadsheets/d/1ErDf1NMQWZob6arMI8-Xs4vLANDSisOWhiedhPng79k/edit#gid=0 (문서 소유자:Ohmry님)

**Comment by MrWaterT** [comment]
> @MrWaterT 안녕하세요~ 어제 디코로 메시지를 드리긴했는데 너무 시간이 늦어서 못보신거같아가지고 여기에도 멘션 드립니다. 최초 번역 감사드려요!! 덕분에 게임 너무 재밌게 잘하고있습니다 ㅎㅎ😁😁
> 
> 이 이슈는 트레이너 대화 스크립트가 한국어 번역이 안된 것 같아서 생성했습니다. PokéRogue Community Discord의 dev_corner 채널에 여쭤보니 Tempo-anon님이 스레드 세워서 기존사람들&다른사람들이랑 같이 진행하라고 하셔서요~. (디코메시지는 그래서 드리게됐습니다.) 그래서 기존 번역자을 찾다가 returntoice님이 PokéRogue wiki Discord에 사람들 모여있다길래, 거기에서 의견 나누고 번역 협업 진행중입니다.
> 
> ※※※혹시 @MrWaterT 님이 기존에 계획하고 있으셨던 게 있으면 알려주세요! 도와드리고 싶습니다.

작업 내용도 예정도 딱히 없으니 신경 쓰지 않으셔도 될 것 같습니다.

**Comment by dorri-riddo** [comment]
@sodaMelon @MrWaterT 안녕하세요, 포케로그 한글 번역/로컬리이징 관심 있어서 연락 드립니다.

[번역 진척도 문서](https://docs.google.com/spreadsheets/d/1ErDf1NMQWZob6arMI8-Xs4vLANDSisOWhiedhPng79k/edit?gid=0#gid=0) ramos, viola 에 제 깃허브 아이디를 남겨두었는데, 
PR 이전까지 번역담당자 지정을 어떻게 하실지 몰라 겹칠 때를 대비하여 여기에도 멘션 드립니다.
좋은 하루 보내세요.

**Comment by returntoice** [comment]
> @sodaMelon @MrWaterT 안녕하세요, 포케로그 한글 번역/로컬라이징 관심 있어서 연락 드립니다.
> 
> [번역 진척도 문서](https://docs.google.com/spreadsheets/d/1ErDf1NMQWZob6arMI8-Xs4vLANDSisOWhiedhPng79k/edit?gid=0#gid=0) ramos, viola 에 제 깃허브 아이디를 남겨두었는데, PR 이전까지 번역담당자 지정을 어떻게 하실지 몰라 겹칠 때를 대비하여 여기에도 멘션 드립니다. 좋은 하루 보내세요.

저희 모두 포케로그위키 디스코드(https://discord.gg/CUmj49RT)의 한국어 채널에서 관련 이야기 진행하고 있습니다! 이쪽으로 와 주시면 될 듯해요.

**Comment by flx-sta** [comment]
So.. this issue is used as a Chatroom for Korean translation? So keep it open ?

**Comment by sodaMelon** [comment]
@Flashfyre 
hi
Maybe it's almost over!
I will close.

**Comment by flx-sta** [comment]
@sodaMelon wrong person tagged but thanks for clearing that up

**Comment by sodaMelon** [comment]
OMG
 
Fixed now @flx-sta, have a nice day
