### ISSUE TITLE
[BUG] Toxic Chain Activates on Status Moves

### ISSUE THREAD

**Issue by xdotsv** [pagefaultgames/pokerogue#1767]
**Describe the bug**
The Toxic Chain ability badly poisoned my Pokemon when a status move was used

**To Reproduce**
1. Encounter a member of the loyal three
2. Hope that the loyal three member uses a non-damaging move AND gets the 30% toxic chain activation
3. See error

**Expected behavior**
Toxic Chain should only activate on a damaging move.

**Screenshots / Videos**
N/A

**Device**
Android Phone

**Additional context**
In my specific case, it was Fezandipiti using the move Flatter.

**Comment by DustinLin** [comment]
Can we get a source for the expected behavior? I don't see the requirement that it needs to be a damaging move anywhere (bulbapedia, pokemondb, smogon)

**Comment by drew9696** [comment]
I’ve found 2 unofficial sources that reinforce this:
https://www.smogon.com/forums/threads/toxic-chain-update-description.3731624/


https://videogames.si.com/guides/pokemon-scarlet-violet-toxic-chain

**Comment by Snailman11** [comment]
Link to Toxic Chain on Discord https://discord.com/channels/1125469663833370665/1247816303054422061
