### ISSUE TITLE
[Feature] Achievement for maxing out Luck

### ISSUE THREAD

**Issue by Terrorforge** [pagefaultgames/pokerogue#1768]
**Is your feature request related to a problem? Please describe.**

Just hit SSS Luck for the first time and was surprised there wasn't an achievement for it.

**Describe the Feature**

Achievement that unlocks when you have 14 Luck and hit SSS rank. Call it "High Roller" and use the Epic shiny sparkle as an icon, maybe?

**Additional context**

**Comment by Tempo-anon** [comment]
Will consider new achievements in the future.
