### ISSUE TITLE
[Feature] Starter page filters

### ISSUE THREAD

**Issue by Terrorforge** [pagefaultgames/pokerogue#1770]
**Is your feature request related to a problem? Please describe.**

There are so many starters with so many interesting features that it quickly becomes hard to keep track of what you've unlocked, what you're still working on, what you meant to try, etc. The starter screen tries to convey a lot of this information, but it almost tries too hard - when you're looking for, say, your shinies, there's so much else happening it's easy to get lost.

**Describe the Feature**

A button to the side that lets you select a few filters to sort through the starter page. Any starter the doesn't fit the filter is grayed out like when you don't have enough points left to select it.
The dream would of course be some very sophisticated search where you can select by pokemon that know a certain move and evolve a certain way etc., but that sounds like a UI nightmare. Probably best to keep it to a handful of simple categories. My suggestions:

- Shiny
- Passive unlocked
- Hidden ability unlocked
- Egg moves unlocked: None/Some/All
- Pokemon of a certain type

All of these could also include their negations, e.g. show only pokemon that AREN'T shiny, and you could allow players to activate multiple filters to e.g. show only Fire-types with unlocked Passives

**Additional context**

**Comment by Tempo-anon** [comment]
Will be done with https://github.com/pagefaultgames/pokerogue/pull/2916
