### ISSUE TITLE
[BUG] Ice Hammer does not work with Contrary

### ISSUE THREAD

**Issue by Terrorforge** [pagefaultgames/pokerogue#1773]
**Describe the bug**

Used Ice Hammer on Lurantis with Contrary. Instead of getting a speed boost as expected, got a speed drop instead.

**To Reproduce**

1. Get Contrary Lurantis
2. Click Ice Hammer
3. Get speed drop

**Expected behavior**

Ice Hammer causes a speed drop. Contrary is supposed to reverse it, turning it into a speed boost.

**Screenshots / Videos**
![image](https://github.com/pagefaultgames/pokerogue/assets/5107449/8c36497d-36fa-4c8d-8859-1ef2bff15707)
-1 speed after using Ice Hammer (in previous fight)

![image](https://github.com/pagefaultgames/pokerogue/assets/5107449/c07f6f45-ed00-4316-952b-8274f96b587e)
Pokemon is Contrary.

**Device**
Chrome on PC

**Additional context**

**Comment by drew9696** [comment]
I was unable to reproduce this locally

**Comment by RNGezeus** [comment]
I am unable to reproduce on official browser.

Did you get any other contrary move effect to test in that session? Did you test ice hammer further in same session? is session available for others try?
