### ISSUE TITLE
[BUG] Alternate form Pikachu enable MaxMushroom in item pool but cannot use it

### ISSUE THREAD

**Issue by RNGezeus** [pagefaultgames/pokerogue#1785]
Have I searched?
Tried looking up "Pikachu" and "Cosplay" to find similar topics.

**Describe the bug**
Cosplay and Partner Pikachu enable MaxMushrooms to appear in item pool, but they can't make use of it

**To Reproduce**
Have only alternate form pikachu as Gmax possiblity
Reroll rogue items for MaxMushroom
Use Mushroom on Pikachu

**Expected behavior**
I expect Pikachu to either Gmax or the shrooms to not be available

**Screenshots / Videos**

https://github.com/pagefaultgames/pokerogue/assets/46976469/9e4d8034-9df3-48f2-a0df-da8ea88813c9

**Additional context**
Cosplay Pikachus getting Partner stats reduce need of this, but it still needs to be addressed in case you want the stat spread of G-max and because this creates a useless item roll that fools players.

In the time I found 3 max mushrooms I did not find any thunder stone so I presume they work as intended but cannot confirm.

**Comment by Snailman11** [comment]
Link to Discord (costume pikachu can take the max mushroom but not dynamax) https://discord.com/channels/1125469663833370665/1267743684212949014

**Comment by Snailman11** [comment]
Post August Update, this is still a thing

**Comment by frutescens** [comment]
TY for reporting. The fix will be in the next update.
