### ISSUE TITLE
[BUG] Cosplay Pikachu can use thunderstone to no effect

### ISSUE THREAD

**Issue by RNGezeus** [pagefaultgames/pokerogue#1787]
Have I searched?
Tried looking up "Pikachu" and "Cosplay" to find similar topics.

**Describe the bug**
Cosplay Pikachus's can make use of thunderstone but it has no effect and wastes the reward

**To Reproduce**
Have a party that contains a Thunder stone evolution mon and cosplay Pikachu
Find thunder stone in reward
Use thunder stone on cosplay pikachu

**Expected behavior**
I expect either an error message same as mons that can't use them (see roserade in video), or it evolving into Raichu.

**Screenshots / Videos**

https://github.com/pagefaultgames/pokerogue/assets/46976469/48a9c8b2-a835-4eb1-b0fd-314b274de515

**Additional context**
By my rough testing the Cosplays themself do not add the stone to pool

**Comment by Gamez0** [comment]
This PR needs more attention.
When Partner Eevee can evolve but Cosplay Pikachu can't, it feels unnatural. I think it would be more natural if either both can evolve or neither can.

**Comment by Snailman11** [comment]
This Exists post August Update
 https://discord.com/channels/1125469663833370665/1253714819115384893

**Comment by frutescens** [comment]
TY for reporting. The fix will be in the next update.
