### ISSUE TITLE
[BUG] Guts Raticate affected by attack drop from Burn

### ISSUE THREAD

**Issue by Terrorforge** [pagefaultgames/pokerogue#1790]
**Describe the bug**

Found a Flame Orb. Got my Guts Raticate burned, and it's damage dropped by about half. So not only is it not exempted from the Burn attack drop like a Guts pokemon is supposed to be, it's also not getting the Guts attack boost, which would cancel out the Burn penalty. It's behaving as if it didn't have Guts at all.

**To Reproduce**

1. Acquire Flame Orb on Guts Raticate
2. Compare damage before and after getting burned
3. Check other Guts pokemon to see if the problem is universal

**Expected behavior**

Per [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Guts_(Ability)): 
> Additionally, a Pokémon with this Ability does not lose Attack due to [burn](https://bulbapedia.bulbagarden.net/wiki/Burn_(status_condition)).

**Screenshots / Videos**

![Screenshot 2024-06-04 12 52 21](https://github.com/pagefaultgames/pokerogue/assets/5107449/a24c20e7-1ea9-43e1-88bd-606115cbf597)
This is how much damage a wild Confagrigus takes from what's supposed to be a Super Effective Guts Strong Jaw Crunch. Before I got burned, this was doing ~90% to other Cofagrigus in the area.

![image](https://github.com/pagefaultgames/pokerogue/assets/5107449/056c10d8-2206-4b6d-a89e-c98cb4cd6fc7)
It has the correct ability.

**Device**
Chrome on PC. Verified that the problem also exists on my downloaded Android version.

**Additional context**

Session data: [sessionData2_Terrorforge_GutsBurn.zip](https://github.com/user-attachments/files/15550370/sessionData2_Terrorforge_GutsBurn.zip)

**Comment by RNGezeus** [comment]
you tried swapping it out and in again to verify this isn't just Mummy being active? It doesn't show on ability screen if it is.

**Comment by Terrorforge** [comment]
It was Mummy.
