### ISSUE TITLE
[BUG] Shiny displaying differently on web vs. mobile

### ISSUE THREAD

**Issue by Terrorforge** [pagefaultgames/pokerogue#1791]
**Describe the bug**

While investigating #1790 I noticed that when loading a web save on my Android, my Rare Shiny Raticate (black fur) was displaying as the Common Shiny version (golden fur).

**To Reproduce**

1. Start game with Rare Shiny pokemon on web
2. Load the save on mobile

**Expected behavior**

The selected Shiny variant remains the same regardless of platform.

**Screenshots / Videos**

![Screenshot 2024-06-04 12 52 21](https://github.com/pagefaultgames/pokerogue/assets/5107449/5ad69cc3-1cd4-4347-a068-3fca07e21143)
On PC web version.

![Screenshot_20240604_131042_Chrome](https://github.com/pagefaultgames/pokerogue/assets/5107449/a80f2db1-fae7-4907-a5c9-22061dd426d7)
On downloaded Android version.

**Device**

Chrome on PC, downloaded app version on Android phone.

**Comment by flx-sta** [comment]
Not able to reproduce on `beta` (29a5dd006868e14c80f9a5fbef6f6335a182bc89)
