### ISSUE TITLE
[BUG] battle crash

### ISSUE THREAD

**Issue by BubbleBear** [pagefaultgames/pokerogue#1798]
**Describe the bug**

![image](https://github.com/pagefaultgames/pokerogue/assets/17879773/0a61485d-355f-4a03-930c-517d9b48146d)
it happens on certain condition which i'm not quite sure, i'm going with Yveltal agains Grimer.
but with the error consoled, it is about reading undefined which requires a strict type check.

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Device**

**Additional context**

**Comment by Tempo-anon** [comment]
Reverted the commit that caused the issue. Ctrl f5 and you should be good to go
