### ISSUE TITLE
[BUG] Failed to resolve import "i18next-korean-postposition-processor" from "src\plugins\i18n.ts". Does the file exist?

### ISSUE THREAD

**Issue by Destacar123** [pagefaultgames/pokerogue#1804]
I pulled the new GitHub update using Powershell for my locally hosted version of PokeRogue, no errors with the update and it installed successfully. However when I go to launch the game I get the following error message:

"[plugin:vite:import-analysis] Failed to resolve import "i18next-korean-postposition-processor" from "src\plugins\i18n.ts". Does the file exist?
C:/Users/brand/Desktop/Pokerogue/pokerogue/src/plugins/i18n.ts:3:55
1  |  import i18next from "i18next";
2  |  import LanguageDetector from "i18next-browser-languagedetector";
3  |  import processor, { KoreanPostpositionProcessor } from "i18next-korean-postposition-processor";
   |                                                    ^      
4  |  import { deConfig } from "#app/locales/de/config.js";
5  |  import { enConfig } from "#app/locales/en/config.js";"

I have checked the location in question and the i18n.ts file has been installed, which I have also tried removing and manually reinstalling to the location with no difference in result. It will not let me play the game until this error has been addressed - apologies if this is a simple fix but I am a newbie at commands/coding, etc.

All I did was use the "git pull" command today on Powershell.

I have provided screenshots of the error message on the localhost, as well as the noted file in my file explorer.

I am playing on the Opera GX web browser on my Windows PC.

Nothing else to add, other than it was working perfectly until I pulled the new update files.

![Screenshot 2024-06-04 200828](https://github.com/pagefaultgames/pokerogue/assets/171732840/216922c9-e8fd-4012-b9f5-f8e7bf115069)

**Comment by XGSleepWalker** [comment]
Run npm install on your console and the error should go away.

**Comment by Destacar123** [comment]
This did indeed fix the issue, thank you
