### ISSUE TITLE
[QoL] Remember the last nature picked for each specie

### ISSUE THREAD

**Issue by walt253** [pagefaultgames/pokerogue#1810]
Sweeping through a list of natures types for each starter can be very tedious when you have a lot, a nice QoL would be to simply make the game remember the last nature the player picked for each specie.

**Comment by pmbarrett314** [comment]
Related #1446 and #1400

**Comment by prime-dialga** [comment]
Also implemented here #1401

**Comment by Dakurei** [comment]
Implemented in https://github.com/pagefaultgames/pokerogue/commit/111f4362fcc1f88f640923368297a0379257e11c
