### ISSUE TITLE
[Feature] Offline Mode

### ISSUE THREAD

**Issue by KillerDogeEmpire** [pagefaultgames/pokerogue#1812]
Is it possible to make it so you can grind offline and it save on your account then. I know that this might not be accepted but I feel like it's useful. I like to play pokerogue, but I don't always have internet and would like to continue progress on my account.

If in any way you can add a feature to play offline but gain progress that would be appreciated. even if it's only for single player if you add multiplayer. I just want to play on the go. Also doesn't help that I only have 1gb of data so I technically couldn't play on the go for very long currently.

**Comment by KillerDogeEmpire** [comment]
if this is a no, I will stop making feature requests. I am just curious and do want to enjoy the game more than I can now

**Comment by Greenlamp2** [comment]
well, i mean, it's in the roadmap, so ..
![image](https://github.com/pagefaultgames/pokerogue/assets/44787002/ebe3b9ac-9b1c-4b8f-9609-775f954cb764)

**Comment by KillerDogeEmpire** [comment]
@Greenlamp2 will ot also be for if there is no wifi, plus save the progress since that just says for when the servers crash
