### ISSUE TITLE
[BUG] Metal Burst fails 

### ISSUE THREAD

**Issue by hightowernl** [pagefaultgames/pokerogue#1816]
**Describe the bug**

Metal Burst calculates the damage the user took and then double it to the opponent, if the user moves last. I faced an Electabuzz that was faster and used Volt Switch. It switched into Electrode and my Metal Burst failed. It should do damage even if the opponent used a move like Volt Switch or U-Turn.
**To Reproduce**

1. Face a faster opponent with Volt Switch
2. Use Metal Burst while the opponent uses Volt Switch
3. Opponent switches into another Pokemon

**Expected behavior**

Metal burst should double the damage even when the opponent used a move that switched it out.
**Screenshots / Videos**

**Device**

PC
**Additional context**

**Comment by schmidtc1** [comment]
This bug also affects Mirror Coat and Counter, since the target is set to the attacker but the attacker switches out, the move fails instead of redirecting the target to the new opponent.
