### ISSUE TITLE
[BUG]The game save exits to the main menu.

### ISSUE THREAD

**Issue by cqDiarmuid** [pagefaultgames/pokerogue#1824]
Hello to all the developers. Today while playing the game, I encountered an issue. For the past few days, after completing the classic mode, I've been changing my phone's date to June 20th to try to obtain my favorite Pokémon. I did the same today, but after finishing, I changed the time back and found that I couldn't play the game normally. Any action involving the save file, like using candy, drawing from the gacha, or defeating a boss, causes the game to exit to the main menu, preventing me from playing. Does this mean my save file is corrupted? Or should I wait until June 20th? I really love this game and have invested a lot of time into it, so I hope my save file isn't ruined 😩. Please, could the developers help me with this?

**Comment by torranx** [comment]
unfortunately, that is what happens when you try to mess with the game to your own advantage. im 100% sure no dev will help you with that.

**Comment by cqDiarmuid** [comment]
> unfortunately, that is what happens when you try to mess with the game to your own advantage. im 100% sure no dev will help you with that.

Well, I really like Rayquaza, I have to pay attention to it next time.

**Comment by SerendipityBean** [comment]
> unfortunately, that is what happens when you try to mess with the game to your own advantage. im 100% sure no dev will help you with that.

1. Why respond just to be an ass?
2. It's a singleplayer game who gives a shit if he wants rayquaza.

**Comment by torranx** [comment]
> > unfortunately, that is what happens when you try to mess with the game to your own advantage. im 100% sure no dev will help you with that.
> 
> 1. Why respond just to be an ass?
> 2. It's a singleplayer game who gives a shit if he wants rayquaza.

i dont think im the one being an ass here. dont expect to mess with a system and not get an unexpected result like this. yes its a singleplayer game, but this game is online and op tried to get ahead of other players who may want the same rayquaza. if you want to play it at your own will and get everything you want, you can go offline.

wont be replying here anymore :)

**Comment by cqDiarmuid** [comment]
i don't know what happened. But when I logged into the game today, I found that I could play normally. Thank you, everyone.
Rayquaza is really cool. I hope everyone learns from my lesson and can draw it on the 20th.
