### ISSUE TITLE
[BUG] Screen starts flashing after evolution

### ISSUE THREAD

**Issue by afellowcorn** [pagefaultgames/pokerogue#1829]
**Describe the bug**
The screen started rapidly flashing after two Fletchlings evolved at the same time. More specifically, it started flashing after the first evolved and the screen switched back to the regular view, then back to the evolution screen for the second Fletchling.
Behaviour persists after saving and quitting to menu, as well as continuing afterwards. Reloading fixes display.

**To Reproduce**
Replication attempt was unsuccessful.

**Screenshots / Videos**
SEVERE FLASHING WARNING
https://github.com/pagefaultgames/pokerogue/assets/128231119/6b3fb9c3-11b7-4ca8-8570-b41bdc1c0417

**Device**
Windows 11 laptop, Firefox browser

**Additional context**
Whole team: Vivillion, Suicune, Bombirdier, Furret + 2 Fletchlings
Biome: Grassy Field
Wave: 23

Whole team on replication attempt: Shaymin, Nidorina, Meowth, Flamigo + 2 Fletchlings
Biome: Lake
Wave: 30

**Comment by flx-sta** [comment]
Unfortunately we are not able to debug/analyze this issue without any kind of reproduction guid/walkthrough. Feel free to reopen if able to
