### ISSUE TITLE
[BUG]cannot start the game 

### ISSUE THREAD

**Issue by XAw3s0mE** [pagefaultgames/pokerogue#1841]
if I’m loading the page there is just a purpleish screen. I need to reload the page a lot until the game starts. Then I’m loading my safefile and the game just freeze. Sometimes the safefile is loading. But then the game is freezing after a few waves. Can someone help me pls ?

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Device** windows 8, google chrome. 

**Additional context**

**Comment by CodeTappert** [comment]
Are you from Germany and or have Telekom as your Internetprovider?

**Comment by CodeTappert** [comment]
> Yeah I do. Why ?

They have problems with this game. So use a VPN and everything should be fine.

**Comment by XAw3s0mE** [comment]
Can I download a VPN for free ? Do you have a website ?
