### ISSUE TITLE
[BUG] Repeated inputs when on battery power

### ISSUE THREAD

**Issue by 3lueOCE** [pagefaultgames/pokerogue#1849]
**Describe the bug**
When playing on my laptop, without being plugged in to external power, the game repeats a single key press multiple times. 

**To Reproduce**
1. Open game
2. Disconnect laptop from external power source
3. Input key press tied to any of the recognised bindings
4. ~70% of the time, have the input repeated one or more times

**Expected behavior**
A single key press should result in a single control input

**Device**
Issue occurs in Opera GX browser and in local executable, both are Chromium based.
Device is an HP Spectre x360 laptop, running Windows 11 Home Version 23H2 (current at 27th March, 2024)

**Additional context**
Issue seems to be more common at higher game speed multipliers.

**Comment by Tempo-anon** [comment]
Addressed in https://github.com/pagefaultgames/pokerogue/pull/1842

**Comment by Greenlamp2** [comment]
and final fix there: https://github.com/pagefaultgames/pokerogue/pull/1936
