### ISSUE TITLE
[BUG] Cannot view TM details on mobile

### ISSUE THREAD

**Issue by ben-lear** [pagefaultgames/pokerogue#1865]
**Describe the bug**
New feature to view the effects of a TM move prompts for C or shift button, but C button does not appear on mobile when hovering over the TM

**To Reproduce**
Hover over TM in shop on mobile
![IMG_0574](https://github.com/pagefaultgames/pokerogue/assets/110984302/fcfd66d8-731f-40fc-90d8-62a89602614c)

**Expected behavior**
C button should appear so player can view summary

**Screenshots / Videos**

**Device**
iPhone 14

**Comment by prime-dialga** [comment]
#1893 should fix it, however testing is still required...
