### ISSUE TITLE
[BUG] Selecting other pokémon is possible while Manage Moves

### ISSUE THREAD

**Issue by hibiyasleep** [pagefaultgames/pokerogue#1879]
**Describe the bug**

**To Reproduce**
1. New Game
2. Focus at any pokémon
3. Manage Moves
4. Select any move
5. then instantly press any arrow key, BEFORE the second list appear
6. 
    1. if current cursor is on uncaught, then freeze
    2. else, showing other pokémon's moves.

by the way, this does not allow selection of impossible moves.

**Expected behavior**

Arrow key should be ignored between selections.

**Screenshots / Videos**

<img width="1194" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/5380174/ca750c7f-6629-4cec-bb33-bcf19143a950">

Frozen screenshot as 6. i.

<img width="1194" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/5380174/3a9ad6f9-9386-4ab4-b5a9-b7f881198ede">

Showing other pokémon's moves as 6. ii.

**Device**
macOS Chrome (PWA)

**Additional context**

**Comment by flx-sta** [comment]
Starter select ui is being redone with filters anyway rn.
