### ISSUE TITLE
[BUG] Shiny not able to rotate forms

### ISSUE THREAD

**Issue by Brassidius** [pagefaultgames/pokerogue#1887]
**Describe the bug**

**Expected behavior**
This issue happened after hatching a shiny mareep. I believe this issue is because the mareep has only the blue shiny sparkle, not the first yellow sparkle ✨️,  the other level2 shiny I have has both sets of sparkles next to them. My hypothesis is that, when the mareep hatched, the server pinged or had a skip. This led the hatched pokemon to miss out on the first ✨️ code? Perhaps the game just registers it as a normal mareep without the first shiny part.

**Screenshots / Videos**
![Screenshot_20240606_130541_Chrome](https://github.com/pagefaultgames/pokerogue/assets/171972439/a659c482-2198-42a5-979e-a3e2d608ab54)

![Screenshot_20240606_131341_Chrome](https://github.com/pagefaultgames/pokerogue/assets/171972439/f7b7c4c9-918e-4481-a8f3-a2e7f36145cb)

**Device**
This happened on my android device, I later confirmed the issue on my laptop as well.

**Additional context**
It's not a priority or really even a recreatable bug, just something I noticed and wanted to bring to your attention.

**Comment by Tempo-anon** [comment]
This issue happens because you do not own base Mareep. Can you try catching base Mareep?
