### ISSUE TITLE
Circle Throw fainting a pokemon causes phantom active pokemon

### ISSUE THREAD

**Issue by LucasTheDrgn** [pagefaultgames/pokerogue#19]
When player's active pokemon is fainted by Circle Throw (and presumably other "damage, then switch target" moves) the user will be prompted to send out a replacement pokemon, then Circle Throw continues resolving and prompts the player to send out another pokemon. Another stats bar slides in under the first pokemon's stats bar, and the second pokemon chosen is the one that the user is selecting moves for and is hit by attacks. The first pokemon chosen is not considered to have participated in the battle, but their exp received message is put in the info box as if it were the active participant. This effect persists through starting new battles. Switching to the incorrectly appearing pokemon seems to fix this.
![doublemon](https://github.com/pagefaultgames/pokerogue/assets/22486923/3afed67a-1d62-4f1c-acf3-acf2bbe0244d)
![doublemon2](https://github.com/pagefaultgames/pokerogue/assets/22486923/c625e977-73b1-48e6-832c-e2bd9e1ff945)

**Comment by molker** [comment]
fixed in [this commit](https://github.com/pagefaultgames/pokerogue/commit/96288d29ce22a9e8d285b78038cadb3e4b5d42b4)
