### ISSUE TITLE
[Feature] Add different rival pokemon

### ISSUE THREAD

**Issue by Arxalc** [pagefaultgames/pokerogue#1904]
**!! SPOILERS FOR FINAL CLASSIC BOSS !!**
I've edited this to focus the Rival's Rayquaza instead. Though I'm keeping this here in case this wants to be implemented int he future.
**Is your feature request related to a problem? Please describe.**

Not related to a problem. 
I think this would improve Classic replayability and spice things up a little. Since the final boss is always Eternatus, people tend to go for certain types of pokemon each time (cough Tinkaton). I believe this will encourage more varied teams. Also, it'll be cool.

**Describe the Feature**

* After beating Classic for the first time, other pokemon can now appear as the final boss. These will likely be form-changing legendaries ex. Origin Form Palkia, Primal Dialga, Mega Mewtwo, Koraidon, etc.
* Add unique dialogue like Eternatus's.
* (Maybe) add unique moves/items/interactions, like how GMax Eternatus has a Mini Black Hole that steals items. Ex. Primal Dialga's presence makes the duration of X-items fluctuate.
* In Endless, each 250th wave boss can be chosen from this pool.

The bosses will require review balance-wise.

**Additional context**

Made this before looking at how party is structured in the code. It's super easy to do. I'm closing this because the Devs can easily add this any time when they choose.

**Comment by skillor** [comment]
I am also playing pokerogue a lot and I totally agree with you. I think Classic Mode gets quite repetitive after some playthroughs. But don't you think it is even more important to let the rival have other legendaries, because we are seeing rayquaza even more than the final boss?

**Comment by Arxalc** [comment]
> I am also playing pokerogue a lot and I totally agree with you. I think Classic Mode gets quite repetitive after some playthroughs. But don't you think it is even more important to let the rival have other legendaries, because we are seeing rayquaza even more than the final boss?

🤔 True...
