### ISSUE TITLE
[BUG] Multiple lures with same remaining duration do not stack

### ISSUE THREAD

**Issue by anbecker** [pagefaultgames/pokerogue#1912]
**Describe the bug**
If you have multiple lures with the same remaining duration, their icons will stack, and they will not both be counted toward increased double battle encounter rate.

**To Reproduce**
Example: I have four super/max lures running. One of them has 5 battles remaining on it. I collect a regular lure from the end of a battle. Instead of adding a regular lure icon, the super lure with a '5' next to it increments to a counter of quantity 2 (the white number). I enter a boss battle. Despite having 5 lures running, it is only counted as four, so it is possible for it to be a single battle at a 50% chance.

**Expected behavior**
The new double battle lure should be listed separately from the pending ones, and should be counted toward increased doble battle encounter rate.

**Screenshots / Videos**
<img width="652" alt="Screenshot 2024-06-07 at 8 35 12 AM" src="https://github.com/pagefaultgames/pokerogue/assets/16811393/cf53b410-5ccd-4c5a-a674-c308816d50e3">

**Device**
Arc Browser (Chromium based), macOS. This info is irrelevant, but hey.

**Additional context**
5 lures should guarantee a double battle for bosses - if one is not counted, it hurts people's chances at a legendary boss encounter.

**Comment by kleenxfeu** [comment]
I second this, same issue on windows/edge

**Comment by CodeTappert** [comment]
l

**Comment by CodeTappert** [comment]
Closed as solved by the linked pr
