### ISSUE TITLE
[BUG] Users can "create" golden tickets via web developer tools

### ISSUE THREAD

**Issue by JonasLindermayr** [pagefaultgames/pokerogue#1914]
Via the developer tools it is possible to "create" golden tickets

There is a german youtube video about it.. he shows how to replicate it.
He spreads it also a lot over social media like tiktok.

https://www.youtube.com/watch?v=UQYVtS-MZT4

**Comment by CodeTappert** [comment]
Yeah i have seen this on Tiktok also.

**Comment by flx-sta** [comment]
It's client side-code after all... 
time to verify voucher counts through the server too

**Comment by CodeTappert** [comment]
> It's client side-code after all... time to verify voucher counts through the server too

Creates a lot of server load

**Comment by JulianStiebler** [comment]
Could you not define like a sanitizer that just rejects abnormal value changes send to the updateall endpoints? That would solve a lot of problems.

**Comment by flx-sta** [comment]
Well the general idea right now is:
There is no multiplayer.
You are only cheating yourself (except the scoreboard, but there is worse).
