### ISSUE TITLE
[BUG] Infestation incorrectly interacts with Ghost-type Pokémon

### ISSUE THREAD

**Issue by WillukuC** [pagefaultgames/pokerogue#1915]
**Describe the bug**
Infestation when used on a Ghost-type Pokémon deals damage, but its secondary effect is ignored.

**To Reproduce**
1. Send a Pokémon with Infestation vs a Ghost-type
2. Click on 'Infestation'
3. See error

**Expected behavior**
Infestation should deal damage and do damage over time to the Ghost-type. The reason this effect is ignored is because it also has a trapping effect, which is ignored by Ghost-types. The trapping is correctly ignored, but the per-turn damage should still take effect.

**Device**
PC (Firefox)

**Comment by Snailman11** [comment]
Link to Discord's Bug report: (ghost types dont take the dot from infestation)
https://discord.com/channels/1125469663833370665/1254970595465232394

**Comment by Snailman11** [comment]
Link To Discord's Bug report(No retreat can be used multiple times)
https://discord.com/channels/1125469663833370665/1244583333812506708

https://github.com/user-attachments/assets/6e7ef3dd-27f3-44d4-a7a8-5f5d037bf7ea

No retreat should fail after a ghost type uses it for the second time
https://replay.pokemonshowdown.com/gen9customgame-2191229406-qa9dqfkli10ddjccqlw48gm36gway59pw
