### ISSUE TITLE
Thousand Arrows super-effectiveness against certain flying types

### ISSUE THREAD

**Issue by creative-pig** [pagefaultgames/pokerogue#1917]
**Describe the bug**
Thousand Arrows is not super effective against flying types that have a secondary typing that is weak to ground.

**To Reproduce**
Use Thousand Arrows on a rock-flying, electric-flying, steel-flying, or fire-flying type Pokemon.

**Expected behavior**
The move should be super-effective in these cases.

**Device**
Browser, PC

**Additional context**
I believe this issue also applies to Pokemon with Levitate.

**Comment by RNGezeus** [comment]
All seems to work as intended, including the fact that move grounds them so any hits after first one will do super effective damage.

**Comment by creative-pig** [comment]
Apologies, I had no idea it was intended to work this way.
