### ISSUE TITLE
[BUG] Localization: German name of Surskit has typo

### ISSUE THREAD

**Issue by kvngrnr** [pagefaultgames/pokerogue#1925]
**Describe the bug**
The german name of the pokemon Surskit is wrong. It's "Geweiher" instead of "Gehweiher" (h is missing).

**To Reproduce**
1. Set the game to german.
2. Look at Surskit's name in the starter sceen or have a surskit in your party in a run.

**Expected behavior**
The correct german name is "Geweiher" as stated [here](https://bulbapedia.bulbagarden.net/wiki/Surskit_(Pok%C3%A9mon)#:~:text=German-,Gehweiher,-From%20gehen%20and) or [here](https://pokewiki.de/Gehweiher).

**Screenshots / Videos**
<img width="477" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/67913362/45dbac9b-629d-4fcb-838d-ab4b48644e4a">

**Device**
Playing on Chrome on a Mac. But it's browser-independent.

**Comment by Madmadness65** [comment]
Fixed in 3d87e86e58, thanks for the report
