### ISSUE TITLE
[BUG] Egg moves do not save

### ISSUE THREAD

**Issue by HyperRes** [pagefaultgames/pokerogue#1932]
Changing egg moves before adding the mon to the party will not save the egg moves. This will save the egg moves in the starter screen for any next runs, but not the current run if you start it. Once you have edited the mons move set and you add it to the party changing any egg moves will have no effect and the mon will start with whatever move set it had prior to opening the starter screen.

**Comment by flx-sta** [comment]
@HyperRes Would you mind showing a video of the exact procedure ?

**Comment by RNGezeus** [comment]
I Presume this is what he meant.

https://github.com/pagefaultgames/pokerogue/assets/46976469/5728afda-34b9-4ba0-89c8-0732fdc83c30

**Comment by HyperRes** [comment]
> @HyperRes Would you mind showing a video of the exact procedure ?

What @RNGezeus posted is exactly what I meant. I can consistently recreate it every time if you want more video.

**Comment by gjeodnd12165** [comment]
Seeing the codes, [addToParty](https://github.com/pagefaultgames/pokerogue/blob/57e90b8f4bbea27dccb1052584f0fc37a13058a8/src/ui/starter-select-ui-handler.ts#L1115) adds the copy of the moveset while [selectMoveSwapWith](https://github.com/pagefaultgames/pokerogue/blob/57e90b8f4bbea27dccb1052584f0fc37a13058a8/src/ui/starter-select-ui-handler.ts#L1172) modify the origial moveset.

I'm trying to fix it, but I don't come up with some simple solution that doesn't change structure of StarterMovesets.

**Comment by RNGezeus** [comment]
> Seeing the codes, [addToParty](https://github.com/pagefaultgames/pokerogue/blob/57e90b8f4bbea27dccb1052584f0fc37a13058a8/src/ui/starter-select-ui-handler.ts#L1115) adds the copy of the moveset while [selectMoveSwapWith](https://github.com/pagefaultgames/pokerogue/blob/57e90b8f4bbea27dccb1052584f0fc37a13058a8/src/ui/starter-select-ui-handler.ts#L1172) modify the origial moveset.
> 
> I'm trying to fix it, but I don't come up with some simple solution that doesn't change structure of StarterMovesets.

How hard / intense is it to query if users party contains the chosen pokemon after manage moves menu closes, and if it does contain them then call remove from party -> add to party?
