### ISSUE TITLE
[BUG] In Fire only challenge Im able to catch other types

### ISSUE THREAD

**Issue by hayuna** [pagefaultgames/pokerogue#1947]
**To Reproduce**
Choose fire only challenge
Catch something what is not fire type

**Expected behavior**
Message similar to paradox catching. "You cannot catch other than fire types pokemon"

**Screenshots / Videos**
<img width="1614" alt="Screenshot 2024-06-08 at 13 23 29" src="https://github.com/pagefaultgames/pokerogue/assets/19636010/028284f0-5399-44ef-934d-674e268a5290">

**Device**
Mac / Chrome

**Comment by kvngrnr** [comment]
That is the expected behaviour. You just can't use them in battle. Here's the developers explanation:
https://old.reddit.com/r/pokerogue/comments/1davsr2/new_challenge_mode/l7n6cwg/
