### ISSUE TITLE
[BUG] Multi-Lens with healing moves heals too much

### ISSUE THREAD

**Issue by Tempo-anon** [pagefaultgames/pokerogue#1952]
**Describe the bug**
https://discord.com/channels/1125469663833370665/1248936374426665013

**To Reproduce**
Have a multi-lens with a healing move
Opponent has endure (token)
Use the healing move and the first hit will knock them to 1hp. Each subsequent hit will also produce healing instead of 0 since the opponent is still at 1hp

**Expected behavior**
Subsequent hits that deal 0 damage should not heal

**Screenshots / Videos**
n/a

**Device**
n/a

**Additional context**
n/a

**Comment by flx-sta** [comment]
With “healing move” you mean like drain ?

**Comment by Tempo-anon** [comment]
https://github.com/pagefaultgames/pokerogue/pull/1974 solves this issue
