### ISSUE TITLE
[BUG] the talent **No guard** does not work.

### ISSUE THREAD

**Issue by BelG13** [pagefaultgames/pokerogue#1966]
**Describe the bug**

in my endless run I fuzed a suicune with a machamp in order to have a pokemon that has the move **glaciate** and the talent **No guard**,  but it ended up not working and glaciate is not working 100% of the time like it is supposed to.
**To Reproduce**

1. Create a endless run
2. capture a machamp that has no guard
3. capture a suicune and teach him the move glaciate
4. fuze them (machamp is the sacrifice)
5. try to use glaciate on an opponent.

**Expected behavior**

glaciate is supposed to kill 100% of the time and should also always work due to **no gard** effect.

**Device**

I am using Chrome on Mac

**Comment by Tempo-anon** [comment]
Are you confusing Glaciate (65 base power move) with Sheer Cold (OHKO move)? Also, OHKO moves do not guarantee the OHKO with protection tokens.

**Comment by BelG13** [comment]
I am talking about the Sheer Cold sorry. but wit **no gard** isn't the attack at least supposed to hit 100% of the time even though it may not kill because of the tokens ?
