### ISSUE TITLE
Failed to Load Save Error

### ISSUE THREAD

**Issue by brettibus** [pagefaultgames/pokerogue#198]
![image](https://github.com/pagefaultgames/pokerogue/assets/167575765/78f4b4fb-f9e6-47ed-b1d0-35d3fda85ce8)
this randomly appeared mid run and now I cannot access the game. tried clearing cache, restarting etc

**Comment by Flashfyre** [comment]
This is not something for GitHub. Please see the data recovery channel in the Discord.
