### ISSUE TITLE
[BUG] Multi Lens + Outrage doesn't stop after 3 turns.

### ISSUE THREAD

**Issue by Yasashi2588** [pagefaultgames/pokerogue#1995]
**Describe the bug**
When having a Pokemon with Outrage (and possibly other multi turn moves) and Multi Lens as equipped item causes the pokemon to keep using outrage even after the confusion kicks in. The confusion appears after the first hit of the 2nd/3rd turn and all subsequent hits take confusion into account. My Dragonite kept using Outrage for 6 turns and didn't even stop after hurting itself with confusion.

**To Reproduce**
1. Obtain a Pokemon with Outrage (or possibly other multi turn confusion moves)
2. Obtain a Multi Lens from rewards and equip it onto the outrage Pokemon.
3. Use Outrage.
4. Wait until it gets confused and continues to use Outrage with no way of switching out or choosing other actions.

**Expected behavior**
Pokemon should stop using outrage after it gets confused. Confusion should only happen after the last Multi lens hit.

**Device**
Android Phone and Chrome Browser.

**Comment by Gammer0909** [comment]
From what I can see, the "Multi Lens" doesn't exist, are you talking about the Wide Lens? If so, that shouldn't effect anything, however it's still a bug, I'll look into it.

**Comment by Yasashi2588** [comment]
> From what I can see, the "Multi Lens" doesn't exist, are you talking about the Wide Lens? If so, that shouldn't effect anything, however it's still a bug, I'll look into it.

No i mean multi lens, the item that makes the pokemon holding it do less dmg but 2/3/4 hits depending on how many are stacked.

**Comment by innerthunder** [comment]
Fixed by https://github.com/pagefaultgames/pokerogue/pull/2662
