### ISSUE TITLE
[BUG] Baton Pass + Yawn bug

### ISSUE THREAD

**Issue by hightowernl** [pagefaultgames/pokerogue#1997]
**Describe the bug**

Baton Pass carries Yawn effect over.
**To Reproduce**

1. Have Baton Pass
2. Opponent uses Yawn
3. Player uses Baton Pass
4. The Pokemon you send out will fall asleep

**Expected behavior**

"Baton Pass does not pass non-volatile status conditions, infatuation, drowsiness (from Yawn or G-Max Snooze), a type change, Ability change, a move learned by Mimic, or a transformation (from Transform or Imposter)." From [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Baton_Pass_(move)#:~:text=Baton%20Pass%20does%20not%20pass,(from%20Transform%20or%20Imposter).)
**Screenshots / Videos**

**Device**

PC
**Additional context**

**Comment by DustinLin** [comment]
Able to reproduce

https://github.com/pagefaultgames/pokerogue/assets/39450497/ce506bbe-a4ad-4a24-8b85-cefbab886fdf

**Comment by DustinLin** [comment]
Taking a look at this...
