### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vmhoang** [pagefaultgames/pokerogue#2001]
**Describe the bug**

Enemy Galvantula used volt switch killing the target. After switching the pokemon, there are no pokemon switched out after galvantula volt switch 
**To Reproduce**

1. Go to 'classic mode- forest biome - Bugsy gym leader'
2. Wait for Enemy Galvantula used volt switch killing the target
3. After team switched out a new pokemon

**Expected behavior**
After volt switch, a new pokemon from Bugsy appear
**Screenshots / Videos**

![image](https://github.com/pagefaultgames/pokerogue/assets/65335717/61f4c293-4a6a-4391-a234-15571f91ec55)
![image](https://github.com/pagefaultgames/pokerogue/assets/65335717/1060f8d9-bb27-4852-81f8-679031e67c82)
![image](https://github.com/pagefaultgames/pokerogue/assets/65335717/90040173-2987-43a4-89c3-d9c2936a1f74)
![image](https://github.com/pagefaultgames/pokerogue/assets/65335717/874627d4-088e-4701-8492-bead9503342a)

**Device**

PC
**Additional context**

**Comment by torranx** [comment]
please add title for the issue

**Comment by CodeTappert** [comment]
It happens with every move that kills both sides while the enemy (and you) both still have another pokemon
