### ISSUE TITLE
[BUG]Enemy uses Flip Turn and switches out but no pokemon comes in.

### ISSUE THREAD

**Issue by kohi8** [pagefaultgames/pokerogue#2007]
**Describe the bug**

Rival Ivy's Pokemon, Brionne, uses Flip Turn it does damage to my Pokemon(Pikachu) and it faints,
 Then the move switches the user out but no Pokemon Comes in.
 If my Pokemon survives the move works fine.

**To Reproduce**

1. Make a Pokemon use Flip Turn and kill you with it.
2. The Move will bug out and not switch to another Pokemon.
3. Continue to fight the wind...(or save and quit to try another day)

**Expected behavior**

Flip Turn deals damage and then switches the user out to the next Pokemon in your party.
The user will not be switched out if the user is the only Pokémon in the party that can battle,

[Video of  Flip Turn working](https://streamable.com/eha1on)

**Screenshots / Videos**
[Video of Pikachu fainting](https://streamable.com/z4y1o1)

[Video of Rolycoly fainting](https://streamable.com/o991ya)

**Device**
PC, Windows 11 pro

**Additional context**

edit.
I tested if this bug happens if the player's Pokemon uses Flip Turn -> enemy Pokemon dies and there is no bug.

**Comment by innerthunder** [comment]
@DustinLin was this fixed with recent changes to U-turn, etc.?

**Comment by DustinLin** [comment]
Think it's good, tested on `main`:

https://github.com/user-attachments/assets/cbed733c-7497-4c3c-92ba-e378b60fdd5d
