### ISSUE TITLE
[BUG] Double battle softlock v2, Not enough replacements for fainted mons

### ISSUE THREAD

**Issue by RNGezeus** [pagefaultgames/pokerogue#2016]
**Describe the bug**
If a double battle ends with both your mon dying and you only got one extra team member to replace them it softlocks trying to replace 2nd mon with no valid candidates

**To Reproduce**
have 3 mons (untested if bigger party size but other members fainted also produces same result)
Have all mons on battlefield faint at end
replace 1st mon
try to replace 2nd mon in vain.

**Expected behavior**
That game recognizes no valid living members and stops trying to force you to replace a corpse with a corpse.

**Screenshots / Videos**

https://github.com/pagefaultgames/pokerogue/assets/46976469/138d083f-b221-4ad9-8d43-cd4d4d3ceaa3

**Additional context**

**Comment by Arxalc** [comment]
Is this a trainer battle? I tried to recreate it but it seems to be working.
2v2, used perish song. After all pokemon fainted, sent out Squirtle and it took me to the shop.

**Comment by RNGezeus** [comment]
This was a wild battle, I can test if it applies differently depending on if next battle is single or double.

**Comment by Greenlamp2** [comment]
Yes i fixed it with https://github.com/pagefaultgames/pokerogue/pull/2005
