### ISSUE TITLE
[BUG] Psychic Surge terrain not removed and re-applied when entering trainer battle

### ISSUE THREAD

**Issue by Terrorforge** [pagefaultgames/pokerogue#2018]
**Describe the bug**

My Delphox's Psychic Surge passive creates psychic terrain during wild pokemon battles, and when I enter a trainer battle the psychic terrain is not removed so that Psychic Surge can trigger again.

**To Reproduce**

1. Have Delphox with Psychic Surge passive unlocked
2. Activate Psychic Surge during wild battle
3. Enter trainer battle before the Psychic Terrain dissipates.

**Expected behavior**

Trainer battles start from a "clean slate", removing all battlefield effects.

**Screenshots / Videos**

![image](https://github.com/pagefaultgames/pokerogue/assets/5107449/df23152f-8977-48b9-a16b-46599f86774a)
Turn 1 against a Battle Girl

**Device**

Chrome on PC

**Additional context**

Session data: [sessionData1_Terrorforge-psychicTerrain.zip](https://github.com/user-attachments/files/15754165/sessionData1_Terrorforge-psychicTerrain.zip)

**Comment by RNGezeus** [comment]
I believe this is also true for weather effects, unsure if it applies to Lightscreen/Reflect.

**Comment by Terrorforge** [comment]
Yes, I believe I saw it happen with rain once.

**Comment by Snailman11** [comment]
Closed by #2027 , mentioned above
