### ISSUE TITLE
[BUG] Private Instance - Importing Data Fails due to "stored trainer or secret ID" not matching

### ISSUE THREAD

**Issue by fatmagic** [pagefaultgames/pokerogue#2023]
**Describe the bug**
When attempting to Import Data from the "Live" PokeRogue server _(pokerogue.net)_ and import into a Privately Hosted instance of PokeRogue _(my own server, not single player on Windows, but a hosted private server running on Ubuntu 20 VM)_ I'm running into an error that states the "store trainer of secret ID" doesn't match. Importing Session (save slots) between Live and Private **works** just fine, but not the Data set.

I reported this first [over on the "rogueserver" issues](https://github.com/pagefaultgames/rogueserver/issues/37), but I think it may be more related to the Client import, so I am cross-posting the issue here hoping for some help/insight.

Any idea how to update the exported data with the correct stored trainer or secret ID to make it import?

**To Reproduce**
1. Export Data from pokerogue.net
2. Manage Data > Import Data into Private Server
3. Error: "session out of date: stored trainer or secret ID does not match"

**Expected behavior**
It hasn't worked for me yet, so I assume the expected behavior is to import my full live PokeRogue data set.

**Screenshots / Videos**
Session/Save Slot imports fine:
![image](https://github.com/pagefaultgames/pokerogue/assets/20613563/5ad5d666-a0dc-4f3e-a282-704cf8ffdc97)

But importing data freezes up the client on my private server, and responds with this error in Dev Tools:
![image](https://github.com/pagefaultgames/pokerogue/assets/20613563/ed809175-7c68-4be6-95f7-b4b8b66108e6)

**Device**
Microsoft Edge on Windows

**Additional context**
My private server is lockstep with the live PokeRogue & RogueServer updates/commits, no custom edits on either _(except to define the internal API server IP address via env variables in .env)_. I'm git pulling the data for both as they are updated, keeping my server in-line with both live versions.

**Comment by mjferrante83** [comment]
I don't believe this is a bug.

I got around this but that's because I am doing a self-hosted implementation that uses a SQL server. If you are as well, here is how I got around this:
![image](https://github.com/pagefaultgames/pokerogue/assets/36816678/9ccb9481-363a-4958-8349-0708d32e4f62)

This screenshot is from the LIVE server. In my Firefox browser, I pressed F12 to pull up the DEV console. When you load up the game from the LIVE server, it will dump your your TrainerID and SecretID to console.

Armed with this info, in your PRIVATE instance, create a new account. Once created, you'll need to enter your SQL database, pull up the table with the freshly made account, and change the TrainerID and SecretID fields to match whats on your live server (you'll need to look up the appropriate SQL commands to navigate your database -- far too much to explain here).

After those changes are made, log back into your PRIVATE instance with that account you created, then try the Import again.

**Comment by fatmagic** [comment]
> I don't believe this is a bug.
> 
> I got around this but that's because I am doing a self-hosted implementation that uses a SQL server. If you are as well, here is how I got around this: ![image](https://private-user-images.githubusercontent.com/36816678/338212816-9ccb9481-363a-4958-8349-0708d32e4f62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMjgyODgsIm5iZiI6MTcxODAyNzk4OCwicGF0aCI6Ii8zNjgxNjY3OC8zMzgyMTI4MTYtOWNjYjk0ODEtMzYzYS00OTU4LTgzNDktMDcwOGQzMmU0ZjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDEzNTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MjU1ODI3MjBjZjg5YjU3NWRhYjUwMjk5NzM0ODAyOTAyNmYyOWZmY2ZmMjg5NmE2ZjBjMmJkMTBhNjk0YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sv_buoRSdmTBV766oFfagSHG__Dz4zLZuC9N3ANdo_k)
> 
> This screenshot is from the LIVE server. In my Firefox browser, I pressed F12 to pull up the DEV console. When you load up the game from the LIVE server, it will dump your your TrainerID and SecretID to console.
> 
> Armed with this info, in your PRIVATE instance, create a new account. Once created, you'll need to enter your SQL database, pull up the table with the freshly made account, and change the TrainerID and SecretID fields to match whats on your live server (you'll need to look up the appropriate SQL commands to navigate your database -- far too much to explain here).
> 
> After those changes are made, log back into your PRIVATE instance with that account you created, then try the Import again.

This is exactly what I needed!!! OK I will try this and report back!! Thank you so much @mjferrante83

**Comment by fatmagic** [comment]
@mjferrante83 IT WORKED! Awesome thank you so much :)
