### ISSUE TITLE
[BUG] random trainers mid E4 gauntlet

### ISSUE THREAD

**Issue by RNGezeus** [pagefaultgames/pokerogue#2031]
**Describe the bug**
Random trainers can appear in the midwaves between E4 members

**To Reproduce**
I don't know if you can force them but this has happend in 2-3 of my last 4 runs.

**Expected behavior**
That the Elite 4 doesn't turn into the Elite 5. 

**Screenshots / Videos**
![E4 imposter](https://github.com/pagefaultgames/pokerogue/assets/46976469/467f139f-1449-4132-9d16-692e3968cec4)

**Additional context**
I could accept themat 181 as part of champions road but it's really weird to get interrupted by them right before champion

**Comment by Tempo-anon** [comment]
Not really a bug since nothing precludes trainers from spawning on odd 180 floors. Also funnily enough, trainers never spawn on X1 floors because there's a bug where the sprites won't load

**Comment by RNGezeus** [comment]
I imagined as much. It just feels so thematically bizarre that a random trainer pops out of nowhere in middle of E4. If the mystery events/encounters get implement they are also kinda weird to get in middle of E4.

**Comment by Tempo-anon** [comment]
The fix should be in game-mode.ts `isWaveTrainer` to return false if waveIndex is 183, 185, 187, and 189

**Comment by Tempo-anon** [comment]
Technically not a bug but this PR addresses it: https://github.com/pagefaultgames/pokerogue/pull/2610
