### ISSUE TITLE
[BUG] "New form" indicator persisting for future caught Pokémon

### ISSUE THREAD

**Issue by travbp** [pagefaultgames/pokerogue#2033]
**Describe the bug**
Caught a Squawkabilly and the caught Pokémon info screen showed I had caught a new form (Green Plumage). Caught a Purugly on the next level and the caught Pokémon info screen still showed the new Green Plumage form.

**Expected behavior**
New form indicator doesn't persist with next caught Pokémon

**Screenshots / Videos**
![image](https://github.com/pagefaultgames/pokerogue/assets/112346662/f9d73119-b883-4a07-aa3d-7b4a516726fc)

**Device**
Steam Deck Offline (Admiral Billy app)

**Comment by Opaque02** [comment]
This should be fixed in a bug patch that went out not too long ago. Try refreshing just to make sure you've got the latest version

**Comment by Tempo-anon** [comment]
Should be fixed with https://github.com/pagefaultgames/pokerogue/pull/2029
