### ISSUE TITLE
[BUG] Reviver Seed freeze

### ISSUE THREAD

**Issue by KarelSavonet** [pagefaultgames/pokerogue#2035]
**Describe the bug**
After having Reviver Seed activated on my Rhyperior, the game freezes. Sound and animation still play, but no option to continue the text prompt of saying 'Reviver Seed activated'.

**To Reproduce**
Sadly I have not found when this behaviour gets triggered. At first I thought it was only the case when it was your last Pokémon that gets revived, but now I have encountered this problem multiple times mid battle with multiple Pokémon left. It was, however, always during a rival fight, but that is only because that is the only time the item gets triggered during my run.

**Device**
Windows PC - Google Chrome

**Comment by KarelSavonet** [comment]
**Update**
It seems to NOT occur when I am not spamming the enter key to go as fast through the text as possible. I'll update if it actually does at one point.

**Comment by Tempo-anon** [comment]
If this happens again please open  the console with F12 and show the error logs

**Comment by KarelSavonet** [comment]
Will do, didn't know the error logs would show up in console.

**Comment by flx-sta** [comment]
Please open a new issue if you encounter this again
