### ISSUE TITLE
Eiscue causing game crash

### ISSUE THREAD

**Issue by TrickyxGod** [pagefaultgames/pokerogue#2037]
Using the Pokemon Eiscue is causing game breaking bugs, where server freezes and does not progress. 

1. Select Eiscue as pokemon 
2. Have target pokemon physical attack Eiscue so he loses head protection 
3. A. Have Eiscue level and learn new move while head is not protected
3. B. Have Eiscue faint while head is not protected 

**Expected behavior**
Have game progress as usual

**Device**
PC / Chrome

**Comment by TrickyxGod** [comment]
Additional issue; game crashes when trying to load game where head is missing 

![image](https://github.com/pagefaultgames/pokerogue/assets/172253452/2611d696-5bac-4e76-ad33-104d604e5786)

**Comment by torranx** [comment]
Please check discord bug reports or changelog before making an issue on github. This can be solved by clearing cache. Please close the issue if that solves it.
