### ISSUE TITLE
[Feature] Adding spike count to field flyout.

### ISSUE THREAD

**Issue by timonkobusch** [pagefaultgames/pokerogue#2038]
**Describe the Feature**
Spike field harzard is stackable and the flyout could display a 1x, 2x, 3x next to the spikes.

**Comment by torranx** [comment]
Good idea, made progress so far but needs more testing

<img width="773" alt="Screenshot 2024-06-11 at 3 44 56 AM" src="https://github.com/pagefaultgames/pokerogue/assets/68144167/2e94deb0-9a2d-439e-ade0-d21929121217">

**Comment by timonkobusch** [comment]
I will look into it tomorrow and test it locally. I will change according to the rules of pokemon (toxic spikes are not stackable)
