### ISSUE TITLE
[BUG] Starter selection cycling options text missing

### ISSUE THREAD

**Issue by Tempo-anon** [pagefaultgames/pokerogue#2050]
**Describe the bug**
The text for cycling starter options is missing in challenge mode. It also disappears from other modes once you start a challenge starter-select

**To Reproduce**
Start a challenge 

**Expected behavior**
The text should still be there

**Screenshots / Videos**
![](https://cdn.discordapp.com/attachments/1241164581997510656/1249785271793483928/image.png?ex=666890bc&is=66673f3c&hm=5787a4e52065f88fc9aec53208392805627bfa2fb2ca2a219f98069efdd32376&)
Note the lack of cycling options

**Device**
n/a

**Additional context**
n/a

**Comment by flx-sta** [comment]
@Tempo-anon this. has nothing to do with the challenge mode.
Whichever mode was selected first will have the buttons display.
Any other one won't.

e.g.
1. New-Game -> Endless Mode
2. move cursor on a pokemon which you have unlocked multiple genders (e.g.) and it shows the cycle button/s
3. Press Cancel until you are back in the Start-Menu
4. New-Game -> Classic
4. cursor on the same pokemon -> NO MORE BUTTONS

**Comment by Greenlamp2** [comment]
related either from #2054 #1982 or #1859
