### ISSUE TITLE
[BUG] Major Loss of data on my account

### ISSUE THREAD

**Issue by Ollisk1** [pagefaultgames/pokerogue#2052]
**Describe the bug**
I had pokerogue loaded up on my iphone from a few days prior, I have since played on my PC (Around 2 days worth of playtime, has really demotivated me from playing anymore as ive lost 20 classic completions and 100+ribbons in that time) anyway, since i had the session loaded up on my phone and i made alot of progress on my PC, when i went back onto my phone it was still loaded with the previous save for my account, so then when i went back onto my PC and loaded up the game the state of my account that my phone was in was then loaded onto my PC and my whole account

**To Reproduce**

Honestly im not too sure if this would be recreate able. I feel like ive just gotten very unlucky with this situation but i have explained it exactly as above.

**Expected behavior**

**Screenshots / Videos**

Photo one is my account yesterday which is the correct save state (I had the photo because i sent it to my friend to flex about my stats) and Second photo is what happened to my account after this ordeal.
![pokerogue acc](https://github.com/pagefaultgames/pokerogue/assets/172311472/48d1ec20-74ff-4ca9-9cc0-7c75df903eff)
![pokerogueoldacc](https://github.com/pagefaultgames/pokerogue/assets/172311472/a934f696-428c-4084-80fe-960db3091fbb)

**Device**
Both iPhone + Windows, Both devices were using Opera GX but they are not linked to eachother so i dont think that is related.

**Additional context**

**Comment by Shwheelz** [comment]
I had the same issue on my account.  Beat classic mode at least twice last week, had a bunch of egg vouchers left over that I was saving for a good legendary, and now all of them, ribbons, and achievements got wiped out.

**Comment by Shwheelz** [comment]
Thanks, but unfortunately this data loss has persisted to PC and my iPhone too.  Whatever happened was saved to the database and my data is legitimately gone.

**Comment by flx-sta** [comment]
Unfortunately we are not able to recover loss of data. We are constantly trying to
Mitigate these issue but cannot guarantee it never happening
