### ISSUE TITLE
[BUG] Pikachu forms can hold Max Mushroom

### ISSUE THREAD

**Issue by hayuna** [pagefaultgames/pokerogue#2056]
**Describe the bug**
Pikachu forms can hold Max Mushroom

**To Reproduce**
Have Pikachu form
Give him Max Mushroom

**Expected behavior**
Should not be able to give him this item, its not changing form into gigantamax

**Screenshots / Videos**
<img width="1707" alt="Screenshot 2024-06-10 at 21 39 30" src="https://github.com/pagefaultgames/pokerogue/assets/19636010/89e39e61-83b3-4837-9220-dbde69cada9c">

**Device**
Mac / Chrome

**Comment by frutescens** [comment]
TY for reporting. The fix will be in the next update.
