### ISSUE TITLE
[BUG] Power Construct not selectable on starter screen after it has been hatched from an egg

### ISSUE THREAD

**Issue by Creative-Genius2** [pagefaultgames/pokerogue#2060]
Zygarde’s second ability Power Construct is implemented (partly) but is unselectable on the starter screen, even if you have hatched one from an egg or caught one in the wild if it has the ability.

**Expected behavior**: You should be able to switch between Aura Break and Power Construct on the starter select screen if you have gotten it as an egg or have caught one with said ability.

**Device**
 IPhone/PC

**Comment by Madmadness65** [comment]
Zygarde's Power Construct isn't a second ability for Zygarde, rather it's a singular ability on the 50% and 10% Power Construct Zygarde forms, separate from the 50% and 10% Aura Break forms. The thing with Zygarde (and Rockruff too, it has the same issue) is that the listed abilities don't change when the form is changed, if the alternate form has a different set of abilities than the base form, so it can be a little visually confusing.

**Comment by Creative-Genius2** [comment]
So its similar to how Battle Bond Greninja works them? If so couldn’t it be set like “Change Forme” like how you can with Greninja? I do agree that it is confusing though lol ^^’
