### ISSUE TITLE
[Feature] add a code formatter (please!)

### ISSUE THREAD

**Issue by flx-sta** [pagefaultgames/pokerogue#2069]
**Is your feature request related to a problem? Please describe.**

It’s quite frustrating and tedious to stay on par with the existing code formatting as there is no standardized way to format the code

**Describe the Feature**

Can we please add an opinionated code formatter like prettier ?

I know there is people out there that might not be happy with the formatting it will dictate but thats always going to be the case with a project of this size. There is a lot of noise in PRs here and there because of formatting going back and forth.

**Additional context**

**Comment by HighMans** [comment]
Agreed, this PR for example with the imports.

https://github.com/pagefaultgames/pokerogue/pull/2057/files

**Comment by Greenlamp2** [comment]
I agree. You can create a PR with what you think would fit best for this issue

**Comment by flx-sta** [comment]
> I agree. You can create a PR with what you think would fit best for this issue

I've created a draft with a minimal change to have a look at it first
https://github.com/pagefaultgames/pokerogue/pull/2101
