### ISSUE TITLE
Spread moves hit user if ally is KO'd and there is no replacement.

### ISSUE THREAD

**Issue by GodkarmachineOBabaghanoush** [pagefaultgames/pokerogue#207]
Specific situation : Machamp uses Earthquake while Qwilfish is on the field.
Opponent KO's Qwilfish before Earthquake goes off.
Because every other Pokemon was KO'd, Machamp moves to a new position.
Machamp then uses Earthquake, and promptly hits itself with it.

**Comment by bennybroseph** [comment]
Still occurs, easy to reproduce

https://github.com/pagefaultgames/pokerogue/assets/13838608/05a7e6b2-9374-4ee6-a7eb-05e41d546c5f

**Comment by DustinLin** [comment]
Think this was fixed, not sure exactly which PR though

https://github.com/pagefaultgames/pokerogue/assets/39450497/b0b09c6d-f4ef-4307-b28d-f3114a1c0370

**Comment by Jancojicanoder** [comment]
> Think this was fixed, not sure exactly which PR though
> 
>  spreadhit.mov

Shouldn't the earthquaker be in the 2nd slot? Since bulbasaur is in the 1st slot, he doesn't change positions, which is relevant in the issue

**Comment by flx-sta** [comment]
Tested locally on `beta` branch e84649854dfaff5dc02da255a09496332ba47e9c
Not reproduceable
