### ISSUE TITLE
Failed to update games. [BUG] 

### ISSUE THREAD

**Issue by MirhasVida** [pagefaultgames/pokerogue#2072]
**Describe the bug**
Failed to update games.

**To Reproduce**
While turn on the game, it crashes with error messages.

**Expected behavior**

**Screenshots / Videos**
![KakaoTalk_20240611_132020180](https://github.com/pagefaultgames/pokerogue/assets/128056797/c1e43eb5-d277-4dbf-aa78-77ff5b7d5e39)

**Device**
Phone

**Additional context**

**Comment by KKTRKKT** [comment]
I believe this issue needs to be addressed on the [Pokerogue-App](https://github.com/Admiral-Billy/Pokerogue-App) repository.

**Comment by Greenlamp2** [comment]
indeed
