### ISSUE TITLE
[BUG] potential memory leak

### ISSUE THREAD

**Issue by BubbleBear** [pagefaultgames/pokerogue#2073]
**Describe the bug**
game crashes periodically since about 4 days ago.

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Device**

**Additional context**

**Comment by FynnYeong** [comment]
Me too

**Comment by Tempo-anon** [comment]
inflight does have a memory leak. Tracked in https://github.com/pagefaultgames/pokerogue/issues/2353
