### ISSUE TITLE
[BUG] Pokemon sprites messed up in GEN 1 starter selection screen.

### ISSUE THREAD

**Issue by itsdawei** [pagefaultgames/pokerogue#2074]
**Describe the bug**

Pokemon sprites messed up in GEN 1 starter selection screen.

**To Reproduce**

Start new game.

**Expected behavior**

**Screenshots / Videos**

![image](https://github.com/pagefaultgames/pokerogue/assets/54293336/4f967f47-9795-4aeb-97d6-55f766521647)

**Device**

Mozilla Firefox 126.0.1
Linux archlinux 6.6.32-1-lts

**Additional context**

**Comment by KKTRKKT** [comment]
I have the same problem

**Comment by itsdawei** [comment]
After restarting the browser, the problem is fixed.
