### ISSUE TITLE
[BUG]Pokemon cost for poor people :D

### ISSUE THREAD

**Issue by reviix99** [pagefaultgames/pokerogue#2079]
I lost access to my main account because stupid me logged out by accident and couldnt remember the login name anymore.

Booted up new account only to see Pokemon costs being this??

If this is reproducable it would be hella funny, booted up new account to have pokemon cost messed up.
![Bild_2024-06-11_091756295](https://github.com/pagefaultgames/pokerogue/assets/172364398/3c5f2263-3798-4807-9ef6-b6c2c063641c)

**Screenshots / Videos**
![Bild_2024-06-11_091711785](https://github.com/pagefaultgames/pokerogue/assets/172364398/9f6846f5-80ed-49e6-a89e-3781dcecbe79)

PC

**Comment by BubbleBear** [comment]
XDD this is funny
