### ISSUE TITLE
Snowscape.json missing [BUG]

### ISSUE THREAD

**Issue by DynaManic42** [pagefaultgames/pokerogue#2080]
**Describe the bug**
Just before level 35, a file was requested called "snowscapes.json", and expected to be at the address:

PokeRogue-Windows/resources/app/game/battle-anims/snowscape.json

Aditional info:

Referrer Policy:
strict-origin-when-cross-origin

It just stopped, not allowing me to hit escape. The file also is not in the battleanims in the repo, could someone please provide the file?

**To Reproduce**

There isn't an exact way to replicate, but I was in a beach biome and maybe the change in biome to a snowy one might've triggered it.

**Expected behavior**

The game to continue as normal :(

**Screenshots / Videos**

**Device**

PC deployment by AdmiralBilly, github.

**Additional context**

**Comment by Pigamo** [comment]
I had the same issue with rollout.json and something else on a different run.

![image](https://github.com/pagefaultgames/pokerogue/assets/58117669/55febec3-8c22-4ac6-993f-a4045c48f56c)

**Comment by DynaManic42** [comment]
> I had the same issue with rollout.json and something else on a different run.
> 
> Edit: I went to the resource page, refreshed a bunch, and then it loaded on the page and in the game. Not sure why this happens. But it did resume the run.

I asked ChatGPT, and it just created a localhost at 8000 from the offline files I downloaded, and it worked. Needed to export and import data back to the offline files, but a good fix for small errors.

**Comment by DynaManic42** [comment]
Yet for some reason it worked
