### ISSUE TITLE
[BUG] Purifying Salt not working as advertised

### ISSUE THREAD

**Issue by Ninefl4mes** [pagefaultgames/pokerogue#2085]
**Describe the bug**
Purifying Salt should prevent all status conditions on the Pokemon that has it. As things stand, however, it does not seem to prevent status conditions that are applied as a side effect from offensive moves. By now I've already seen Hurricane apply confusion to my Pokemon, as well as a status token applying poison to it.

**To Reproduce**

1. Have a Pokemon with Purifying Salt be hit by an offensive move that has a chance to apply status.
2. Alternatively, be hit by any offensive move while status tokens are active in endless.

**Expected behavior**

The status effects should not be applied, since the ability is supposed to prevent that outcome.

**Screenshots / Videos**

![Got hit by Dynamic Punch here.](https://github.com/pagefaultgames/pokerogue/assets/76103088/355d28db-74bc-416c-a73f-3545ba9bcb59)

![Image](https://github.com/pagefaultgames/pokerogue/assets/76103088/9537c2a6-e95f-4daf-9b17-d91be836f29b)

**Device**

I'm playing on PC, using the Pokerogue-App client.

**Additional context**

This bug seems to only affect status as a secondary effect of moves. Outright status-applying moves like Stun Spore fail as they should. The run I noticed this issue in is an Endless (Spliced) run and my Pokemon got the Purifying Salt ability by splicing a Garganacl into it.

**Comment by Fabiankreuzer** [comment]
As far as my knowledge of Pokémon goes, confusion should be applied like all other secondary/volatile status conditions (bound, seeded, etc.). I did not find any information about it, though, so I checked on Pokémon Showdown, where at least confusion works on a Pokémon with Purifying Salt. It's also not listed (at least by Bulbapedia) as an ability which cannot be suppressed by something like Gastro Acid, which would also count as a secondary/volatile status.

**Comment by Ninefl4mes** [comment]
Interesting, didn't know that it did not block Confusion. Just tried out Nuzzle on a Nacli in a new run to test things further, but that didn't apply Paralysis. That said, I definitely also got poisoned earlier, after my Blastoise had already been fused with Garganacl. Pretty sure it was a poison token. I'm currently trying to replicate it but no luck so far.

**Comment by RNGezeus** [comment]
I found 1 website referring to it like this:
"A Pokémon with the ability Purifying Salt cannot have major status ailments inflicted on it.
Any major status ailment can be cured in and outside of battle with a Full Heal, Full Restore, Heal Powder, Lava Cookie, Old Gateau or Casteliacone."

When I get some free time I'm gonna confirm it on my copy of Scarlet

I'm also interested if this just affects moves with 100% chance and misses moves with random chance of status (flamethrower, discharge etc.).

**Comment by Ninefl4mes** [comment]
Okay, I think I know what caused it now. Just got a burn from a status token and the opposing Pokemon had Mold Breaker due to the Pangoro that had been spliced into it. Makes sense that Purifying Salt could get ignored by abilities like that.

As for it not protecting from Confusion, that is indeed how it works in Scarlet/Violet. Tested it just now. I guess I can close this issue then since it wasn't a bug after all.
