### ISSUE TITLE
[BUG] Text rendering issues

### ISSUE THREAD

**Issue by Julienraptor01** [pagefaultgames/pokerogue#2089]
**Describe the bug**
The text sometimes has rendering issues in multiple languages on multiple platforms

**To Reproduce**
1. Load the website and set your settings to french
2. Look at the main menu
or
1. Set the language to english
1. Create a new Game
2. Look at Gastly Ice Beam / Acid moves

**Expected behavior**
Text not to be broken 🙂

**Screenshots / Videos**
(click to view)
<details>
  <summary>Windows 10 Firefox French</summary>

![image](https://github.com/pagefaultgames/pokerogue/assets/49841713/096f606c-18f9-4e3e-9b4a-3b95129d42ed)
</details>
<details>
  <summary>Windows 10 Firefox English Ice Beam</summary>

![image](https://github.com/pagefaultgames/pokerogue/assets/49841713/817c3a19-1838-4bc5-ba91-60c2cfdc10c1)
</details>
<details>
  <summary>Windows 10 Firefox English Acid</summary>
  
![image](https://github.com/pagefaultgames/pokerogue/assets/49841713/d24fbdd3-8366-46bc-a2d9-1d165c205dc8)
</details>
<details>
  <summary>Android 14 Chrome French</summary>

![Screenshot_20240611_132807_Chrome.png](https://github.com/pagefaultgames/pokerogue/assets/49841713/e2a10ca0-b1bc-4647-bbdd-cbfb2ef4b8f9)
</details>
<details>
  <summary>Android 14 Chrome English Ice Beam</summary>

![Screenshot_20240611_132935_Chrome.png](https://github.com/pagefaultgames/pokerogue/assets/49841713/58490553-0743-4c1e-b73f-ffeacea061a8)
</details>
<details>
  <summary>Android 14 Chrome English Acid</summary>
  
![Screenshot_20240611_132941_Chrome.png](https://github.com/pagefaultgames/pokerogue/assets/49841713/dda3258e-63c7-45c7-b3ef-6c92e724765b)
</details>

**Device**
Happen both on :
- Firefox on Windows 10
- Chrome on Android 14

**Additional context**
it was working fine yesterday so like 17h ago-ish

**Comment by BubbleBear** [comment]
it happens on certain characters, you don't even need to change language in settings.
probably the font file is broken
