### ISSUE TITLE
[Feature] Start the game with both male and female starter pokemon

### ISSUE THREAD

**Issue by corentin-feys** [pagefaultgames/pokerogue#2103]
**Is your feature request related to a problem? Please describe.**
I introduced a friend to the game and when choosing her first team, she asked me if she could choose female pokemon. I thought you might just be able to toggle the gender but I was surprised to find only the male starters are available at first. It's a small but I think important option to have.

**Describe the Feature**
New players should have the ability to toggle the gender of the starting pokemon with G (as if they had been caught).

**Additional context**
I looked through the code and I believe changing this one line, 1308, in /src/system/game-data.ts should do it:
From:
`const defaultStarterAttr = DexAttr.NON_SHINY | DexAttr.MALE | DexAttr.DEFAULT_VARIANT | DexAttr.DEFAULT_FORM;`
To:
`const defaultStarterAttr = DexAttr.NON_SHINY | DexAttr.MALE | DexAttr.FEMALE | DexAttr.DEFAULT_VARIANT | DexAttr.DEFAULT_FORM;`

**Comment by corentin-feys** [comment]
> 👍 The question is how to make it 'retroactive' for all the players? 🤔

Right I hadn't thought of that. Looks like @timchi94 sorted it out though! Thanks a lot!

**Comment by frutescens** [comment]
Will be in the next update. Thank you for reporting this!
