### ISSUE TITLE
[BUG] Entry hazards sometimes not triggering on switched in pokemon

### ISSUE THREAD

**Issue by CDeltakai** [pagefaultgames/pokerogue#2107]
**Describe the bug**

Entry hazards appear to occasionally not work and not affect the next switch in. It seems to occur more consistently when it comes to terastalized pokemon but I have experienced it happen with other pokemon as well - most recent memory being a hisuin voltorb.

Entry hazards still work most of the time, and I am unsure of the exact mechanism that is causing them to not work when they don't.

EDIT: This issue appears to happen most frequently when facing the rival (ivy in this case)

**To Reproduce**

1. Place down entry hazards during battle
2. Make enemy switch pokemon
3. Switched pokemon is not affected by entry hazard

**Expected behavior**

Entry hazards should affect any pokemon switching into them unless they are immune to it i.e poison/steel types ignore toxic spikes, flying types ignore spikes of any kind 

**Screenshots / Videos**

![image](https://github.com/pagefaultgames/pokerogue/assets/100399514/3070932b-6188-44d5-b401-b073076d69ce)
- The HP bar isn't shown in this image but Torterra did not get affected by any of the entry hazards

![image](https://github.com/pagefaultgames/pokerogue/assets/100399514/e82bfcde-6421-4f07-8ae8-e8c1d4fbc922)
- In this image Torterra was already damaged and did not take damage from the entry hazards, also did not get poisoned from toxic spikes which were there from the previous turn.

![image](https://github.com/pagefaultgames/pokerogue/assets/100399514/3242b281-e71d-4c12-be80-9ab7badfbb09)
- Again against the rival, the entry hazards appear to not be triggering. This issue seems to be happening most often when dealing with the rival.

**Device**

PC, Firefox

**Additional context**

**Comment by RNGezeus** [comment]
How frequent is this? Do you have a save file for testing? To my memory I have never experienced this issue with stealth rocks anywhere, never used spikes so can't talk about those.

**Comment by Greenlamp2** [comment]
Fixed with https://github.com/pagefaultgames/pokerogue/pull/2108
