### ISSUE TITLE
Regarding the Aesthetic Issue of the New Simplified Chinese Font[Feature]

### ISSUE THREAD

**Issue by PkJDio** [pagefaultgames/pokerogue#2113]
To be honest, the new font gives a sense of disharmony that does not fit the game, leaving a very unpleasant impression.

If possible, I hope the simplified Chinese font can be reverted or an option to switch fonts can be added.

**Comment by linxizz** [comment]
I totally agree. That's not at all what a pixel game should be like.

**Comment by wb-hwang** [comment]
I feel uncomfortable when I see the new font, especially since I am still playing on Android.

**Comment by Tempo-anon** [comment]
Closing for now after speaking to some Chinese players.
