### ISSUE TITLE
[BUG]Graphical bug on level up screen

### ISSUE THREAD

**Issue by God-of-platypus** [pagefaultgames/pokerogue#2119]
**Describe the bug**

When leveling up or using the iv scanner, some white block appears on the screen as seen in the screenshot section.

**To Reproduce**

1. Load a save
2. Level up or use the iv scanner
3. See error

**Expected behavior**

It is expected to see the same screen but without the white block

**Screenshots / Videos**

![image](https://github.com/pagefaultgames/pokerogue/assets/119050482/d7f115be-b31b-4cc3-a6a0-e6638f3de3c4)
**Device**

Ubuntu 23.04
Firefox nightly

**Additional context**

**Comment by Heretwik** [comment]
![image](https://github.com/pagefaultgames/pokerogue/assets/172503554/9ca26474-087f-4c14-aaeb-172f381bc139)

Always the same form repeated in the french translate, appears in many texts and menus, looks like a strange form

**Comment by Heretwik** [comment]
Seems repaired now !

**Comment by knispeja** [comment]
Duplicates https://github.com/pagefaultgames/pokerogue/issues/2089

**Comment by CodeTappert** [comment]
As stated by @knispeja This is a duplicate
