### ISSUE TITLE
[BUG] Eiscue causes a bug.

### ISSUE THREAD

**Issue by rutaru1234** [pagefaultgames/pokerogue#2131]
**Describe the bug**
 If Eiscue is defeated, a bug occurs. Also, a bug occurs if you fail to capture Eiscue encountered in the wild. (Screen freezing bug)

**To Reproduce**

 1. Meet Eiscue in the wild.
 2. Knock it down.＝A bug occurred.
 3. Failed to capture it in one go.＝A bug occurred.
 4. Run away＝No bugs occur.

 ★ We meet in battle.＝You can't run away, you can't capture it, and a bug occurs if you defeat it.

**Expected behavior**

**Screenshots / Videos**
 
[video.zip](https://github.com/user-attachments/files/15805529/video.zip)

**Device**
 Laptop

**Additional context**

**Comment by Tempo-anon** [comment]
Press ctrl+f5 to clear your cache. You probably don't have the noice face cry updated
