### ISSUE TITLE
[Feature] Changes to late classic mode Rival. (SPOILERS)

### ISSUE THREAD

**Issue by Yasashi2588** [pagefaultgames/pokerogue#2140]
**Is your feature request related to a problem? Please describe.**
Currently Fairy/Steel turns classic into easy mode and to counteract that, the Rival could get a random uber legendary from the list below instead of always having the same one.

**Describe the Feature**
Every Run the Rival randomly gets one of the following Legendaries starting on floor 145 and upgrade them to their ultimate form on floor 195:

- Mewtwo > Mega Mewtwo X or Y
- Kyogre > Primal Kyogre
- Groudon > Primal Groudon
- Rayquaza > Mega Rayquaza
- Zygarde 50% > Zygarde Optimum
- Dusk-Mane/Dawn-Wing Necrozma > Ultra Necrozma
- Zacian Hero of many battles > Crowned Sword
- Zamazenta Hero of many battles > Crowned Shield

Maybe:
- Palkia > Origin Palkia
- Dialga > Origin Dialga
- Zekrom > Black Kyurem
- Rehiram > White Kyurem
- Diancie > Mega Diancie

**Additional context**
This would change classic mode up from only preparing for Rayquaza and eternatus. And of course all picks should appear in their rare shiny variant.

**Comment by HyperRes** [comment]
Imo this would be good as a NG+ of sorts so the rival would always have mega ray on the first run. Idk how u fix the end screen with mega ray in the background tho

**Comment by Tempo-anon** [comment]
This seems unlikely due to needing new ending CGs with how iconic the T2 shiny Rayquaza is. More legendary opponents for more variety has been implemented through evil teams.
