### ISSUE TITLE
[BUG] Game does not progress after Honey Gather triggers when catching Combee

### ISSUE THREAD

**Issue by amayesingnathan** [pagefaultgames/pokerogue#2144]
**Describe the bug**
After battling and catching a Combee at floor 4, it shows the catch screen, followed by receiving EXP as usual. Then when Honey Gather triggers for the first time for the newly caught Combee, the game stops progressing. The idle animation of the pokemon out continues to play and tooltips still show, but the text is stuck at "Meowth gained 40 EXP. Points!", for example, and no controls will do anything to progress or exit, and I waited at least a couple of minutes. Only refreshing to reload the save works but the problem persists until you faint the Combee. 

**To Reproduce**
1. Enter battle with Combee with Honey Gather.
2. Catch the Combee. Refreshing the same battle I used any combination of starter pokemon to catch it, damage and no damage, and both Poke Balls and Great Balls (all I had at the time).
3. Progress the text until after you receive EXP and Honey Gather triggers.
4. Game locks up. 

**Expected behavior**
The game would just progress normally.

**Screenshots / Videos**

Screen Recording
https://github.com/pagefaultgames/pokerogue/assets/92682126/0a5c7344-a9e1-4ee9-9cca-6a911b0a9b78

Developer Console error that appeared when game freezes:
[Developer Console Error.txt](https://github.com/user-attachments/files/15808966/Developer.Console.Error.txt)

**Device**
PC - Firefox

**Additional context**
I've only been able to reproduce this upon repeatedly reloading the save at the beginning of the battle with Combee. I haven't yet tried this in a new save or anything but I'll update this if it happens again.

**Comment by zacharied** [comment]
I can confirm that this does not always happen with Honey Gather activation -- using starter with ability override, the activation works fine. Might have something to do with the Honey Gather mon being caught.

**Comment by zacharied** [comment]
The ability activation works fine even if I set the opponent to have Honey Gather and catch them. This may not actually be a Honey Gather bug. It's important to note that the ability activation dialogue does eventually disappear in the given video, implying that it's not Honey Gather's effects causing the crash.

**Comment by amayesingnathan** [comment]
> The ability activation works fine even if I set the opponent to have Honey Gather and catch them. This may not actually be a Honey Gather bug. It's important to note that the ability activation dialogue does eventually disappear in the given video, implying that it's not Honey Gather's effects causing the crash.

You may be right, I made that assumption based on the fact that if I just fainted the Combee then the game did not crash, and the only thing I noticed being different was the lack of Honey Gather proc. And it wasn't until after the proc that the game locked up, but it could easily be something unrelated to Honey Gather. I haven't re-encountered the scenario so apologies I can't be of any more help.

**Comment by Tempo-anon** [comment]
Going to close this out as it's not reproducible. Next time, be sure to also upload your session data for debugging purposes
