### ISSUE TITLE
If a Pokemon copycats a fire move and uses it on a pokemon with flash fire, the Copycat Pokemon will get the flash fire effect instead.

### ISSUE THREAD

**Issue by rastawr** [pagefaultgames/pokerogue#217]

**Comment by rastawr** [comment]
To be specific about the scenario, my Chandelure used inferno on a wild clefable, and then it copycatted it back. I _think_ the ability popup said "Clefable's Flash Fire", when it used it on my Chandelure, and although my Chandelure didn't take any damage from the attack, Clefable got a boost from it with Chandelure getting nothing.

**Comment by allen925** [comment]
I've tried a few cases about it. It seems like it's a display thing that not showing Chandelure's Flash Fire, only if you're encountering the magic guard one, but the actual effect of flash fire on Chandelure is applied correctly. 
(the issue could be solved if someone fix it between time posted and now, that is totally possible)
Videos for reference: 


https://github.com/user-attachments/assets/f4336711-65f1-4de8-8a42-cfabe7be8b71


https://github.com/user-attachments/assets/7feaff2e-1bd1-4945-b7b3-512bb8a26ce2


https://github.com/user-attachments/assets/9d04bca8-0b05-454e-a9ca-bb1a4005545b

**Comment by flx-sta** [comment]
Not a bug.
Basically `Magic Guard` is preventing the Flash Fire effect correctly

-----

Verified via playtest using overrides.ts:
```ts
const overrides = {
  OPP_LEVEL_OVERRIDE: 5,
  OPP_SPECIES_OVERRIDE: Species.CLEFABLE,
  OPP_MOVESET_OVERRIDE: [Moves.COPYCAT, Moves.COPYCAT, Moves.COPYCAT, Moves.COPYCAT],
  STARTER_SPECIES_OVERRIDE: Species.CHANDELURE,
  MOVESET_OVERRIDE: [Moves.INFERNO, Moves.FLAMETHROWER],
  ABILITY_OVERRIDE: Abilities.FLASH_FIRE,
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
  ```
