### ISSUE TITLE
[BUG] Incorrect cursor wrapping in audio settings

### ISSUE THREAD

**Issue by MokaStitcher** [pagefaultgames/pokerogue#2172]
**Describe the bug**
In the settings audio tab if pressing up when on the top option the settings move around to the bottom of the tab. Depending of the type of controls used and actions taken afterwards this can lead to completely moving the options off screen or crash the game

**To Reproduce**
Using the audio tab, but this likely would happen for any tab with less settings than can fit on screen.
***Basic version***
1. Go to Settings
2. Move to Audio tab
3. Press up
4. The settings get shifted down to the bottom of the screen
5. (Pressing down fixes it)

***Crash (only with controller):***
1. Go to Settings, Audio tab
3. Press up, settings get shifted down
4. Move to a different tab
5. Go back to audio tab
6. Cursor is on the first, empty slot in the menu
7. Press left of right to attempt modifying the phantom setting
8. If using controller, screen turns black. With touch and keyboard there's still an error in the console but things keep working

***More fun***
1. Go to Settings, Audio tab
3. Press up, settings get shifted down
4. Leave settings, then back to audio tab
5. Menu is still shifted down, cursor on the first, empty slot
6. Press up
7. Settings get shifted down one more row
8. You can keep pressing up to move the settings completely off screen
9. (Press down as many time as needed to fix)

**Expected behavior**
When in the top slot of the menu and there is room for extra settings on screen, pressing up should wrap around the cursor to the last setting, without the settings moving around

**Screenshots / Videos**
Audio menu shifted down twice:
<img width="750" alt="Screenshot 2024-06-13 at 12 20 40" src="https://github.com/pagefaultgames/pokerogue/assets/54149968/c6f9d3ef-1688-4089-b3cd-81e0febc782b">

The bug in action, using touch overlay to show what I'm doing:

https://github.com/pagefaultgames/pokerogue/assets/54149968/ebbd287d-6788-4058-a8c4-4cbbbd4a77ba

Same thing but using a controller. Game softlocks when trying to move left/right on an empty setting

https://github.com/pagefaultgames/pokerogue/assets/54149968/87ab0d43-4381-4f9e-9fcb-dea87b966c6f

**Device**
Mac OS / Firefox, also tested on Android phone, behaves the same as with simulated touch controls on FF

**Comment by torranx** [comment]
please add spaces before and after the video links. that should get rid of the ugly links, and embed the videos instead
