### ISSUE TITLE
[BUG] Softlocked after choosign reward

### ISSUE THREAD

**Issue by RNGezeus** [pagefaultgames/pokerogue#2173]
**Describe the bug**
The session is softlocking trying to entry next wave

**To Reproduce**
1. Complete combat
2. Pick a reward
3. Locked

**Screenshots / Videos**
https://github.com/pagefaultgames/pokerogue/assets/46976469/0a771b71-9741-4d40-bd9c-e69a807c47b3

**Device**
PC

**Additional context**
I have absolutely no idea on this one was just meant to be a basic Fire run, here's the session
[SoftLock.zip](https://github.com/user-attachments/files/15818721/SoftLock.zip)

Edit: Huh, might be a hardcrash instead of softlock. Game doesn't even resize as i modify the window.

**Comment by shadowxx3** [comment]
Same 
![Uploading 17182821376063625141974774833423.jpg…]()

**Comment by shadowxx3** [comment]
Just round a way , you Need to enter the Battle that blocks you , save the game , enter the saved file again and you should be ok

**Comment by Greenlamp2** [comment]
Fixed with #2153
