### ISSUE TITLE
[BUG] Soft lock after roar on double battle. Video & console logs provided.

### ISSUE THREAD

**Issue by HighMans** [pagefaultgames/pokerogue#2190]
**Describe the bug**
Soft lock after roar on double battle. Video & console logs provided.

**To Reproduce**
Session and data can be provided to a dev on discord. View video for steps.

**Expected behavior**
No soft locking.

**Screenshots / Videos**

https://github.com/pagefaultgames/pokerogue/assets/42877729/11c82db2-d443-4f1c-9ddf-b51ca6d1799f

**Device**
PC

**Additional context**

**Comment by Graymare** [comment]
This also happens with Dragon Tail, I would surmise it also affects any other "forced removal" attack.

**Comment by HighMans** [comment]
> Can't play the video, maybe reupload

Nothing wrong on my end, try downloading it?

**Comment by DustinLin** [comment]
https://github.com/pagefaultgames/pokerogue/assets/39450497/3d2e3836-e38d-4989-a892-aace07172055

able to reproduce:
bug is trying to run after roar-ing an opponent in a doubles battle

**Comment by DustinLin** [comment]
looking into this...

**Comment by Graymare** [comment]
To clarify, this bug also happens in double battles whenever Dragon Tail is used and does **not** KO, without any attempt to Run from the battle.  If Dragon Tail does KO, the game works fine.

To Reproduce:
Have a double battle with two pokemon on each side.
Dragon Tail one opponent such that it does not faint from Dragon Tail's damage.
Game softlocks.

**Comment by DustinLin** [comment]
is this still an issue with the changes from #2553 ?

**Comment by innerthunder** [comment]
fixed by https://github.com/pagefaultgames/pokerogue/pull/3346
