### ISSUE TITLE
[Feature] Saved Starter Pokemon Teams + Default Abilties/Natures/etc

### ISSUE THREAD

**Issue by LukeHartNS** [pagefaultgames/pokerogue#2191]
Sorry if this has already been requested, couldn't find anything in the issues.

When starting a new game, I often want to reuse a team of Pokemon.  In addition to there not being the ability to create and save teams (unless I'm dumb and missing it completely), your pokemon ability choices are not retained.  In particular, I think guts is a better ability for rattatta than run away, but that's not the default setting.

It would be nice to be able to manually set the default setup for a given Pokemon.  The egg moves appear to work like that, just not the abilities/gender/etc.

**Comment by Joshua-Stresing** [comment]
I agree with this, when you want to try and do some fast runs it can get infuriating to go through the trouble of planning out a team and starting a run only to find out some random thing isn't what you wanted it set to despite always setting it to said option.

**Comment by FrijDom** [comment]
This is especially annoying with certain mons that have gendered/forme-exclusive evos, stats, moves, etc. (Combee, Salandit, Lechonk, Rockruff, Indeedee, etc.); Since the default is male, half the time when grinding runs for eggs I end up with a male Combee as a starter.

**Comment by Dakurei** [comment]
Implemented in https://github.com/pagefaultgames/pokerogue/commit/111f4362fcc1f88f640923368297a0379257e11c
