### ISSUE TITLE
[BUG] Max Mushrooms and Mega Not Both Functional

### ISSUE THREAD

**Issue by SpecsGastro** [pagefaultgames/pokerogue#2196]
**Describe the bug**
On my Classic run, I have a Rare Shiny Blastoise that has both Max Mushrooms (currently active) and a recently obtained Blastoisite (active, but Blastoise is in GMax form). From past experience, I had imagined that deactivating both items on the Check Team screen and then activating the Blastoisite would cause Blastoise to become Mega Blastoise. Blastoise reverted to regular Blastoise upon deactivating the Max Mushrooms, but when attempting to Mega Evolve it, the Evolution screen would come up, and Blastoise would simply idle there without anything happening, forcing me to refresh the page. 

**To Reproduce**
1. Have a Pokémon with both Max Mushroom and Mega Stone
2. Deactivate both, reverting to normal form
3. Attempt to reactivate the item of the form the Mon was not in.

**Expected behavior**
As stated above, from previous interactions with form changing items, I had thought that Blastoise would have no issue Mega Evolving once taken down to its normal state. I am not sure if it is a problem with the new Check Team page or if it is perhaps because my Blastoise is Rare Shiny?

**Screenshots / Videos**
![image](https://github.com/pagefaultgames/pokerogue/assets/172738189/5b69a753-5762-402c-8509-b9f15533659c)

**Device**
PC

**Additional context**
I have not tested this with any other Pokémon, but in the past this sort of interaction has worked fine. Additionally, I am able to revert and Gigantomax Blastoise without the bug occurring, it only appears to be when I try to Mega Evolve. Strangely, I attempted to spend a single wave as regular Blastoise to see if that would change anything. When I did this, and then attempted to Mega Evolve, refreshing and Continuing the save would jump straight to the idling Blastoise on the evolution screen. I loaded up a different save, then reloaded this one, and I was bumped back two floors (to before I had deactivated the Max Mushrooms).

**Comment by Haliaxical** [comment]
I am experiencing a similar bug with just the Blastoisinite on a red shiny Blastoise in Endless mode. I do not have Max Mushrooms, just a base form Blastoise. When I attempt to pick up the Mega Stone for the first time and give it to Blastoise the game moves to the evolution screen and I see Blastoise's idle animation on repeat until I am forced to refresh the page. 

This occurs each time I attempt to pick the Mega Stone as the end-of-floor reward - I have seen the stone on two separate floors now and have refreshed a few times on each floor with the same result every time. Picking any other item functions normally.

**Comment by to0fpase** [comment]
I just softlocked my endless run with the same shiny Blastoise with the same issue, except it loads the evolution screen on file boot. I'm very disappointed.

**Comment by Tempo-anon** [comment]
Looks like this is resolved.
