### ISSUE TITLE
Shellder changed abilities on evo

### ISSUE THREAD

**Issue by Aeiiry** [pagefaultgames/pokerogue#220]
Don't have a picture of the before/after, but I simply used a water stone on my shellder that had skill link, and the cloyster it evolved into had shell armor instead.

**Comment by Aeiiry** [comment]
Just did another run and didn't experience this, no idea of any similarities or differences in the circumstances

**Comment by bennybroseph** [comment]
Cannot Reproduce

**Comment by Madmadness65** [comment]
Cannot reproduce this issue
