### ISSUE TITLE
[BUG] Softlock after releasing lead mid battle.

### ISSUE THREAD

**Issue by RNGezeus** [pagefaultgames/pokerogue#2201]
**Describe the bug**
Moving cursor left after confirming release lets you release lead mid battle.

**To Reproduce**
1. Start battle
2. go into party and press release on a member not in battle
3. hold left and then confirm release, or press left in very quick succesion after confirming release.
4. witness lead going bye-bye
5. go back and try continue combat
6. Softlock

**Expected behavior**
Game to not let me release lead.

**Screenshots / Videos**
https://github.com/pagefaultgames/pokerogue/assets/46976469/f9509496-6250-4d7d-8628-71fee94683d6

**Device**
PC

**Additional context**
There are a lot of menus you can break similarly between menu transitions. Most common people find is "manage moves" for mons with big lvl 1 moveset. Very easy to move before menu loads leading to you getting to a different mon than intended

**Comment by ysh4296** [comment]
- i think show text function at class MessageUiHandler makes a 'change mode gap' at Text animation Event ("`Do you really want to release ${pokemon.name}?`")

- we can move cursor to leader pokemon in this 'change mode gap', because input handler changes after the gap

- we have two choices
    - blocking or adding specific input handler at this 'change mode gap' (i'm not sure what to implement here)
    - save this.cursor as variable after select a pokemon (but still allow to move cursor)

what would be better choice?

**Comment by Tempo-anon** [comment]
Unwinnable by insanity trope moment. The corresponding linked PR should fix this.
