### ISSUE TITLE
[Feature] Batch hatching/skipping option plus customizable options for it.

### ISSUE THREAD

**Issue by Joshua-Stresing** [pagefaultgames/pokerogue#2202]
As someone who is farming egg vouchers and does huge batches of egg hatching. I tend to run into the time sync of spamming a button to go through 90+ hatches of common pokemon that I'm never gunna bother looking at because it takes to much time.

It would be great if there was an option to skip a batch of hatching eggs and skip to just adding whatever they end up giving you. To max out the quality of life of this feature, being able to enable skipping ONLY certain types of rarities woulda be great, so I could skip commons and still see my legendaries hatch. It'd also be great to be alerted if you get something rare like an ability you didn't have before on something, a shiny, and so on even if you would be skipping that rarity normally.

So as an example I have it set to skip Commons and Rares, and I hatch 100. When they hatch I wouldn't have to look at something else while I mindlessly spam click through 100 eggs and instead it shows me something for the 1 shiny that was in the batch, and the 2 abilities I didn't have on 2 pokemon. And if there was a legendary or epic that was supposed to also hatch in that batch for whatever reason I could still see it hatch like normal.

I know this would take some finagling to work, but any level of implementation of any of this would be an enormous bonus to gameplay for anyone that's mass collecting.

**Comment by Joshua-Stresing** [comment]
I did not see that it was apparently being worked on already. 10/10 stuff here. :)

**Comment by torranx** [comment]
Resolved in https://github.com/pagefaultgames/pokerogue/pulls?q=is%3Apr+egg+skip+is%3Aclosed
