### ISSUE TITLE
[BUG]can not continue the game

### ISSUE THREAD

**Issue by cheeseburqxy** [pagefaultgames/pokerogue#2205]
can not continue the game when finishing killing the boss of level 550.
![image](https://github.com/pagefaultgames/pokerogue/assets/35998790/52ba3e8e-ec01-41f0-8dfe-b1c6851c53db)

**Comment by koni368** [comment]
same here but for 400 
![bug poke](https://github.com/pagefaultgames/pokerogue/assets/172840665/1caa277f-c20b-4ede-9001-3cdee9ac9b3c)

**Comment by Knavethefish** [comment]
Had the same issue on floor 1050 of endless. Deleted save and started another, same problem on floor 50.

**Comment by Tempo-anon** [comment]
Fix is in. Shift f5
