### ISSUE TITLE
[BUG] Stuck in Ice Cave on Endless

### ISSUE THREAD

**Issue by Terrorforge** [pagefaultgames/pokerogue#2209]
**Describe the bug**

Had a peculiar bug where I kept getting the Ice Cave biome over and over. My pokemon would be called back and sent out again as if the biome had changed, but it would just be Ice Cave again. I'm not entirely sure how long it went on because I didn't pay enough attention to when it started, but it was the case at least from waves 2041-2049, and a few waves prior to that. After reaching the paradox boss at 2150, it appears to have resolved itself.

**To Reproduce**

Unsure. End up in Ice Caves on Endless I guess, but I'm not sure if this problem is actually specific to that biome or if it can happen anywhere.

**Expected behavior**

The biome changes.

**Screenshots / Videos**

![image](https://github.com/pagefaultgames/pokerogue/assets/5107449/278f400b-e04e-4732-b83e-6c77c2f34679)

![image](https://github.com/pagefaultgames/pokerogue/assets/5107449/49da1255-1865-4386-8d9d-26954e50ca64)
Two waves later. Notice how the trainer sprite is out, but it's just Ice Cave again. It happened immediately again on waves 2144 and 2149, but I failed to get screenshots.

**Device**

Chrome on PC.

**Additional context**

Unfortunately I messed up and exported my "data" instead of my "session" when I was on 2141 and started to pay attention. But here's that data and the session data from later in the run on the off chance it helps:
[data_Terrorforge_IceCave.zip](https://github.com/user-attachments/files/15841876/data_Terrorforge_IceCave.zip)
[sessionData_Terrorforge_IceCave_TooLate.zip](https://github.com/user-attachments/files/15841881/sessionData_Terrorforge_IceCave_TooLate.zip)

**Comment by Tempo-anon** [comment]
There was a brief bug where biomes were not cycling correctly (resulting in one player being stuck in the Town biome for 30+ waves!) The issue should be resolved now.
