### ISSUE TITLE
Pokerogue Ability Display [Maybe a BUG]

### ISSUE THREAD

**Issue by Anjaconda** [pagefaultgames/pokerogue#2223]
the animation for when an ability is activated has changed for me and i'm wondering if that is a bug or an intentional design choice because the text is nearly fully off of the bar.
https://github.com/pagefaultgames/pokerogue/assets/172850113/d35dd500-a51d-4498-92f5-18a37a78fa8f

**Comment by Tempo-anon** [comment]
It's to allow space for the word "passive" as well as other languages

**Comment by Anjaconda** [comment]
that makes sense, thanks for telling me
