### ISSUE TITLE
[BUG] Sprites broke down and pulled the wrong ones

### ISSUE THREAD

**Issue by Tystorm27** [pagefaultgames/pokerogue#2232]
![Buggy](https://github.com/pagefaultgames/pokerogue/assets/172860076/bdc9ae2e-5a07-44e4-9fcc-188612c65f0b)
**Describe the bug**

**To Reproduce**
Unsure of how it happened I hit 190 and it decided to do this, restarting the game or my computer has not fixed it

**Device**
PC

**Comment by Mewtwo2387** [comment]
Try clearing browser cache
