### ISSUE TITLE
[BUG] Super-fang is not affected by multi-lens despite being a damage dealing attack

### ISSUE THREAD

**Issue by CDeltakai** [pagefaultgames/pokerogue#2237]
**Describe the bug**

I am not 100% if this is actually a bug or an intended balance decision, but Super-fang (and potentially other similar moves like Nature's Madness/Ruination) do not get multiple hits when the pokemon using the move is holding Multi-Lens.

**To Reproduce**

1. Have a pokemon with Super-fang hold Multi-lens
2. Use Super-fang on enemy pokemon
3. Enemy is only hit once by Super-fang.

**Expected behavior**

Super-fang should have hit multiple times with Super-fang, effectively cutting enemy HP by 75% if holding one multi-lens, or more times with more multi-lens. 

**Screenshots / Videos**

**Device**

PC, Firefox

**Additional context**

**Comment by HighMans** [comment]
> I believe it's by design, it would be way too strong otherwise: with a max stack multi-lens (3) a single super fang inflicts 93.75% damage of total health, no matter the user or the target. 🤔

Agreed lmfao, that would be OP AF

Imagine metal burst with max stack multi-lens lol

**Comment by flx-sta** [comment]
This is by design to keep the move at bay.
