### ISSUE TITLE
[Feature] Hotkey to reroll rewards

### ISSUE THREAD

**Issue by RNGezeus** [pagefaultgames/pokerogue#2247]
**Is your feature request related to a problem? Please describe.**
Rerolling now takes 2 clicks, moving down and then confirm. More effort than needed and introduces minor chance of errors happening. I'd like this reduced to 1 click

**Describe the Feature**
Ability to bind reroll to a hotkey

**Additional context**
Could also be solved by placing cursor back to reroll. IMO a dedicated reroll hotkey would be smoother though and makes accidental rerolls more of a user error than double Ghost inputs or UI not reacting due to user speed or lag.

**Comment by tejuRajbabu** [comment]
Agreed on this, I'd be happy to work on this if this gets traction!

**Comment by torranx** [comment]
already being worked on https://github.com/pagefaultgames/pokerogue/pull/2167#discussion_r1639958548

**Comment by RNGezeus** [comment]
> already being worked on #2167

ah, I only searched issues board so I missed it. Nice.

**Comment by torranx** [comment]
Resolved in https://github.com/pagefaultgames/pokerogue/pull/3666
