### ISSUE TITLE
[Feature]More Uses For Candy

### ISSUE THREAD

**Issue by KillerDogeEmpire** [pagefaultgames/pokerogue#2290]
You know how some people max out the upgrades for pokemon but still have a ton of candy? Why not make it so people can use the candy to upgrade pokemon into a shiny. it would be in order so you would pay for it to becom a normal shiny, then a tier 2 and finally an epic, and the price would increase per upgrade. this will make another use for candies, plus make it a little easier to get those shiny legendaries.

Also if you do this, consider letting us upgrade IVS with candies as well.
It also can be used for egg moves. Doing these all would make candies more useful and not a waste just being stock piled adding up

This could be an example of the prices

Boost IVs = 25 candies
Tier 1 shiny 65
tier 2 80
tier 3 100.

you could always adjust the prices of how much they'd be but this is an example

**Comment by Tempo-anon** [comment]
There are definitely plans for using excess candy to be able to improve IVs, get shinies, and get egg moves.
