### ISSUE TITLE
[BUG]업적 보상 미지급

### ISSUE THREAD

**Issue by IWFYM** [pagefaultgames/pokerogue#2312]
알에서 전설 포켓몬을 잡았는데 업적 보상으로 주는 바우처를 받지 못함 게임 아이디 IWFYM

**Comment by CodeTappert** [comment]
Please provide english Text

**Comment by Tempo-anon** [comment]
Achievements do not give voucher rewards. The voucher is only the icon for it.
업적은 바우처 보상을 제공하지 않습니다. 바우처는 아이콘일 뿐입니다.
