### ISSUE TITLE
[BUG] Black Pixels appear over Wo-Chien back sprite during battle

### ISSUE THREAD

**Issue by FaylenSol** [pagefaultgames/pokerogue#2318]
Wo-Chien has a bad pixel on the top of its eyestalks on the "Rear" version that appears and vanishes. It is on its normal form, yellow shiny, and red shiny form. It is rather distracting. :(

**To Reproduce**

1. Select Wo-Chien as a starter or catch Wo-Chien during a run
2. Use them in battle
3. See the bad pixels appear and disappear. 

**Expected behavior**
Not having black pixels suddenly appear 

**Screenshots / Videos**
![image](https://github.com/pagefaultgames/pokerogue/assets/11862636/b7b025de-b307-4d74-93f2-4bf3c10985f9)

**Device**
PC, on Google Chrome.

**Additional context**

None

**Comment by chaosgrimmon** [comment]
fixed
