### ISSUE TITLE
[Enhancement] Deprecated packages

### ISSUE THREAD

**Issue by 3ae3ae** [pagefaultgames/pokerogue#2353]
While installing the program, I found that two packages are deprecated.

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.

npm warn deprecated koa-router@10.1.1: **IMPORTANT 10x+ PERFORMANCE UPGRADE**: Please upgrade to v12.0.1+ as we have fixed an issue with debuglog causing 10x slower router benchmark performance, see https://github.com/koajs/router/pull/173

Inflight should be replaced with lru-cache, and koa-router should be updated.
In particular, inflight has a memory leak issue.

**Comment by Tempo-anon** [comment]
Going to keep this issue open until inflight is ripped out

**Comment by torranx** [comment]
Resolved in https://github.com/pagefaultgames/pokerogue/pull/3213
