### ISSUE TITLE
[BUG] Sheer Force edge cases

### ISSUE THREAD

**Issue by Tempo-anon** [pagefaultgames/pokerogue#2354]
**Describe the bug**
There's still a few edge cases involving Sheer Force. Opening this general ticket to track them

**To Reproduce**
Use the moves

**Expected behavior**
Sheer Force does not disable Relic Song transforming Meloetta
Eerie Spell and Secret Power are not correctly disabled
Still need to decide how this interacts with Grip Claw
Missing some unit tests on King's Rock stacks
Not working with No Retreat and some other 100% selfstatusmoves
Still sets up hazards with attacks that set up hazards

**Screenshots / Videos**
n/a

**Device**
n/a

**Additional context**
n/a

**Comment by Snailman11** [comment]
https://discord.com/channels/1125469663833370665/1222643458813071420/1286780765127839785
Electro shot is unaffected, no popup

**Comment by Snailman11** [comment]
https://github.com/user-attachments/assets/71f91c32-7bf5-493b-8fb2-a2264f6a7243

-Relic Song Still does not block Meloetta forme change
-No retreat works,
-Ceaseless and Stone Axe do not set hazards
