### ISSUE TITLE
[Feature] Reveal your Pokémon line-up when you clear Classic Mode 

### ISSUE THREAD

**Issue by ventulus95** [pagefaultgames/pokerogue#2357]
**Describe the Feature**
Sometimes you want to know which lineup won in Classic mode. We'd like to see you implement the ability to take a screenshot of your Pokémon lineup to commemorate your win.
Even better would be to have all the Pokémon exposed and standing with their trainers.

**Comment by Tempo-anon** [comment]
This has been implemented now that we have a hall of fame and run history
