### ISSUE TITLE
[BUG] Mono Gen Challenge And Evolution

### ISSUE THREAD

**Issue by Kanbe-Kotori** [pagefaultgames/pokerogue#2363]
Magby is available in Gen2 Challenge, but it becomes unavailable after evolved into magmar. Is it a bug or a feature?

**Comment by Kanbe-Kotori** [comment]
And this also cause the game to get stuck and not continue

**Comment by Tempo-anon** [comment]
Not a bug. Magmar is gen 1, and Magmortar is gen 4. Only Magby is usable in gen 2 challenge
