### ISSUE TITLE
[BUG] Unlocked Egg Moves Changed after Beating Classic Mode for the First Time

### ISSUE THREAD

**Issue by lazkmet** [pagefaultgames/pokerogue#2369]
Cleared Classic Mode with starter Comfey, only Buzzy Buzz egg move unlocked. When starting next run, Buzzy Buzz is locked and Revival Blessing is unlocked. Not sure whether it has something to do with the "has beaten the game" medal, but my other starter Pokemon which I took to the end with me kept their unlocked egg moves.

**To Reproduce**
1. Complete a run for the first time with a starter Comfee that only knows the egg move Buzzy Buzz
2. Attempt to start a new run, find that the unlocked Egg Moves have changed

**Expected behavior**
I expected my pokemon to keep the egg moves I had previously unlocked.

**Screenshots / Videos**
![image](https://github.com/pagefaultgames/pokerogue/assets/82974005/d4ca019e-5b78-411e-9c61-a07e8559b30d)
Unfortunately I do not have an image of my team before the Egg Move switched, so you'll have to take my word for it that Buzzy Buzz was the only unlocked move.

**Device**
Playing in Google Chrome, on a Windows 11 Laptop - Username: ThiefOfVoid413

**Additional context**
The Comfee had Pokerus from a different starter, and the run spanned multiple days so it was not from one of the current Pokerus starters.
After finishing the run, I pulled a bunch of eggs from the Gacha (several from the Egg Move pool), which may have had an effect on the "Egg Moves Known" flags?

**Comment by Tempo-anon** [comment]
3 days ago there were egg move changes. 
Comfey's egg moves went from   
```
[Species.COMFEY]: [ Moves.BUZZY_BUZZ, Moves.POLLEN_PUFF, Moves.STRENGTH_SAP, Moves.MATCHA_GOTCHA ],
//to 
[Species.COMFEY]: [ Moves.REVIVAL_BLESSING, Moves.POLLEN_PUFF, Moves.STRENGTH_SAP, Moves.MATCHA_GOTCHA ],
 ```

You unlocked the first move slot so that is why Comfey has revival blessing instead of buzzy buzz
