### ISSUE TITLE
Rare candy don't heal our dead pokemon.

### ISSUE THREAD

**Issue by HerIsDia** [pagefaultgames/pokerogue#237]
Idk if it's a feature or something missing from the games, but in the normal pokémon game when a mon is dead and then we use a rare candy on it. The HP that the pokemon gains from the level up is added to the current hp of the pokemon to revive it. I guess it might be a feature but I want to be sure so I'm doing this issue.

Steps for reproducing the issue:
- Play the game
- Having a dead pokemon
- Use a rare candy on it

**Comment by Flashfyre** [comment]
This is not a bug, it is an intentional balance change because rare candies are so common and there is a bug difference between a fainted Pokemon and a Pokemon with 1hp.
