### ISSUE TITLE
[BUG] Getting hit by hail triggers enigma berry

### ISSUE THREAD

**Issue by Knowaion** [pagefaultgames/pokerogue#2376]
This happened to me in Endless in the Ice Cave Biome, using Latias facing a Snorunt. After defeating the Snorunt, Latias got pelted by the hail, which triggered its Enigma Berry. This should not happen, as Enigma Berry should only trigger on attacks.

**Comment by schmidtc1** [comment]
I can't seem to reproduce this. Are you sure it was hail that triggered the berry, and your Latias wasn't hit with a super effective move during the turn? The berries usually trigger at the end of the turn so it might've just seemed like hail triggered it.

**Comment by Knowaion** [comment]
No I'm not sure. Maybe the enigma berry triggered in response to an attack but the message just appeared after the hail proc.

**Comment by flx-sta** [comment]
Can not reproduce on `beta` (5edaec9f98f47edde4432ef4703530ec6ec4277b)
