### ISSUE TITLE
[BUG] 9세대 몬스터 그래픽이 깨졌는데 안고쳐집니다

### ISSUE THREAD

**Issue by mike75-sj** [pagefaultgames/pokerogue#2381]
오로지 9세대만 깨졌고 나머지는 멀쩡합니다. F5도 눌러봤고,다시 깔아도 봤고,설정도 바꿔봤지만 고쳐지지 않았습니다
이 노트북은 최근에 170정도 주고 산거라 거의 새거나 다름이 없습니다 뭐가 잘못된지 모르겠습니다
![스크린샷 2024-06-19 020258](https://github.com/pagefaultgames/pokerogue/assets/173187180/b787a456-cc52-4bdc-bc34-7f9acfda79b6)

**Comment by Tempo-anon** [comment]
Shift + F5

**Comment by Tempo-anon** [comment]
Broken images mean your cache is out of date. Use shift + F5 to clear your cache and it should be fixed
손상된 이미지는 캐시가 오래되었음을 의미합니다. 캐시를 지우려면 Shift + F5를 사용하세요. 그러면 수정되어야 합니다.
