### ISSUE TITLE
[BUG] Friendly King’s Shield move lowers other Friendly Pokémon’s Attack in double battle when both friendlies are hit by opposing Pokémon’s Breaking Swipe

### ISSUE THREAD

**Issue by davidfague** [pagefaultgames/pokerogue#2382]
**Describe the bug**

**To Reproduce**

1. Go to double battle.
2. Use King’s shield with one of your Pokémon.
3. King’s shield Pokémon gets hit by opposing Pokémon’s wide contact move: Breaking Swipe
4. Attack is lowered on opposing Pokémon and friendly Pokémon that is not protected by King’s shield.

**Expected behavior**

**Screenshots / Videos**

**Device**

**Additional context**

**Comment by lockadox** [comment]
Breaking Swipe lowers the attack of those hit by it.

**Comment by davidfague** [comment]
Oh I see. Thanks for clarifying.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Tempo-anon** [comment]
Not a bug
