### ISSUE TITLE
Pokemon fainted by destiny bond opens pokemon change screen after shop[BUG]

### ISSUE THREAD

**Issue by nkong678** [pagefaultgames/pokerogue#2387]
**Describe the bug**
When a pokemon is fainted by destiny bond, the shop appears before you send out your next pokemon. After the shop resolves, the screen to send out your next pokemon appears without the option to send out a pokemon. This soft locks the game.

**To Reproduce**
1. Find wobbuffet
2. Faint to destiny bond
3. Resolve Shop

**Expected behavior**
1. Pokemon faints to destiny bond
2. Send out next pokemon
3. Shop appears

**Screenshots / Videos**
Figured out how to resolve (win battle without pokemon fainting to destiny bond), and missed chance to take video. Didn't understand bug until after.

**Device**
Mac, google chrome

**Additional context**

**Comment by Snailman11** [comment]
https://github.com/pagefaultgames/pokerogue/pull/1236
