### ISSUE TITLE
[BUG] Ice face cancelling Multi hit attacks

### ISSUE THREAD

**Issue by RNGezeus** [pagefaultgames/pokerogue#2388]
Emptied filter and searched on "Ice Face", can't see any bug reports like this

**Describe the bug**
When using multi-hit moves such as bulled seet, bone rush etc. on a Ice face user the attack breaks face and then immediately stops without doing remaining hits

**To Reproduce**
Use any multi-hit move on a pokemon with Ice Face

**Expected behavior**
The first hit to break face, subsequent to do damage

**Screenshots / Videos**
https://github.com/pagefaultgames/pokerogue/assets/46976469/b25b2d68-2936-4d03-8421-81fafb9e6402

**Additional context**
https://www.reddit.com/r/PokemonSwordAndShield/comments/rofufd/how_does_eiscues_ice_face_work_in_detail/
" Ice face will only block the first hit of a multi hit. Surging strikes will beat the shit out of eiscue. "

https://game8.co/games/pokemon-sword-shield/archives/278552
"multi-hit attacks like [Icicle Spear], which can break through Ice Face with the first hit and continue to deal damage."

Reduce it to (P) status until fixed?

**Comment by zacharied** [comment]
This was introduced by #2165, specifically https://github.com/zacharied/pokerogue/blob/e10d67858f3a657705c4d0ef984e4de6ab57ed8d/src/data/move.ts#L1579.
