### ISSUE TITLE
[BUG]When wild Pokemon use 'return' at weather 'Sunny' game stops

### ISSUE THREAD

**Issue by ChoiSungwoo1216** [pagefaultgames/pokerogue#2394]
**Describe the bug**

풀숲에서 날씨가 Sunny일 때, 더블매치에서 야생  솜솜코가 유턴을 쓰고 야생 엘풍이 기가드레인을 쓰는 타이밍에 에러가 난다

에러 로그에서는 arena를 찾지 못한다고 나와있다.

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

![화면 캡처 2024-06-19 112621](https://github.com/pagefaultgames/pokerogue/assets/97146749/d724bf4a-7b84-45d5-ad91-264bab17bc30)
![화면 캡처 2024-06-19 112649](https://github.com/pagefaultgames/pokerogue/assets/97146749/a74bc842-f755-4b6b-92ab-27256ae4d07b)
**Device**

* pc
**Additional context**

**Comment by Tempo-anon** [comment]
This issue should be fixed now. Clear your cache (Shift + F5) and open a new issue if this persists.
