### ISSUE TITLE
[BUG] The Legendary egg I had is gone.

### ISSUE THREAD

**Issue by idonghun** [pagefaultgames/pokerogue#2398]
The Zaxian Pickup Legendary egg that I pulled out on June 16 is gone.

The statistics also show that 5 eggs were pulled out, but only 4 eggs were actually hatched.

![스크린샷 2024-06-19 160510](https://github.com/pagefaultgames/pokerogue/assets/173238772/74fe20bd-76ed-4736-b8de-07a7240da145)
![스크린샷 2024-06-19 160913](https://github.com/pagefaultgames/pokerogue/assets/173238772/db85cede-46dc-4f99-b659-f98c12ed2a0b)
![스크린샷 2024-06-19 160949](https://github.com/pagefaultgames/pokerogue/assets/173238772/0347b21b-c920-4fa1-8e66-f860bb2aa0b4)
![스크린샷 2024-06-19 161055](https://github.com/pagefaultgames/pokerogue/assets/173238772/91f0206c-8771-4a84-bab3-d5c5d71a0266)

**Comment by flx-sta** [comment]
We are not able to restore lost data.
