### ISSUE TITLE
[BUG] Delta stream only triggering if end result is super effective

### ISSUE THREAD

**Issue by RNGezeus** [pagefaultgames/pokerogue#2418]
Did search the issue board for "Delta" and can't see this mentioned

**Describe the bug**
Delta stream is currently nerfed and seems to only work if a move is calculated as being super effective after type combination is taken into account. This means that moves that do neutral due to type combinations before delta stream is active end up not getting reduced in effectiveness.

**To Reproduce**
use an electric move on a Dragon/Flying before and after delta stream and compare

**Expected behavior**
That delta stream always reduces move effectiveness when calculating flying weakness and not just for super effective cases (I find it hard to phrase this concisely)

**Screenshots / Videos**
strong winds inactive: Electric/rock/ice doing,  6(normal) / 10(super) / 23(super)
https://github.com/pagefaultgames/pokerogue/assets/46976469/ba54730c-0dc8-43d1-9bb5-c9473bca1532

strong winds active: Electric/rock/ice doing,  6(normal) / 5(normal) / 12(super)
https://github.com/pagefaultgames/pokerogue/assets/46976469/c67b9b40-6ac2-41d8-a078-00077a69568e

**Additional context**
Clear documentation with examples is a bit rough to find so I understand if bulbapedia can be misleading that it only activates if end result was super effective based on "Strong winds cause moves that would be super effective against pure Flying-type Pokémon to instead deal neutral damage to all Flying-type"
https://bulbapedia.bulbagarden.net/wiki/Delta_Stream_(Ability)

Using Showdowns damage calculator I got results that reduced electric damage towards target when Delta winds was active after giving it dragon type in addition to flying
https://calc.pokemonshowdown.com/

I have verified that showdown is correct using personal game copies, Spark did 15 dmg with stream active saying not very effective, 30 without doing neutral. I can provide scuffed mobile footage if demanded.

Edit: Clarifcation that electric was tested against a flyting/dragon for the case where secondary resists electric

**Comment by Tempo-anon** [comment]
I seem to remember Delta Stream being implemented this way because that's how the Bulbapedia description made it sound. If you've verified on Showdown then this is a bug
