### ISSUE TITLE
[BUG] Game Settings not saved

### ISSUE THREAD

**Issue by yoshiyahoo** [pagefaultgames/pokerogue#2422]
**Describe the bug**
Every time I close and re-open my browser, my Game Settings are reset to default. 

**To Reproduce**
1. Close your browser
2. Open your browser
3. Launch PokeRogue
4. Log in
5. Go to Game Settings
7. See Error

**Expected behavior**
I expect my Game Settings to be saved when I enter Pokerogue. I don't have to set them again manually.

**Video**
![Click Here](https://github.com/pagefaultgames/pokerogue/assets/6581612/983e8e18-5ad2-428e-ba68-2b90371ec2c9)

**Device**
I play on the Vivaldi Browser on Windows 11

**Comment by l-33ter** [comment]
- Do you play in 'incognito-mode'?
- Did you try an other browser?
- Did you try ![turn off](https://github.com/pagefaultgames/pokerogue/assets/77815858/0b1c710a-33c9-471a-9b1d-c80fe17e794d)

**Comment by yoshiyahoo** [comment]
I don't play in incognito mode. I will test turning off those two programs and see what happens.

**Comment by yoshiyahoo** [comment]
Just tested it on google chrome, Arc, and Firefox and there's no issue. I'm not sure what's going on with my Vivaldi on windows, but I don't think it's a problem on the games end

**Comment by Tempo-anon** [comment]
Check your vivaldi settings to make sure you're saving local data. Going to close this issue out.
