### ISSUE TITLE
[BUG] Game Result is not Saved

### ISSUE THREAD

**Issue by shufel90** [pagefaultgames/pokerogue#2424]
I'm playing the game on two desktops.
On desktop A, I played in Endless Mode and got past 500 floors.
However, when I switched to desktop B, I got a game over.
The new Pokémon I caught during gameplay did not unlock in the starting roster.
Most of them were caught while playing on desktop A.
My PokeRogue Id is temsini.
I played that game on 2024.Jun.19th
I playing in Firefox v.127.0.1

**Comment by l-33ter** [comment]
Do you [play from here](https://pokerogue.net/)? Or you do play on **localhost**?

**Comment by shufel90** [comment]
in pokerogue web page, not local playin pokerogue web page, not local play

**Comment by shufel90** [comment]
in pokerogue web page, not local play
