### ISSUE TITLE
[BUG] Partner Pikachu evolves into Raichu.

### ISSUE THREAD

**Issue by 3ae3ae** [pagefaultgames/pokerogue#2430]
**Describe the bug**

Partner Pikachu evolves into Raichu.

**To Reproduce**

Use Thunder Stone on your partner Pikachu.

**Expected behavior**

Partner Pikachu should not be able to evolve.

**Comment by Madmadness65** [comment]
In canon, yes, this is true. However, it (and Partner Eevee) was explicitly made able to evolve, so they wouldn't be stuck as the partner forms the whole time.

**Comment by 3ae3ae** [comment]
Okay, thank you for your response.
