### ISSUE TITLE
[BUG] Sand attack affected by levitate

### ISSUE THREAD

**Issue by RNGezeus** [pagefaultgames/pokerogue#2447]
**Describe the bug**
Sand attack currently negated by levitate

**To Reproduce**
Sand-attack on a levitate user

**Expected behavior**
Sand-attack to work on levitate (and flying types, but haven't bothered testing that)

**Additional context**
https://bulbapedia.bulbagarden.net/wiki/Sand_Attack_(move)
"Sand Attack is now a Ground-type move, but it is not affected by immunities to Ground-type. "

https://bulbapedia.bulbagarden.net/wiki/Levitate_(Ability)
"Despite the fact that its descriptions from Generation IV on state that Levitate gives immunity to all Ground-type moves, Pokémon with Levitate are affected by the status move Sand Attack."

**Comment by FreshTuna** [comment]
Interesting. I'm new here, and I would like to follow up how their gonna handle this problem. 🧐

**Comment by Frogatog** [comment]
I think all that's needed for this is for Sand Attack to get the same `NeutralDamageAgainstFlyingTypeMultiplierAttr` attribute that Thousand Arrows has.

**Comment by Tempo-anon** [comment]
Does sand attack affect levitate and flying types now?

**Comment by Snailman11** [comment]
Link to Discord (Sans Attack + Levitate)
https://discord.com/channels/1125469663833370665/1260188925604139121

**Comment by frutescens** [comment]
Sand attack is able to hit non-grounded flying types and Pokemon that used magnet rise in the current game. 
The bugged interaction between Pokemon with the ability Levitate and Sand Attack has been fixed in beta and will hopefully be live soon.
