### ISSUE TITLE
[Feature] Egg Hatching Time in Pockerogue Game is Too Time-Consuming

### ISSUE THREAD

**Issue by KAMJAIM** [pagefaultgames/pokerogue#2453]
I've been playing Pockerogue for a while now and really enjoy the game. However, I find that the egg hatching time is excessively long and is starting to take away from the overall experience. Waiting for eggs to hatch feels like it significantly slows down progress and can be quite frustrating. I believe that reducing the hatching time would greatly improve the gameplay and make it more enjoyable for everyone.

Watching around 300 eggs hatch is really exhausting. I'm curious when a new update addressing this issue will be released.

**Comment by torranx** [comment]
Duplicate https://github.com/pagefaultgames/pokerogue/issues/2202. Please search issues or pull requests first before opening one.
