### ISSUE TITLE
[BUG] Thousand Arrows grounds the opponent without being used

### ISSUE THREAD

**Issue by Tempo-anon** [pagefaultgames/pokerogue#2464]
**Describe the bug**
Thousand Arrows adds BattlerTagType.IGNORE_FLYING even when not actually used

**To Reproduce**
Hover over Thousand Arrows

**Expected behavior**
The grounding effect only applies after the move is used

**Screenshots / Videos**
![](https://i.ember.zone/PrXoBjFGl7eajTmz.png)

**Device**
n/a

**Additional context**
n/a

**Comment by ngiraud99** [comment]
This bug faces the same problem as this [Issue](https://github.com/pagefaultgames/pokerogue/issues/2447).

We need to implement a check that allows ground attacks to hit targets despite standard ground immunities. However with the current way how thousand arrows is implemented, NeutralDamageAgainstFlyingTypeMultiplierAttr is already applied if you hover over the attack.
