### ISSUE TITLE
[BUG] Night Shade is unaffected by multi hit lens 

### ISSUE THREAD

**Issue by DaltJM** [pagefaultgames/pokerogue#2468]
**Describe the bug**

Using nightshade does not proc the multi hit item.
**To Reproduce**

1. Have Ghouldango 
2. Equip Ghouldango with multi hit item
3. Use night shade 

**Expected behavior**

That night shade would hit 1 + however many multi hit lens. 
**Screenshots / Videos**

**Device**

**Additional context**

**Comment by damocleas** [comment]
This is intended behavior, and is not a bug.
