### ISSUE TITLE
[BUG] CORS policy error

### ISSUE THREAD

**Issue by QHPHBias** [pagefaultgames/pokerogue#2472]
![image](https://github.com/pagefaultgames/pokerogue/assets/37543914/dd4cbfb0-98cc-43a0-a53b-0fe334b6a48d)

Access to fetch at 'https://api.pokerogue.net/account/info' from origin 'https://pokerogue.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by r0kiE** [comment]
same problem

**Comment by wmathor** [comment]
same problem

**Comment by flx-sta** [comment]
Does the same issue appear on mobile-data and/or other devices ?
On a private browsing window ?

**Comment by QHPHBias** [comment]
> Does the same issue appear on mobile-data and/or other devices ? On a private browsing window ?

No
On a private browsing window.

**Comment by flx-sta** [comment]
If a private browsing windows works it has to do with caching on your device
