### ISSUE TITLE
Dachsbun's Well Baked Body[BUG]

### ISSUE THREAD

**Issue by ZzDanier** [pagefaultgames/pokerogue#2484]
**Describe the bug**
Ability did not trigger

**To Reproduce**

1. Double Battle
2. Allied Entei side attacked into dachsbun with fire fang
3. Dachsbun took damage

**Expected behavior**
Dachsbun should  not take damage and should get a defense increase

**Screenshots / Videos**
[image](https://github.com/pagefaultgames/pokerogue/assets/173446729/dc436b10-9914-4488-8dbd-4d8f1d3d31e6)

**Device**
Firefox

**Additional context**

**Comment by Tempo-anon** [comment]
Needs more context. Was there ability suppression like neutralizing gas or mold breaker on the field?

**Comment by sudhamhebbarbrown** [comment]
Koffing has neutralizing gas.
