### ISSUE TITLE
[BUG] Confusion damage occurs too early

### ISSUE THREAD

**Issue by Gamez0** [pagefaultgames/pokerogue#2488]
**Describe the bug**

When an enemy attacks itself due to the confusion status, its health decreases first, followed by the message indicating that it attacked itself. In other words, health decreases too early.

**To Reproduce**

I have updated the step more specifically
1. First battle with rival (Classical mode)
2. Abra used confusion to Torchic(rival)
3. Torchic got confusion status
5. The health decreases first before the message "... is confused" is displayed
6. Reached error

**Expected behavior**
The message "... is confused" and "It hurt itself ..."  should appear first.
Then the health should decrease.

**Screenshots / Videos**

**Device**

PC, chrome (126.0.6478.114)

**Additional context**

**Comment by DustinLin** [comment]
This below looks normal to me? Perhaps it only happens during the rival battle?


https://github.com/pagefaultgames/pokerogue/assets/39450497/37955344-9e26-42fd-8f3c-25cece6b5898

**Comment by Gamez0** [comment]
@DustinLin Yeah, when I tried to reproduce in normal battle the issue didn't occur, I'll try to bring reproduce.

**Comment by Tempo-anon** [comment]
Closing for now. Please open a new issue if you can reproduce this.
