### ISSUE TITLE
[BUG] Chrome is absolutely wrecked after installing this

### ISSUE THREAD

**Issue by SoosSaas420** [pagefaultgames/pokerogue#2490]
Google Chrome has multiple bugs now. I installed everything properly and it ran fine for like 20 minutes or so. Then, I lost connection to localhost and problems began. I could not relaunch, but much worse: I cannot access the PokeRogue Website anymore. It opens on the violet starting screen that shows before the black box even appears, but nothing happens after that. 
Also, I get logged out of my Google Account every time I close Chrome and Reopen it. 
I tried different things, un- or reinstalled every single one of the programs I mentioned, nothing. 

I appreciate any help you can offer, and if there is no fix for this, thank you for nuking my pc!

**Comment by l-33ter** [comment]
First of all, you do not install anything! If you [play from here](https://pokerogue.net/) you don't have to install anything!

Anyway: Can you, at least tell us some information? What System do you have? Where do you install **npm**? Windows | WSL | Linux | Apple? - If you install it, and something crashed, what does the terminal printing out? Like in my ![picture](https://github.com/pagefaultgames/pokerogue/assets/77815858/8e644d00-fb1b-4e1b-a7b5-d8fd834a15cc). If something go wrong, then the **WILL** be an error message!

Does the [pokerogue.net](https://pokerogue.net/) page display an error, EVEN when you are in !['Incognito-Mode'](https://github.com/pagefaultgames/pokerogue/assets/77815858/00de3199-106f-46d1-b727-16cad8fc7579) ???

So we can only help you if you tell us more information what you've done!
