### ISSUE TITLE
[Feature] Change/Remove breeders in certain biomes

### ISSUE THREAD

**Issue by walt253** [pagefaultgames/pokerogue#2495]
**Is your feature request related to a problem? Please describe.**
Breeders appearing on certain biomes make no sense. I noticed the breeders seem to be able to spawn in any biome.
Here is a list of biomes where I think this makes no sense.

_Nonsense at all_
Sea&Seabed: They have their clothes on.
Space: How did they get there? Maybe give them a spacesuit.

_Probably shouldn't be here_
Abyss/Desert/Factory/Laboratory/Power Plant/Slum/Wasteland: Doesn't seem a good place to breed mons.
Cave/Fairy Cave/Ice Cave/Volcano: Why would they show up in caves? Also in Volcano it's maybe too hot for breeding.
Dojo: Maybe have a Dojo breeder instead.
Graveyard: Not sure breeding with graves around is a good idea.

**Describe the Feature**
Either remove them from biomes where they don't make sense, OR change their sprite for those biomes.

**Comment by Tempo-anon** [comment]
Right now breeders are supposed to show up in plains, grass, tall grass, metropolis, beach, lake, meadow, and fairy cave. HOWEVER, in the `randomTrainerType` function of `arena.ts` the game will automatically default to a breeder if the specified biome does not have any trainers for that tier.

**Comment by Tempo-anon** [comment]
The real reason is because no biome has a 0% of trainer spawns
![](https://cdn.discordapp.com/attachments/1176874654015684739/1255345802889658409/image.png?ex=667ccb62&is=667b79e2&hm=89a40574b61a0bbce568854d0b0a8b8842be9ad0aefca0b37e1742b3c961e9db&)

**Comment by Tempo-anon** [comment]
Correction: there are a few biomes that use the 0 value like lab and end so this is just a gameplay/balance/design question

**Comment by Tempo-anon** [comment]
Seems this is less likely now that someone has added breeders in space into the splash messages
