### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by agergo100** [pagefaultgames/pokerogue#25]
There are too many things that I don't know and it also helps others to understand those features.

**Comment by molker** [comment]
What kinds of things would you want to be added to the FAQ?

**Comment by molker** [comment]
a lot of those are more fitting to just go in the [wiki ](https://wiki.pokerogue.net/doku.php?id=start)
the FAQ in the README is more for questions about contributing
if you're in the discord as well, item rarity and a few mechanics are explained in pinned posts in "pokerogue-chat"
we are working on adding to the discord FAQ as well, will take these into consideration there
