### ISSUE TITLE
[Feature] I wish there was a function to find the password

### ISSUE THREAD

**Issue by sugyoum** [pagefaultgames/pokerogue#2522]
It would be nice to be able to find the password. Since you use the password once and play the game for a long time, it is easy to forget the password and you may not be able to play the game as a result. Therefore, I wish there was a function to either just remove the password or find the password.

**Comment by CodeTappert** [comment]
See https://discord.com/channels/1125469663833370665/1230522227020271696 in the offical discord

**Comment by sugyoum** [comment]
I don't have access to Discord.

**Comment by CodeTappert** [comment]
> I don't have access to Discord.

https://forms.gle/bjkXg3Bd7UCsvox58
