### ISSUE TITLE
[BUG] Arena Trap dialog prompt doesn't disappear

### ISSUE THREAD

**Issue by EmberCM** [pagefaultgames/pokerogue#2524]
**Describe the bug**
After getting the "Arena Trap prevents switching" dialog, the prompt arrow stays when switching dialogs

**To Reproduce**
1. Have an opponent with Arena Trap
2. Attempt to Run without a special run ability
3. Click Fight after the dialog appears

**Expected behavior**
The dialog arrow disappears

**Screenshots / Videos**
![run](https://i.ember.zone/u9QF7GsC7UmI9AVK.png)
![fight](https://i.ember.zone/a3YhBzC4U4CBhsc4.png)
![back](https://i.ember.zone/2ZWKx0gGnwWJn1EJ.png)

**Device**
Firefox Browser on PC

**Additional context**
Dialog is created here: https://github.com/pagefaultgames/pokerogue/blob/main/src/data/ability.ts#L3841
Arena Trap trigger message: https://github.com/pagefaultgames/pokerogue/blob/main/src/data/ability.ts#L3289

**Comment by innerthunder** [comment]
fixed by https://github.com/pagefaultgames/pokerogue/pull/3271
