### ISSUE TITLE
Trainer is persistant if a trainer fight start after a pokemen die at the end of a fight from poison

### ISSUE THREAD

**Issue by Salixe1214** [pagefaultgames/pokerogue#253]
This is a bit specific and doesn't affect the playability, but when a pokemon die from poison at the end of a fight and is revive with an item, if the next fight is a trainer fight, you need to summon a new pokemon that will live on top of the trainer. The trainer will now live on the field for all the fight.

![image](https://github.com/pagefaultgames/pokerogue/assets/49760514/b909735d-3daa-49f1-9eea-eaaf72f5942e)
![image](https://github.com/pagefaultgames/pokerogue/assets/49760514/35da293b-e6da-4286-b023-b5c922a3f390)

**Comment by knispeja** [comment]
Technically this does affect playability, it forces you to switch away from the Pokemon you revived for no reason. More detail in my comment here: https://github.com/pagefaultgames/pokerogue/issues/894#issuecomment-2124188396

This pretty much is a duplicate of these:
- https://github.com/pagefaultgames/pokerogue/issues/222
- https://github.com/pagefaultgames/pokerogue/issues/894

**Comment by flx-sta** [comment]
Duplicate of #253
