### ISSUE TITLE
[BUG] Disguise doesn't work?

### ISSUE THREAD

**Issue by C-ater** [pagefaultgames/pokerogue#2558]
**Describe the bug**
Disguise does not protect from damage?

**To Reproduce**

1. Hit Mimikyu 
2. Mimikyu dies 
3. Disguise activates afterwards...?

**Expected behavior**
Disguise makes you take portion of damage (that I forgot) and protects Mimikyu from further damage

**Screenshots / Videos**

https://github.com/pagefaultgames/pokerogue/assets/173323483/e2aeb508-75cd-4bf3-8cc2-42abcc4e8064

**Device**
Phone (Samsung S22)

**Additional context**
I've had this happen multiple times where I'll OHKO a Mimikyu through Disguise, and this same sequence of events occurs. 

Everytime this has happened, Mimikyu was OHKO'd by the move it was supposed to block

I've only ever had this happen to the AI

**Comment by torranx** [comment]
This should be fixed by now, please close upon confirmation.

**Comment by C-ater** [comment]
Mimikyu now is a pain  on Ivy's team and not a free kill 💀
