### ISSUE TITLE
[BUG] Rhyperior "Solid Rock" don't work with passive "Filter" up

### ISSUE THREAD

**Issue by LordReferto** [pagefaultgames/pokerogue#2567]
When Rhyperior get Solid Rock with the passive Filter unlocked with candies, solid rock won't stack correctly. For example, ground moves should deal [2x * (0.75 (solid rock) * 0.75(Filter)) = 1.12x] damage, but instead the move still deal at least 1.5x damage as only filter act. Also the left tooltip will show that Filter reduced the damage from supereffective move, but Solid Rock never occour. 
Not even sure if Filter actually work correctly since the damage is really high anyway

**To Reproduce**
Get a Rhyhorn with Filter passive
Evolve it to Rhyperior
Get almost oneshotted by ground moves

**Expected behavior**
Not getting destroyed by supereffective moves with both passives up

**Screenshots / Videos**
![filter](https://github.com/pagefaultgames/pokerogue/assets/173718124/bcc39a8a-c77d-4440-8e84-95c870ef5301)
![solid rock](https://github.com/pagefaultgames/pokerogue/assets/173718124/20fe6cfb-4a7b-4964-a43a-2758ac584e96)
![before an earthquake](https://github.com/pagefaultgames/pokerogue/assets/173718124/e47a57e7-3dd8-4807-9a0f-bdf3dc14a562)
![after earthquake](https://github.com/pagefaultgames/pokerogue/assets/173718124/dee273e9-ec32-49ac-9e90-b78689bc6a35)
![defensive stats (1 level later)](https://github.com/pagefaultgames/pokerogue/assets/173718124/b1c6cf9b-62ec-48b8-88da-c47d3c0d28c2)

**Device**
Pc

**Comment by Tempo-anon** [comment]
Will be fixed in https://github.com/pagefaultgames/pokerogue/pull/2592
