### ISSUE TITLE
[BUG]: Hard/Softlock when round starts or opening certain eggs

### ISSUE THREAD

**Issue by Luxadevi** [pagefaultgames/pokerogue#2569]
**Describe the bug**
I have a bug where the game freezes completely but is still running  
So i still can hover over the items, i can still hear music but nothing happens.
The console says : "Uncaught (in promise) TypeError: Decoding failed."

**To Reproduce**
I have added my save, it has the behavior with the first 3 saves when starting the battle.

**Screenshots / Videos**
![Screenshot_20240624_203719](https://github.com/pagefaultgames/pokerogue/assets/116653852/2ee86ed0-d853-41be-9f1a-8ba1129db785)

**Device**
Linux arch based distro, firefox latest.

**Additional context**
Previously i had this with a egg opening animation and it was hard stuck since you cannot cancel eggs.
  
Link to save:
https://we.tl/t-Q9TZsucjYO

**Comment by Luxadevi** [comment]
https://discord.com/channels/1125469663833370665/1125662770629709935/1254898270749200557

I also have a password change lined up so i only could test with Firefox for now, 
It looks like i am not the only one with issues regarding eggs locking the game and the game flat out freezing.
If i can provide you with anything else let me know.

**Comment by flx-sta** [comment]
Here is a direct link to download for anyone without a discord account:
https://cdn.discordapp.com/attachments/1125662770629709935/1254898270363455624/data_luxamon2.prsv?ex=667b2a96&is=6679d916&hm=6d0375a06fc799286e2c4911cfac9739f933b23108ff81be729c29c0d9870c8d&

**Comment by CynicalBull** [comment]
I'm having the same issue, and also have an active password change request (account merge?) open.

![image](https://github.com/pagefaultgames/pokerogue/assets/173769417/b05bc2bd-a747-440b-b719-a35c3dcf33d5)

https://cdn.discordapp.com/attachments/1048089077607563265/1255056102068846623/sessionData1_TheCynicalBull.prsv?ex=667bbd94&is=667a6c14&hm=6d02cc3cf6347bce43f22f2c0c017114bd512ed0b7a84ff22d546dc090e27534&

**Comment by Luxadevi** [comment]
Would it otherwise be possible to move these password changes up so we can do some testing with different browsers/devices?

**Comment by CynicalBull** [comment]
I logged into my account on Chrome and bypassed the frozen egg. So, this may be a browser issue.

**Comment by Luxadevi** [comment]
Yeah i was almost that it's firefox exclusive, but then again i bypassed the egg on fox as well after a while, but still having issues with battles in general and cannot continue 75% of my saves...

**Comment by Luxadevi** [comment]
I have updated Firefox and it hasn't happened in 5 hours, only once it got softlocked but could resume by skipping the battle itself.
I was reading the changelog of firefox, 
Is this related/bugfix for this issue, im not specialized in js, so let me know!
Keep the issue open for at least a day more so i know for sure it is not recurring.

 
[Firefox-bugfix](https://bugzilla.mozilla.org/show_bug.cgi?id=1891816)

**Comment by flx-sta** [comment]
> I have updated Firefox and it hasn't happened in 5 hours, only once it got softlocked but could resume by skipping the battle itself. I was reading the changelog of firefox, Is this related/bugfix for this issue, im not specialized in js, so let me know! Keep the issue open for at least a day more so i know for sure it is not recurring.
> 
> [Firefox-bugfix](https://bugzilla.mozilla.org/show_bug.cgi?id=1891816)

honestly hard to tell and not worth the time and effort of investigation. 
Time will tell I guess

**Comment by Tempo-anon** [comment]
Closing this issue as it's been 3 weeks
