### ISSUE TITLE
[BUG] leader lino in badlands-180 infinite battle

### ISSUE THREAD

**Issue by zabixmo** [pagefaultgames/pokerogue#2575]
**Describe the bug**
When you are fighting with the leader Lino, there is a Pokemon that does not finish going out into the field and gets stuck. You have to wait for the sandstorm to eliminate you.

![image](https://github.com/pagefaultgames/pokerogue/assets/75588606/6f23eba2-29a2-4aca-9f59-0994be9dbcd3)

**Comment by Tempo-anon** [comment]
Should be fixed now
