### ISSUE TITLE
Pokerogue Type advantage fighting to steel

### ISSUE THREAD

**Issue by RedMisfit** [pagefaultgames/pokerogue#2577]
Was using Pikachu against magneszone and used flying press, a fighting move. Magnezone being electric/steel it should have been super effective, instead it was "not very effective". Very puzzled, my pikachu has ability is just static and no type changing items or moves had been used, I assume it must be a bug

**Comment by Tempo-anon** [comment]
Flying Press is fighting + flying type. The fighting is 2x against Magnezone but flying is 1/4x. When those get multiplied together it's 1/2 or not very effective
