### ISSUE TITLE
[BUG] NO CANDIES FROM HATCHING EGGS

### ISSUE THREAD

**Issue by gabemt88** [pagefaultgames/pokerogue#2588]
**Describe the bug**
I am not getting candies from hatching some eggs. i mainly noticed it on shines but even with non shinies i'm having this issue multiple times
It shows the candies gained as they are hatching but when i got to the starter selection menu, the new candies are not there .

--on PC website--

is there a way to get the candies? i've lost out on a lot, including red and blue shinies which were supposted to give 40 and 20 candies each!! but i got none for hatching them

**Comment by flx-sta** [comment]
This is a known issue. Unfortunately there is nothing we can do to restore lost candies.
