### ISSUE TITLE
[BUG] Game Crash when using Primal Groudon on Firefox.

### ISSUE THREAD

**Issue by MehGroot** [pagefaultgames/pokerogue#2591]
**Describe the bug**
Whenever I send out my level 2 Shiny Primal Groudon the game freezes as soon as "The Sunlight Got Hot" Appears. There doesn't seem to be a way to continue after this. The game just locks up. I'm not sure if the bug is specifically tied to this shiny, but definitely only occurs when Primal Groudon is used. The issue does not occur when using Chrome.

**Reproduce the Bug**

1. Using Firefox open Pokerogue. 
2. In Battle Send out Primal Groudon.
3. The ability activates.
4. Game Freezes.

**Expected behavior**
Would expect that the ability would trigger and the game would continue.

**Device**
Playing on a PC, using the latest version of firefox.

**Additional context**
Attempted a hard reload to see if it clears the issue, but no luck there. Issue does only seem to be present when specifically Primal Groudon's ability triggers. Other sunlight effects don't cause the issue, weather effects in general are otherwise fine.

**Comment by flx-sta** [comment]
Can you provide a screenshot/print/copy of the console output?
Also a video would be helpful.
An export of the session-data too (must be uploaded to Discord as Github doesn't accept the files)

**Comment by Tempo-anon** [comment]
Closing as this is not reproducible. Please open an issue again if this persists with some additional info to help debug
