### ISSUE TITLE
[BUG][modifier-select-ui-handler] Position of cursor is hard-coded so it's hard to localize

### ISSUE THREAD

**Issue by EnochG1** [pagefaultgames/pokerogue#2620]
**Describe the bug**
Translation team are trying to localize modifier-select-ui-handler texts.
https://github.com/pagefaultgames/pokerogue/pull/2527

But there's issue because some of positions(x,y) are hard-coded.
So if it's not English, cursor and label texts look weird.
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/2a3ab473-1f1f-4642-b8f4-c2313ebfa1c3)
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/8549cacb-59e3-4831-82c1-fa4ddba71df5)

It seems to calculate coordinates of cursor, not as concrete value.
I would like to ask for the help of an expert on the screen rather than make issue by adjusting the cursor position myself.

**To Reproduce**
1. Change label of 'transfer', 'check team' in modifier-select-ui-handler.ts
2. Run game in test mode and check position of cursor.

**Expected behavior**
If it's not English or not same as original label, cursor and label texts look weird.

**Screenshots / Videos**
![image](https://github.com/pagefaultgames/pokerogue/assets/19601207/42054398-4fed-4d67-bfdc-53e05b7d93bb)

**Device**
Chrome. (But it doesn't matter)

**Additional context**
CC : @Adri1

**Comment by Adri1** [comment]
Problem solved directly in PR #2527
