### ISSUE TITLE
[BUG] Multi Hit Lens No Longer Triggers On Earthquake 

### ISSUE THREAD

**Issue by DaltJM** [pagefaultgames/pokerogue#2632]
**Describe the bug**

Earthquake no longer hits multiple times. But other moves on the same pokemon do. 
**To Reproduce**

1. Have multi hit lens and earthquake 
2. Use earthquake 
3. Note that it doesn't hit more than once 
4. Use another move to confirm the other move hits more than once

**Expected behavior**

That earthquake hits more than once like it did a few days ago. 
**Screenshots / Videos**

**Device**

**Additional context**

**Comment by DaltJM** [comment]
This may or may not be a local device issue. Earthquake is now working as intended. If the issue can't be replicated, assume it was just me.

**Comment by flx-sta** [comment]
@DaltJM im gonna close this then. In case its back feel free to re-open it or open a new issue
