### ISSUE TITLE
[BUG] Imposters breaks the game

### ISSUE THREAD

**Issue by kleenxfeu** [pagefaultgames/pokerogue#2635]
**Describe the bug**
Upon switching a guzzlord spliced with an imposter ditto, the game locks up. It doesn't freeze per say because the sprites are still moving up and down, but I can't do anything.
However, if the switch happens when the promp pops up at the start of a battle, it doesn't freeze. In this case, opening up the summary screen of the transformed species (in this case guzz/ditto transformed into claydol), I have a black screen, the game freezes.

I don't remember it being an issue with a simple ditto.

**Comment by Snailman11** [comment]
Grand Transform Aggregated Issues (Fusion Transform Softlock, Delayed Visual, Form Not Saved)
https://discord.com/channels/1125469663833370665/1267976989957029900/1267976989957029900


This one is the same  @as Issue 2481(Spliced Transform) https://github.com/pagefaultgames/pokerogue/issues/2481
