### ISSUE TITLE
Rivalry appears to incorrectly trigger in multi battles

### ISSUE THREAD

**Issue by umbra3275** [pagefaultgames/pokerogue#264]
![2024-04-23_19:05:07_rivalry-triggering-wrongly](https://github.com/pagefaultgames/pokerogue/assets/128765872/4f231e28-8465-471b-8e85-a4791d0a42c0)
This was a repeated phenomenon in this battle, and unfortunately it's a rare enough interaction that I can't do much testing of it.

**Comment by lucfd** [comment]
The ability message pops up whenever the ability activates, which includes the damage reduction of attacking a Pokemon of the opposite gender. Ability appears to be working fine but this should probably be changed

**Comment by umbra3275** [comment]
oh! my bad I should have read further on the wiki, I hadn't known about the damage reduction
