### ISSUE TITLE
[BUG] Inconsistencies with multi lens

### ISSUE THREAD

**Issue by kleenxfeu** [pagefaultgames/pokerogue#2641]
**Describe the bug**
A gholdengo with contrary, equipped with 2 multi lens will have its att special raised only once, while it works as it should with only 1 multi lens (meaning att spe raised twice).
It does seem to work from times to times, but it mostly doesn't. I haven't found a pattern yet.

**Comment by ben-lear** [comment]
There's also a single vs double battle issue which may or may not be related to what's being reported here

Single battle works fine (even with multi-lens):
https://github.com/pagefaultgames/pokerogue/assets/110984302/be40f919-5b74-41e8-93be-1df02aaac066

double battle sharply raises stats (even with multi-lens):
https://github.com/pagefaultgames/pokerogue/assets/110984302/575248ba-dccd-4fd1-a3e4-ecd120be5414

**Comment by ben-lear** [comment]
Here's a session which may be useful for testing and debugging these issues:
[gholdengo multi lens session.zip](https://github.com/user-attachments/files/16018851/gholdengo.multi.lens.session.zip)

**Comment by Tempo-anon** [comment]
Fixed with #2664
