### ISSUE TITLE
[BUG] weather get covered but shouldnt be

### ISSUE THREAD

**Issue by zsw12abc** [pagefaultgames/pokerogue#2651]
**Describe the bug**

![image](https://github.com/pagefaultgames/pokerogue/assets/11704698/bd80e41b-e3ca-4ff7-adcb-b8bd23015961)

the Desolate Land is covered by Orichalcum Pulse. but shouldnt.

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Device**

**Additional context**

**Comment by flx-sta** [comment]
Please make sure to fill out the description properly. Otherwise there is no way for us to help

**Comment by flx-sta** [comment]
no response within a month
