### ISSUE TITLE
[BUG] Accuracy lowered with wide lens?

### ISSUE THREAD

**Issue by KingOfRogues** [pagefaultgames/pokerogue#2655]
I added a widelens to a gengar, and my 100% accurate moves immediately started missing.

steps to reproduce:
Add widelens to your team
Use 100% accurate moves

expected behavior should be wide lens increasing not decreasing accuracy

Playing on pc via chrome

Weirdly the wide lens lowers accuracy of other pokemon its not on as well, I missed a 100% accurate move in a double battle on a non-wide lens pokemon with my wide lens pokemon also in play.

**Comment by Terrorforge** [comment]
You sure you weren't in a biome with fog, such as the graveyard or (iirc) swamp? I don't think wide lens compensates for that.

**Comment by KingOfRogues** [comment]
> You sure you weren't in a biome with fog, such as the graveyard or (iirc) swamp? I don't think wide lens compensates for that.

No, I am not 100% sure, maybe that was the issue my bad. Just weird timing I guess.
