### ISSUE TITLE
[BUG] Sheer Cold not K.O.ing

### ISSUE THREAD

**Issue by Astraea21** [pagefaultgames/pokerogue#2665]
When using sheer cold against a non-boss pokemon of lower level in endless with 0 endure tokens, the move is leaving pokemon at 1 HP.  This happened multiple times with the pokemon previous to the seaking being a persian. Screenshots of the most recent attached.
![image](https://github.com/pagefaultgames/pokerogue/assets/86131365/1021082b-bedc-4dee-b146-fe93d9413fd9)
![image2](https://github.com/pagefaultgames/pokerogue/assets/86131365/2cd34b9a-c7cf-4bf3-a79b-6fa21185119f)

**Comment by flx-sta** [comment]
@Astraea21 I can't reproduce it on my local instance.
Are you able to share your session where this bug occurs?

**Comment by Astraea21** [comment]
Sure thing, I've gotten rid of sheer cold on the kyurem at this point though if that matters
[sessionData_astraea21.zip](https://github.com/user-attachments/files/16022105/sessionData_astraea21.zip)

**Comment by flx-sta** [comment]
@Astraea21 yeah... it kinda does. Best case would be to be at the same exact point you showed the screenshot from. But I guess we can try to restore it anyway.

Unfortunately I need you to upload the actual sessionData file (unzipped!) to the [Discord](https://discord.gg/54v3N9xs) because I won't be downloading ZIP files as they may contain malicious code.
You can then link the discord message here

**Comment by Astraea21** [comment]
that is perfectly fair and reasonable lol.  what channel should I put it in?  want me to put sheer cold back on it and see if it still does it? or no because it could mess with stuff more?

**Comment by flx-sta** [comment]
> that is perfectly fair and reasonable lol. what channel should I put it in? want me to put sheer cold back on it and see if it still does it? or no because it could mess with stuff more?

I think you can just create a new thread inside [Bug-Reports](https://discord.com/channels/1125469663833370665/1126338176659763210) where you throw some info and the file in

**Comment by Astraea21** [comment]
Sorry for late response, but post made!

**Comment by flx-sta** [comment]
https://discord.com/channels/1125469663833370665/1256614651236585616/1256614651236585616

**Comment by Astraea21** [comment]
Saw the response, TYVM for the help!
