### ISSUE TITLE
[BUG] Boss-bar sections inconsistent in endless mode DOUBLE-BATTLE

### ISSUE THREAD

**Issue by flx-sta** [pagefaultgames/pokerogue#2668]
**Describe the bug**

After fixing the reload bug for boss-sections it seems the boss-sections are not inconsistent for endless mode in double-battles

**To Reproduce**

- Session-Data [download (Discord)](https://cdn.discordapp.com/attachments/1239451578151211078/1255990429074329600/sessionData1_Sjofi_4.prsv?ex=667f23bd&is=667dd23d&hm=712de7cdeb7e8aa534d01690f9aefc0805454c6aa018e1d01495f36093e86d79&)

**Expected behavior**

After reloading the sections should stay consistent

**Screenshots / Videos**

<img width=400 src="https://media.discordapp.net/attachments/1176874654015684739/1255983842901364876/image.png?ex=667f1d9b&is=667dcc1b&hm=d9a61d03e6e9d882c8593d1ca2753b2ee6898962a49a91b1d8922084795f1f24&=&format=webp&quality=lossless&width=982&height=1116" />

**Device**

Idk, ask Temp

**Additional context**

CC: @Tempo-anon

**Comment by kleenxfeu** [comment]
Noticed this as well, on a windows PC with edge.
