### ISSUE TITLE
[BUG] Ceaseless Edge does not set up multiple layers of spikes with Multi Lens

### ISSUE THREAD

**Issue by Terrorforge** [pagefaultgames/pokerogue#2671]
**Describe the bug**

Gave my Toxapex with Ceaseless Edge Multi Lens thinking it would be cool to set up two layers of spikes at a time. However, while the attack now goes off twice, only one layer of spikes is set.

**To Reproduce**

1. Give a pokemon Ceaseless Edge and a Multi Lens
2. Use Ceaseless Edge

**Expected behavior**

When a move is executed twice, its secondary effects should also happen twice, as happens with e.g. Power-Up Punch.

**Screenshots / Videos**

![image](https://github.com/pagefaultgames/pokerogue/assets/5107449/c2c43cf3-8bb1-40be-a602-5bd3feb77c34)
![image](https://github.com/pagefaultgames/pokerogue/assets/5107449/3ef85e9d-0241-4cab-abe2-85b57b29b250)
It should not even be possible for my Toxapex to only have one layer of spikes up.

**Device**

Chrome on PC

**Comment by schmidtc1** [comment]
I believe this is due to the parent class having firstHitOnly as true when calling super:
https://github.com/pagefaultgames/pokerogue/blob/67a21b8a9496af739e14ca60954244891fc7fffe/src/data/move.ts#L4203

**Comment by schmidtc1** [comment]
> I believe this is due to the parent class having firstHitOnly as true when calling super:
> 
> https://github.com/pagefaultgames/pokerogue/blob/67a21b8a9496af739e14ca60954244891fc7fffe/src/data/move.ts#L4203

Testing with it as false doesn't seem to affect Reflect/Stealth Rock/other trap moves

**Comment by torranx** [comment]
is this confirmed to be not a UI issue only? i mean the flyout is maybe only showing inaccurate number

**Comment by Terrorforge** [comment]
Not confirmed either way, no. I did only get the "spikes were scattered" message once, after the first hit, but that could also be a UI issuel.

**Comment by schmidtc1** [comment]
Seeing as setting 'firstHitOnly' to false solves the issue, I feel as though it's not a UI issue.
