### ISSUE TITLE
[BUG] U-turn incorrectly applies some effects to the switched in Pokemon

### ISSUE THREAD

**Issue by innerthunder** [pagefaultgames/pokerogue#2680]
**Describe the bug**

When a Pokemon uses U-turn, some strange (and potentially game-breaking) interactions can take place:
- If the user attacks into a target with Rough Skin or Iron Barbs and faints on U-turn's last hit, the "Faint" status effect is applied to the switched in Pokemon instead of the user, causing the switched in Pokemon to also "faint" (see the video below).
- If the user attacks into a target with Flame Body, and the user would get burned on U-turn's last hit, the switched in Pokemon is burned instead of the user.

**To Reproduce**

1. Have a Pokemon with U-turn and 3x Multi-Lens (can be done via overrides)
2. Give the enemy Pokemon Rough Skin and Iron Barbs as its ability and passive (via overrides)
3. Attack into the enemy Pokemon with U-turn

**Expected behavior**

The effects listed above should be applied to U-turn's user, not its switch target.

**Screenshots / Videos**

Here's a video of U-turn's behavior when the user faints while using it:

https://github.com/pagefaultgames/pokerogue/assets/168692175/40fb9862-2c07-4eee-93d7-c4cdae02c594

**Device**

PC (Chrome)

**Additional context**

I already tried to fix this by adding another `MoveEffectTrigger` type for U-turn's attribute, but the same problems as before were observed. I think the problem is related to `FaintPhase` and `ObtainStatusEffectPhase` using battler indexes instead of the Pokemon themselves to apply effects, but I'm not sure what a clean fix to that would look like.

**Comment by EmberCM** [comment]
This is related #83

**Comment by DustinLin** [comment]
This was also mentioned in issue #682, that issue references #165 which may be worth looking at

**Comment by Zieldo** [comment]
Can confirm U-turn causing the switched in Pokémon to be burned when hitting Flame Body

**Comment by DustinLin** [comment]
anyone working on this? else I can take a look into it

**Comment by schmidtc1** [comment]
I don't think anyone has started a PR for it, have at it.

**Comment by innerthunder** [comment]
I looked over this a few days ago, but I didn't get very far. I have a good idea of why these issues are popping up, though, and it's a combination of two things:
- `FaintPhase`, `ObtainStatusEffectPhase`, and all other `PokemonPhases` apply their effects to a Pokemon using their `BattlerIndex` instead of a direct reference to a `Pokemon` object. This means that if a Pokemon applies an effect to a target, the effect is applied to whoever's in the target's position when the effect's respective phase starts.
- Moves that use the `ForceSwitchOutAttr` (e.g. U-turn, Dragon Tail) unshift a `SwitchSummonPhase` after all the other effect phases from that attack have already been added.

So in the video I posted earlier, the phases for when U-turn is being resolved end up in this order:
- `SwitchSummonPhase` (U-turn forces the user to switch)
- `DamagePhase` x2 (The opponent's health is updated after the last hit of U-turn, and the user's health is updated after proccing the opponent's Rough Skin/Iron Barbs)
- `FaintPhase` (The user is meant to faint, but instead the switched-in Pokemon, who's now in the user's field position, takes the effect)

I think there are two methods to fixing this, but each method introduces its own complications:
- You could make `PokemonPhases` reference their target Pokemon by object reference instead of `BattlerIndex`, but this would require a pretty hefty rewrite of the affected phases, and it would introduce cases where you'd end up with a Pokemon fainting while in your party.
- You could insert the `SwitchSummonPhase` in a place where it doesn't interfere with `FaintPhases`, `ObtainStatusEffectPhases`, etc., but then you still have to deal with how the UI is presented, since that's handled outside of that phase.

**Comment by DustinLin** [comment]
Just testing to see that this affects the enemy 'mon as well

https://github.com/pagefaultgames/pokerogue/assets/39450497/978ac269-dab4-43b7-b4af-ae962cbeadef

To add onto the above comment, what is happening is the`ForceSwitchOutAttr` tag is calling the `switchOut()` function in `pokemon.ts` (which prompts the user/CPU to select a different pokemon, and adds the necessary `SwitchSummonPhase`). After that, U-Turn (and it's associated `DamagePhase` is considered over), and the RoughSkin's ability `DamagePhase` activates (and the rest is as innerthunder describes). 


The second solution method that innerthunder talks about involves trying to switch out *after* the `DamagePhase`(s) of the opponent's abilities. This would solve the bug because allowing the subsequent `DamagePhase`(s) to go first would lead to a proper checking of the pokemon's HP and adding a `FaintPhase` when needed. The problem is that currently the damage phase of UTurn can't be decoupled from `switchOut()`, since the latter is not a separate phase and just a function call.

**Comment by DustinLin** [comment]
As expected this is present for other abilities as well:


https://github.com/pagefaultgames/pokerogue/assets/39450497/b83e7a37-3af0-400a-a16a-e1998005a5db

**Comment by Snailman11** [comment]
Link to discord's ()
https://discord.com/channels/1125469663833370665/1246190022168805527

**Comment by innerthunder** [comment]
@DustinLin is this issue fixed in beta now?

**Comment by DustinLin** [comment]
The first 2 are fixed, the last is still broken:

https://github.com/user-attachments/assets/45174dc8-fc15-450d-9184-9582742d0b84

https://github.com/user-attachments/assets/09977f2f-0958-4699-8673-28b12b86235f

**Comment by DustinLin** [comment]
For the last case I'm pretty sure I know the cause: it has to do with the ability leaf animation and rendering on pokemon "in battle". From the force switch, the UTURN messes it the sprite visibility. I fixed something similar in #3346 for wild battles. Pretty sure I can extend it to trainer battles in the last case

**Comment by DustinLin** [comment]
wild battles it works from #3346 fix

https://github.com/user-attachments/assets/dd7ea38e-a0aa-4d92-b9f2-5c7d5f32e89a

**Comment by innerthunder** [comment]
closing now, should be fixed by https://github.com/pagefaultgames/pokerogue/pull/2980 and https://github.com/pagefaultgames/pokerogue/pull/3346
