### ISSUE TITLE
[BUG] Some POST_APPLY moves are applying effects through protect

### ISSUE THREAD

**Issue by schmidtc1** [pagefaultgames/pokerogue#2689]
**Describe the bug**

Some moves that have the MoveEffectTrigger.POST_APPLY tag are applying their effects despite not hitting through protect. Changing to MoveEffectTrigger.HIT fixes the issue, but I am not sure if this causes other bugs.

**To Reproduce**

1. Give opponent protect move(s)
2. Use a post apply move with additional effects (ceaseless edge, jaw lock, etc.)
3. See effect applied after damage is blocked.

**Expected behavior**
The effect should not be going through after being blocked.

**Screenshots / Videos**

https://github.com/pagefaultgames/pokerogue/assets/62030095/54749570-b615-4ff4-93aa-0855945ae2f6

**Device**
Chrome

**Additional context**

See code below for where the attributes are being applied (L2947-L2948)
https://github.com/pagefaultgames/pokerogue/blob/15671a6922dadbfe905502fa6df0e6fc8f6b29a1/src/phases.ts#L2947-L2950

**Comment by innerthunder** [comment]
These interactions should be fixed with https://github.com/pagefaultgames/pokerogue/pull/2731
