### ISSUE TITLE
[BUG] Color Change & Trace Game Crash

### ISSUE THREAD

**Issue by SDergus** [pagefaultgames/pokerogue#2707]
**Describe the bug**
Game stops working due to too much recursion when Kirlia, with trace ability copying a Kecleon's color change, is hit with Ancient Power (unsure about other pokemon and move combinations)

**To Reproduce**
(Assuming it's not due to this exact combination)
1. Have pokemon with Trace ability copy foes Color Change ability
2. Get hit by a move
3. Crash

**Expected behavior**
Pokemon type changes to type of move being hit by

**Screenshots / Videos**
[YouTube link to demonstration](https://youtu.be/uoAMLRcDt4M)

**Device**
PC, in Firefox browser

**Comment by Snailman11** [comment]
Softlocks whenever both Kecleon and Ralts both use moves with secondary effects

Uploading PokéRogue 2024-08-26 00-48-24.mp4…

**Comment by Snailman11** [comment]
Link to the Discord Post (Freeze with a RangeError message)
https://discord.com/channels/1125469663833370665/1290742591330979921

**Occurs When two Pokemon with the Sheer force exclusion attribute hit the other one. **
https://discord.com/channels/1125469663833370665/1261695553625133086
