### ISSUE TITLE
[BUG] BGM audio is not consistent in volume anymore

### ISSUE THREAD

**Issue by OreoCupcakes** [pagefaultgames/pokerogue#2717]
**Describe the bug**
Commit  #2691 messed up the volume of tracks in the game. Some tracks are way too loud now, others are quiet.

**To Reproduce**
1. Play the game and just notice the swinging audio levels of some biomes, sound effects, etc.

Some examples include:
- The evil team theme being too quiet.
- When evolving the Pokemon cries are extremely loud vs the evolution congratulations theme.
- Entering a trainer battle, the trainer music is pretty quiet. Once you win the battle, the start of the victory theme is extremely loud.

**Expected behavior**
Audio before the commit sounded consistent in volume, but now it's all over the place no matter what levels your BGM and SE audio sliders are at.

**Screenshots / Videos**

**Device**
Windows 10 22H2, Firefox.

**Comment by flx-sta** [comment]
@Fontbane
