### ISSUE TITLE
U-turn causes game freeze repeatedly (cannot read properties of undefined (reading scene)

### ISSUE THREAD

**Issue by Pirant0409** [pagefaultgames/pokerogue#273]
![pr](https://github.com/pagefaultgames/pokerogue/assets/33604772/7c602aa3-5923-4601-acd1-e6eb2bc98b2e)
Browser : Brave (chromium)

Situation : 
- Battle start
- Meowscarada uses U-turn against Skuntank
- Switching from Meowscarada to any other pokemon
- Skuntank uses explosion
- Either my pokemon dies or not, game freeze + scene is undefined in console

Tried +10 times, happenned everytime.
Tried with default configuration (normal speed, english language, ...) : it happenned aswell

**Comment by lucfd** [comment]
Could you please export your session data and upload it here?
