### ISSUE TITLE
[BUG] Arena traps (spikes, stealth rock, etc.) do not proc on transition to a double battle

### ISSUE THREAD

**Issue by schmidtc1** [pagefaultgames/pokerogue#2740]
**Describe the bug**

When transitioning between waves, if you transition into a double battle with arena traps already set up, no arena trap damage/effect occurs. 

**To Reproduce**

1. Set up arena traps (spikes, stealth rock)
2. Pick up 3 lures to guarantee a double battle
3. Defeat the opposing pokemon to transition to a new wave with a double battle (MAKE SURE THIS IS NOT A TRAINER BATTLE)
4. Observe the lack of arena trap activation

**Expected behavior**

Arena traps should either not proc on transition at all (they currently proc on single battle transitions, see video below), or they should proc on double battle transitions as well.

**Screenshots / Videos**

https://github.com/pagefaultgames/pokerogue/assets/62030095/6d5f3fd8-b8eb-4476-bdfa-fb873bad31ed

**Device**

Chrome, PC

**Additional context**
This likely relates to #2735

**Comment by Snailman11** [comment]
https://github.com/pagefaultgames/pokerogue/issues/5006

Placed under [Bug] Enemy Pokemon do not take Damage from Hazards, or Activate their PostSummon Abilities in Double Battles while Having One Eligible Pokemon
as this is likely a broader issue with how single Pokémon function.
