### ISSUE TITLE
[BUG] Shiny display on team select screen

### ISSUE THREAD

**Issue by HiddenAbilitree** [pagefaultgames/pokerogue#2744]
**Describe the bug**
On mount, sprites of shinies in the team selection screen are their normal counterparts and will change to the shiny sprite after hovering over it, and will retain the shiny version after unhovering.

**To Reproduce**
Open a new PokeRogue instance or refresh an existing one.
Select New Game.
Select any game mode.
Shiny Pokemon will show the default sprite in the team selector.
Hover over the Pokemon.
The sprite switches to the shiny version.
When moving off of the shiny Pokemon, the shiny sprite stays.

**Expected behavior**
It should show the shiny sprite instead of the default version by default.

**Screenshots / Videos**
Before hovering.
<img width="79" alt="Screenshot 2024-07-01 at 3 47 58 PM" src="https://github.com/pagefaultgames/pokerogue/assets/59267569/89509730-c96f-4d93-9c84-3861dd00a41e">

After the first and any subsequent hovers.
<img width="76" alt="Screenshot 2024-07-01 at 3 48 12 PM" src="https://github.com/pagefaultgames/pokerogue/assets/59267569/3a93eef8-bc27-4e5a-a6d5-8f83e25318b7">

After moving off of the Pokemon.
<img width="140" alt="Screenshot 2024-07-01 at 3 48 18 PM" src="https://github.com/pagefaultgames/pokerogue/assets/59267569/706c104e-acb7-45b0-bd3e-f53d53d81655">

**Device**
MacBook Pro Sonoma 14.5

**Additional context**
Occurs on Firefox 127.0.2 and Chrome 126.0.6478.127

**Comment by Snailman11** [comment]
Fixed with the UI update
