### ISSUE TITLE
[BUG] Incorrect displayed type effectiveness for Sheer Cold vs. an Ice type

### ISSUE THREAD

**Issue by AndrioCelos** [pagefaultgames/pokerogue#2756]
**Describe the bug**

The type hint for Sheer Cold on an Ice-type target shows `falsex`.

I'm not sure whether this applies to other one-hit KO moves.

**To Reproduce**
1. Have a Pokémon that knows Sheer Cold.
2. Enter a battle against an Ice-type Pokémon.
3. Ensure type hints are on in the display settings.
4. Move the cursor to Sheer Cold in the Fight menu.

**Expected behavior**

It should display 0× (because Ice-type Pokémon are immune to Sheer Cold). Unsure what multiplier should be displayed for non-boss targets that aren't immune to the move, since type effectiveness doesn't apply there either.

**Screenshots / Videos**
![image](https://github.com/pagefaultgames/pokerogue/assets/6897624/ca628bc3-97fd-448c-9b2a-8cbeab1474ad)

**Device**
Firefox v127.0.2 on Windows 11

**Comment by hayuna** [comment]
FYI to someone who will be fixing this issue

class: Pokemon
method: getAttackMoveEffectiveness
function inside method: applyMoveAttrs returns boolean instead of number
