### ISSUE TITLE
[BUG] [Question] Rare candy used on fainted pokemon

### ISSUE THREAD

**Issue by hayuna** [pagefaultgames/pokerogue#2780]
**Describe the bug**
In pokemon games after using rare candy on fainted pokemon, pokemon revive with couple HP
In pokerouge, pokemon is still fainted, is this expected?

**To Reproduce**
Have fainted pokemon
Get rare candy from the store
Use rare candy on fainted pokemon

**Expected behavior**
Revive pokemon after using rare candy on it

**Comment by Madmadness65** [comment]
This is an intentional gameplay decision as noted in #237 . As such, this is not a bug.
