### ISSUE TITLE
[BUG] Metronome calling Beak Blast hardlocks the game

### ISSUE THREAD

**Issue by EJS2K** [pagefaultgames/pokerogue#2790]
**A pokemon using metronome, calling beak blast, hard locks the game (complete freeze, need to reload page).** I tried doing it more than once, seems to happen every time (since the same move keeps getting called).

**To Reproduce**

1. Get a pokemon with metronome (i used munchlax).
2. Use metronome.
3. Get beak blast.
4. Crash.

**Expected behavior**
Move working and doing damage

**Device**
This was done on mobile, not tested on PC. Using google chrome.

**Additional context**
To note the exact battle flow:
Lead with hydreigon against a donphan on endless mode
Swapped to munchlax when given the prompt
Chose metronome
Donphan went first, used scary face
Metronome went off, beak blast got selected.
Beak blast "charging" animation goes off, and then it freezes.

**Comment by schmidtc1** [comment]
The issue is coming from this line of code which is called from ChargeAttr:
