### ISSUE TITLE
[BUG] Encore causes same-move fail in Double Battle on target swap

### ISSUE THREAD

**Issue by Zieldo** [pagefaultgames/pokerogue#2794]
**Describe the bug**
Encore caused move fail in Double Battle, even though it was the same move.

**To Reproduce**
1. Go into a double battle with the opponents being a Patrat and an Indeedee
2. Bring Ghastly and Fletchinder
3. Aura Sphere kill the Patrat with Ghastly
4. Next turn, choose Aura Sphere on the Indeedee. Have it outspeed you and use Encore.
5. Ghastly will fail to use Aura Sphere, even though that's the move you were Encored into. Possibly due to swapping targets?

**Expected behavior**
Ghastly should Aura Sphere the Indeedee after being Encored

**Screenshots / Videos**
https://github.com/pagefaultgames/pokerogue/assets/132167496/e2a04e94-deb8-489d-bc1e-6d2ed566c318

**Device**
PC app by Admiral Billy

**Additional context**
Fully reproducible on game restart

**Comment by Snailman11** [comment]
Attempted to replicate
https://discord.com/channels/1125469663833370665/1231799388263682089/1278136902125486110

-Encore also wears off at the of a mon's move rather than the turn

**Comment by Snailman11** [comment]
Tried to reproduce 
https://discord.com/channels/1125469663833370665/1231799388263682089/1278136902125486110
