### ISSUE TITLE
[BUG] Dark / Flying Dual Type incorrect weaknesses

### ISSUE THREAD

**Issue by lazkmet** [pagefaultgames/pokerogue#2798]
**Describe the bug**
When fighting with Yveltal, a Dark / Flying type, I sometimes get hit by a Bug- or Fighting- type move that is treated as Supereffective, even though it should be neutral damage based on Flying's resistance to that damage type cancelling out Dark's weakness. It seems to be completely random, and sometimes the same move can be supereffective and normal damage when used in succession by the same opponent.

**To Reproduce**
In a Flying-Type only challenge, fight Pokemon who know fighting type or bug type moves (X-Scissor, Superpower) and have Yveltal take damage from these moves. I am not sure if there are other trigger conditions, so it may take multiple attacks to occur.
I was playing Classic mode in a Flying-Only run.

**Expected behavior**
I expect that Yveltal should receive neutral damage from Fighting- and Bug-type moves, because they are Supereffective against Dark types, but Not Very Effective against Flying types

**Screenshots / Videos**
![image](https://github.com/pagefaultgames/pokerogue/assets/82974005/13feddee-5004-49a8-b3d0-be5f50f01a57)

![image](https://github.com/pagefaultgames/pokerogue/assets/82974005/e905eeef-9bc7-4281-b042-c302a0836b9b)

**Device**
I am on PC, playing in a Google Chrome browser window

**Comment by Tempo-anon** [comment]
Did you use roost

**Comment by lazkmet** [comment]
I just looked up how Roost works, and that’s probably it. I did have Roost on Yveltal, and used it quite frequently, so that would explain this behavior. Whoops!

**Comment by lazkmet** [comment]
Closing - Not a bug
