### ISSUE TITLE
[BUG] Tangled Feet does not raise evasiveness (On fusion)

### ISSUE THREAD

**Issue by RosewoodWeevil** [pagefaultgames/pokerogue#2811]
Not tried on Tangled Feet normally but Tangled Feet does not raise Pokemons evasiveness when fused Pokemon becomes confused. Evasiveness might be raised and not show instead but no moves have been missing so far.

**To Reproduce**
1. Take Pokemon with Tangled Feet (Example; Flamigo)
2. Fuse with Pokemon without Tangled Feet in first slot (Example; Jangmo-o)
3. Get Jangmo-omigo with Tangled Feet confused

**Expected behavior**
For a Pokemon with the Ability Tangled Feet to raise evasiveness when it becomes confused

**Screenshots / Videos**
![grafik](https://github.com/pagefaultgames/pokerogue/assets/174818892/c2b28557-df23-4622-aa8a-9ddece16ab3b)

**Device**
Playing on Browser on PC

**Comment by Tempo-anon** [comment]
Tangled Feet provides an in combat evasion doubling effect. It is not a visible stat buff.
```ts
new Ability(Abilities.TANGLED_FEET, 4)
      .conditionalAttr(pokemon => !!pokemon.getTag(BattlerTagType.CONFUSED), BattleStatMultiplierAbAttr, BattleStat.EVA, 2)
      .ignorable(),
  ```

**Comment by RosewoodWeevil** [comment]
ah my bad, i got hit 3 times in a row and it didnt show under evasion so i assumed
