### ISSUE TITLE
[Feature] IV Scanner QoL

### ISSUE THREAD

**Issue by Zieldo** [pagefaultgames/pokerogue#2812]
**Is your feature request related to a problem? Please describe.**
IV Scanner requires a lot of extra presses for the very few times you actually want to use it. Makes it a perma-skip for me, even if I'd want to use it. 
A very minor gripe is also that you have to remember what it shows.

**Describe the Feature**
Make IV scanner a separate option to choose in battle somewhere.

Another option would be to make it so it shows the IV info when you hover over it or over the Pokemon — I personally think this would be the better of the two options.

**Comment by blade1981m** [comment]
I personally really like the optional implementation idea on this. One thing to consider though is that some people may prefer the current implementation. I think one way to potentially address this would be to make it a config option so that people can choose which implementation they prefer.

**Comment by Zieldo** [comment]
> I personally really like the optional implementation idea on this. One thing to consider though is that some people may prefer the current implementation. I think one way to potentially address this would be to make it a config option so that people can choose which implementation they prefer.

Agreed, best of both worlds!

**Comment by HasBert** [comment]
I totally agree with you @Zieldo and I really like the 2. idea of your feature request (hover/tap to show IVs). @blade1981m  In my opinion this feature request should be the default option, and the current one can be set, if really wanted.

I even removed the IV Scanner from my session savefile, because it's so annoying in endless.

**Comment by innerthunder** [comment]
We've added an option with the last update to highlight enemies' stat info (Shift/C) based on IV Scanner readings (https://github.com/pagefaultgames/pokerogue/pull/3285), which hopefully addresses these issues 😄
