### ISSUE TITLE
[BUG] Cannot choose yes or no option after catching Pokémon

### ISSUE THREAD

**Issue by AmeyAvhad** [pagefaultgames/pokerogue#2817]
**Describe the bug**
Whenever I catch a Pokémon on the next screen, I can't choose the yes or no option tried reloading, clear cache, etc. doesn't help. so I can't proceed to next stage unless I kill it. Please help I finally got a wild shiny Pokémon.

**To Reproduce**
1.Catch a Pokémon.
2.On the next screen can't choose the option. 

**Expected behavior**
I was able to choose the yes or no option and proceed.

**Screenshots / Videos**
![image](https://github.com/pagefaultgames/pokerogue/assets/75404011/3d3df4f4-9fba-4aa4-9c0c-f2a3f5b406c7)

**Device**
Device: Laptop 
Browser: Microsoft Edge

**Comment by flx-sta** [comment]
@AmeyAvhad clear your cache. That Issue was just hotfixed
