### ISSUE TITLE
[BUG] Managing 2-Move Starter's Move Crashes the Game

### ISSUE THREAD

**Issue by Endermage77** [pagefaultgames/pokerogue#2844]
**Describe the bug**
When starting a new game, if you try to change the move of a pokemon that only has one move using the Manage Moves menu, it causes the game to freeze, forcing you to reset. This is most noticeable with Smeargle, who only has Sketch if you haven't yet unlocked any of its egg moves.

**To Reproduce**
1. Begin a **New Game**
2. Select a starter with **exactly one move** available (e.g. Smeargle)
3. Select "**Manage Moves**"
4. Attempt to **swap out the starter's move**
5. Crash occurs

**Expected behavior**
I was personally expecting nothing to happen or a message saying something to the tune of "No other moves available." to display.

**Screenshots / Videos**
The game frozen at the moment of the crash:
![image](https://github.com/pagefaultgames/pokerogue/assets/25313980/2a69181d-d081-4146-86fa-b038162750b3)

When the crash occurs, this error gets thrown in the console: 
![image](https://github.com/pagefaultgames/pokerogue/assets/25313980/20e5cfed-7709-4840-acb1-6022aa26d70b)

**Device**
Playing on a Google Chrome browser on Windows 10 PC.

**Additional context**

**Comment by lnuvy** [comment]
@Endermage77 Hi, I found out that it was a bug and opened a PR for it. Thanks for reporting issue!
