### ISSUE TITLE
[BUG] Shiny Zubat's back sprite uses incorrect pallete

### ISSUE THREAD

**Issue by Endermage77** [pagefaultgames/pokerogue#2845]
**Describe the bug**
When you have a shiny Zubat on your side of the field, it uses the deep blue color palette for a shiny Golbat instead of a regular, green-colored shiny Zubat.

**To Reproduce**
1. Begin a **New Game**
2. **Start** with a **shiny Zubat**
3. Observe the **incorrect color**

**Expected behavior**
The shiny Zubat's back sprite should have a green color palette, as observed in its summary screen.

**Screenshots / Videos**
Shiny Zubat in the starter select menu:
![image](https://github.com/pagefaultgames/pokerogue/assets/25313980/cb073680-93cd-4492-8944-779c97d951db)

Shiny Zubat in the pokemon summary menu:
![image](https://github.com/pagefaultgames/pokerogue/assets/25313980/6c62c140-4ac5-4098-9949-b5b4cb022427)

Shiny Zubat's icon sprite in the team:
![image](https://github.com/pagefaultgames/pokerogue/assets/25313980/15c4f519-b6da-4a35-9555-01cc32d5bab0)

Shiny Zubat's battle sprite (note the deep blue color)"
![image](https://github.com/pagefaultgames/pokerogue/assets/25313980/7cbf3050-c3b7-46aa-8164-50ddadbd6c68)

**Device**
Experienced on the Google Chrome Browser, playing on Windows 10.

**Additional context**
I have not yet encountered a front-facing shiny Zubat, so that may or may not be broken as well.

**Comment by flx-sta** [comment]
<img width="865" alt="image" src="https://github.com/user-attachments/assets/64db9ce5-b4d7-44b6-9c48-85a92d5c363d">
has been fixed
