### ISSUE TITLE
[BUG] missing pokemon texture in battle

### ISSUE THREAD

**Issue by Kanbe-Kotori** [pagefaultgames/pokerogue#2846]
![LI@OK 45OII{J2EK$8VOR4K](https://github.com/pagefaultgames/pokerogue/assets/13415090/006801cc-c6e3-4d4c-8347-58934296ff5c)
This happened after the boss fight on level 90, where the opposing pm used destiny bond to kill my pm. After the recover music played, the fight went like this.

**Comment by Kyurl21** [comment]
Also happend to me after the boss fight in stage 70. My pokemon defeated the Boss pokemon but died in that turn because of salt cure.

**Comment by flx-sta** [comment]
duplicate of #61
