### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Judyeevee** [pagefaultgames/pokerogue#2854]
**Describe the bug**
1. Go to 'New Game'
2. See error: There are no points for me to choose a Pokemon. This occurred after I failed my first run on this account.
![螢幕擷取畫面 2024-07-06 201106](https://github.com/pagefaultgames/pokerogue/assets/174878911/1041dfb9-d83b-4af8-9313-d40f2ca99912)

**Screenshots / Videos**
![螢幕擷取畫面 2024-07-06 201106](https://github.com/pagefaultgames/pokerogue/assets/174878911/1041dfb9-d83b-4af8-9313-d40f2ca99912)

**Device**
Playing in google/ using Windows 11

**Additional context**
Plz HELP I can't play the game

**Comment by hayuna** [comment]
0/10 means that you have used 0 point. Limit is 10. If you select any pokemon and click "add to party" then your points will be used. (For example if you choose Eevee - you will see 4/10)

**Comment by DustinLin** [comment]
Should probably be closed/resolved
