### ISSUE TITLE
Issues I noticed since starting to play the game

### ISSUE THREAD

**Issue by Bardockthe1st** [pagefaultgames/pokerogue#29]
![Mega blastoise survives with 0 hp](https://github.com/pagefaultgames/pokerogue/assets/165945943/2ffb1ea5-935b-40a1-af5c-1fcd2521ae34)
I was able to get Mega Blastoise. In a fight it should have died to Beheeyem when psybeam brought me down to zero hp but nothing happened

I have also noticed follow me does not work as intended, despite the move being used I can attack other pokemon

**Comment by Flashfyre** [comment]
This has been reported a lot already in the Discord, just haven't gotten to it. You're not actually at 0 HP either, it's a visual bug with the battle info.

**Comment by Bardockthe1st** [comment]
Ah okay I wanted to join the discord but a message popped up saying the link was invalid/ had potentially expired

**Comment by Madmadness65** [comment]
As far as I'm aware, the issue of visually being at 0 HP has been fixed.
