### ISSUE TITLE
[AUDIO PROBLEM] Victory music loop not mixed well, causes jarring sound on repeat

### ISSUE THREAD

**Issue by mgroth0** [pagefaultgames/pokerogue#2911]
**Describe the bug**

Not quite a "bug", but more of an audio problem caused by the audio itself. The victory music (the song that plays when you win a battle) doesn't loop nicely. After about one minute, it fades to silence... then hits you again with the duh-duh-duh-duh-dah-dah-dah! out of nowhere. It's so jarring and annoying that I need to mute the game when I'm thinking about which move to replace. 

**To Reproduce**

1. Win a battle
2. Listen to the victory music that plays while deciding which item to get
3. Notice when the song repeats, it is not mixed well

**Expected behavior**

Maybe not a code issue, but the audio track should just loop in a nicer way? 

I guess the initial sound effect from winning the battle could be cut out into its own track, and it could just play once. Then the rest of the track could play in a loop, and instead of fading out at the end it could just loop continuously.

**Comment by torranx** [comment]
IIRC this has been fixed before, but if encountered again, please open a new issue.

**Comment by Snailman11** [comment]
https://github.com/user-attachments/assets/9c7f21d2-eff7-4459-8280-ffc428c6a682

Seems better now
