### ISSUE TITLE
[Feature] UI request: Clearer indication of when a "Generation-Only" or "Type-Only" challenge will be failed based on catching a pokemon

### ISSUE THREAD

**Issue by lazkmet** [pagefaultgames/pokerogue#2919]
**Is your feature request related to a problem? Please describe.**
I recently completed a Gen-4 only run, but was not awarded the achievement for some reason. Last time I ran the Flying-Type only challenge, I was able to catch and release an off-type pokemon and still get the achievement. I assume this is because I did not keep it for any additional floors, or that I did not send it into battle. However, my most recent run included Munchlax (which I did not evolve), Azelf, Buneary > Lopunny, Bidoof > Bibarel, Luxray (Dropped mid-run), Rhyperior, and Electabuzz > Electivire (Evolved before ever sending into battle). I assume I did not get the achievement either because the game treated Rhyperior or Electivire as not Gen-4, even though those evolutions were added in that Gen, or because I kept Electabuzz for quite some time before finding the evolution item.

**Describe the Feature**
When the player is about to take an action that would invalidate their challenge run (either catching a pokemon, evolving the active pokemon, or sending a pokemon out in battle, I am not sure when the trigger takes place), a popup appears, saying "[catching this pokemon / sending out this pokemon / evolving this pokemon] will invalidate the current active Challenge run (Generation IV only)".

The options in the menu for this popup are:
"Release" (if the action is catching a pokemon), which immediately releases the pokemon while treating it as caught
"Cancel" (if the action is switching to a specific pokemon or evolving the current pokemon), which prevents sending out the pokemon / treats it as though you cancelled the evolution normally
or
"Continue" (all cases), which allows the player to continue with the action, possibly invalidating the achievement for their selected challenge run

If the player is in a situation where they cannot cancel the action (only one pokemon remaining in the party, in which sending it out would invalidate the run), the option to cancel would be grayed out, or a different message would appear indicating that the challenge run will be invalidated when sending out the pokemon.

**Additional context**
It is not clear from the descriptions of the challenges what would cause the run to be failed, so nuanced cases like evolutions added in later gens, typing that changes based on an item/ability, or catching and releasing a pokemon for the sole purpose of IVs and candies can lead to a challenge run not giving the achievement without warning, which is quite frustrating.

**Comment by Tempo-anon** [comment]
You do not fail challenges by catching Pokemon. What likely happened is you finished a classic run instead of starting a challenge run. The challenge run achievements only unlock when you start the run of as a challenge run.
