### ISSUE TITLE
[Feature] Distinguish which Pkmn helds which item in double battle with the same species

### ISSUE THREAD

**Issue by Brsk79** [pagefaultgames/pokerogue#2920]
In a double battle with two pkmn of the same species, it is impossible to recognize which pkmn is holding which item.
I understood by playing that items are sorted and follow some kind of an order, but it happened to me for example in this case with two Dusknoirs and it was not possible to determine which one was holding which item.
A simple separator would be enough, with an "empty" icon if one of the two has no items (just to avoid confusion).

![image](https://github.com/pagefaultgames/pokerogue/assets/56032555/2320f09a-76a9-4113-9910-13244371a4a3)

**Comment by Tempo-anon** [comment]
Target selecting one of them will make the corresponding mini icon flash.
