### ISSUE TITLE
[BUG] Terrain affecting ungrounded Pokemon

### ISSUE THREAD

**Issue by chaosgrimmon** [pagefaultgames/pokerogue#2926]
**Describe the bug**
Terrain effects should only apply to Pokemon on the ground. Currently, they apply to Pokemon that are ungrounded, whether Levitating, FLYING-type, or Magnet Rising, and to Pokemon in a semi-invulnerable turn, ie. offscreen due to Phantom Force, Dig, Dive, or Fly.

**To Reproduce**
1. Find or override a Pokemon to have a relevant Abiilty/Typing, or relevant Moves.
2. Use a Terrain.
3. Perform an action that would allow the Terrain to activate. (Priority move for Psychic, status effect for Misty, damage for Grassy, Sleep for Electric)
4. Notice that the Terrain effect applies, even though the target Pokemon is under an effect that should prevent that (or in the case of Grassy Terrain, the Pokemon heals when it shouldn't).

**Expected behavior**
![image](https://github.com/pagefaultgames/pokerogue/assets/31082757/e6c36aba-e13c-4d21-9c98-e22ceacad4eb)
The effect relevant for the Terrain used in step 3 should not apply.

**Screenshots / Videos**
![image](https://github.com/pagefaultgames/pokerogue/assets/31082757/9ff8cfaa-d263-437c-93e8-ba54a88248e5)
(Bulbasaur, using a priority move, which Psychic Terrain blocks even though Bronzor is semi-invulnerable and thus not on the Terrain.)

**Additional context**
Psychic Terrain cancelling priority moves is in `terrain.ts`, and presumably the other effects are scattered all over the codebase, including the Same-Type Power Multiplier.
Making sure that opponents targeted did not have `SemiInvulnerableTag` (imported from `battler-tags.ts`) allowed the following, (note Shadow Sneak is the most recent move used) but obviously this is a systemic issue and should be addressed all at once.
![image](https://github.com/pagefaultgames/pokerogue/assets/31082757/67a304e0-5ffe-41db-a49f-682ed3a63d98)

**Comment by schmidtc1** [comment]
https://github.com/pagefaultgames/pokerogue/blob/ffbc922e0991ecd9de4d30e2488072cb7fe837c8/src/field/pokemon.ts#L1822-L1823
The Same Type Power Multiplier, at least, is implemented correctly (assuming I'm looking at the right thing). Ungrounded pokemon do not receive the multiplier.

**Comment by schmidtc1** [comment]
https://github.com/pagefaultgames/pokerogue/blob/ffbc922e0991ecd9de4d30e2488072cb7fe837c8/src/phases.ts#L2426-L2429
Grassy terrain is also implemented correctly. It does not heal ungrounded pokemon.

**Comment by schmidtc1** [comment]
https://github.com/pagefaultgames/pokerogue/blob/ffbc922e0991ecd9de4d30e2488072cb7fe837c8/src/field/pokemon.ts#L1933-L1935
Misty terrain is also implemented correctly for both dragon-type damage-halving
https://github.com/pagefaultgames/pokerogue/blob/ffbc922e0991ecd9de4d30e2488072cb7fe837c8/src/field/pokemon.ts#L2480-L2488
and status effects. 
So it seems like just Psychic terrain is the issue.

**Comment by chaosgrimmon** [comment]
![image](https://github.com/pagefaultgames/pokerogue/assets/31082757/578088f7-dcc6-4176-a14e-b6b0a2e60879)

Yeah that's probably the issue. That's on me, I should've actually tested the Ability/Type causes instead of assuming they were as broken as semi-invulnerable was.

**Comment by schmidtc1** [comment]
https://github.com/pagefaultgames/pokerogue/blob/ffbc922e0991ecd9de4d30e2488072cb7fe837c8/src/field/pokemon.ts#L1122-L1124

Well it seems like ```isGrounded()``` doesn't check for semi-invulnerable states, so you're still right that each terrain type still needs an additional check for if the mon is in a semi-invulnerable state.

**Comment by chaosgrimmon** [comment]
Yeah, I'm trying to see now if slapping it into `isGrounded()` will cause any issues/if it fixes anything.

**Comment by chaosgrimmon** [comment]
Alrighty, I'm happy with the results of my testing and should be good to go to finish up the PR.
Thanks for your help, and for reminding me I made this report.
