### ISSUE TITLE
[BUG] PM and player textures are both rendered

### ISSUE THREAD

**Issue by Kanbe-Kotori** [pagefaultgames/pokerogue#2933]
This bug occurs when the leader pm in the last battle dies and is revived in the rest area
![U)IC27ABEDH71G%UI{{ )3J](https://github.com/pagefaultgames/pokerogue/assets/13415090/a9d33796-7f65-4ca2-8cb4-9753a1e7326c)

**Comment by jennypop** [comment]
I also got this bug just now
![Screenshot 2024-07-10 143407](https://github.com/pagefaultgames/pokerogue/assets/16927341/2746de58-d872-434b-b627-36a78720d835)

**Comment by flx-sta** [comment]
Duplicate of #222
