### ISSUE TITLE
[BUG] Parental Bond weird behavior

### ISSUE THREAD

**Issue by GitHuBinet** [pagefaultgames/pokerogue#2935]
I've experienced weird damage calculation by the second hit.

While the first hit does about 75/80% damage, the second hit is supposed to KO the opponent considering the fact that the ability makes the second hit half the damage of the first. In my case, it happened several times during my run with Farigiraf (passive ability unlocked) than the second hit actually hit only about 5%. The 2HKO happen only when the first hit reach about 95% damage.

This is not a serious bug, but this make Parental Bond less amazing than it should be (especially for Girafarig family)

**Comment by Tempo-anon** [comment]
Would need a video or session data showing this in action in order to see what's happening

**Comment by GitHuBinet** [comment]
Ok, I missed the time when it changes to 25%. But I don't know if it's hit 25% here. It seems really weak. 

[Capture vidéo du 09-07-2024 16:43:05.webm](https://github.com/pagefaultgames/pokerogue/assets/60224791/a1eaaeed-d9f5-441f-8f00-de9b30a44ec5)

**Comment by GitHuBinet** [comment]
It's in french sorry, but you should easily see the problem (if there is)

**Comment by Tempo-anon** [comment]
The first hit did 163 damage. The second hit did 40. The second hit is around 25% damage of the first hit. Seems to be working as expected.
