### ISSUE TITLE
[BUG] Smeargle Learns No Moves On Level-Up

### ISSUE THREAD

**Issue by Endermage77** [pagefaultgames/pokerogue#2938]
**Describe the bug**
Smeargle in Pokerogue doesn't learn any moves whatsoever by level up.

**To Reproduce**
1. Begin a game with Smeargle in the Party
2. Raise Smeargle's level to 11
3. See that Smeargle does not learn Sketch as expected

**Expected behavior**
Smeargle should learn an extra Sketch every 10 levels, starting from level 11.

**Screenshots / Videos**
A Smeargle's current moveset at level 12 (showing both level and moves by screenshotting during screen transition). Note how it does not have a second move available.
![image](https://github.com/pagefaultgames/pokerogue/assets/25313980/e3509312-eb31-4321-acda-3bf3f9942f32)

**Device**
Playing in browser on Google Chrome in Windows 10.

**Additional context**
This bugged learnset unfortunately makes Smeargle incredibly useless as a starter, as the only way to get it the Sketches it needs to stay relevant beyond earlygame is to spend precious Memory Mushrooms.

**Comment by schmidtc1** [comment]
Smeargle's learnset in Gen 9 is only Sketch at level 1: https://bulbapedia.bulbagarden.net/wiki/Smeargle_(Pok%C3%A9mon)#By_leveling_up
I agree though, perhaps this should be changed to match prior generations to make Smeargle more relevant.

**Comment by flx-sta** [comment]
> this should be fixed and reverted 
> smeargle shouldn't suffer playability for the sake of consistency 
 \- Damo, 2024-07-25

**Comment by schmidtc1** [comment]
This has a PR: #2986

**Comment by Snailman11** [comment]
This seems to be fixed, just tested it and Smeargle learns Sketch at 11 when it does not have the move (correct in recent games)
