### ISSUE TITLE
[BUG] "/account/info: missing token" on login with rogueserver

### ISSUE THREAD

**Issue by sanmewww** [pagefaultgames/pokerogue#2953]
**Describe the bug**
Unable to login with beta or main branch at HEAD with latest main branch of [rogueserver](https://github.com/pagefaultgames/rogueserver)

**To Reproduce**
1. Start rogueserver with the example Dockercompose file in the repository, under `api.pokerogue.local`.
2. `npm run build` pokerogue with `VITE_SERVER_URL` defined as `http://api.pokerogue.local:8001`
3. Host with `vite --host --port $PORT`, under  `pokerogue.local`.
4. Connect to pokerogue using Chrome.
5. Register account, does not automatically login.
6. Login with account fails, `GET http://api.pokerogue.local:8001/account/info` returns `401`.

rougeserver logs:

```
2024/07/10 12:41:51 /account/info: missing token
```

**Expected behavior**
Login should succeed.

**Screenshots / Videos**
N/A

**Device**
PC, Windows, Chrome latest

**Additional context**
N/A

**Comment by sanmewww** [comment]
After quick investigation, it seems like browser cookie is not being set correctly. If I manually send POST request to `/account/login` to get auth token, then set that as cookie manually as `pokerogue_sessionId=token`, I am able to login.

FYI: my browser definitely has cookies enabled.

**Comment by sanmewww** [comment]
Cookie has `Secure`, requires https .. (:

**Comment by EvilCalf** [comment]
Sorry, I'm having the same issue. My two services are also on the same server, so I would like to ask how I can avoid this problem.

server-1    | 2024/07/25 09:26:23 /account/info: missing token

Thank you.
