### ISSUE TITLE
[BUG] Decidueye is registered as 6724 instead of 0724 in the Pokedex, preventing it from being used in Generation 7 Mono Runs

### ISSUE THREAD

**Issue by Breeze3250** [pagefaultgames/pokerogue#2959]
**To Reproduce**

1. Start with Rowlett in a Generation 7 Run
2. Evolve to Decidueye

**Screenshots / Videos**
![incorrect pokedex number](https://github.com/pagefaultgames/pokerogue/assets/139270978/99ce947f-8da6-4522-9157-c3fea9e67145)
![image](https://github.com/pagefaultgames/pokerogue/assets/139270978/80e01507-f51c-4737-a8f5-79ff7d6d9f88)

**Device**

PC

**Comment by Madmadness65** [comment]
That is Hisuian Decidueye, and as such, is a Generation 8 Pokémon, not Generation 7.
