### ISSUE TITLE
Suggestion: Downloadable version

### ISSUE THREAD

**Issue by PlayfulPiano** [pagefaultgames/pokerogue#297]
Hey, I was wondering if in the future there could be a consideration for a downloadable version of the game? Web browsers sometimes have some added performance issues when running games through them, which wouldn't occur if it was a standalone program.

Just to be clear this isn't suggesting to replace the web browser version entirely, just to have a secondary version that could be done offline. Kind of like how Super Smash Flash 2 and Minecraft both used to have web and downloadable versions.

Thanks!

**Comment by grok-dev** [comment]
Not sure what the official response will be here but I would personally suggest checking out Admiral Billy's pokerogue app here:

https://github.com/Admiral-Billy/Pokerogue-App

I've used the first release version since it dropped and it has been incredible for me.

**Comment by PlayfulPiano** [comment]
Ah thanks!
