### ISSUE TITLE
[BUG] Perish Song incorrectly reactivates after reset when switching into previously out Pokemon

### ISSUE THREAD

**Issue by umbresp** [pagefaultgames/pokerogue#2982]
**Describe the bug**

Certain conditions can cause Perish Song to falsely affect a Pokemon which has switched out.

**To Reproduce**

1. Get hit by Perish Song in a doubles battle
2. End the battle when both your Pokemon have perish count 1
3. In the next battle (which must be singles), switch out to the second Pokemon which was just recalled 
4. The second Pokemon does not faint if you did both battles without reloading. However, if you reload the page then perform step 3 again, the Pokemon will faint after one turn

**Expected behavior**

I'm not sure whether immediately switching into a Pokemon with perish count 1 should cause it to faint the next turn. On one hand, it was switched out, so the perish count should reset. On the other hand, it was in on consecutive turns. However, at least one of these behaviors are definitely wrong and both can be observed depending on reset.

**Screenshots / Videos**

**Device**

PC/Chrome

**Additional context**

**Comment by Tempo-anon** [comment]
Should be fixed with #3119
