### ISSUE TITLE
[BUG] Epic Yungoos shiny party icon has an extra pixel

### ISSUE THREAD

**Issue by ItsFrankieD** [pagefaultgames/pokerogue#2991]
The bottom right corner of the epic Yangoos shiny (724_2) party icon has an extra black pixel, though I don't see the pixel present on the sprite in the current branch.

Given this is a sprite issue, I assume it is platform agnostic. I'll go ahead and note anyway that I play on Firefox on a Windows 10 build, as well as the default Samsung browser on Android.

![image](https://github.com/user-attachments/assets/e0764ec4-ff65-49d4-814b-ab1f091bf54d)

**Comment by Tempo-anon** [comment]
Merged into beta
