### ISSUE TITLE
Urshifu ability not functioning

### ISSUE THREAD

**Issue by holohok** [pagefaultgames/pokerogue#2993]
**Describe the bug**
I used wicked blow on protect and it didn’t go through. It happened a little bit ago so if it seems to work in testing then I probably used it again neutralizing gas or something.  
**To Reproduce**

Urshifu dark wicked blow vs protect

**Expected behavior**
Move should go through protect 

**Screenshots / Videos**

**Device**
PC

**Additional context**

**Comment by schmidtc1** [comment]
Works fine in testing. Likely neutralizing gas or another ability-suppression effect as you mentioned.

https://github.com/user-attachments/assets/c14807af-bcd3-48df-a103-9d8434a2984e

**Comment by Tempo-anon** [comment]
Closing since not reproducible. Next time please submit a video or preferably your session data.
