### ISSUE TITLE
Visual Glitch In Combate [BUG]

### ISSUE THREAD

**Issue by Anjaconda** [pagefaultgames/pokerogue#3021]
**Describe the bug**
the charecter sprites have disapeared and even finishing a fight does not restore them
**To Reproduce**
I opened 3 eggs at the end of an area then when I entered the next one in classic mode and the chaarecter sprites of both my and my opponents pokemon disapeared including the attack animation

**Screenshots / Videos**
<img width="1440" alt="Screenshot 2024-07-13 at 11 59 10 PM" src="https://github.com/user-attachments/assets/f1991f56-65f5-4018-a2bb-965a4f159b98">

**Device**
Macbook Air google Browser

**Comment by flx-sta** [comment]
@Anjaconda can you please provide your session data & make a screenshot of the console?

**Comment by Tempo-anon** [comment]
Known bug where sprites disappear if your Pokemon faints on the last fight of a biome. Refreshing will fix the issue.
