### ISSUE TITLE
[BUG] Eruption Hits through Flash Fire

### ISSUE THREAD

**Issue by damianlarson** [pagefaultgames/pokerogue#3027]
**Describe the bug**
Eruption hits through Flash Fire as an ability.

**To Reproduce**
1. Use a mon with Flash Fire vs. any mon that can use Eruption (in discovering this, I was using Heatran vs. Groudon). Found this using a Skarm/Heatran core, so when Skarm is in, Groudon would use Eruption.
2. Switch in on a turn where Eruption is being used
3. See that damage is still applied despite Eruption being a Fire-type move

**Expected behavior**
Flash Fire should pop and no damage is taken

**Screenshots / Videos**

**Device**
PC, Win 11, Firefox 128.0

**Additional context**

**Comment by Tempo-anon** [comment]
If you're fighting a Groudon it's probably a boss which means it has its passive, turboblaze. Turboblaze functions like mold breaker so it ignores flash fire.
