### ISSUE TITLE
[Feature] Icon indicator for playable Pokemons

### ISSUE THREAD

**Issue by yukioz** [pagefaultgames/pokerogue#3052]
# Description

Add icon indicator to show playable pokemons during challenges runs.
example: while playing Gen I challenge, if a pikachu appears, a green icon shows up "🟢" indicating you are allowed to play with it.

# Detailment
- [ ] The icon should be placed next to pokemon level.
- [ ] Pokemons that are not allowed in the run should not display de icon.

# Additional Comments

**Comment by Tempo-anon** [comment]
The UI for the pokemon health bar menu is already cluttered. This was implemented through hovering instead
