### ISSUE TITLE
Missing signature moves for pikachu on Android[BUG]

### ISSUE THREAD

**Issue by Firestone001** [pagefaultgames/pokerogue#3066]
**Describe the bug**

**To Reproduce**

1. Go to 'start new game and Gen 1 starter selection.
2. Scroll to cosplay pikachu
4. See that all cosplay Pikachu's are missing signature moves such as Tough/Libre is missing flying press, Belle/Beautiful is missing icicle crash, and Ph.d./smart is missing electric terrain.

**Expected behavior**

**Device**

**Additional context**

**Comment by flx-sta** [comment]
@Firestone001 Please add some more details so we can properly investigate the issue.
Which signature move is missing? 
Which cosplay are you referring to?
Are you playing offline or online?

**Comment by Firestone001** [comment]
Have added requested info.

**Comment by flx-sta** [comment]
There was a patch for Memory-Mushroom which seemed to have removed the signature moves for cosplay forms of pikachu.
<img width="722" alt="image" src="https://github.com/user-attachments/assets/f1a5e9e6-1a61-4ced-8bcc-13b7bc40398f">

**Comment by Firestone001** [comment]
Was this intentional?

**Comment by flx-sta** [comment]
Half. It was discarded in favor of update velocity. It’s planned to be re-implemented

**Comment by Firestone001** [comment]
OK, good to know. Thanks!

**Comment by flx-sta** [comment]
Duplicate of #2783
