### ISSUE TITLE
[QUESTION] If i enable the login screen, does this mean that my self-hosted server will store the userdata in its storage? 

### ISSUE THREAD

**Issue by Cuphead74832** [pagefaultgames/pokerogue#3072]
My question is that i want to host my OFFLINE pokerogue server for me and my roomates and their multiple devices, now the server is in an OFF THE LINE ROUTER point, i found how to enable it here.
https://github.com/pagefaultgames/pokerogue/issues/1328

Can PokeRogue run offline and have its own user database apart from the pokerogue.net user database?

**Comment by flx-sta** [comment]
@Cuphead74832 Yes you can set your server up locally by using the server repo https://github.com/pagefaultgames/rogueserver. You just gotta make sure to hook it up in your local network correctly and to update the correct env variables for the client when launching it
