### ISSUE TITLE
[BUG] Broken statistics menu when account is first created

### ISSUE THREAD

**Issue by MokaStitcher** [pagefaultgames/pokerogue#3076]
**Describe the bug**
When an account is created some data seem to not get initialized properly in gameData.gameStats, breaking the statistics menu. This only happens the very first time the game is played with an account, after that reloading the page will fix it

**To Reproduce**
You need a fresh account for this, so it's easiest to reproduce by running the game locally, or you'll have to make a new account every time. I've confirmed it behaves the same on live when registering a new account

1. Open a new incognito window with the game
2. If not running locally, register a new account
3. Go through the tutorial and open the menu
4. Go to Statistics menu and press down a few times
5. The "captured pokemon" and "eggs hatched" elements get repeated each line instead of the normal statistics

This will fix itself by doing any of the following:
- refresh the page
- change a setting that sends you back to main menu like the language
- start a run then save and quit to main menu

**Screenshots / Videos**

How the statistics menu look when playing with a fresh account:
<img width="1177" alt="stats-broken" src="https://github.com/user-attachments/assets/56397788-6af1-4309-8cb1-9b89246e1bba">

How it's supposed to look:
<img width="798" alt="stats-normal" src="https://github.com/user-attachments/assets/7fc94dcb-7e17-4644-9229-1d45d7a426ad">

https://github.com/user-attachments/assets/33ed027d-ad44-42f9-b490-142eea089b09

**Device**
Mac OS / Firefox

**Additional context**
This is probably not game breaking but since it seems some data is not initialized properly on account creation, it might actually be a problem if something else than statistics is also affected and someone plays for a very long time on a fresh account without ever reloading the page.
Also not sure what would happen if somehow one would happen to hatch a legendary egg while in this state (or any of the other non initialized statistics)

**Comment by Mewtwo2387** [comment]
Can confirm that `subLegendaryPokemonSeen`, `subLegendaryPokemonCaught`, and `subLegendaryPokemonHatched` is not initialized as 0 on a fresh save, because of how retroactive counting of sublegendary pokemon is implemented.

This will happen if you encounter one in this state:

![image](https://github.com/user-attachments/assets/f305efdf-b6f4-46ea-8c35-6726469de970)

**Comment by Tempo-anon** [comment]
Thanks for the bug report! Should be fixed with https://github.com/pagefaultgames/pokerogue/pull/3122
