### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by buildfill** [pagefaultgames/pokerogue#3106]
### Describe the bug

dunno why, but whenever i try to add a pokemon for my starter it doesn't and gives me the error sound

### Expected behavior

fix idk

### What OS did you observe the bug on?

Mac/OSX

### Which browser do you use?

Chrome

**Comment by flx-sta** [comment]
We'd need more information to provide you with help.
e.g. a screenshot of your console.
1. Press `F12` to open the dev-tools
2. Select the `Console` tab
3. Take a screenshot of the content

**Comment by Tempo-anon** [comment]
Are you pressing enter? Try pressing Z instead of enter.
