### ISSUE TITLE
[Bug] localhost /account/info: missing token 

### ISSUE THREAD

**Issue by EvilCalf** [pagefaultgames/pokerogue#3140]
### Describe the bug

I start [rogueserver](https://git.homegu.com/pagefaultgames/rogueserver) by docker-compose and [pokerogue](https://github.com/pagefaultgames/pokerogue) on one server.
And my env is 
`VITE_SERVER_URL=https://{public ip}:8001`
If i use localhost or internal ip, it will be `net::ERR_CONNECTION_REFUSED`. So i set the public ip.

At last, i can not login in. It shows `server-1    | 2024/07/25 09:26:23 /account/info: missing token`

### Expected behavior

log in

### What OS did you observe the bug on?

Mac/OSX, Linux

### Which browser do you use?

Chrome

**Comment by flx-sta** [comment]
> If i use localhost or internal ip, it will be net::ERR_CONNECTION_REFUSED. So i set the public ip.

That's odd. It could be because you have no https certificate or something else. Things like those have never been tested.

----

The "missing token" message is returned from [rogueserver/api/common.go](https://github.com/pagefaultgames/rogueserver/blob/4cac6b6ce8fbdcaf6ef640b8c0d80a8afe2c9a37/api/common.go#L69-L84)
means the request is missing the session-token. The session token should be read from a cookie which seems to be missing then

**Comment by EvilCalf** [comment]
I track the code and find the document.cookie is empty.https://github.com/pagefaultgames/pokerogue/blob/28c5dc6b59cd363c1dff55550bcaa620e7e29dda/src/utils.ts#L301. So the sId is empty https://github.com/pagefaultgames/pokerogue/blob/28c5dc6b59cd363c1dff55550bcaa620e7e29dda/src/utils.ts#L334
![QQ_1721956433918](https://github.com/user-attachments/assets/63c27c37-c610-4baf-a470-dd5bfbafb2e1)

**Comment by EvilCalf** [comment]
> > If i use localhost or internal ip, it will be net::ERR_CONNECTION_REFUSED. So i set the public ip.
> 
> That's odd. It could be because you have no https certificate or something else. Things like those have never been tested.
> 
> The "missing token" message is returned from [rogueserver/api/common.go](https://github.com/pagefaultgames/rogueserver/blob/4cac6b6ce8fbdcaf6ef640b8c0d80a8afe2c9a37/api/common.go#L69-L84) means the request is missing the session-token. The session token should be read from a cookie which seems to be missing then
So can I skip the authorization verification step

**Comment by EvilCalf** [comment]
https://github.com/pagefaultgames/pokerogue/blob/28c5dc6b59cd363c1dff55550bcaa620e7e29dda/src/ui/login-form-ui-handler.ts#L73
I set console.log to check Utils.sessionIdKey, response.token. They all have value, but document.cookie is empty

**Comment by EvilCalf** [comment]
![QQ_1721958841404](https://github.com/user-attachments/assets/154a7c42-d721-4aa9-9cc6-0e6ffdbf1184)
I find the browser has no cookie too.

**Comment by flx-sta** [comment]
You should check the answer from the server when logging in.
It should have a `Set-Cookie` header

**Comment by EvilCalf** [comment]
![QQ_1721960156629](https://github.com/user-attachments/assets/b024c9ef-8ce6-4071-9895-55ed51c8c5f7)
Is this? It seems has no a Set-Cookie header

**Comment by CuriousRookie** [comment]
cookie is set by `setCookie` in `utils.ts`, `VITE_SERVER_URL=https://{public ip}:8001`, but in devtools seems it is `http`

`Secure` may cause javascript failed to set or get cookie

**Comment by EvilCalf** [comment]
:( So how can i fix this.
Thank you.

**Comment by EvilCalf** [comment]
I set console.log(document.cookie) under the below lines:
https://github.com/pagefaultgames/pokerogue/blob/5f82449120b16290a812ac964e38f0327c33e245/src/utils.ts#L242
It is also empty

**Comment by CuriousRookie** [comment]
how about the response of `account/login`, the value of `response.token` is not empty?

**Comment by EvilCalf** [comment]
Yes. It is not empty.
![QQ_1721962246051](https://github.com/user-attachments/assets/1dded118-d4f3-4acd-b011-680af2cf994b)

**Comment by CuriousRookie** [comment]
i have no idea, remove `Secure;` works to me, not use docker, start with `npm run start:dev` and `rogueserver.exe --debug`, use internal ip `172.16.xxx.xxx` with port `8080` and `8081`

**Comment by EvilCalf** [comment]
remove Secure? How to do?

**Comment by CuriousRookie** [comment]
> I set console.log(document.cookie) under the below lines:
> 
> https://github.com/pagefaultgames/pokerogue/blob/5f82449120b16290a812ac964e38f0327c33e245/src/utils.ts#L242
> 
> 
> It is also empty

same as you, modify 

` document.cookie = ``${cName}=${cValue};Secure;SameSite=Strict;Path=/;Expires=${expiration.toUTCString()}``; ` 

to 

` document.cookie = ``${cName}=${cValue};SameSite=Strict;Path=/;Expires=${expiration.toUTCString()}``; `

in `utils.ts setCookie`

**Comment by EvilCalf** [comment]
It worked! THANK YOU !!!!!!
And I have a new error....
![QQ_1721966889567](https://github.com/user-attachments/assets/73a7d901-0fed-4105-9566-8570cefe7c0d)
Response as below:
![QQ_1721966911762](https://github.com/user-attachments/assets/f2198bae-ed32-4067-b7bb-8931e733365e)

**Comment by flx-sta** [comment]
Yeah `Secure` means the cookie is only allowed in https content.
Maybe we should put in a mechanism that takes that into account

**Comment by EvilCalf** [comment]
> Yeah `Secure` means the cookie is only allowed in https content. Maybe we should put in a mechanism that takes that into account

Thank you，can you help me take a look at the new problem I encountered earlier.

**Comment by flx-sta** [comment]
@EvilCalf this isn’t an error. This can also happen on live. Basically the client is requesting session for save-slots that are empty
