### ISSUE TITLE
[Bug] Unnecessary fetch on logout

### ISSUE THREAD

**Issue by Vassiat** [pagefaultgames/pokerogue#3159]
### Describe the bug

When opening the menu the ```Log out``` sends fetch of the battle-anims file despite being unnecessary

### **To Reproduce**

1. Open Dev-Tools -> ```Network```
2. Filter by common (e.g. "common-health" or "common-h" to see clearly)
3. Login and log out to see how fetches are sent

### Expected behavior

No unnecessary fetch loads that can slow down loading

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/a93b496d-3a25-4386-80b5-9113f97ed090)
_example doing the start-exit process several times and filtered by "common-h"_

#### What OS and Browser did you observe the bug on?
Linux/Vivaldi

**Comment by flx-sta** [comment]
Cant repro
`main` (f25d4e1ee2ec0a04d1631fd1e1bcb74a90295e2a)
