### ISSUE TITLE
[Bug] Curse bypasses Crafty Shield

### ISSUE THREAD

**Issue by chansyu** [pagefaultgames/pokerogue#3161]
### Describe the bug

A ghost-type Pokemon can successfully hit a target using Crafty Shield. The target loses HP at the end of the turn.
Refer to https://bulbapedia.bulbagarden.net/wiki/Curse_(move)

### Expected behavior

Crafty Shield should block the effect of Curse performed by a Ghost-type Pokemon.

### Screenshots / Videos

[screen-capture.webm](https://github.com/user-attachments/assets/fdff7424-8ba4-4565-af23-30992f873249)

### What OS did you observe the bug on?

Linux

### Which browser do you use?

Chrome

### Additional context

Bug is prevalent in both the beta and main branch at the moment.

**Comment by Tempo-anon** [comment]
> This move is not blocked by [Protect](https://bulbapedia.bulbagarden.net/wiki/Protect_(move)), [Detect](https://bulbapedia.bulbagarden.net/wiki/Detect_(move)), or [Spiky Shield](https://bulbapedia.bulbagarden.net/wiki/Spiky_Shield_(move)), but is blocked by [Crafty Shield](https://bulbapedia.bulbagarden.net/wiki/Crafty_Shield_(move)).

Gamefreak why...

**Comment by chansyu** [comment]
One special test case to consider.
> If the user is not already Ghost-type and becomes Ghost-type due to [Protean](https://bulbapedia.bulbagarden.net/wiki/Protean_(Ability)) upon executing Curse, the user will use the Ghost-type Curse on itself (regardless of [Follow Me](https://bulbapedia.bulbagarden.net/wiki/Follow_Me_(move)) or [Rage Powder](https://bulbapedia.bulbagarden.net/wiki/Rage_Powder_(move))). This cannot be blocked by [Crafty Shield](https://bulbapedia.bulbagarden.net/wiki/Crafty_Shield_(move)).

**Comment by chansyu** [comment]
Currently working on it...

**Comment by chansyu** [comment]
Relevant PR was merged
