### ISSUE TITLE
[Bug] Substitute sprite in summary after caught Oddish

### ISSUE THREAD

**Issue by hayuna** [pagefaultgames/pokerogue#3168]
### Describe the bug

Shiny Epic Variant of Oddish in summary screen after caught pokemon display Substitute sprite 

### Expected behavior

Correct sprite of Oddish (Shiny Epic Variant)

### Screenshots / Videos

<img width="1052" alt="Screenshot 2024-07-28 at 01 49 37" src="https://github.com/user-attachments/assets/299b039b-2a80-4de6-ac03-a74583a6f35a">

### What OS did you observe the bug on?

Mac/OSX

### Which browser do you use?

Chrome

**Comment by flx-sta** [comment]
can't repo `beta` (2d1fe13efad724d69fe40ec2ed240a349ae3d1d4)
