### ISSUE TITLE
[Feature] Support for special characters (not supported by Emerald Pro)

### ISSUE THREAD

**Issue by sodaMelon** [pagefaultgames/pokerogue#3180]
**Is your feature request related to a problem? Please describe.**

(it's not important, but for fun.)
PokeRougue game use Emerald pro. but it doesn't surpported many special characters like ☆, ♥, ♪ and so on.
If I add those letters, we'll be able to decsribe when a Pokémon is singing , NPC trainer's humming in the game. 

**Describe the Feature**

I was thinking of adding it to [Pokemon platina font](https://github.com/MrWaterT/PokePT_Wansung) recently created by MrWarterT. [Emerald pro](https://fontstruct.com/fontstructions/show/832818/pok_mon_emerald_pro) was last updated in 2016, so I think it's inappropriate.

here are the sample. ( formal ♪ was replaced by pixel style font)
![sample-musicnote](https://github.com/user-attachments/assets/3fed64c5-4dfd-4fed-b4e3-597b70a64e75)
- not trying to change the dialog!!! just sample for ♪
- It's not finished, **still need to consider margins and compatibility with other pixel fonts.)**

**Additional context**

If it's okay to do this, @returntoice  will join us. he can make font.

- ref1:  special characters in Platina, 4th Pokemon game. (just referecnes, I have no intention of doing it exactly the same!)
![image](https://github.com/user-attachments/assets/f81c12bb-873d-4f59-8b58-569a03b9f794)
- ref2: the letters in Emerald Pro
![image](https://github.com/user-attachments/assets/4e0364b8-9ad9-4560-8c3d-8d6c60328fbf)

**Comment by sodaMelon** [comment]
maybe we will start this task on weekend.

**Comment by sodaMelon** [comment]
i made 4 characters, but there's a something problem for add. 
(When I added it, the Korean characters were enlarged and displayed in the game.)
I'll check this out and fix it later, maybe on this Monday or Tuseday
![image](https://github.com/user-attachments/assets/d878ea4a-691d-4302-ad7a-13a5165f8b60)
![image](https://github.com/user-attachments/assets/59126dc8-7ab1-43bc-afbe-e2bb4daaec67)

**Comment by sodaMelon** [comment]
It's not a problem. Compared with font in game, I noticed it was adjusted by another way. 
(I will ask to mrWaterT, or adjust mine by fontforge later)

**Comment by sodaMelon** [comment]
here are example for (♪.★,♥,♣)
![image](https://github.com/user-attachments/assets/28296d4a-84fa-4e47-b9de-f26de4a37edf)

**Comment by frutescens** [comment]
Closing b/c fixed by your PR #3535
