### ISSUE TITLE
[Suggestion] [QOL] Show stats augmentation

### ISSUE THREAD

**Issue by DhalEynn** [pagefaultgames/pokerogue#321]
Hello,

I think it would be very interesting to be able to see at what point you are in term of stats augmentation, aka the +6/-6 for each stats when you use capacities like "Sword dance" or when you are tagged with "Growl" or the like.
I would suggest either a menu on the left side that you could open with a keybind, or to show it on the left between the opponant HP bar and the text box.

Thanks for the time you took reading this, and have a nice day !

**Comment by Flashfyre** [comment]
This has been in planning for a while and it's what I've been working on since last night. It's also been suggested too many times to count.

**Comment by DhalEynn** [comment]
Ah, thanks then ! 
I didn't see it in the issues, so I created one here ^^
Have a nice day then ;)
