### ISSUE TITLE
[Bug] Some prompt options no longer loop-around the cursor

### ISSUE THREAD

**Issue by Anusien** [pagefaultgames/pokerogue#3218]
### Describe the bug

On the team selection screen, when selecting a Pokemon you get a list of items like Add to Party, Toggle IVs, etc. You used to be able to wrap around this list: pushing up at the top went to the bottom and pushing down at the bottom went to the top. This no longer works.

### Expected behavior

Can circularly wrap lists in both directions.

### What OS did you observe the bug on?

Mac/OSX

### Which browser do you use?

Chrome

**Comment by flx-sta** [comment]
@Anusien would you be able to provide a list (and most preferably a video) of all the ones that can't do that (anymore?)

**Comment by Anusien** [comment]
I don't know that a video would help. It would just be me hitting the up or down key at a menu and having nothing happen. But here's the list I've found so far:

Broken:
* Opening menu
* Will you switch Y/N (I don't know that this one worked before tbh)
* Use IV Scanner Y/N (I don't know that this one worked before tbh)
* Select a game mode (I don't know that this one worked before tbh)
* The menu when you select a Pokemon when starting a game: Add to Party, Toggle IVs...
* Select nature. menu when starting a game
* Use candy men when starting a game
* Your party is full. Release a Pokemon to make room for Wild X?

Working:
* Pokeball selection
* Choose a Pokemon: the send out screen
* Do what with this Pokemon?
* Scrolling through a Pokemon's move list
* Hitting ESC and getting the menu with Game Settings, Achievements, Stats...
* Do what with this Pokemon: the menu when you're in the shop, select an item like Soul Dew, and then select a Pokemon

**Comment by flx-sta** [comment]
Could you adjust the title to say `[Bug] Some prompt options no longer loop-around the cursor`

**Comment by Snailman11** [comment]
Can't replicate, probably fixed
