### ISSUE TITLE
[Feature] Make it easy to go back to team filters

### ISSUE THREAD

**Issue by Anusien** [pagefaultgames/pokerogue#3220]
**Is your feature request related to a problem? Please describe.**
I love the new team selector options to filter by generation, stat, etc. But I find it really unwieldly to be at the top. The only way you can change these is by going to the top, either by pushing up from the top row or pushing down from the bottom row. This can be an issue because there are a *lot* of Pokemon. This is a computer interface metaphor that doesn't make sense here because you can't use the mouse to click them the way you can a normal computer menu.

**Describe the Feature**
The generation selector used to be on the left, which meant you could easily get to it. I'd love to put these new filters back on the sides, so I can get to them way more quickly.
Another way to do it would be to add a hotkey to go to the filter.

**Comment by Tempo-anon** [comment]
C is the shortcut to jump you to the filters
