### ISSUE TITLE
[Bug] Toxic Spikes implementation issues

### ISSUE THREAD

**Issue by innerthunder** [pagefaultgames/pokerogue#3240]
### Describe the bug

The move Toxic Spikes has several bugs in its implementation. This report compiles the bugs reported in other issues and in the Discord.

### Unreported issues with Toxic Spikes (data/evidence below)
1. When used in a double battle with both enemies active, Toxic Spikes sets two layers of spikes
2. After using Toxic Spikes in a previous double battle, the status affliction message appears twice for each affected enemy

### Other reported bugs related to Toxic Spikes for reference:
1. Toxic Spikes is removed from the field after reloading the save (https://github.com/pagefaultgames/pokerogue/issues/684)
3. Grounded Poison-type Pokemon do not absorb Toxic Spikes upon entering the field (https://github.com/pagefaultgames/pokerogue/issues/935)
4. Pokemon take (toxic) poison damage immediately after being poisoned by Toxic Spikes (https://github.com/pagefaultgames/pokerogue/issues/1320)

### Session export file

In this save, Toxic Spikes was used once by the player's Toxapex in a previous double battle. You can observe the duplicate messages at the start of battle as well as the fact that enemies are afflicted with Toxic Poison rather than normal poison.

[sessionData1_innerthunder (1).zip](https://github.com/user-attachments/files/16422919/sessionData1_innerthunder.1.zip)

### Expected behavior

- Using Toxic Spikes successfully in a double battle should add 1 layer of spikes to the enemy's side of the field
- The "__ was poisoned by Toxic Spikes!" message should only show once per affected enemy as they enter the field

### Screenshots / Videos

The start of Turn 1 in a battle after Toxic Spikes was used once in a double battle:
![image](https://github.com/user-attachments/assets/1ed87d3e-3047-45b1-a3b9-2ef9c8a9ff58)

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Chrome

**Comment by Snailman11** [comment]
Here is a link to the Toxic Spikes bugs posted on discord;
1. Does not save after reload (Hazards)
[⁠Reloading save removes spikes](https://discord.com/channels/1125469663833370665/1267188711511031838)
Does not get absorbed by Poison types
[⁠Toxic Spikes not being absorbed](https://discord.com/channels/1125469663833370665/1267643732878954538)
Early poison tick damage
[⁠Toxic spikes and early damage](https://discord.com/channels/1125469663833370665/1241770168665903174)

**Comment by Snailman11** [comment]
Spikes also sets twice in double battles
