### ISSUE TITLE
[Bug] Docker installation, an error will be reported after entering the page

### ISSUE THREAD

**Issue by a877429929** [pagefaultgames/pokerogue#3248]
### Describe the bug

Docker installation, an error will be reported after entering the page

### Expected behavior

Docker installation, an error will be reported after entering the page

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/85b49659-8b4c-4c8e-8c43-d28867f336e5)

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Chrome

**Comment by a877429929** [comment]
> We would require more information to be able to help you. It looks like some networking issues which can be related to a whole lot of stuff.
> 
> are you experienced in using docker ?

I am using the compose.yml provided on dockerhub
`services:


  # Use this reverse proxy or add to your own with http://web:8000 and http://server:8001 at /api/
  # Simple reverse proxy that forwards requests to the web and server services
  nginx:
    image: ceramicwhite/pokerogue:nginx-proxy
    container_name: pokerogue-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - web
      - server

  web:
    image: ceramicwhite/pokerogue:latest-accounts
    container_name: pokerogue
    init: true
    restart: unless-stopped
    depends_on:
      - server
    # ports:
    #   - 8000:8000

  server:
    image: ceramicwhite/pokerogue:server-latest
    container_name: pokerogue-server
    init: true
    command: ["--debug", "--dbaddr", "db", "--dbuser", "pokerogue", "--dbpass", "pokerogue", "--dbname", "pokeroguedb"]
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    # ports:
    #   - "8001:8001"

  db:
    image: mariadb:11
    container_name: pokerogue-db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 10s
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pokeroguedb
      MYSQL_USER: pokerogue
      MYSQL_PASSWORD: pokerogue
    volumes:
      - database:/var/lib/mysql

volumes:
  database:

networks:
  default:
    name: pokerogue-network
`

**Comment by flx-sta** [comment]
IDK where that file is coming from tbh.
Try playing with the env variables. It seems your server-url is misconfigured (not using localhost:8001).

**Comment by a877429929** [comment]
This file comes from dockerhub, I copied it completely，I tried to open it with https, but got the same error.
![image](https://github.com/user-attachments/assets/7b55a8fa-1851-4af6-9172-fa0050fac93f)

**Comment by torranx** [comment]
Please open a new issue if you are still encountering this.
