### ISSUE TITLE
[Bug] Ivy cudgel doesnt change its type in the type hints

### ISSUE THREAD

**Issue by flx-sta** [pagefaultgames/pokerogue#3263]
### Describe the bug

the move is a fire type but it doesnt show it

### Expected behavior

it supposed to show 0.25x not 4x

### Screenshots / Videos

<img width="699" alt="image" src="https://github.com/user-attachments/assets/341f6dfa-0168-4fca-98db-23143b0217ba">

### What OS did you observe the bug on?

Other

### If other please specify

All

### Which browser do you use?

Other

### If other please specify

All

### Additional context

[Discord Thread | 1266342712248893494](https://discord.com/channels/1125469663833370665/1266342712248893494)

**Comment by Tempo-anon** [comment]
Was being worked on in https://github.com/pagefaultgames/pokerogue/pull/1330

**Comment by innerthunder** [comment]
@flx-sta did #3417 cover this?

**Comment by flx-sta** [comment]
> @flx-sta did #3417 cover this?

I would assume since temp mentioned the PR that I simply mirrored
