### ISSUE TITLE
[Bug] Good as Gold does not prevent stat drop from Parting Shot

### ISSUE THREAD

**Issue by umbresp** [pagefaultgames/pokerogue#3283]
### Describe the bug

When using Parting Shot against a Pokemon with Good as Gold, the switch-out is prevented but the stat drop is not. 

### Expected behavior

The expected behavior is that the move fails altogether.

### What OS did you observe the bug on?

Mac/OSX

### Which browser do you use?

Chrome

**Comment by Snailman11** [comment]
Link to Discord's bug report (Prankster Whimsicott + Parting shot into dark type still lowered my offensive stats)
https://discord.com/channels/1125469663833370665/1260240283271168152

-Probably a broad issue where the switch out  part is blocked but the stat drop isn't.

**Comment by torranx** [comment]
Fixed in https://github.com/pagefaultgames/pokerogue/pull/3195
