### ISSUE TITLE
Repeated dive action when opponent dived pokemon gets paralysis stunned

### ISSUE THREAD

**Issue by cYuza** [pagefaultgames/pokerogue#329]
After I paralysed the opponent Dondozo, it used dive.
while under water, it was unable to move due to paralysis.

* It spent the next few moves repeatedly using dive and entering the "going under water" stage of the move, without attacking.
* It was treated as though it was still under water (attacks did not hit)
* it fixed itself after ~5 turns (I didn't count and it was a very fast play speed, so don't trust the estimate too much)

this bug triggered twice in that fight.

**Comment by bennybroseph** [comment]
Fixed in https://github.com/pagefaultgames/pokerogue/pull/741
