### ISSUE TITLE
[Bug] Type Conversion and State Problem

### ISSUE THREAD

**Issue by esperar** [pagefaultgames/pokerogue#3300]
### Describe the bug

When a Poison-type Pokémon uses a move that changes its type and then becomes poisoned, if it is returned to its Poké Ball and taken out again, it maintains its Poison type. This seems to apply to other status condition bugs as well. It appears there is a need for a fix so that when the type returns to normal, the status condition is also removed.

### User data export file

.

### Session export file

.

### Expected behavior

.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/f04eb341-7ef3-4d14-9102-0f77c64de58a)

### What OS did you observe the bug on?

Mac/OSX

### Which browser do you use?

Other

### If other please specify

arc

**Comment by flx-sta** [comment]
@esperar can you please provide a proper title ?

**Comment by esperar** [comment]
> @esperar can you please provide a proper title ?
I did.

**Comment by innerthunder** [comment]
Not a bug. From [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Poison_(status_condition)#Prevention):

> A Pokémon that is currently [Poison-type](https://bulbapedia.bulbagarden.net/wiki/Poison_(type)) or [Steel-type](https://bulbapedia.bulbagarden.net/wiki/Steel_(type)) cannot become poisoned, except by Pokémon with the [Corrosion](https://bulbapedia.bulbagarden.net/wiki/Corrosion_(Ability)) Ability; in Generation II only, [Twineedle](https://bulbapedia.bulbagarden.net/wiki/Twineedle_(move)) can poison Steel-type Pokémon as well. **However, a poisoned Pokémon retains this status condition even if it [gains any of these types](https://bulbapedia.bulbagarden.net/wiki/Type_change) in battle (or regains the lost type once it is switched out or the battle ends).**
