### ISSUE TITLE
password find function Additional 

### ISSUE THREAD

**Issue by tree31** [pagefaultgames/pokerogue#3313]
**Is your feature request related to a problem? Please describe.**
I reset the settings on my PC. I logged out of Pocket Log. I forgot my password and can't play.
**Describe the Feature**
I want to know my password

**Additional context**

![Passwords do not match](https://github.com/user-attachments/assets/e5ca65b8-6dd3-46ed-852e-f19d2b8a1c77)

**Comment by DayKev** [comment]
Did you not connect your account with Google or Discord?

**Comment by tree31** [comment]
yes Used before that feature existed

**Comment by flx-sta** [comment]
we're currently working on a password recovery feature that will be announced at a later date

For now unfortunately there is nothing we can do to recover passwords

**Comment by tree31** [comment]
I'll wait until it comes out
