### ISSUE TITLE
[Feature] 2vs poke move target is ally, then next poke attack move target select is on ally. attack move target select should always on emeny

### ISSUE THREAD

**Issue by ynntk4815** [pagefaultgames/pokerogue#3314]
attack move use cases most target is enemy

if poke move target is ally, cause next poke move target change to ally not enemy.

**Comment by ynntk4815** [comment]
https://www.twitch.tv/videos/2214577168?t=4h59m23s

second poke use Light Screen cause next turn first poke use attack move on ally
most cases player have no intention to attack ally, so attack move select always should on enemy

**Comment by PLMMJ-FH** [comment]
I cannot understand what the meaning is supposed to be here because of the butchered english

**Comment by Snailman11** [comment]
I can kind of understand, Probably the same as Discord's bug report: 
https://discord.com/channels/1125469663833370665/1267857123501412363 (Using team buffs in doubles causes pokemon 2 to target pokemon 1 by default.)
