### ISSUE TITLE
About the rate of catching Pokemon

### ISSUE THREAD

**Issue by KaI2uuN** [pagefaultgames/pokerogue#3318]
I've been a Pokémon fan for 20 years, and since I've played all the mainline Pokémon games and fan-modified ROMs, I've played almost all of them, but what I can say is Pokerogue.What you guys created is the game that I enjoyed playing and was the most impressed with. It's number 1, and it's so good that even the main series of Pokémon games are second to it. But the only thing that made my playing no longer fun was the limitations of catching Pokemon, which sometimes made me not want to continue playing. Because if there is no Master ball

And when we find the Pokemon we want Fighting to reduce the amount of blood you can catch is a difficult thing. I didn't have any problems with it, but I really liked it. But what really took the fun out of playing for me was using the Ultra balls / Rouge Ball to catch everything. times caught Difficult, the whole team still has all their blood intact. Keep throwing balls until my entire team is dead. I ran out of nearly 30 Ultra balls / Rouge Balls. I had to reset to catch them again. Then do the same thing, use the ball to catch until the team is all dead and it won't stick. I've been resetting and catching like this and it's been the 3rd day now, and that Pokemon still hasn't been caught. I've reset it hundreds of times in total. It shouldn't be so hard to catch that the ball used to catch it is a ball that is second only to the real Master Ball, plus throwing it each round before resetting, almost 20 balls. If one day it resets 20 rounds, that's 400 Ultra balls / Rouge Balls per day. It shouldn't be. Makes the catching rate with Ultra balls / Rouge Ball ugly like this It makes the game completely fun. Hopefully the team will sympathize with the players by adjusting the catch rate so that it doesn't torture the players. Each round takes several minutes to catch and hit, plus they have to wait to reset to do the same thing over and over for several days to catch. It shouldn't be that difficult with just one Pokémon. Wasting time pumping a team to play through a level shouldn't have to result in wasting more time catching monsters than spending time passing nearly a hundred levels just because you want to catch a single Pokemon to add to your team. I would like to ask the team to fix this point. I would be very grateful because this is a game that everyone loves because everything is fun and perfect. Don't let just throwing the ball and catching just one Pokémon into the team cause the players to lose their fun and become torture instead. thank you

**Comment by DayKev** [comment]
Note that the RNG is seeded, and that seed is saved when you save the game. Meaning, if you reload the same fight over and over and take the exact same actions, the exact same outcomes will happen again. So no matter how many times you reload, you might not be able to catch the Pokémon in front of you, unless you can manage to manipulate the RNG differently enough (which can be difficult).
If you can't catch a Pokémon after a couple of reloads, it's best to just move on to the next wave and continue the run.
