### ISSUE TITLE
[Bug] Reviver seed fight freeze

### ISSUE THREAD

**Issue by tomba-pls** [pagefaultgames/pokerogue#3324]
### Describe the bug

Used giga impact while having a reviver seed. My poke fainted on the turn recharging from giga impact. After the stat drop caused by the enemy move, I am unable to proceed with the text prompt. The animations/music still play. The move order used during the fight was Belly Drum - Earthquake x2 - Giga impact. The console displays some errors:
![image](https://github.com/user-attachments/assets/f56ccb6e-0bb1-4638-b9b1-ba33dc142923)

### User data export file

[sessionData1_SnorlaxIssue.txt](https://github.com/user-attachments/files/16482977/sessionData1_SnorlaxIssue.txt)

### Session export file

[data_SnorlaxIssue.txt](https://github.com/user-attachments/files/16482978/data_SnorlaxIssue.txt)

### Expected behavior

Text window proceeds to next turn

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Chrome

**Comment by Snailman11** [comment]
Link to Discord's Bug report (Reviver Seed Bug)
https://discord.com/channels/1125469663833370665/1274492864314998875

**Comment by Snailman11** [comment]
Another Rev Seed Related Crash https://github.com/pagefaultgames/pokerogue/issues/4219
(Dtail and KO)

**Comment by Snailman11** [comment]
Seems to be fixed by 
[Bug] Fix crash when using enemy move override
https://github.com/pagefaultgames/pokerogue/pull/4352
