### ISSUE TITLE
It seems Wasteland is no longer visible.

### ISSUE THREAD

**Issue by hugolden** [pagefaultgames/pokerogue#3328]
### Describe the bug

When getting out of badlands with a map, there is no option moving to Wasteland, The player is moved to volcano by default.

### Expected behavior

There should be an option of moving to Wasteland somewhere.

### What OS did you observe the bug on?

PC/Windows, iOS

### Which browser do you use?

Other

### If other please specify

QQBrowser

**Comment by damocleas** [comment]
You are not guaranteed to go to Wasteland, this is intended behavior!
