### ISSUE TITLE
[Bug] the game freezes when seed sower (grass field) is activated by flip turn

### ISSUE THREAD

**Issue by HubukiNinten** [pagefaultgames/pokerogue#3434]
### Describe the bug

On the wave 165, it was a trainer battle with Team Flare Boss. On the turn that Mega Gyarados used Flip Turn, I sent out Arboliva, Arboliva got hit by Flip Turn and it activated Grass Field by Arboliva's ability, and Mega Gyarados returns to the entry, and the game freezed. I think the game always freezes when grass field is activated by an ability on the turn that opponent's Pokemon used switching moves.

### Expected behavior

I think the game always freezes when grass field is activated by an ability on the turn that opponent's Pokemon used switching moves.

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Chrome

**Comment by Snailman11** [comment]
Probably fixed by https://github.com/pagefaultgames/pokerogue/pull/3346 

Seems to be fixed post august
