### ISSUE TITLE
[Bug] Fused Pokemon's ability was changed randomly in save file after update?

### ISSUE THREAD

**Issue by cjfsisco** [pagefaultgames/pokerogue#3440]
### Describe the bug

Had a save file with a fused Mega Lopunny and Regigigas with the Normalize ability (only Regigigas ability I have unlocked). Recently continued the file and realized the ability had been changed to Slow Start.

### User data export file

[data_JEFEFRANCISCO.txt](https://github.com/user-attachments/files/16552764/data_JEFEFRANCISCO.txt)

### Session export file

[sessionData_JEFEFRANCISCO.txt](https://github.com/user-attachments/files/16552765/sessionData_JEFEFRANCISCO.txt)

### Expected behavior

Ability should not have been changed from one to another without unfusing/fusing a new Pokemon (occurred offline). 

### What OS did you observe the bug on?

Android

### Which browser do you use?

Chrome

**Comment by Snailman11** [comment]
This was probably fixed by https://github.com/pagefaultgames/pokerogue/pull/3173 ([Hotfix] Fix Pokemon in pre-patch saves swapping abilities)
