### ISSUE TITLE
[Bug] Endless `%50` waves soft-lock

### ISSUE THREAD

**Issue by flx-sta** [pagefaultgames/pokerogue#3453]
## Describe the bug

When fighting a `%50` wave e.g. `4950` there is a soft-lock with a console error.
PR #3346 caused it by calling `pokemon.destroy()` in `BattleEndPhase`

## Session export file

[⬇️ sessionData3_Guest.txt](https://github.com/user-attachments/files/16555476/sessionData3_Guest.txt)
<sub>Make sure to change to `prsv` file-extension</sub>

## Expected behavior

It shouldn't soft-lock and continue to next wave

## Screenshots / Videos

![discord image from starkrieg](https://media.discordapp.net/attachments/1244839350919888897/1271283091922751539/image.png?ex=66b6c624&is=66b574a4&hm=7781b3664990020ba34ae751e1940243620bf370b94175b547101e4e26fd6d23&=&format=webp&quality=lossless&width=1100&height=302)

## Additional context

- First reported [discord message from Starkrieg](https://discord.com/channels/1125469663833370665/1245857678991822879/1271283224831594507) (might be not visible/locked to some)

**Comment by DustinLin** [comment]
PR #3346 made that call because it assumes that after `BattleEndPhase` the enemy pokemon aren't referenced anymore. Seems that in endless (and maybe other situations) this may not be the case?

**Comment by torranx** [comment]
> PR #3346 made that call because it assumes that after `BattleEndPhase` the enemy pokemon aren't referenced anymore. Seems that in endless (and maybe other situations) this may not be the case?

Why are we even calling something based on assumption?

**Comment by DustinLin** [comment]
I'm not sure if the original code was calling `.destroy()` for optimization reasons, if so then I think it's reasonable to make assumptions about when objects won't be needed anymore. Pre- pr #3346 the assumption was that pokemon won't be needed right after the `MoveEffectPhase` (which turned out to be wrong).

**Comment by DustinLin** [comment]
From flx's comment in #3346 , the phases towards the end of battle go in this order:
```
Start Phase BerryPhase
Start Phase TurnEndPhase
Start Phase BattleEndPhase | THIS calls p.destroy() on all enemies
...
Start Phase EggLapsePhase
Start Phase ModifierRewardPhase
Start Phase AddEnemyBuffModifierPhase
```

I'm curious why there is a `AddEnemyBuffModifierPhase` in the first place after the battle is over (and the enemy pokemon fainted), what are we trying to accomplish here? Will the same pokemon appear in a later wave? If not then this seems like a pointless phase to run, and perhaps we should think about removing it.

**Comment by flx-sta** [comment]
@DustinLin me too. It's yet another phase chaos.

We have to fix it first though. Can the `p.destroy()` call safely be removed?

**Comment by DustinLin** [comment]
pr #3461

doing some testing

**Comment by DayKev** [comment]
> From flx's comment in #3346 , the phases towards the end of battle go in this order:
> 
> ```
> Start Phase BerryPhase
> Start Phase TurnEndPhase
> Start Phase BattleEndPhase | THIS calls p.destroy() on all enemies
> ...
> Start Phase EggLapsePhase
> Start Phase ModifierRewardPhase
> Start Phase AddEnemyBuffModifierPhase
> ```
> 
> I'm curious why there is a `AddEnemyBuffModifierPhase` in the first place after the battle is over (and the enemy pokemon fainted), what are we trying to accomplish here? Will the same pokemon appear in a later wave? If not then this seems like a pointless phase to run, and perhaps we should think about removing it.

I think that was the phase that adds the endless tokens. Presumably moving it to either before the BattleEndPhase or after the next EncounterPhase (so that there are Pokémon that exist to use for the 🍝 code to do its work) should be fine?
