### ISSUE TITLE
[Bug] No Retreat failed after enemy use Spirit Shackle

### ISSUE THREAD

**Issue by allen925** [pagefaultgames/pokerogue#3459]
### Describe the bug

I should be able to use No Retreat after enemy trapped me. (Move is completely failed instead. ) 

(bulba link: https://bulbapedia.bulbagarden.net/wiki/No_Retreat_(move))
![image](https://github.com/user-attachments/assets/fd9880c9-30b2-4985-ac6c-b7c750aa65c9)

the code related to it is in move.ts:
```
      .attr(AddBattlerTagAttr, BattlerTagType.TRAPPED, true, true, 1),
```
That should be differentiating source of trapped tag by no retreat itself or other sources

### Expected behavior

Should be able to cast it at least once (or repeatedly) if enemy trapped it. 

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Chrome

### Additional context

it is easily reproducible so i don't think extra file/video is needed.

**Comment by Snailman11** [comment]
Video For it failing after Mean Look https://discord.com/channels/1125469663833370665/1125894949020381285/1272025018028658759

**Comment by innerthunder** [comment]
fixed by https://github.com/pagefaultgames/pokerogue/pull/3488
