### ISSUE TITLE
[Bug] Screen Freezes after finishing battle

### ISSUE THREAD

**Issue by AmrouKourchid** [pagefaultgames/pokerogue#3460]
### Describe the bug

after Wave 88, my screen freezes completely as seen in the image below.
and i get this error message in the console: Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

environment:
opera GX version: LVL5 (core: 111.0.5168.54)
System:Windows 11 64-bit
Chromium version:125.0.6422.143

### Expected behavior

Moves to round 89 and proceeds normally.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/e97a69fd-b635-4a5c-8f3b-11ab23417ccf)
[pokerogue.io-1723209511020.log](https://github.com/user-attachments/files/16561668/pokerogue.io-1723209511020.log)

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Opera

**Comment by torranx** [comment]
Fixed in https://github.com/pagefaultgames/pokerogue/pull/3455
Note: this should take effect on next beta release
