### ISSUE TITLE
[Bug] Game crashes when Hariyama with passive got attacked by Dragon Tail

### ISSUE THREAD

**Issue by NoRuBal** [pagefaultgames/pokerogue#3473]
### Describe the bug

**Problem:**
Game crashes when Hariyama with passive(Stamina) got attacked by Dragon Tail.
(Game won't crash after removing passive from Hariyama with Gastro Acid, so I'm pretty sure that's a problem with passive.)

### User data export file

[sessionData2_viktor29a.txt](https://github.com/user-attachments/files/16568613/sessionData2_viktor29a.txt)

### Session export file

[data_viktor29a.txt](https://github.com/user-attachments/files/16568615/data_viktor29a.txt)

### Expected behavior

Game should not be crashed after Hariyama fled by Dragon Tail.

### Screenshots / Videos

https://github.com/user-attachments/assets/1aadfdc0-591a-4ba6-a62e-592e56d330e7

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Edge

### Additional context

**Steps to Reproduce:**
1. Prepare enemy Hariyama with passive(Stamina) in double battle.
2. Attack hariyama with Dragon Tail.
4. The game crashes.

**Console Output:**
TypeError: Cannot read properties of undefined (reading 'currentBattle')
    at getPokemonNameWithAffix (index-4979af11.js:6373:48588)
    at b7.showAbility (index-4979af11.js:15948:4601)
    at f8.start (index-4979af11.js:15935:15349)
    at j7.shiftPhase (index-4979af11.js:16463:34409)
    at wv.end (index-4979af11.js:15883:68598)
    at wv.end (index-4979af11.js:15935:22625)
    at index-4979af11.js:15935:22478
    at onActionInput (index-4979af11.js:6365:1567)
    at vw.processInput (index-4979af11.js:6371:581)
    at H7.processInput (index-4979af11.js:15947:23090)
window.onerror	@	index-4979af11.js:16595

**Comment by innerthunder** [comment]
Should be fixed in beta by https://github.com/pagefaultgames/pokerogue/pull/3346

**Comment by NoRuBal** [comment]
> Should be fixed in beta by #3346

Oh, there was a duplicated issue. My bad to didn't check it enough. The issue can be closed.
