### ISSUE TITLE
[BUG] Abilities That Use PostSummonAbAttr Do Not Apply Summoned Abilities if the Player Initially Agrees to Switch. Abilities Include: Imposter, Hadron Engine, Primordial Sea, Download, Schooling, Drizzle,

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#3482]
### Describe the bug

Abilities with that attribute do not apply their abilities when they should if the player initially agrees to switch, then declines when the party screen appears.

Reproduce by Starting with at least two Pokémon with either having an ability that uses PostSummonAbAttr, Press the Yes option, then press X/back.

[Tera Shift is included]

https://discord.com/channels/1125469663833370665/1263401058223390753 This Bug as reported on Discord.

### Expected behavior

I expect the ability to be applied if the player backs out of switching.

### Screenshots / Videos

https://github.com/user-attachments/assets/786948c3-2d44-41a7-be02-318cf35c4b14

[
![Screenshot (241)](https://github.com/user-attachments/assets/f826046b-6bef-45b4-9881-c5d731184b49)
![Screenshot (242)](https://github.com/user-attachments/assets/0de3afcf-7349-4337-9c55-109fa8ad5a18)
](url)

### What OS did you observe the bug on?

PC/Windows

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

### Additional context

Currently Skill Swap does not reapply some swapped abilities. Changing how it works here might fix that. 
https://discord.com/channels/1125469663833370665/1261931153959686165

Sometimes PostSummonAbAttr abilities sometimes fail to redeploy on reload
(Summoning abilities don't activate when reloading a session)
https://github.com/pagefaultgames/pokerogue/issues/1005

**Comment by Snailman11** [comment]
Hadron Engine, also mentions reload https://github.com/pagefaultgames/pokerogue/issues/1688 (Hadron Engine does not activate if you exit out of switch menu)

**Comment by PigeonBar** [comment]
Updating this to include Forecast: https://discord.com/channels/1125469663833370665/1126338176659763210/threads/1289916179627905105
