### ISSUE TITLE
[Bug] Sturdy proc notification when Quick Claw procs

### ISSUE THREAD

**Issue by ItsFrankieD** [pagefaultgames/pokerogue#3496]
### Describe the bug

I'm experiencing this on a Mega Latios fused with an Archaludon. The Mega Latios has Tinted Lens, and the Archaludon has Sturdy. Any time there's a Quick Claw proc, the Sturdy notification slides in from the left as if I survived a would-have-been OHKO.

### Expected behavior

For the ability proc notification to not appear.

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Firefox

**Comment by Snailman11** [comment]
https://github.com/user-attachments/assets/4301ca0a-2892-4db3-9e02-a0569491d7d7

![Screenshot (278)](https://github.com/user-attachments/assets/fc0d8785-d028-474d-8de4-9717669b889f)

**Comment by Snailman11** [comment]
https://github.com/user-attachments/assets/f12ffcd5-1daf-4b19-b14e-bc2fbc0b3b48
