### ISSUE TITLE
Self reload on ios safary

### ISSUE THREAD

**Issue by Damecek** [pagefaultgames/pokerogue#3526]
### Describe the bug

Hi I play this always on my iPhone. The webpage is stored on my desktop as an app. The higher level I am more frequently the game crashes to white screen and self reload. Lately it happens always I switch apps. This was not happening on lower levels. 

### User data export file

[sessionData_Damecek.txt](https://github.com/user-attachments/files/16594610/sessionData_Damecek.txt)

### Expected behavior

The games should not reload on itself. 

### What OS did you observe the bug on?

iOS

### Which browser do you use?

Safari

### If other please specify

Stored as app on desktop

**Comment by flx-sta** [comment]
This is mostly out of our control. People reported better performance if they request “desktop site” inside the browser.

we are working actively on optimizing the memory/CPU usage of the game.
