### ISSUE TITLE
[Bug] Stuck in menu after exporting data

### ISSUE THREAD

**Issue by MokaStitcher** [pagefaultgames/pokerogue#3533]
### Describe the bug

After exporting game data from the Manage Data menu, the cursor won't move anymore and the menu can't be closed
Exporting session data rather than game data works fine

### Expected behavior

After downloading the file we should get control back

### Screenshots / Videos

(sound on to hear the sound effects when i attempt to move my cursor or do anything)

https://github.com/user-attachments/assets/df71b1e1-878d-46c6-83c9-ea37e7c93e42

### What OS did you observe the bug on?

Mac/OSX

### Which browser do you use?

Firefox

### Additional context

I've exported my data a lot of times in the past and it always worked fine, last time I did it was on July 7th.
(It's possible that I always closed the game right after exporting and never noticed the issue, but unlikely)

**Comment by flx-sta** [comment]
I can confirm this issue. Happens on live and beta

**Comment by frutescens** [comment]
Fixed! Thank you for reporting this.
