### ISSUE TITLE
[Bug] Sacrificial moves not activating PostFaintAbAttr

### ISSUE THREAD

**Issue by torranx** [pagefaultgames/pokerogue#3548]
### Describe the bug

`SacrificialAttr` and `SacrificialAttrOnHit` do not proc `PostFaintAbAttr` when:
- The Pokemon using the sacrificial move hasn't taken any attacks yet hence the ff code does not run
```ts
if (pokemon.turnData?.attacksReceived?.length) {
      const lastAttack = pokemon.turnData.attacksReceived[0];
      applyPostFaintAbAttrs(PostFaintAbAttr, pokemon, this.scene.getPokemonById(lastAttack.sourceId)!, new PokemonMove(lastAttack.move).getMove(), lastAttack.result); // TODO: is this bang correct?
    }
```

### Expected behavior

It should proc abilities extending `PostFaintAbAttr` 

### What OS did you observe the bug on?

Mac/OSX

### Which browser do you use?

Chrome

**Comment by DayKev** [comment]
You mean like, if a Primal Kyogre used Memento as the first move of the battle, its `PostFaintClearWeatherAbAttr` (which extends `PostFaintAbAttr`) wouldn't get run? Is this specifically for only enemy Pokémon?

**Comment by torranx** [comment]
> You mean like, if a Primal Kyogre used Memento as the first move of the battle, its `PostFaintClearWeatherAbAttr` (which extends `PostFaintAbAttr`) wouldn't get run? 

yes

> Is this specifically for only enemy Pokémon?

I dont think so, player should be affected too

**Comment by DayKev** [comment]
I tested it with, well, the scenario I mentioned and the weather cleared properly after I swapped into my reserve Pokémon. I think for players (and enemy trainers?) the bug is bypassed because of the switch, but for wild Pokémon there wouldn't be any switch/return/whatever phase (which recently was changed because of... this bug I guess?) meaning that's the only bugged scenario now?

**Comment by DayKev** [comment]
```ts
const overrides = {
  MOVESET_OVERRIDE: [Moves.MEMENTO, Moves.SPLASH],
  OPP_MOVESET_OVERRIDE: Array(4).fill(Moves.SPLASH),
  STARTER_FORM_OVERRIDES: {[Species.KYOGRE]: 1},
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```
Chose Kyogre and Shuppet from starter select screen.

https://github.com/user-attachments/assets/0b2607dc-f6b5-49eb-8df2-d87c41935fe0

No bug.

**Comment by torranx** [comment]
Tested once again, confirmed that abilities with `PostFaintAbAttr` does not proc with said scenario (try logging to console inside:

```
if (pokemon.turnData?.attacksReceived?.length) {
      const lastAttack = pokemon.turnData.attacksReceived[0];
      applyPostFaintAbAttrs(PostFaintAbAttr, pokemon, this.scene.getPokemonById(lastAttack.sourceId)!, new PokemonMove(lastAttack.move).getMove(), lastAttack.result); // TODO: is this bang correct?
    }
```

In your replication, the weather disappeared because the `PreSwitchOutClearWeatherAbAttr` procced

**Comment by DayKev** [comment]
Which is like I said, the bug gets bypassed because it's a trainer Pokémon that fainted and not a wild Pokémon that fainted.

**Comment by torranx** [comment]
mb totally forgot about your 2nd comment - then this comment is true

**Comment by Snailman11** [comment]
This is a wild Battle

https://github.com/user-attachments/assets/a562eb2a-0ae8-4520-8c3f-b1ce1325c91b

Seems Fixed
