### ISSUE TITLE
[Bug] Aerilate + population bomb results in only one hit vs ghost types

### ISSUE THREAD

**Issue by Fubs** [pagefaultgames/pokerogue#3570]
### Describe the bug

I have a pokemon with the ability Aerilate and the move Population Bomb.

https://bulbapedia.bulbagarden.net/wiki/Aerilate_(Ability)
https://bulbapedia.bulbagarden.net/wiki/Population_Bomb_(move)

Population Bomb is a normal type move that hits 10 times. Aerilate should make Population Bomb become flying type and receive a 20% power boost. However, when attacking a ghost type pokemon, it seems that only the first hit of Population Bomb works correctly. The target will take one hit, and then the move will simply end.

### User data export file

[data.txt](https://github.com/user-attachments/files/16635952/data.txt)

### Session export file

[session.txt](https://github.com/user-attachments/files/16635961/session.txt)

### Expected behavior

A pokemon with the abiility Aerilate using Population Bomb against a ghost type target should result in up to 10 hits. All 10 hits should be considered a flying-type move affected by both STAB and the 20% boost from Aerilate.

### Screenshots / Videos

https://github.com/user-attachments/assets/b9ee14c6-2b78-4371-8e75-534935710064

### What OS did you observe the bug on?

Linux

### Which browser do you use?

Firefox

**Comment by Snailman11** [comment]
Link to Discord's bug report (Aerilate, Population Bomb Bug) https://discord.com/channels/1125469663833370665/1254821254490361989

**Comment by frutescens** [comment]
Should be resolved with the next release. Thank you for reporting this.
