### ISSUE TITLE
[Bug] Missing/Gone health-bar UI

### ISSUE THREAD

**Issue by flx-sta** [pagefaultgames/pokerogue#3571]
## Describe the bug

Sometimes the health-bar UI (including the type and all) is misplaced in `beta` right now

This should be fixed before the release!

## Reproduction Steps

> Reported by @DayKev 
- just switching your pokemon back and forth will eventually trigger it

## Expected behavior

The UI element should move back into screen properly

## Screenshots / Videos

![image](https://media.discordapp.net/attachments/1176874654015684739/1273935510808690741/image0.jpg?ex=66c06c66&is=66bf1ae6&hm=0cfa84dd15f5c77ef666d974da198749e0930c038e7c74c54d331a6581d67107&=&format=webp&width=1682&height=1116)

## Additional context

Discord-Messages:
- https://discord.com/channels/1125469663833370665/1176874654015684739/1273930570824552530

**Comment by CodeTappert** [comment]
I have mentioned this several times already. :D

**Comment by flx-sta** [comment]
> I have mentioned this several times already. :D

You have an guaranteed reproduction guide? Or just the same that @DayKev mentioned?

**Comment by CodeTappert** [comment]
> > I have mentioned this several times already. :D
> 
> You have an guaranteed reproduction guide? Or just the same that @DayKev mentioned?

playing on steam deck

**Comment by DayKev** [comment]
Fixed with #3588
