### ISSUE TITLE
[Bug] Missing type-hints for immunities

### ISSUE THREAD

**Issue by flx-sta** [pagefaultgames/pokerogue#3573]
## Describe the bug

See screenshots.
Type-hints don't display correctly

## Expected behavior

the type should be "grayed out" since it doesn't affect the enemy pkm (unless some special conditions are met)

## Screenshots / Videos

![image](https://media.discordapp.net/attachments/1273029028210671748/1273821779990806650/image.png?ex=66c0027a&is=66beb0fa&hm=3bb230b3c9fe48aa7d08ee7b2bc815ecf91cb48f5a745549a673c91d3861533e&=&format=webp&quality=lossless&width=1884&height=1116)

### Additional context

Discord Messages:
- https://discord.com/channels/1125469663833370665/1273029028210671748/1273821780175229021
- https://discord.com/channels/1125469663833370665/1176874654015684739/1273963881718616076
- https://discord.com/channels/1125469663833370665/1176874654015684739/1273964747804377088
- [possible fix - by allen](https://discord.com/channels/1125469663833370665/1176874654015684739/1273994191491563521)

**Comment by CodeTappert** [comment]
Also Dragon on Fairy

![image](https://github.com/user-attachments/assets/acd739af-0730-4d7d-80b5-438a3f442c10)


So maybe all immunities?

**Comment by CodeTappert** [comment]
![image](https://github.com/user-attachments/assets/e9976517-5012-4801-927d-de0957cbcdb4)
Psycho on Dark

**Comment by CodeTappert** [comment]
Electric on Ground

![image](https://github.com/user-attachments/assets/4725b2c8-c93b-42bc-ba4f-1b5391ef5728)

**Comment by CodeTappert** [comment]
Did someone actually started working on this? If not i can give it a try

**Comment by flx-sta** [comment]
> Did someone actually started working on this? If not i can give it a try

Is did but got stuck on writing test coverage. Unfortunately I’m busy with getting ready to fly back to the US
