### ISSUE TITLE
[Bug] Turtwig Icon in starter-select is broken 

### ISSUE THREAD

**Issue by flx-sta** [pagefaultgames/pokerogue#3574]
## Describe the bug

Turtwig icon in starter-select is RED and something

## Expected behavior

It should display properly and not as RED

## Screenshots / Videos

![image](https://media.discordapp.net/attachments/1273029028210671748/1273034055201591308/image.png?ex=66c0709a&is=66bf1f1a&hm=2f0936094534dd37a91e1dfd9cfe00c154fadfef31f01930e08e1064b68f0544&=&format=webp&quality=lossless&width=1634&height=522)
![image_2](https://media.discordapp.net/attachments/1273029028210671748/1273944841126019072/bug_grafico_beta_pokerogue.png?ex=66c07516&is=66bf2396&hm=19c84eec57f132eb25345aa2a85c1a335052f3c1c988eca06e415617c5ded5c7&=&format=webp&quality=lossless&width=1632&height=1116)

## Additional context

Discord-Message:
- https://discord.com/channels/1125469663833370665/1273029028210671748/1273034055541194752
- https://discord.com/channels/1125469663833370665/1273029028210671748/1273944841306505256

**Comment by flx-sta** [comment]
@Opaque02

**Comment by flx-sta** [comment]
> Opaquer
>  — 
> Today at 3:22 PM
> so for the missing sprite, i made a quick hack for the spritesheet to try and fix it - here's the spritesheet along with an image of it before and after in the starter select - it seems to work based on my 30s test, but i don't have time to fully test things out and see if it's actually working, so i'm putting this here so someone else can pick it up and test it and make a PR for it 🙂
> ![image](https://github.com/user-attachments/assets/17206655-84d6-4297-ac7a-6093b59a2240)
> before (current beta):
> ![image](https://github.com/user-attachments/assets/45a98c44-ca72-47da-b8a4-eac947d36429)
> after:
> ![image](https://github.com/user-attachments/assets/0a6f6f67-3ad0-40a2-83c3-923fdd8c0e63)
>

**Comment by Opaque02** [comment]
Found some info - see [here](https://discord.com/channels/1125469663833370665/1273029028210671748/1273995202109112360) for info and fix, [here](https://discord.com/channels/1125469663833370665/1273029028210671748/1273995440253177957) for a screenshot of the current beta and [here](https://discord.com/channels/1125469663833370665/1273029028210671748/1273995471614119948) for a screenshot of the fix. 

This has not been extensively tested - the spritesheet was manually created and tested in about 30 seconds total, so I haven't done extensive testing, but that's all I can do tonight. More info [here](https://discord.com/channels/1125469663833370665/1273029028210671748/1273995744910639246), along with the next few messages. Someone from the discord is going to make a fix and post it once tested if it's working - see messages too

**Comment by chaosgrimmon** [comment]
Also. The variant iconsheets were not changed by the variant PR.

This causes

![Image](https://github.com/user-attachments/assets/472d6c4e-e4d9-4517-9ee1-225135e29f1e)

![Image](https://github.com/user-attachments/assets/4e3afa6c-e301-408d-879e-f2732adefbc5)

**Comment by chaosgrimmon** [comment]
I'm working on it now, but couldn't get beta footage of it until recently due to the tutorial softlock.

**Comment by chaosgrimmon** [comment]
https://github.com/pagefaultgames/pokerogue/pull/3579 merged~
