### ISSUE TITLE
[Bug] IV Scanner not showing IVs

### ISSUE THREAD

**Issue by pguilimaf** [pagefaultgames/pokerogue#3592]
### Describe the bug

I'm currently playing on Endless mode, and got an IV Scanner. When I used it on a double battle, it showed just one IV of a pokémon and none on the other. Now, it doesn't show any IV on single battles.
![image](https://github.com/user-attachments/assets/0306da2e-af67-4dc3-8921-8ce03bac86c0)

### Session export file

@patapancakes 
[sessionData_DelitaCabureh.txt](https://github.com/user-attachments/files/16645777/sessionData_DelitaCabureh.txt)

### User data export file

@patapancakes [data_DelitaCabureh.txt](https://github.com/user-attachments/files/16645779/data_DelitaCabureh.txt)

### Expected behavior

I expected to see the 2 IVs of the pokémon, but they didn't show. And the only IV that showed the range was Best and colored orange.

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Opera

### If other please specify

I use opera, but I play on pc.

**Comment by innerthunder** [comment]
should be fixed by #3616
