### ISSUE TITLE
[Bug] game not loading after new update

### ISSUE THREAD

**Issue by AveragePKMN** [pagefaultgames/pokerogue#3640]
### Describe the bug

After i got the latest update today i've been dying to play but my game is stuck on a screen with an empty text box
see here
![Screenshot (57)](https://github.com/user-attachments/assets/9ca4a678-b593-42c8-a1af-473774cd5f06)

### Expected behavior

i was expecting for the game to actually load so i could play

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Other

### If other please specify

Offline mode app

### Additional context

Only started happening after the latest update. Options just simply don't load

**Comment by kurguri** [comment]
me either , have you tried only used bulbasaur to start classic ?  will it stuck too?

**Comment by AveragePKMN** [comment]
No I have never cheated, btw it doesn't load the options to select 'New game' 'Load game' 'Continue' or 'Settings'

**Comment by kurguri** [comment]
So you mean you can't even open the home screen in offline mode properly? As far as I see,it really happens more in offline version after this update, and the only way to avoid this is to play online until now

**Comment by AveragePKMN** [comment]
Welp, that sucks. i guess i'll have to take a lil break until the problem is solved

**Comment by flx-sta** [comment]
Feel free to request the issue to be reopened if the issue persists
