### ISSUE TITLE
[Bug] Unlocked egg moves missing

### ISSUE THREAD

**Issue by helena-muniz** [pagefaultgames/pokerogue#3642]
### Describe the bug

I had unlocked dragon energy for a Palkia, but it's not displayed on my move list anymore. It was replaced by origin pulse, a move i had not unlocked and wasn't displayed before.

### Session export file

U2FsdGVkX192xh/2+xKWcOhHO2+LYhsYykN1/njhX59axZzvy5v6keHAM1gCp76oQtXlXZb/HpHDp1mRchkSgO5ZdVxyUrw61DRZVAzkIk8qEy0vMVjz9c7vq2i0QFb5iqjRUZow5U2vs//zt5cOPC2tlBu7HNyIk8SdzqkJf7PCK7C3KUkPXlM2JuZX5GKnRzdcgg6B6Am0818qyaPVvlaNVRyf13Mitv3mWf2rkWonbo+106+WoLlV8/iLxSNBlpCaB47GWKSx/y5v25oJHOYBeMN6nZhIR7IRcFG6umE9KjWBlGk3S+v9XIKZzsS549BPVFBlZENJaimFXPlhh94Sc2LR1Hw9PkbCBolZ8IGvJjcdc8EbiuEau09wITwtasA4XwH9Chro5KUPmqTqE+z4TnLSGe7zoCyKSVqXBMuwBCXB51bXi2DQd6ZnPCFi1v/9DliKdNx+bR2BzqbzyiOg3c7k2GlniM8ESaSZC9eSmcZlRgss+ajz/NpdNTcDELFsk0TkxdNlL72vklvM5BzTu6r3sn4GbyGo1jcrHeBCZ10ofTPc1uSPrSPkjDp+xB79YgyqLHaiLAuuMPYV0VJYBg4F0paJaNp1Ul2JtE1rIFD9XSP6piWSs/BO8xioqm7dvFKQDiNlBRyxBEgB44jB49JT3YOJfZLbOQr5+aXvWFfW7bSuluNunP8cbETR7QDAOyxCQJyvYarXA9YKmcDZVrP1tJuYriE966aoKNJmYpU5F7WxHjw+k58hfa+mUqNHMWB7DECvYH2CfXAlLg4j/n+yjR4bmKe8abs/NAQPrVpsfAZ382mNRvcS2xVQRzVbNec4EsdVJ8i2aMHLJX+rsmY0d0DNui2dc/nUFW4bNyVj70KnQEFnPCQkFW6X9vceuDuVN9bZ5mikRE7K7ytBDPX23zurlKJe+0QqsRmGP9WYr3zn6sarqHGeowzhHOvorcPBB3mqsNmWWG01Fok8uUX6dA6RcKS1IJSVyu/5Oydgf6MrKRCDNop3JCItL8Ss0IWMNAr7Ypx6NHrf/m8kKzCnphPRQZ784bpTkATVI31MKixqzQv28FGsdCSFz+SiViagu6aUTfNeqgzmC6hOBogIJjI/5i0iyyGJOV7wWklHgyMKnG1WCsTjq++94jlKg2kEcPUNC2bCRp7BivrohyVEjHxP7I8Seh9liaYYSVvGiMAeJr3bsBHxa1aRXiFprB3WnyiveL3PtuapIKn6h+mNvNjgii6ZUzZOwSNLr5xnjGKhSjaDjx6mjQOu81xCpkuS7b71aLQcesUkCL/CiiHC3irdjpd4bIhdNQ1WU0k4KQKDhv5NW8sIuWmf5GbJomhXJgvLE7LNopZ6Iry30m2a3Z1Yp4hq5OYbF1Hi9So5hI5k1YPlwkU5WbsTJPAeG3Pn46da8+lnF5Y5rjBah21ue22tpPiB72T5qifFIzSkbUseEqLpA0Cf6FdmIPsHWalpPnjhVEmhrum0xf+Kkh7pcnIh8VvF9Rkzh5mG1zykeuDrMbqc7cx23kK87IsboNl1T40apTo22XGNb8YyI1+ZVkVVtPumPihcJqQQNaHWvGrHlWxwQRCMwQOW+YAtkMycGLTT0RjQLwXrBaFDvY1g6/FUfr1jB88hwIf6yyrZNLkuuBwbtoS6wRtkKrhdVDUH5Way8o1d6A1J2rV93Zn8rrpPHQKirwwdg+2+nFhIFraEtMGiEyImYjSktAf/mwe7HeVTozdyV5OHHzScNgyVoCQBLG7GrnBk0drueCilHg5a86h/xVSzEw/3E26arbhKo+172CTN1+BOk2O96ImuFeUPyCq9J5CBTBeukXf0Rg1auhlVTvpOY29gc/1Cpwn2ct1fHaAsT/qLx74yQX7xVujL+U9n0LbDPF6tGEYR0so+so2zBoVP2ek2MMyfz596GcY8okQOZRuipNsxzwzUQoBHTxjkvsw8Ml7NPcREbGDkQDgFxzyH9xHPpQdnGstEyezwIliuyZHHARDBkKT0VGbC00X8iGLAOeASficdvbBe/+dJWC3Om85qN9Xsx30dvJkIV87LhkC8w9B2WURWSgkCFFM50VAt+d5lKlEayol6oH6022PH2zUZtyQmvcEkVcGKSBBDrXdtsPvWHRYIBEjW67pg6qNkdKz8e9ZMToK+N73wCY0ZcYSv+hgCYT/nXc7cmoZw+sVWdwD2fdvf46GAFYkf5DsV5f2JavbdaxmOYnHmxGzdn2Ni5ElblKSrWa5l6IAuBavcAsMldlRmwHnuYdniL0bfdjYyarVo3XjQRZ55l9iEttW9Y219K4Tiu0YtZTiNylGgTcRXQtAeAWZOYHsK/AtXwDDBFsngknGL6uToL48oOCuqBB0XN3/Mkbzx+FxpHF3xGssaZj7uETLtS94iNDDV+yiHofeLwhkM7E4RBgjje0+NEb7tPtFHWSf9XhZLS/WIXw==

### User data export file

[sessionData_DiHelena.txt](https://github.com/user-attachments/files/16661755/sessionData_DiHelena.txt)

### Expected behavior

Unlocked moves should remain unlocked (?)

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Firefox

**Comment by ElizaAlex** [comment]
It appears that Palkia was changed to now get Origin Pulse _instead_ of Dragon Energy. Egg move updates happen fairly frequently, and whenever a move you have unlocked is changed it is automatically replaced by the new move.

**Comment by frutescens** [comment]
Thanks @ElizaAlex for answering! For future reference, the channel #balance-changelog on the PokeRogue Discord server will post any future Egg Move-related changes.
