### ISSUE TITLE
[Bug] exp gain skip is ignored

### ISSUE THREAD

**Issue by flx-sta** [pagefaultgames/pokerogue#3644]
>  [Original Discord report](https://discord.com/channels/1125469663833370665/1274758406540099634)

## Describe the bug

The Exp-Gain `Skip` settings seems to be broken/not respected anymore

## Expected behavior

When settings `Exp Gain: Skip` it should skip the animation for exp-gain completely

## Screenshots / Videos

https://github.com/user-attachments/assets/9f7fca2c-b7f4-4e30-a6d0-01b3c7eb34f9

**Comment by Snailman11** [comment]
Link to Discord's Bug Report (skip exp bugged)
https://discord.com/channels/1125469663833370665/1239417534445387827
