### ISSUE TITLE
[Bug] Costume Pikachu shouldn't trigger or accept Mega Mushroom

### ISSUE THREAD

**Issue by Anusien** [pagefaultgames/pokerogue#3651]
### Describe the bug

I had a party consisting of:
* Munkidori
* Lucario
* Swellow
* Tandemaus
* Pikachu (Cool Cosplay)
* Ninetales

I got offered a Max Mushroom in the shop. The game correctly warned me that it wouldn't do anything before applying it to other monsters. But it let me apply it to PIkachu, which did nothing. The game let me enable or disable the mushroom, but I could not move it.

### Session export file

[sessionData_Anusien.txt](https://github.com/user-attachments/files/16665475/sessionData_Anusien.txt)

### User data export file

[data_Anusien.txt](https://github.com/user-attachments/files/16665478/data_Anusien.txt)

### Expected behavior

The game should not allow you to apply Max Mushrooms to costume PIkachu. Or if it does, it should allow you to move it.

In a similar vein, having costume PIkachu alone shouldn't be enough to make the relevant items even appear in shops.

### What OS did you observe the bug on?

Mac/OSX

### Which browser do you use?

Chrome

**Comment by LilyAlternis** [comment]
Thanks for making the post! 
It's a known thing in the discord although I think its time it gets fixed so it doesn't drop although it may take time to find a way to do it.
I guess this also applies to the thunder stone.

**Comment by Snailman11** [comment]
I link #1785

**Comment by frutescens** [comment]
TY for reporting. The fix will be in the next update.
