### ISSUE TITLE
Lightning rod not working as standard.

### ISSUE THREAD

**Issue by scrazerax** [pagefaultgames/pokerogue#366]
Had a cubone with the lightning rod ability against a pikachu. Pikachu used thundershock and it got absorbed by lightning rod but then cubone got paralyzed, when its secondary effects should not occur as the move got absorbed by lightning rod

**Comment by bennybroseph** [comment]
Cannot Reproduce

https://github.com/pagefaultgames/pokerogue/assets/13838608/cc697ac5-c0a3-4426-be9e-defe42577d4e

**Comment by Madmadness65** [comment]
Cannot reproduce. Are you sure it wasn't Static proccing from a physical move against Pikachu?
