### ISSUE TITLE
[Bug] Lumina Crash ignoring SpDef drop

### ISSUE THREAD

**Issue by veganusaur** [pagefaultgames/pokerogue#3671]
### Describe the bug

When I use lumina crash on cresselia it appears that every time it does the same damage on subsequent turns despite the -2 SpDef drop.

### Expected behavior

I would expect a noticeable difference in damage

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Chrome

**Comment by torranx** [comment]
Tested and can't replicate. If encountered again, please open a new issue and provide session data.

**Comment by veganusaur** [comment]
Where is the session data saved or how do you log it?

**Comment by torranx** [comment]
> Where is the session data saved or how do you log it?

Menu > manage data > export session data > select save slot of where the bug happened.

note that the filetype is not supported by github so you can't post it here. but you can go ahead and open a bug report on discord and ping me there

**Comment by veganusaur** [comment]
posted it a few minutes ago in discord, but don't see you in the @ on discord
