### ISSUE TITLE
[Bug] Disguise Opens Up a Parallel Universe when Mimikyu faints from the 1/8th Damage on Transformation to Busted Form (Doubled Shop, Consecutive Switch Offers, Sprites Stay on Screen)

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#3676]
### Describe the bug

https://discord.com/channels/1125469663833370665/1275611725387010180
Link to Videos and Discord bug report where it was first reported

1. Find a wild Mimikyu
2. Get its health to <1/8th while keeping its disguise intact.
3. Break the Disguise once its health is <1/8
4. Profit twice with double shop with real items

-Sprites stay on screen; the HP bar obscures the real one, and Pokémon sprites persist through the next battles
-Shops are doubled only for the wave when this was performed
-Saying yes to switching lets you switch twice (consecutively)
-Trainer battles softlock with the player unable to execute a move if the trainer has more than one other pokemon in their party
-Suppressing Disguise with Turboblaze prevents this bug from triggering.
-Resolved when reloading

### Expected behavior

Mimikyu should faint gracefully and not do that when fainting from Disguise

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

**Comment by Snailman11** [comment]
Might be related to
https://github.com/pagefaultgames/pokerogue/issues/2769

**Comment by torranx** [comment]
@DayKev
