### ISSUE TITLE
Fake Out fails when a switch is forced

### ISSUE THREAD

**Issue by Scepty-SSB** [pagefaultgames/pokerogue#368]
When a pokemon is switched out by Dragon Tail (and possibly other forced switch moves, I haven't tried all of them) and the player  then selects fake out on the switched-in pokemon, the move will fail despite having been selected on the pokemon's first actionable turn.

**Comment by Eridanus91** [comment]
I can confirm it also fails if you U-turn into a Fake Out user.

**Comment by Eridanus91** [comment]
> > I can confirm it also fails if you U-turn into a Fake Out user.
> 
> How recently have you had this happen? A fix was pushed out for this recently

It's been a while, so I guess it was fixed.

**Comment by Scepty-SSB** [comment]
> How recently have you had this happen? A fix was pushed out for this recently

Happened to me 2 days ago
