### ISSUE TITLE
[Bug] Arena Trap, Shadow Tag and Magnet Pull Lingers After a Pokemon has been Forced Out

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#3713]
### Describe the bug

Link to Discord's Bug report (Shadow Tag - 2 bugs in double battles)
https://discord.com/channels/1125469663833370665/1275424376103374968/1275973836453449889

-Videos are too big so they're on Discord

1. Enter a Double Battle where one of the pokemon active has Arena Trap, Shadow Tag, or Magnet Pull
2. Have one of your pokemon use Dragon tail, Circle Throw, or roar on the pokemon with the above ability
3. Attempt to run away the next turn with your grounded steel type (Not ghost type)

-This does not occur if the pokemon with that ability has fainted, rather than been forced out.
-This could apply if that pokemon used U-turn, Volt Switch, etc.

### Expected behavior

The player is freed from trapping abilities after phasing that pokemon and can run away or switch freely.

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

**Comment by Snailman11** [comment]
Whether this applies to abilities outside of Arena trap, etc needs to be tested

**Comment by Snailman11** [comment]
**Includes Dazzling**
https://discord.com/channels/1125469663833370665/1289421987390816318

**Comment by Snailman11** [comment]
**Includes Cloud Nine**

https://github.com/user-attachments/assets/3eef4fed-ddb0-4608-870d-ff0233d3e930

**Comment by PigeonBar** [comment]
(The linked PR is meant as a partial fix that only fixes the bug for trapping abilities. The bug will continue to affect other abilities such as Dazzling, so we will eventually also need a fix that is more general but also riskier).
