### ISSUE TITLE
[Bug] Frenzy moves wont stop by paralyze

### ISSUE THREAD

**Issue by allen925** [pagefaultgames/pokerogue#3718]
### Describe the bug

I am guessing it's not just paralyze, but I'll just leave idea here, that frenzy moves like thrash continues after being interrupted by paralyze, which is an incorrect behaving. 
![image](https://github.com/user-attachments/assets/114ef9e2-7fd2-4668-b1fd-e8af83457749)

(but if my PR of rollout non stop got merged, it would be a lot more obvious that if you're paralyze and choose to use rollout, there's a possibility you won't be able to command a long time if pokemon survive. )

https://github.com/user-attachments/assets/18844638-311a-4157-b015-fe0bbc98bd4f

### Expected behavior

stop if paralyzed and maybe other status effects, something like 
```
      .attr(MissEffectAttr, frenzyMissFunc)
      .attr(NoEffectAttr, frenzyMissFunc)
```
but status effect version should trigger

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Chrome

**Comment by Snailman11** [comment]
Check if 
https://github.com/pagefaultgames/pokerogue/pull/3041 fixes this

**Comment by schmidtc1** [comment]
> Does #3041 fix this @schmidtc1

I don't think it does. You likely need to apply the `noEffectAttr` somewhere in `MovePhase` either where status effects are activated or where moves are cancelled in `doMove()`. That's my guess at least
