### ISSUE TITLE
Sp. Atk. IV is not visible after catching when opposing pokémon hold too many items

### ISSUE THREAD

**Issue by dratinyy** [pagefaultgames/pokerogue#377]
![image](https://github.com/pagefaultgames/pokerogue/assets/24292164/dc1989e3-ab6c-403a-9ff7-eb7e5dd0e0d1)

When the opposing pokémon hold too many items, it is no longer possible to read the sp. atk. IV of the pokémon you just caught. Also the Yes/No option for releasing another pokémon is over the ability and nature which makes it harder to read.

Also thanks a lot for this game it's crazy good!

**Comment by Dakurei** [comment]
Fixed
> Ennemy modifiers disappeared after caught

![image](https://github.com/pagefaultgames/pokerogue/assets/8146474/c86854e6-b7f2-4a6d-9371-2f969ac37df9)
![image](https://github.com/pagefaultgames/pokerogue/assets/8146474/b9e8c349-39c6-4d41-a6f6-7bd2d2080c7d)
