### ISSUE TITLE
[Encounter] Global Trade System (Common)

### ISSUE THREAD

**Issue by ben-lear** [pagefaultgames/pokerogue#3812]
### Event Name

Global Trade System

### Rarity Tier

Common

### Waves

10-150

### Description

It's the GTS. 3 random (not-biome specific) pokemon of a set starter egg tier (evolved based on level) are provided as options for the player to trade in one of their party pokemon for.

**_The pool of pokemon available to spawn from this event is anything that is not classified as paradox/subLegendary/legendary/mythical._**

### Biomes

CIVILIZATION

### Options offered to the player

- [ ] Check Trade Offers
    - _Choose a Pokemon from your team._
    - _Based on the BST of the Pokemon selected, 3 random Pokemon (up to -100/+100 BST) will be offered to choose from for the GTC swap._
    - _If the Pokemon the player selected is a legendary/mythical the ONLY trade options that will be shown are from the following custom pools, based on generation:_
      - Gen 1: Rattata, Pidgey, Weedle
      - Gen 2: Sentret, Hoothoot, Ledyba
      - Gen 3: Poochyena, Zigzagoon, Tailow
      - Gen 4: Bidoof, Starly, Kricketot
      - Gen 5: Patrat, Purrloin, Pidove
      - Gen 6: Bunnelby, Litleo, Scatterbug
      - Gen 7: Pikipek, Yungoos, Rockruff
      - Gen 8: Skwovet, Wooloo, Rookidee
      - Gen 9: Lechonk, Fidough, Tarountula
    - _If the player chooses to swap, the new pokemon will keep all the items of the original pokemon._
    - _Counts as a standard catch_
    - _If the traded in pokemon has passive unlocked, the new pokemon will also have passive unlocked for the run_
    - _If the 3 random Pokemon are undesirable for swapping, the player can back out of the selection and select a new Pokemon from their team (or leave the GTS)._
- [ ] Wonder Trade
    - _Will swap the chosen Pokemon to a completely random species (could be literally anything) with no selection choice._
    - _All items are kept the same, as above_
    - _Counts as catch, as above_
    - _1/128 chance for the Pokemon to be shiny (standard Egg odds), 1/64 chance for the Pokemon to have HA_
- [ ] Trade an Item
    - _Player selects one of the TRANSFERABLE held items on their Pokemon and loses it_
    - _A new item is randomly generated and given to the player based on the tier of the old item_
    - _A Common item upgrades to Great, Great upgrades to Ultra, and so on..._
    - _If an item's tier cannot be found (item doesn't exist in pool, such as Lucky Eggs), it is treated as Great and "upgrades" to Ultra_
- [ ] Leave
  - _no rewards or exp_

**Comment by AsdarDevelops** [comment]
LGTM
