### ISSUE TITLE
[Encounter] The Expert Breeder (Ultra)

### ISSUE THREAD

**Issue by ben-lear** [pagefaultgames/pokerogue#3818]
### Event Name

The Expert Breeder

She's been places, she's even been to Space.

### Rarity Tier

Ultra

### Waves

10-180

### Description

You encounter a Breeder who offers you some rare vouchers if you can beat her challenge. The challenge is: win a battle against the Breeder's team of 3 Pokemon with only a single Pokemon from the player’s team. The Breeder "decides" which Pokemon the player is allowed to use. 

She does this by looking at which PKMN you are __least__ friendly with, arguing that "you need to put more effort in the bond with those PKMN". The 3 Pokemon with the lowest "friendship gained in the run" value on the player's team are offered as choices for who to use in the challenge. Additionally, the amount of eggs that are won from the challenge scale with the chosen Pokemon's BST value.

For teams, check Dev notes.

### Biomes

HUMAN + SPACE

### Biome - Other. Please Specify

SPACE has slightly different variations attached to its behavior.

### Options offered to the player

- [x] Fight with Pokemon 1
    - _The player starts a battle with the single chosen PKMN on their team. They must defeat the Breeder's team_
    - _To add to the risk of this encounter, if the player loses, it is treated as a Game Over and the run ends even though it is only a single Pokemon on their team._ 
- [ ] Fight with Pokemon 2
    - _The player starts a battle with the single chosen PKMN on their team. They must defeat the Breeder's team_
    - _To add to the risk of this encounter, if the player loses, it is treated as a Game Over and the run ends even though it is only a single Pokemon on their team._ 
- [ ] Fight with Pokemon 3
    - _The player starts a battle with the single chosen PKMN on their team. They must defeat the Breeder's team_
    - _To add to the risk of this encounter, if the player loses, it is treated as a Game Over and the run ends even though it is only a single Pokemon on their team._ 

#### Reward

Based on the BST of the PKMN you chose to defeat her, you get the following amount of eggs.

The eggs being rewarded are decided by a formula that grants "points":
- 1 point is granted for each 20 BST below the box legendary mark (680 BST). Minimum 1 point.
- 2 points are granted for each starter cost tier below tier 7. Minimum 0 point (tier 7). Max 12 points (tier 1).
- It caps at 30 points. For each 6 points, the player is given a rare egg. The rest are given as common eggs.

This is what it looks like in practice:

![image](https://github.com/user-attachments/assets/c3fa7deb-9de7-47f1-9195-86d1ae58c774)

### Explanation/Notes on Design

Playing on the Breeder theme, Baby Pokémon, Breeders giving eggs and on the Breeders in Space joke.

### Notes to Artists

Would probably need a Breeder in a spacesuit. Or not. I don't know.

### Notes to Developers

Evolutions must be hardcoded:
- Wave 30+: Evolve all Cleffa, Elekid, Magby... to their 2nd stage
- Wave 45+: Evolve the likes of Riolu, Mantyke, Munchlax.
- Wave 60+: Fully evolve everything 

#### Space Breeder

When found in Space, these are the Breeder's three Clefables:
Winning this fight (it's a 1v3) rewards the player with a _**minor**_ achievement: "Breeders in Space!"

- Clefable ("Ace Clefable"):
    -  x6 Protein + x1 Carbos
    - Shiny: No (Base form)
    - Tera: Steel
    - Adamant Nature
    - Ability: Magic Guard
    - Perfect IVs
    - Moves:
        - Meteor Mash
        - Fire Punch
        - Ice Punch
        - Thunder Punch

- Clefable 2 ("Clefaboulest"):
    - Shiny: Yes (T2 shiny)
    - Modest Nature
    - Ability: Magic Guard
    - Perfect IVs
    - Moves:
        - Moonblast
        - Mystical Fire
        - Ice Beam
        - Thunderbolt

- Clefable 3 ("Clefable the Great"):
    - Shiny: Yes (T3 shiny)
    - Nature (-Atk +Def)
    - Ability: Unaware
    - Perfect IVs
    - Moves:
        - Tri-Attack
        - Stored Power
        - Take Heart
        - Moonlight

#### If not in Space

This is also a 1v3

Her first Pokémon is always a (non-shiny, important to lock it as such) Clefable:

- Clefable ("Ace Clefable"):
    -  x4 Protein
    - Adamant Nature
    - Ability: Magic Guard
    - Perfect IVs
    - Moves:
        - Meteor Mash
        - Fire Punch
        - Ice Punch
        - Thunder Punch

Her 2nd Pokémon is pull from this list:

- Snorlax
- Blissey
- Magmortar
- Electivire
- Lucario
- Roserade
- Toxtricity
- Mr. Rime

Her 3rd Pokémon is a random one from this list:

- Raichu / A. Raichu
- Jynx
- Hitmonlee / Hitmonchan / Hitmontop
- Wigglytuff
- Azumarill
- Wobbuffet
- Chimeco
- Sudowoodo
- Mantine

**Comment by AsdarDevelops** [comment]
@ben-lear "Friendship-gained", if too hard to implement or you feel it's not worth the hassle, can just be "lower 3 BST".

She should not give vouchers, but eggs. She should give vouchers only when eggs wouldn't fit.

If these finally cannot be same-species eggs, the maths should be adjusted so the lower end seems more benefit:

- 1 point is granted for each 15 BST numbers below the box legendary mark (680 BST). Minimum 1 point
- 2 points are granted for each starter cost tier below tier 7. Minimum 0 point (tier 7). Max 12 points (tier 1).
- It caps at 40 points. For each 6 points, the player is given a rare egg. The rest are given as common eggs.
