### ISSUE TITLE
[Bug] Possible crashes when running from Mystery Encounters

### ISSUE THREAD

**Issue by ben-lear** [pagefaultgames/pokerogue#3826]
### Describe the bug

What the title says. Here's a screenshot.

![image](https://github.com/user-attachments/assets/622e784d-7b18-4d71-bc0e-d2f908f5e0ad)

### Expected behavior

I shouldn't be allowed to run from Marley, she's a trainer.

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Chrome

**Comment by AsdarDevelops** [comment]
I can't close the issue myself, but the bug is fixed.

**Comment by ben-lear** [comment]
Fixed
