### ISSUE TITLE
[Bug] Shedinja Doesn't Have Access to Nincada's Egg moves by Memory Mushroom/Relearn.

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#3842]
### Describe the bug

Discord Bug Report: (Shedinja cannot learn egg moves from mushroom, even if nincada was brought from starter screen)
https://discord.com/channels/1125469663833370665/1277793919677235254

-Evolve a Nincada with egg moves unlocked into Ninjask and Shedinja at level 20, observe that Shedinja can't remember them with a Memory Mushroom

https://github.com/user-attachments/assets/bd743f31-328a-4a8a-9195-305a979f9e61

### Expected behavior

Shedinja is able to relearn Nincada's Egg moves

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

**Comment by ckincaid17** [comment]
I'm going to work on this 🙂
