### ISSUE TITLE
[Bug] Decorate Does not Bypass Protect

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#3843]
### Describe the bug

> Decorate raises the target's Attack and Special Attack stats by two stages each. Unlike most moves, it bypasses moves like Protect, Detect, and even Max Guard to affect the target but is blocked by Crafty Shield. It cannot affect a target that has a substitute or in the semi-invulnerable turn of a move.
- Bulba 

https://replay.pokemonshowdown.com/gen9doublescustomgame-2188649676

### Expected behavior

Decorate should Bypass Protect

### Screenshots / Videos

https://github.com/user-attachments/assets/8c748806-9b1f-424e-8123-19c84a5dc7a1

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

**Comment by frutescens** [comment]
Fixed. Will be in the next release. TY for reporting.
