### ISSUE TITLE
[Bug] Cursor Does not Default to the First Move slot after a Pokemon is Switched-in, Does not Default to "Fight"

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#3922]
### Describe the bug

-The cursor remembers the move option that was last moved to, and saves it for the pokemon that's switched in.

-The cursor defaults on the Pokemon option after a switch, rather than the Fight option.

Link to Discord Feature Vote where this was brought up: ([QOL] Cursor Memorization Issues)
https://discord.com/channels/1125469663833370665/1239812778345107486

### Expected behavior

![PXL_20240830_195028271](https://github.com/user-attachments/assets/104f2579-42ff-424f-a45d-e01e56daf2a7)
![PXL_20240830_195047681](https://github.com/user-attachments/assets/cdff94c9-3f28-45a2-8ab5-e125805201cc)
![PXL_20240830_195051919](https://github.com/user-attachments/assets/37a909d1-2c01-4956-8edf-a268088276a5)

### Screenshots / Videos

https://github.com/user-attachments/assets/b2486cbc-61a7-49d4-be3c-9e032965afda

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

### Additional context

The cursor should continue to remember the last move used by a mon, and save that for the next turn (it does this currently)

**Comment by frutescens** [comment]
Hopefully fixed in the next update!
