### ISSUE TITLE
[Bug] Unable to open menu after trainer fights

### ISSUE THREAD

**Issue by MokaStitcher** [pagefaultgames/pokerogue#3923]
### Describe the bug

During the reward screen after trainer battles the ESC/M menu does not open at all

### Expected behavior

The menu should open on all reward screens

### Screenshots / Videos

https://discord.com/channels/1125469663833370665/1274450819978231962/1279133659479412766

### Additional context

This bug exists in current live and main, and may be related to #3304 (i haven't checked though)

**Comment by flx-sta** [comment]
![image](https://github.com/user-attachments/assets/66e704cd-0715-4d24-8d40-670ed99e0aa1)

https://github.com/user-attachments/assets/6d9754a7-e595-45dc-9084-5dc73c4ac25a

**Comment by Snailman11** [comment]
Fix in beta ([Bug] Fixed issue where menu can't be opened up after a trainer battle)
https://github.com/pagefaultgames/pokerogue/commit/ce0ba3fbf98ab4baaa2e5c9e8214b4dcc33269e3
