### ISSUE TITLE
[Bug] Shiny sparkle animation not always showing during Egg Hatch Phase

### ISSUE THREAD

**Issue by MokaStitcher** [pagefaultgames/pokerogue#3924]
### Describe the bug

When hatching eggs the sparkle animation doesn't always show up.

I investigated a bit and it seems like the animation for each tier only gets loaded if you play with a Pokemon of that tier in your party (and also probably if you encounter a wild shiny for that tier, but I didn't test for that)

### Expected behavior

The sparkle animation should always get loaded in so that they always show up when hatching eggs

### Screenshots / Videos

Here's what the console looks like when hatching a batch of shiny eggs after opening the game and starting a run with a non shiny Pokemon
<img width="241" alt="Screenshot 2024-08-30 at 22 08 11" src="https://github.com/user-attachments/assets/6fb34c64-cf5a-41e6-b1f4-ae2d59f3b38d">

After that, I exited to the main menu, pulled more eggs, and started a different run with a tier 2 and tier 3 shiny Pokemon in the team.
The tier 2 one was the only one to ever be on the field.
When the eggs hatched both tier 2 and tier 3 shinies had their sparkle animation this time, but not the tier 1 shinies

### What OS did you observe the bug on?

Mac/OSX

### Which browser do you use?

Firefox

**Comment by Snailman11** [comment]
Link to Discord Bug Report: (shiny sparkle animation not happening for mons hatching from eggs)
https://discord.com/channels/1125469663833370665/1242254572022530128
