### ISSUE TITLE
[Bug] Moves That a Pokemon Knows and are not in their List of Learnable TMs Display as "Not Able" Rather than Learned 

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#3930]
### Describe the bug

Pokerogue considers TM learnsets over known moves.

Link to Discord's Bug Report: (Dragon Dance does not show as "learned" when trying to teach the respective TM)
https://discord.com/channels/1125469663833370665/1279237656210968646

### Expected behavior

![Learned](https://github.com/user-attachments/assets/4b4a4669-5577-40ed-b983-3de5c00392a4)

### Screenshots / Videos

![dragondance1](https://github.com/user-attachments/assets/4e376b58-27d5-4300-9e78-5afad21928d8)
![dragondance2](https://github.com/user-attachments/assets/7fb7e516-7534-431a-b99b-f3a2a1496447)
![dragondance3](https://github.com/user-attachments/assets/062f5baa-6e6e-4dc2-8c84-3689c11ddd93)

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

**Comment by frutescens** [comment]
Should be fixed in the next update. Thank you for reporting!
