### ISSUE TITLE
[Bug] Account Hard-Locked after refreshing frozen battle screen

### ISSUE THREAD

**Issue by benjmor** [pagefaultgames/pokerogue#3951]
### Describe the bug

- Was playing a session on Firefox, roughly ~lvl 124
- Took a break, computer went to sleep
- Resumed session
- Game ran normally for a few battles, then stalled out loading another battle
- Refreshed the page, it loads the assets appropriately, but when trying to load account-specific data, throws this error:

![image](https://github.com/user-attachments/assets/76bbdbe9-6f03-4969-aecc-6bb49ae4c077)

Entire account appears to be inaccessible; if I log into the account from a private browser window, the login screen appears and will authenticate, but not load any of my account data.

:(

Account name is `benomoth`.

### Session export file

Menu is inaccessible.

### Expected behavior

For game to load existing session on refresh of the pokerogue.net webpage.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/252046ce-1aee-4e72-9188-6b8af4caad0e)

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Firefox

**Comment by Snailman11** [comment]
The servers were down within the hour this was posted. 
https://discord.com/channels/1125469663833370665/1125514591884034178/1279643038917984349
