### ISSUE TITLE
[Bug] Ineligible Pokemon Contribute Luck In Challenges

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#3955]
### Describe the bug

Shiny Pokemon that have been obtained after a challenge run has begun contribute to the luck total when rolling rewards.

Link to Discord's Bug report (Illegal Pokemon still contribute Luck in challenges)
https://discord.com/channels/1125469663833370665/1266466377695236126

 

### Expected behavior

They shouldn't contribute Luck when not eligible for the challenge.

### Screenshots / Videos

https://github.com/user-attachments/assets/e81cf022-b676-496b-bdad-d4763e3efd2a

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

### Additional context

Pickup and Honey Gather currently do not activate if the pokemon is not eligible.
 
"it definitely shouldn't"
-Walker

**Comment by frutescens** [comment]
Should be fixed in the next update. TY for reporting
