### ISSUE TITLE
[Bug] Voucher Page Inaccessible on Mobile

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#3965]
### Describe the bug

The "Voucher" option is gone from the M menu, and I have no space bar with which to open it from the achievement menu.

Link to Discord's Bug report (Can't access voucher page on mobile)
https://discord.com/channels/1125469663833370665/1279990808438898740

### Expected behavior

The voucher menu is once again openable on mobile.

### Screenshots / Videos

![Screenshot_20240901-193530](https://github.com/user-attachments/assets/64a4903c-3e0d-4df7-8d6b-3fd87e820605)
![Screenshot_20240901-193542](https://github.com/user-attachments/assets/7acda53f-bb8c-43e1-8005-778c4f07de42)

### What OS did you observe the bug on?

Android

### If other please specify

Gameplay

### Which browser do you use?

Other

### If other please specify

Duck

**Comment by Snailman11** [comment]
It can be accessed with A, but either needs better messaging or a (redundant) way to simulate the spacebar.

Additionally, two users on Discord could not toggle it with A, with one having "pressed all buttons". Waiting for a reply about this.

**Comment by frutescens** [comment]
I've asked the art channel if I could commission an 'Action' button so we'll see how that goes

**Comment by frutescens** [comment]
Should hopefully be answered in the next update. TY!
