### ISSUE TITLE
[Bug] Scrappy prevents Super Effective attacks against Ghost types in Inverse challenge

### ISSUE THREAD

**Issue by YamiTheYin** [pagefaultgames/pokerogue#3991]
### Describe the bug

Fighting is x2 effective against Ghost with inverse rules. However a Pokemon with the Scrappy ability is unable to land a super effective Fighting type attack on a Ghost type Pokemon (with no other types that should otherwise change effectiveness).

### Session export file

[sessionData1_YamitheYin.txt](https://github.com/user-attachments/files/16842650/sessionData1_YamitheYin.txt)

### User data export file

[data_YamitheYin.txt](https://github.com/user-attachments/files/16842653/data_YamitheYin.txt)

### Expected behavior

<img width="445" alt="image" src="https://github.com/user-attachments/assets/18f9b68b-1864-460c-8e5e-e6bfbbe8ceeb">

### Screenshots / Videos

https://github.com/user-attachments/assets/1506fd0d-b134-464e-ad67-927cdab9f5f7

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Chrome

**Comment by KimJeongSun** [comment]
it is fixed on #4067

**Comment by flx-sta** [comment]
@KimJeongSun the PR is still open. Only close if merged into `beta` (or `main`) please
