### ISSUE TITLE
[Bug] Normalize + Scrappy + Wonder Guard + Dual Wingbeat interaction issue

### ISSUE THREAD

**Issue by frezgle** [pagefaultgames/pokerogue#4006]
### Describe the bug

In my current endless run, I'm running DOT Shedinja.
After giving an enemy Slither Wing Normalize via Entrainment, Dual Wingbeat is still hitting and killing Shedinja. It's not giving the Supereffective message; it's just hitting. Aerialate is not involved in any way.

### Expected behavior

Dual Wingbeat should not hit Shedinja, as Normalize should be turning it into a Normal type attack. Scrappy should not allow damage.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/4143b8e6-46d9-4e29-88f5-204192f80ba3)
![image](https://github.com/user-attachments/assets/e457a312-6c31-4a17-84a1-708db0edf284)

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Chrome

**Comment by Snailman11** [comment]
https://github.com/pagefaultgames/pokerogue/pull/3988
Should be getting fixed by this
