### ISSUE TITLE
[Bug] Pure Flying types using Roost should become a Normal type

### ISSUE THREAD

**Issue by YamiTheYin** [pagefaultgames/pokerogue#4035]
### Describe the bug

When Rookidee/Corvisquire use Roost they should become Normal type due to being pure Flying types. However, when targeted with a Fighting type move it is Not Very Effective.

### Session export file

[sessionData_YamitheYin.txt](https://github.com/user-attachments/files/16883660/sessionData_YamitheYin.txt)

### User data export file

[data_YamitheYin.txt](https://github.com/user-attachments/files/16883661/data_YamitheYin.txt)

### Expected behavior

When a pure Flying type uses Roost it should become a Normal type rather than typeless. [Bulbapedia Roost page](https://bulbapedia.bulbagarden.net/wiki/Roost_(move))
<img width="290" alt="image" src="https://github.com/user-attachments/assets/b3e6d51c-777f-4959-b841-1292af423b92">

### Screenshots / Videos

https://github.com/user-attachments/assets/92475468-3c9e-4cab-b900-9b375fba67ea

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Chrome

**Comment by flx-sta** [comment]
Duplicate of #3984
