### ISSUE TITLE
[Bug] Pokémon level-up evolution is improperly delayed

### ISSUE THREAD

**Issue by flx-sta** [pagefaultgames/pokerogue#4039]
## Describe the bug

Say you have Charmeleon being level 35 after the battle and you switch into the Rewards screen which offers a candy.
You choose it and give it to said Pokemon which puts it to level 36 which is the evolution to charizard level.
The Pokemon won’t evolve till the next battle though

## Expected behavior

The Pokemon should evolve after being given the candy.

## Screenshots / Videos

TBA

## Additional Context

![image](https://github.com/user-attachments/assets/b8f31461-4a84-4830-a913-5f9526faa1d5)

![image](https://github.com/user-attachments/assets/6a3050e9-7996-4be7-aec3-963c445e1349)

**Comment by Snailman11** [comment]
https://discord.com/channels/1125469663833370665/1259880221625024543
Link to the discord post in the issue
