### ISSUE TITLE
Palafin's Ability (Zero to Hero) Doesn't Work

### ISSUE THREAD

**Issue by KingJigglypuff** [pagefaultgames/pokerogue#404]
As described by the title, Palafin's ability is supposed to trigger when it's switched out, but doing so currently doesn't seem to trigger it. I've tried manually switching out and also using Flip Turn, but neither had an effect.

**Comment by Madmadness65** [comment]
(N)ot yet implemented

**Comment by KingJigglypuff** [comment]
Understood, thanks for responding.
