### ISSUE TITLE
[Bug] Dive Ignores abilities that Use PostDefendAbAttr - includes Sand Spit, Rough Skin, Seed Sower and Gulp Missile.

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#4041]
### Describe the bug

Dive does not activate abilities that use PostDefendAbAttr

Link to Discord's Bug Report (Sand spit didn't activate despite surviving damaging attack)
https://discord.com/channels/1125469663833370665/1280779194246365266
-Videos

### Expected behavior

Dive should function like an 80 bp water type contact move when determining whether it activates PostDefendAbAttr abilities.

### Screenshots / Videos

Loaded Cramorant not firing when hit by Dive

https://github.com/user-attachments/assets/0a7a78e5-cdff-4dc8-a8f8-c3cae41fda44

Seed Sower not activating when hit by Dive

https://github.com/user-attachments/assets/500455f6-1064-43c1-9746-2496592b8500

Fluffy works correctly

https://github.com/user-attachments/assets/f639bcad-20eb-45a6-bda0-5cba70cab25c

Does not affect Fly

https://github.com/user-attachments/assets/b45cdb0a-8bd5-4f8d-ab5f-be95b1e48989

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

**Comment by torranx** [comment]
casually assigning @innerthunder here 🏃‍♂️

**Comment by innerthunder** [comment]
I have a bigger rework of charge moves in the works that should fix this along with other issues :eyes:
