### ISSUE TITLE
[Bug] Sandstorm and Hail damage Triggers on the Semi-Invulnerable Turn of Dig and Dive

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#4042]
### Describe the bug

Diving with either Hail or Sandstorm active still triggers damage on a pokemon in the semi-invulnerable turn of Dig or Dive. 

Link to Discord's Bug report: (Sandstorm hits pokemon using dive)
https://discord.com/channels/1125469663833370665/1246312758958624778

### Expected behavior

Bulba pages for Dive and Dig

> Sandstorm, hail, and Shadow Sky will not cause damage during the semi-invulnerable turn.

> During the semi-invulnerable turn, the user is also immune against damage from sandstorm and hail.

### Screenshots / Videos

Dive

https://github.com/user-attachments/assets/8853637d-af4d-4c53-b9a2-2016a1247e59

Dig

https://github.com/user-attachments/assets/ab8f99ce-0b05-4fd2-93b8-499fb93fc1aa

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

### Additional context

Pokemon in the semi-invulnerable turn of Bounce, Fly, Phantom and Shadow Force correctly take damage.

**Comment by torranx** [comment]
In progress with this
