### ISSUE TITLE
[Bug] Moves Can Miss Against Protect, Baneful Bunker, King's Shield

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#4060]
### Describe the bug

Moves may miss against protect and protect clones. 

### Expected behavior

https://replay.pokemonshowdown.com/gen9customgame-2195472381-exy2nnl4kxvx63gpep5tsp60al6a7lepw
Whether a move is protected against should be considered before accuracy

### Screenshots / Videos

-6 acc Nidoran misses against Cyndaquil's protect.

https://github.com/user-attachments/assets/ee7151da-9106-4f9f-9d4a-241387e5ecd2

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

### Additional context

Protection moves that apply their effect after a move is protected against would not trigger their effects. The protection move retains the lowered success rate, so in effect, this can drastically lower the reliability of protection moves.

Worth mentioning
https://github.com/pagefaultgames/pokerogue/issues/3673
Where moves can miss against mons with immunity abilities, if when acc is checked for would be modified.

**Comment by innerthunder** [comment]
fixed by #4262
