### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Venishsios** [pagefaultgames/pokerogue#4073]
### Describe the bug

I’ve contacted before and have found, and put in my username and password and it tells me the user doesn’t exist?

### Expected behavior

Since I have found my Username and password, it would allow me back into my Account

### Screenshots / Videos

![IMG_6799](https://github.com/user-attachments/assets/99aaf182-b512-49ca-9d83-a0f42ec215fe)

### What OS did you observe the bug on?

iOS

### Which browser do you use?

Safari

**Comment by Snailman11** [comment]
Please direct any password-related/account credentials loss to this discord thread. 
https://discord.com/channels/1125469663833370665/1249564591428599871
