### ISSUE TITLE
[Bug] Teamwork Achievement description

### ISSUE THREAD

**Issue by YamiTheYin** [pagefaultgames/pokerogue#4096]
### Describe the bug

Teamwork achievement description reads as "TRANSFER_MAX_BATTLE_STAT.DESCRIPTION" instead of usual description.
(Also lost completion for the achievement.)

### User data export file

[data_YamitheYin.txt](https://github.com/user-attachments/files/16920696/data_YamitheYin.txt)

### Expected behavior

The usual description of needing to baton pass to another Pokemon with a maxed out stat.

### Screenshots / Videos

![Screenshot_20240907_224434_Chrome](https://github.com/user-attachments/assets/2ad88ad2-b1a2-40a7-88d1-8a5be5ec6155)

### What OS did you observe the bug on?

Android

### Which browser do you use?

Chrome

**Comment by Snailman11** [comment]
Link to Discord's Bug report (Baton achievement bugged out)
https://discord.com/channels/1125469663833370665/1282183095281385542
