### ISSUE TITLE
[Bug] Lures Are Infinite Duration

### ISSUE THREAD

**Issue by OreoCupcakes** [pagefaultgames/pokerogue#4100]
### Describe the bug

Lures refresh back to their initial starting value (10, 15, 30) upon a reload of the game.

### Session export file

[sessionData1.zip](https://github.com/user-attachments/files/16920981/sessionData1.zip)

### Expected behavior

Sessions should save the lure value and keep track of it during a reload.

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Firefox

**Comment by Snailman11** [comment]
Link to Discord's Bug Report (Lures refresh on reload)
https://discord.com/channels/1125469663833370665/1282186962869944391
