### ISSUE TITLE
[Bug] Achievement/Voucher menu broken when closing and reopening

### ISSUE THREAD

**Issue by MokaStitcher** [pagefaultgames/pokerogue#4112]
### Describe the bug

When in the Achievements/Voucher menu, closing the menu while scrolled down on the voucher tab and reopening the menu will result it the menu not loading properly

Steps to reproduce:
- Open Achievements menu
- Switch to Voucher tab
- Go down to the last row of vouchers
- Exit
- Re open the Achievements menu
From this point switching to the voucher tab and back fixes it

### Expected behavior

The menu should reset properly to the "Achievements" screen when reopening it

### Screenshots / Videos

https://github.com/user-attachments/assets/2fef60ed-8a9c-48ae-95c2-e90027fe6c53

### What OS did you observe the bug on?

Mac/OSX

### Which browser do you use?

Firefox

### Additional context

My guess: something about the cursor or scrollcursor is not cleared properly when exiting and since the menu defaults to achievements and there are less achievements than vouchers it's trying to scroll to an invalid index

**Comment by Snailman11** [comment]
Link to Discord's Bug Report (menu achievement bug)
https://discord.com/channels/1125469663833370665/1282189710311166093
