### ISSUE TITLE
[Suggestions] Misc UI/UX additions

### ISSUE THREAD

**Issue by Justfines** [pagefaultgames/pokerogue#413]
Hello, I just found the game, and am excited to get into it; While trying out my first few runs, I noticed some things that could get added that might improve some aspects of the experience (mostly for newer people, like me). Here is a list of what my ideas are:

+ Providing some form of direct menu selections 

   - This could just be selecting, or both select and confirmation
   - This would be most useful for mouse interactions, and rapidly going through larger menus like the starter selection 
  
    * I think this, as stated, would be most useful for mouse controls, but would potentially also provide a more intuitive touch experience for larger screens, if optional
  
+ Adding an optional control or button legend

   - Could be toggled in the settings
   - Could be shown either in a small black (or in another background color, like based on the theme) bar on the bottom of the game, or in the side margins depending on aspect ratio
   - Example contents could be like: "ENTER/SPACE/Z=Confirm, M=Menu..." and could change based on available/current key-binds of the last used input device

     * I think this would allow it to be easier to get used to the controls for those (like me) that are unfamiliar with all the hotkeys, and would be a good reference inherent to the game without needing the wiki out
  
+ Changing Double Battle move selections
  - Possibly could have Moves like growl or other aoe moves would provide the flashing animation while the move is highlighted, or have some feedback that multiple are targeted in another way (like an icon, or have the target select screen appear anyways to be consistent with single target)
  - Additionally on the target selection, during the targeting the text box is empty, and I feel like it should at least still say what Pokemon and what move you are selecting the Target for.

     * I feel like these might be more subjective, especially as someone that's not very hardcore into the Pokemon scene, but I feel there is at least some merit bringing it up, and would provide clarity on what is happening for people coming in
  
+ Starter menu changes
  - Adding a label or marker on the starter selection screen for the Generation of Pokemon that is being selected
  - Additionally possibly always showing at least two generations in addition to the arrows could make it more consistent, and visually obvious that it is a selector

     * I think this change would be good for just making it more intuitive that that section is the generation selector at first glance. A quick mock-up of what I was thinking shown here (via photo editing), with the unavailable scroll up greyed out
  ![mockupUIchange](https://github.com/pagefaultgames/pokerogue/assets/22578581/b4f0fc41-e4bb-4864-91b6-cc7e3a0fcebd)
  
  
+ Other Menu Changes 
  - An additional menu (on either main menu, or on the in-run menu) to view previous tutorial messages in case one got missed
     - Alternatively, an option inside Settings to reset the tutorial messages to appear again.
        * I believe this is useful in case one accidentally skips them through pressing confirm to quickly, or if the messages need to be seen again.
  
  - Similarly, a menu for a more full-screen view of your currently (held) items.
    It would allow fully controller based, or mobile device based users to more easily see what items in their possession can do.
    * An alternative would be to have a button or option for a virtual "inspection" cursor/mode to pop up that could be used to hover over said items instead to reveal on-hover effects (like descriptions)

       * I think this would be important to just allow more options to see that information that currently is only provided on mouse hover
  
  - On the shop/ post battle screen, adding an outline (like a rounded rectangle) around the shop area with a shop label, or some other form of area distinction
  
    * I believe this could be useful for rapid visual distinction between the multi-selection shop and the battle reward items (even though the shop is always above) improving at-a-glance clarity.
  To visually fit within the game's art style and rest of the presentation would require some more work than a simple, but ugly outline though.

**Comment by flx-sta** [comment]
@Justfines thank you for your detailed suggestions.
Can you please update your suggestions by checking which ones are implemented, which ones might be present in other issues.
If something is missing please create a new, self-contained feature suggestion as it's near impossible to maintain these large lists.
