### ISSUE TITLE
[Sprite][Bug][Color] 864 Cursola Variant Mismatch on Static vs Anim

### ISSUE THREAD

**Issue by pom-eranian** [pagefaultgames/pokerogue#4156]
### Describe the bug

Palette errors on exp(erimental) animation spritesheet. Not all colors are replaced, doesn't match static.

https://discord.com/channels/1125469663833370665/1238339524778790922/1283079472316420259

files affected:
(checklist needed)

### Session export file

N/A

### User data export file

N/A

### Expected behavior

Pokemon's animated sprite should match colors on static sprite.

### Screenshots / Videos

left: T3 static, right T3 animated
![966b5e2d-7b71-4a48-a22d-cab6fb57e9e9](https://github.com/user-attachments/assets/8125dd8f-5f2a-49db-afa6-6bb07fff44e0)

### What OS did you observe the bug on?

Other

### If other please specify

all

### Which browser do you use?

Other

### If other please specify

all

### Additional context

WIP template for sprite issues.

**Comment by chaosgrimmon** [comment]
Pretty sure `beta` still isn't the 'main' branch according to GitHub, meaning that when #4186 is merged, this will still have to be closed manually, regardless of magic keyword usage.

**Comment by chaosgrimmon** [comment]
welp
![image](https://github.com/user-attachments/assets/90cd30aa-2565-4d21-b01d-977cd8afcb06)
