### ISSUE TITLE
[Bug] Tera Shift will fail to change form in specific situation

### ISSUE THREAD

**Issue by Madmadness65** [pagefaultgames/pokerogue#4162]
### Describe the bug

When starting a new run with a Terapagos and at least one other Pokémon, if you select to switch a Pokémon, then back out of the menu, the form change will not occur. It will even persist as the base form until it is recalled for whatever reason, either by the player switching Pokémon, or a forced recall, such as for a trainer battle or biome transition, in which it will then activate Tera Shift.

Choosing not to switch will change its form as intended.

### Expected behavior

The form change via Tera Shift should happen regardless of if you enter the switch Pokémon screen or not.

### Screenshots / Videos

A clip of Tera Shift not working as intended due to opening the switch menu.

https://github.com/user-attachments/assets/45ae43c8-481f-431a-8e3b-4090c502c476

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Firefox

**Comment by Snailman11** [comment]
Very Likely related to this
https://github.com/pagefaultgames/pokerogue/issues/3482

**Comment by Madmadness65** [comment]
Ah, fair enough. Guess I looked past that one since this ability wasn't mentioned in that issue.
