### ISSUE TITLE
[Bug] Baddy Bad and Glitzy Glow Set Reflect / Light Screen when Protected against and when they have no Effect

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#4163]
### Describe the bug

-Hitting a Dark type with Glitzy Glow will set Light Screen.

-Hitting a Pokemon under Protect will set Light Screen

-Missing Glitzy or Baddy does not set Light Screen

Link to Discord's Bug Report: (Glitzy glow activating light screen against dark types)
https://discord.com/channels/1125469663833370665/1263344413544022128

### Expected behavior

When Protected against, Glitzy Glow should not set Light Screen
https://replay.pokemonshowdown.com/gen9customgame-2199039552-kgnlw25inhpmm133b2baf8xlimluhkzpw

When Glitzy or Baddy do not affect the targeted Pokemon, Light Screen and Reflect are not set.
https://replay.pokemonshowdown.com/gen9customgame-2199033788

### Screenshots / Videos

Glitzy Sets Screens when the move has no effect

https://github.com/user-attachments/assets/b2489365-3041-480e-a962-ce19b21977c2

Glitzy Sets Screens when the move is protected against

https://github.com/user-attachments/assets/d814f5da-b41e-43ad-bd82-450ed71fc8fd

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

### Additional context

SEPERATE: Glitzy and Baddy set screens when attacking allies. This is also how it currently works in Pokerogue.
https://replay.pokemonshowdown.com/gen9doublescustomgame-2199040724-h0hl79a4nb9fihbo9bdw4v3oifeinazpw

**Comment by innerthunder** [comment]
Seems like a similar issue to https://github.com/pagefaultgames/pokerogue/issues/2689. These moves' effects are internally self-targeted `POST_APPLY` effects, which seem to erroneously ignore the move's effectiveness when applied.

Gonna assign @DayKev to this, as he fixed 2689, but I'd be happy to help out if needed because this might require hefty changes to `MoveEffectTrigger` logic in general.
