### ISSUE TITLE
Stuck in black screen after NEW GAME

### ISSUE THREAD

**Issue by CAPxCRYing** [pagefaultgames/pokerogue#4208]
### Describe the bug

I can't seem to enter the pick starter screen whenever i choose NEW GAME and whatever the game mode i choose. To the left  is supposedly where the normal screen should be and to the right is the F12.
<img width="1799" alt="Screenshot 2024-09-13 at 07 51 30" src="https://github.com/user-attachments/assets/26a3c575-c03f-471c-91ff-23964d020d78">
<img width="1799" alt="Screenshot 2024-09-13 at 07 48 01" src="https://github.com/user-attachments/assets/678a7909-52a9-483b-9959-9e6f1d56583b">
I could however still access my saved runs and play them with everything normal.

### Expected behavior

Access to choose starter pokemon directly

### What OS did you observe the bug on?

Mac/OSX

### Which browser do you use?

Chrome

### Additional context

Started randomly some day without anything special

**Comment by MokaStitcher** [comment]
@CAPxCRYing  Clearing your cookies should fix it
I have been unable to reproduce the issue on my end and get to the root cause unfortunately

**Comment by MokaStitcher** [comment]
For reference on the issue:
- It started after release 4
- for one person, it started specifically after a crash during starter selection [see discord report](https://discord.com/channels/1125469663833370665/1283611202831781972)

Discord bug reports:
- [First report, shortly after the merge](https://discord.com/channels/1125469663833370665/1283563436751458334)
- [other report](https://discord.com/channels/1125469663833370665/1283563436751458334) - asked the player for their save data from local storage but still couldn't get it to reproduc

**Comment by CAPxCRYing** [comment]
> @CAPxCRYing Clearing your cookies should fix it I have been unable to reproduce the issue on my end and get to the root cause unfortunately

Yes it worked! Thanks a lot!!!
