### ISSUE TITLE
Nickname 

### ISSUE THREAD

**Issue by tecknojock** [pagefaultgames/pokerogue#424]
I think it would be fun to be able to nickname our pokemon.

I'd suggest the option be attached to a species rather than upon catching, to not slow down the progress of the game and to be able to be set in the pokedex or in the starting team menu

**Comment by Flashfyre** [comment]
This is in the roadmap on the Discord. You do not need to post an issue for something that is in the roadmap.

**Comment by tecknojock** [comment]
It might be helpful to post the road map in a more publicly available form in that case. I'm used to issues being used for road maps in most projects and I searched them before I added it.
