### ISSUE TITLE
Mystery Encounters beta bugs/breakfix

### ISSUE THREAD

**Issue by ben-lear** [pagefaultgames/pokerogue#4240]
Please add any bugs, session saves, screenshots, logs, etc. here in comments so they can be tracked under a single issue

----

Edit:
Please continue reporting new issues in #4300 4300

**Comment by ben-lear** [comment]
Add better filtering for Clowning Around/Weird Dream in Challenge modes. They should be disabled in monotype/monogen, but be enabled in things like fresh start.

**Comment by innerthunder** [comment]
In `enemy-command-phase.ts`: the enemy AI unnecessarily evaluates their moveset when forced to skip their turn by an ME (see the Fun and Games encounter)
```ts
/** Select a move to use (and a target to use it against, if applicable) */
const nextMove = enemyPokemon.getNextMove(); // this shouldn't be run when forced to skip turns

this.scene.currentBattle.turnCommands[this.fieldIndex + BattlerIndex.ENEMY] =
    { command: Command.FIGHT, move: nextMove, skip: this.skipTurn };
```

**Comment by ben-lear** [comment]
![image](https://github.com/user-attachments/assets/2c312fe2-c16e-4a7f-9c6f-9d3d763e6d6e)

Fun and Games is overriding 0th index pokemon if you choose a different mon for the minigame

**Comment by ben-lear** [comment]
https://discord.com/channels/1125469663833370665/1280631406715863243/1284381915230634076

Normal wild floor was replaced with a ME on reload

**Comment by CodeTappert** [comment]
On Beta (in Shop):
![image](https://github.com/user-attachments/assets/c7a45529-bbfd-4506-a89a-6651ace83096)
ME:
![image](https://github.com/user-attachments/assets/a31fda2b-46cf-4449-b9d0-4d9ed1472577)

same text but the button does not seem to be set to a correct position

**Comment by ben-lear** [comment]
![image](https://github.com/user-attachments/assets/8505bdff-6ee9-4de2-9903-4d5dc9fe88a9)

Update language on option tooltip to accurately describe Trash to Treasure effects

**Comment by ben-lear** [comment]
![image](https://github.com/user-attachments/assets/afd85f10-9df3-4cea-8278-0ab48a0a50be)

disable lock rarities button when rerolls disabled

**Comment by ben-lear** [comment]
May want to disallow seeing the same encounter twice or more for ALL encounters. This is a balance decision though.

**Comment by ben-lear** [comment]
Another balance thing: Macho Brace might be a bit weak atm

**Comment by ben-lear** [comment]
https://github.com/pagefaultgames/pokerogue/blob/783b9d85ee65ac22806d5a216dc11dca3857fdae/src/data/mystery-encounters/encounters/global-trade-system-encounter.ts#L222

All wonder trades are Burmy atm

**Comment by PigeonBar** [comment]
In "Mysterious Chest", if you roll the unlucky option and trigger a game over, then you click "Yes" to the "retry battle" option, the opened chest sprite stays loaded.

https://github.com/user-attachments/assets/f6421dc3-fa57-42cc-b807-1ae2a7de90a1

**Comment by ben-lear** [comment]
https://github.com/pagefaultgames/pokerogue/blob/783b9d85ee65ac22806d5a216dc11dca3857fdae/src/data/mystery-encounters/encounters/fight-or-flight-encounter.ts#L57

enemyLevels calcs are bugged and changing on refresh for a few encounters.

**Comment by CodeTappert** [comment]
![image](https://github.com/user-attachments/assets/aff6b3a8-9931-46b3-86e5-0ccd40a4aa8a)
If the pokemon you do "Light Tranining" in "training session" with already has 31IVs on all stats it gives this weird thing...

**Comment by CodeTappert** [comment]
![image](https://github.com/user-attachments/assets/4de0408a-5ec3-4614-8a2a-37b48a9eda33)
This text is not translatable in field trip

**Comment by CodeTappert** [comment]
The Shady Vitamin Dealer Event doesnt gives you the shop afterwards

**Comment by CodeTappert** [comment]
![image](https://github.com/user-attachments/assets/6410231d-be92-4e5e-9c47-c0f5e3e57ef2)
Titles of Gym Leaders still are wrongly capitalized. 
It tries to translate the already translated title...

**Comment by PigeonBar** [comment]
In "Mysterious Chest", defeating Gimmighoul also doesn't give the shop afterwards

https://github.com/user-attachments/assets/ae4bc044-e062-45f6-be17-27fe6be012cc

**Comment by PigeonBar** [comment]
(Originally in https://discord.com/channels/1125469663833370665/1281859097481711648/1284219054126534709, bug is still active)

If you already have 99 eggs in your egg list, and an ME rewards you with another egg, it can allow you to have over 99 eggs.

![Screenshot 2024-09-13 142533](https://github.com/user-attachments/assets/f6e93bcb-196b-4e60-9c94-4b37138d3c15)

**Comment by CodeTappert** [comment]
![image](https://github.com/user-attachments/assets/2ce3b6fe-561c-4ff0-963e-9aab2572976f)
The sprite dont show sometimes

**Comment by ben-lear** [comment]
![image](https://github.com/user-attachments/assets/5d3b53b2-c1e5-4cea-be7c-ad76b812c43b)

should refactor “catch” logic to be the same as existing and have a SUMMARY option to view pokemon details

**Comment by Opaque02** [comment]
I can't prove this with certainty but in my run it felt like I hit 5-6 shady salesmen. My run's save file is [here](<https://discord.com/channels/1125469663833370665/1281859097481711648/1284538840673026048>)

**Comment by PigeonBar** [comment]
I think `mysteryEncounterSaveData.encounteredEvents` is somehow getting incorrectly reset when reloading the game. This causes the check for "do not spawn an ME within 3 waves of another ME" to fail, which can cause a wild encounter to be replaced by an ME when reloading the game.

Screenshot before reload:

![Screenshot 2024-09-14 122038](https://github.com/user-attachments/assets/7f8a7253-9711-4356-92e0-d1ae0e82c9b6)

Screenshot after reload:

![Screenshot 2024-09-14 122118](https://github.com/user-attachments/assets/5ee27275-7f80-4e59-99ce-ebba7f38c367)

My added `console.log()` statement for checking `mysteryEncounterSaveData.encounteredEvents`:

![Screenshot 2024-09-14 105911](https://github.com/user-attachments/assets/caffe89b-653a-43e7-970d-68625221f81f)

**Comment by damocleas** [comment]
![image](https://github.com/user-attachments/assets/46208026-d64b-41d3-9fc7-43f73ec405b7)
'Fight or Flight' seems to attempt to stat increase its'... Max HP

**Comment by damocleas** [comment]
'An Offer You Can't Refuse' should probably not refer to any pokemon as a 'pet', this can lead to uncomfortable scenarios as I ran into yesterday where a child looking character can refer to a Gardevoir and such

**Comment by CodeTappert** [comment]
![image](https://github.com/user-attachments/assets/921da293-2571-485a-9195-a43575e59049)
SURF and FLY here arent translated (they are just given as that strings in the placeholders instead of using the translated move name)

**Comment by CodeTappert** [comment]
The outro in "the-strong-stuff seems to be never called?

**Comment by CodeTappert** [comment]
In "The Winstrates" the name of the trainers are not correctly loaded from the localization files. It shows the english names (but the translates title)
![image](https://github.com/user-attachments/assets/3b8c2ed3-68e1-459a-a394-794e71c8af91)

**Comment by damocleas** [comment]
After catching the Gimmighoul in "Mysterious Chest" it pauses awkwardly and then moves to the next wave with no end screen

**Comment by ben-lear** [comment]
Some issues with absolute avarice. https://discord.com/channels/1125469663833370665/1284608904906407976

**Comment by Blitz425** [comment]
![image](https://github.com/user-attachments/assets/9016611a-0b70-454b-a206-45bb327cc49d)

Small thing but it shows "Gain a Gastly with its Hidden Ability!" despite not having one

**Comment by Blitz425** [comment]
> 
> Small thing but it shows "Gain a Gastly with its Hidden Ability!" despite not having one

![image](https://github.com/user-attachments/assets/b940fde4-938d-47ea-a665-6ffe2b92f47d)
Follow up, it actually adds the ability button on starter select though pressing it does nothing

**Comment by damocleas** [comment]
It seems during the Winstrate Challenge and similar events you can use pickup against the trainer mons (as this is normal behavior) but it allows you to get their items like leftovers for free multiple times

**Comment by ben-lear** [comment]
Discussion link for Pokemon salesman HA issue:
https://discord.com/channels/1125469663833370665/1229525892624154684/1284626118866898944

Setting item transferability for Winstrates is on the TODO list.

**Comment by Blitz425** [comment]
Got "A Trainer's Test", on reload it turned into a different ME
![image](https://github.com/user-attachments/assets/6be3d8dc-86fc-4aac-ad70-0a80f4775314)

![image](https://github.com/user-attachments/assets/ab0958dc-3890-4bda-8c0b-50e18b185d6f)

**Comment by Snailman11** [comment]
Softlock for "Uncommon Breed" 

> (Beta) "Uncommon Breed" softlocks when giving it food and denying it space in the party

https://discord.com/channels/1125469663833370665/1284675181582880861

**Comment by ben-lear** [comment]
https://discord.com/channels/1125469663833370665/1284675181582880861

**Comment by Blitz425** [comment]
It looks like GTS always gives the same thing for Wonder Trade?

**Comment by PigeonBar** [comment]
Dark Deal has the same `randSeedInt(100)` issue that Mysterious Chest originally had. ~~(I'm sure players will appreciate the buffed 6% chance to be able to catch a 9-cost legendary :) )~~

![image](https://github.com/user-attachments/assets/d8660df1-0966-4cdf-a322-ad4616f496e7)

**Comment by PigeonBar** [comment]
In challenge modes, the Dark Deal encounter can choose to sacrifice a Pokemon that would normally be ineligible for the challenge. This is probably unintended because challenge modes should treat ineligible Pokemon as if they do not exist in your party.

For my example, I am playing a mono-Water challenge, and the encounter chose to sacrifice Victreebel:

https://github.com/user-attachments/assets/7d92e4ba-26f8-4b4a-88cb-968b392570d2

**Comment by Snailman11** [comment]
"The Pokemon Salesman" Game Crash

(Beta) Game Crash after picking up Pokémon from "The Pokémon Salesman" and not adding to team

https://discord.com/channels/1125469663833370665/1284804713392373800

**Comment by Snailman11** [comment]
Black Sludge Doesn't Actually multiply shop prices

> Pokerogue BETA Black sludge bug

https://discord.com/channels/1125469663833370665/1284914742321877002

**Comment by jgardin** [comment]
<img width="1373" alt="image" src="https://github.com/user-attachments/assets/271e1d03-53ec-4660-8147-86352d000933">
After fortune teller transformed the team of pokemon into their "past" selves, the HP/status bar disappeared. After using the move `recover`, the game froze

**Comment by damocleas** [comment]
If possible, please remove your *own* pokemon that you fight in "Training Session" or other relevant ones from updating your "Seen" count.

And please remove Mythicals from any ME's, particularly "Dark Deal" still has some possible, discuss on discord about how best to go about this, to me seems it should just be random if there are no types available.

**Comment by ben-lear** [comment]
Trash to Treasure, Bug-Type Superfan, Shuckle encounter all need to be 1 time spawn only.

**Comment by PigeonBar** [comment]
(Maybe not a bug?) The Slumbering Snorlax encounter is intended to have Snorlax be asleep for a few extra turns, but this does not occur if Snorlax is generates with a Lum Berry held item:

https://github.com/user-attachments/assets/23b1a0a4-8a07-46a6-8880-73871ee206fe

**Comment by PigeonBar** [comment]
Also, the Snorlax treats Sleep Talk with a score of 0, even when it is asleep. This prevents Snorlax from using Sleep Talk, which makes this ME much easier.

![20240915 No Sleep Talk](https://github.com/user-attachments/assets/d9f16585-d497-4cb0-b087-4578790ad663)

**Comment by PigeonBar** [comment]
In Training Session, it appears that if you choose to train a Pokemon that is holding stacks of held items, then:
1. When the Pokemon moves to the opponent's side, its held items get reduced to stacks of 1.
2. When the Pokemon returns to your party, its held items disappear completely.

https://github.com/user-attachments/assets/2792600d-7ca8-41e5-9c75-d1a45653ec08

**Comment by star-krieg** [comment]
Similar case of higher levels upon resetting. Without resetting, the Bronzong's level is 43. Loading the session data here should result in a level 64 Bronzong.

![image](https://github.com/user-attachments/assets/beb4935e-1de3-45fc-b6c7-7ad01b971412)


[sessionData1_starkrieg_live_BerriesAbound.txt](https://github.com/user-attachments/files/17008518/sessionData1_starkrieg_live_BerriesAbound.txt)

**Comment by PigeonBar** [comment]
In Training Session, if you successfully flee from the battle, then you will simply lose the Pokemon that you chose to train:

https://github.com/user-attachments/assets/e8191ae8-e725-44af-9fac-5f646deb990f

**Comment by PigeonBar** [comment]
Just as a QoL, would it be possible for Training Session to indicate which natures and abilities you have already unlocked for the Pokemon that you choose to train?

**Comment by Adri1** [comment]
In Asolute Avarice, if I choose to "Let It Have the Food" and decline to have it in my team, the game stays stuck

https://github.com/user-attachments/assets/e22b7574-22aa-4d1a-a6c7-312a18d578df

**Comment by PigeonBar** [comment]
A minor balance concern: Training Session could incentivize players to keep a really weak Pokemon in their party in order to train it more easily (e.g., Snivy with 4 status moves).

**Comment by Adri1** [comment]
Egg haching happens before the true end of the ME
https://github.com/user-attachments/assets/55d7482f-5a51-4506-9b41-d4ccc06bb42d

**Comment by PigeonBar** [comment]
[P2 Bug] Sometimes, the game will incorrectly apply `mysteryEncounterSaveData.encounteredEvents` to a different session file. Here is an example where I saved and quit during a wave 172 ME, then started a new run from wave 1. The wave 172 ME is still considered "seen", even though I am way before wave 172:

![20240916 Encountered Events 1](https://github.com/user-attachments/assets/f81777d4-53d8-41e9-b0fb-d68e29c2a4eb)

This can cause the game to refuse to spawn ME's due to the "do not spawn an ME within 3 waves of the last one" check. Indeed, I speedran through the session with my Lvl 10000 Pokemon, and I did not get any ME's until wave 176:

![20240916 Encountered Events 2](https://github.com/user-attachments/assets/8a1f22e5-9e97-4d9b-90ec-ff8c48523a1f)

For reference, here is my added `console.log()` statement:

![Screenshot 2024-09-14 105911](https://github.com/user-attachments/assets/02da86ca-c00f-4a17-90ed-33ec3a046472)

Note that this bug seems to stop if you refresh (F5) the page. Also note that this bug may be tricky to reproduce due to another bug where the list of encountered events keeps getting reset (e.g., https://github.com/pagefaultgames/pokerogue/issues/4240#issuecomment-2351051363).

**Comment by VaylenObscuras** [comment]
I noticed some of the encounters dont open the item shop afterwards(Noticed it with the shady vitamin dealer). That seems like a bad idea, as I(and I assume many others) often plan their heals right before the boss. That can really mess your strategy up out of nowhere.

**Comment by flx-sta** [comment]
Please continue reporting new bugs in #4300
