### ISSUE TITLE
[Bug] Currency total reverted to NAN on beta branch

### ISSUE THREAD

**Issue by seanrmon** [pagefaultgames/pokerogue#4247]
### Describe the bug

I saved my endless run last night, about 10 hours ago, I had maybe 120k coins.When I loaded my session, I hit an opposing Pokémon and my total was set to NAN. I'm pretty sure it's caused by golden punch, because if I switch to another Pokémon, my total stays at zero, and if I receive money from another source, e.g. honey gatherer, my total is calculated correctly.

### Session export file

[sessionData_nanbug.txt](https://github.com/user-attachments/files/17001616/sessionData_nanbug.txt)

### Expected behavior

Damage calculated normally

### What OS did you observe the bug on?

Android

### Which browser do you use?

Firefox

**Comment by Opaque02** [comment]
This should be fixed now
