### ISSUE TITLE
[Bug] api.pokerogue.net down

### ISSUE THREAD

**Issue by brunopma** [pagefaultgames/pokerogue#4255]
### Describe the bug

Having issues retrieving session info and logging into pokerogue
![image](https://github.com/user-attachments/assets/816d4cff-abfe-409a-b710-fb29b35e56d7)

### Expected behavior

API should work

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Chrome

**Comment by MokaStitcher** [comment]
the server is down at the moment
