### ISSUE TITLE
[Bug] Thrash (Frenzy Moves) Counter Increments despite Move Failing, Paralysis

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#4277]
### Describe the bug

-The Frenzy Counter is incremented whenever a Frenzy move is selected and;
affects the target, the user is not hurt by confusion, and the attack passes the accuracy check.

**This does not include full paralysis and the move failing due to a missing target.**  (**-I have not checked freeze**)
When a Frenzy move is not executed due to full paralysis or if the move fails, the counter is incremented inappropriately.
However, because the Frenzy move was not executed, the user isn't locked into a specific move and can be switched out through the "Pokémon" option in the battle menu.

-The latter excludes the initial offer to switch granted on a new wild encounter, which does not show up because the counter is still active.

-The Pokémon also seems to lose the ability to use the effect of self-targeting moves (I don't know to what extent)

-If the Frenzy move is used again, the counter increments and the user may become confused if that usage would reset the counter. (is the final turn of the Frenzy move)

-Frenzy moves sometimes continue through full paralysis on their second turn if the first one succeeded.
If It would have ended on the second turn, then confusion does not occur until the first turn thrash is selected again.

Link to Discord's Bug report (Thrash Breaking the option to swap out)
https://discord.com/channels/1125469663833370665/1247785975518597191

### Expected behavior

Thrash's counter should properly reset when it isn't used successfully

### Screenshots / Videos

Failing

https://github.com/user-attachments/assets/049af0b7-66f1-4ee3-a405-f1409a4475ca

https://github.com/user-attachments/assets/b6ece742-8d04-4537-889c-15d91727a23b

Paralysis 

https://github.com/user-attachments/assets/b56ae39e-9c54-4766-b7ea-35bd6729be0d

Self-target moves don't "work" when the thrash counter is higher than 0 (fails to raise stats)

https://github.com/user-attachments/assets/71c021c0-1c2e-4824-8c8a-4e6c93806b2e

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

### Additional context

-Frenzy moves sometimes incorrectly continue through full paralysis if used successfully on the first turn. The pokemon is  paralyzed on the 2nd turn, and uses it successfully and gets confused on the 3rd.
([Bug] Frenzy moves wont stop by paralyze #3718)

-When used on the last turn and a Frenzy move misses, the user is correctly confused.

**Comment by Snailman11** [comment]
Here was an old fix
https://github.com/pagefaultgames/pokerogue/pull/3041

**Comment by geeilhan** [comment]
Issue: Somehow the frenzyMissFunc in move.ts did not run, should a frenzy move fail. As a result the turnCount did not reset properly.

https://github.com/pagefaultgames/pokerogue/blob/2f212f52eb8808bd60c4271835ba38d89158501a/src/data/move.ts#L4868C1-L4876C1

Fix: frenzyMissFunc is called to reset the frenzy values after Thrash is being cancelled due to a Status effect.

https://github.com/geeilhan/pokerogueFork/blob/4bbf9e8b4a8f5fba425e93b5a358677458cd8433/src/phases/move-phase.ts#L431-L433

P.S.: This is my first ever contribution ever. Please give me feedback should there be issues with coding conventions, commit style, etc.
