### ISSUE TITLE
[Bug][Localization] 技能 格斗暴冲 中文描述与游戏不符

### ISSUE THREAD

**Issue by Sepulchar** [pagefaultgames/pokerogue#4280]
![image](https://github.com/user-attachments/assets/08d1f7b5-f2ab-4890-9791-15633ba45274)
![image](https://github.com/user-attachments/assets/dd72c7ee-435d-4e81-a395-3a9cca639365)
中文描述中有“此招式可以命中幽灵属性的宝可梦。”，而英文描述中无。
游戏表现与英文描述相符。

https://github.com/user-attachments/assets/469ce22c-0820-4c19-8712-c775df5d594e

对比神奇宝贝百科 https://wiki.52poke.com/wiki/%E6%A0%BC%E6%96%97%E6%9A%B4%E5%86%B2%EF%BC%88%E6%8B%9B%E5%BC%8F%EF%BC%89 与Bulbapedia https://bulbapedia.bulbagarden.net/wiki/Combat_Torque_(move) ，同样为中文版存在该描述但英文版无。
暂时未能确认宝可梦朱紫中该技能效果。

**Comment by chaosgrimmon** [comment]
> [Bug][Localization] The Chinese description of the skill Fighting Rage does not match the game #4280
> 
> The Chinese description says "This move can hit Ghost-type Pokémon.", but the English description does not.
The game performance matches the English description.
> 
> Comparing Pokémon Encyclopedia https://wiki.52poke.com/wiki/%E6%A0%BC%E6%96%97%E6%9A%B4%E5%86%B2%EF%BC%88%E6%8B%9B%E5%BC%8F%EF%BC%89 and Bulbapedia https://bulbapedia.bulbagarden.net/wiki/Combat_Torque_(move) , the Chinese version has this description but the English version does not.
The effect of this skill in Pokémon Vermillion has not yet been confirmed.

![image](https://github.com/user-attachments/assets/3b9543e0-b026-4c2e-9a0a-4c4a3b11fd1a)
![image](https://github.com/user-attachments/assets/ff113c9a-d976-47b4-bb07-ed7a141f0599)

![image](https://github.com/user-attachments/assets/f32c5c4b-c91c-496f-a564-19fba14c7945)

Seems like the translation was added in https://github.com/pagefaultgames/pokerogue/commit/cd9e0665242e4bc05547c2c19a00b7b7dccb6307
![image](https://github.com/user-attachments/assets/1864ec4c-cf70-4865-92bf-625fb46005b1) back in May
![image](https://github.com/user-attachments/assets/a610e182-4d04-4571-acb8-f0e53940873e)

**Comment by chaosgrimmon** [comment]
![image](https://github.com/user-attachments/assets/107fbf92-5037-4b86-911c-76e0fbd9441e)
Bulba doesn't have a description for a signature move of an uncatchable boss enemy, understandably, so I do think it's up to the localisation teams to decide what would fit best, presumably without the "affects GHOST-types" if that's not actually the case.

**Comment by Snailman11** [comment]
![Uploading Screenshot_20241208-064607.png…]()
