### ISSUE TITLE
[Bug] True force-switch (Roar, Whirlwind, Circle Throw, Dragon Tail...)

### ISSUE THREAD

**Issue by flx-sta** [pagefaultgames/pokerogue#4296]
## Describe the bug

Right now the player can choose their Pokemon which makes these moves actually beneficial for the player, instead of "punishing" him

## Expected behavior

These moves should do a proper force-switch meaning choosing a Pokemon at random.
This would also match the behavior from the original games.

## Additional context

There was a PR https://github.com/pagefaultgames/pokerogue/pull/1927 but unfortunately it was abandoned and is now too out of date to adopt it.
<sub>The original author has no intention to update it either</sub>

**Comment by EvasiveAce** [comment]
I am going to work and fix it.
