### ISSUE TITLE
[Bug] mono type challenge ,Baton Pass

### ISSUE THREAD

**Issue by xiaolizhang77** [pagefaultgames/pokerogue#4325]
### Describe the bug

In a mono type challenge, you can use "Baton Pass" to switch in a Pokémon of a different type.

### Expected behavior

In a mono type challenge, you can use "Baton Pass" to switch in a Pokémon of a different type.

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Chrome

**Comment by Snailman11** [comment]
Does not seem to occur anymore


https://github.com/user-attachments/assets/d2a5637d-9a0d-47d4-8cef-2ca44f51360e


https://github.com/user-attachments/assets/c5062639-2fae-4891-8bf2-3cbc3a94d7b0
