### ISSUE TITLE
[P1 Bug][Beta] Game crashing when using the in game Retry option

### ISSUE THREAD

**Issue by MokaStitcher** [pagefaultgames/pokerogue#4341]
### Describe the bug

When losing a run, if the "Enable Retries" setting is enabled and you choose to retry, the game crashes
This happens when losing to a wild encounter, trainer fight, or ME

### Expected behavior

The battle restarts without crashing (unsure what exactly *should* happen for MEs though, some of them may require special attention on that front?)

### Screenshots / Videos

<img width="1175" alt="Screenshot 2024-09-20 at 14 50 11" src="https://github.com/user-attachments/assets/d3271f17-a5b5-490f-94ae-a2cf88f93bfe">

### What OS did you observe the bug on?

Mac/OSX

### Which browser do you use?

Firefox

### Additional context

[Original discord report](https://discord.com/channels/1125469663833370665/1125894949020381285/1286644374859415626) and [screenshot](https://discord.com/channels/1125469663833370665/1125894949020381285/1286648862261383180)

From my testing, seems to have been introduced with Mystery Encounters bug fixes (5888a7758c85fa410eab68c71ee8503143896067)

**Comment by PigeonBar** [comment]
Seems to be fixed by #4369.
