### ISSUE TITLE
Two turn moves with semi-invulnerability (Dig, Dive, etc.) cause moves like Self-Destruct to fail instead of missing

### ISSUE THREAD

**Issue by bennybroseph** [pagefaultgames/pokerogue#442]
Using a move like Dig and then being hit with Self-Destruct results in nothing happening. The user of Self-Destruct should be instead fainting and missing the attack. 

https://github.com/pagefaultgames/pokerogue/assets/13838608/31455e3a-7672-41cb-86f5-19bdca58a442

I tested most other interactions and they appear to work. Protect, Detect, Ghost Types, etc.

**Comment by Latecomerr** [comment]
Can confirm.  
Palafin used Dive!
Koffin used Self-Destruct!
Palafin used Dive!
Koffin used Self-Destruct!  
Koffing fainted!
