### ISSUE TITLE
[Bug] Opponent's Roar locks game if there isn't a Pokemon to switch into for double battle.

### ISSUE THREAD

**Issue by ken-ux** [pagefaultgames/pokerogue#4480]
### Describe the bug

Battle cannot progress if the opponent's Pokémon uses Roar and you don't have more than two Pokémon on your team during a double battle. There is not an option to cancel the switch caused by the roar.

### Reproduction

1. Enter double battle with only two Pokémon on your team.
2. Have opponent use Roar on either of your Pokémon.

### Expected behavior

Roar should fail if there is no Pokémon for the target to switch with.

### Screenshots / Videos

https://github.com/user-attachments/assets/958361d5-fad1-41e6-99f8-547b9f86467e

**Comment by Snailman11** [comment]
https://github.com/pagefaultgames/pokerogue/pull/4481
Fixed By
