### ISSUE TITLE
[Bug] Elite Four Lacey's Excadrill is missing Fairy tera

### ISSUE THREAD

**Issue by Kraziiks** [pagefaultgames/pokerogue#4487]
### Describe the bug

Title, bulbapedia (see screenshot) says the Excadrill should be Fairy tera. Attached a clip of my fight

(this is my first time posting on github, sorry if i put this in the wrong place :>)

### Reproduction

Seems to have just not been implemented, refreshing the fight still brought out a steel/rock Excadrill

### Expected behavior

Should be Fairy tera

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/37c198a5-764e-443d-bf63-17e0e5ac03bd)

https://github.com/user-attachments/assets/67b5d3a7-9e6a-46ce-a391-be9458370bb5

**Comment by Snailman11** [comment]
Pokerogue Has Trainer Team compositions that differ from the main games.  Tera is distributed randomly among their team members.
