### ISSUE TITLE
[Bug] Zekrom is Dragon/Fire instead of Dragon/Electric

### ISSUE THREAD

**Issue by commando112654** [pagefaultgames/pokerogue#4488]
### Describe the bug

Zekrom's typing in my game shows as Dragon/Fire instead of Dragon/Electric

### Reproduction

I got Zekrom through an event which randomizes all of your pokemon based on rarity, so it was a Kyogre that was turned into a Zekrom on stage 33, I have not checked if the typing is wrong just in this niche case or if the typing of Zekrom is just wrong.

### Expected behavior

I expected Zekrom to be Dragon/Electric instead of Dragon/Fire

### Screenshots / Videos

![image_2024-09-28_025921279](https://github.com/user-attachments/assets/edf6c275-d73d-4d38-81b8-617031160acc)

### Session export file

[sessionData_commando112.txt](https://github.com/user-attachments/files/17173535/sessionData_commando112.txt)

### User data export file

[data_commando112.txt](https://github.com/user-attachments/files/17173537/data_commando112.txt)

**Comment by PigeonBar** [comment]
It is intended for that event to slightly randomize your Pokemon's types (Source: #3822).

**Comment by commando112654** [comment]
My b
