### ISSUE TITLE
Camera zoom breaks certain effects

### ISSUE THREAD

**Issue by Scepty-SSB** [pagefaultgames/pokerogue#450]
Having certain large pokemon on the field (such as G-Max Blastoise) causes the camera to zoom out. This is presumably intended, but causes several visual problems, including the Moonblast background effect not taking up the entire screen and new pokemon sprites popping in on the side of the screen and then sliding to their usual location rather than sliding in from offscreen.

**Comment by flx-sta** [comment]
can't repo
`beta` (28c5dc6b59cd363c1dff55550bcaa620e7e29dda)
