### ISSUE TITLE
[Bug] Chilly Reception's Snow is called during Enemy AI Move Selection

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#4513]
### Describe the bug

If an enemy has Chilly Reception in their moveset, it will always summon snow before any move is executed that turn.

Link to Discord's Bug Report (Chilly Reception sets Snow even if it fails to execute (09/29/2024))
https://discord.com/channels/1125469663833370665/1290130181897584670

### Reproduction

1. Encounter an enemy Pokémon with Chilly Reception and three other moves of higher weight.
2. Have a Faster Pokemon 
3. Observe Snow being set regardless of whether the opponent actually has a chance to move.

### Expected behavior

Snow should only be set if Chilly Reception is executed.

### Screenshots / Videos

https://github.com/user-attachments/assets/d9b7c26e-3cdb-48b5-9fda-c91efb9f0cd1

### Additional context

https://github.com/pagefaultgames/pokerogue/issues/4306

Another Bug where a move is semi-executed during Enemy AI Move Selection

**Comment by DustinLin** [comment]
Able to reproduce:

https://github.com/user-attachments/assets/d7a962ec-a39d-48ac-a17c-599a7a090f27
