### ISSUE TITLE
[Bug] Gorilla Tactics Uses Struggle on Reload

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#4531]
### Describe the bug

After being locked into a move, advancing a wave, then reloading a run, a Pokémon with Gorilla Tactics will use Struggle regardless of the move selected.

Discord Bug Post (Gorilla Tactics misbehaves after Save+Quitting)
https://discord.com/channels/1125469663833370665/1289376299831394345

### Reproduction

1. Have Gorilla Tactics and at least one move
2. Use a move successfully against a target
3. Advance the wave
4. Save + quit, then reload the save
5. Attack and Struggle, Bug occurs

### Expected behavior

It should allow you to choose a move; 
-If the move is the banded move, the move should be executed
-if the move is not the banded move, then the "cannot use" message should be shown.

### Screenshots / Videos

Tackle is Banded. On reload Darumaka Water Gun is selected.

https://github.com/user-attachments/assets/ab3113f3-149c-49e4-9fb9-7bd33d47f74b

Drain Punch is Banded. On reload Drain Punch is selected

https://github.com/user-attachments/assets/45da2fab-d379-44e2-8fd1-9258bd6513f4

### Session export file

[sessionData1_DoCaPlaysGames.txt](https://github.com/user-attachments/files/17197599/sessionData1_DoCaPlaysGames.txt)

**Comment by PigeonBar** [comment]
The game doesn't seem to be able to store the locked move correctly.

The battler tag data that the game attempts to save:

![20240930 Gorilla Tactics Tag 1](https://github.com/user-attachments/assets/e8c7e9ee-eb83-4076-b779-bc1451a7d2ef)

The battler tag data that gets loaded upon reload (`moveId` changes to 0):

![20240930 Gorilla Tactics Tag 2](https://github.com/user-attachments/assets/a1886312-b13b-4178-a278-70d1ca532de0)

**Comment by frutescens** [comment]
Working on the fix -> https://github.com/pagefaultgames/pokerogue/pull/4536
