### ISSUE TITLE
[P3] "Rapid increase" reported when max number was reached

### ISSUE THREAD

**Issue by flx-sta** [pagefaultgames/pokerogue#4537]
### Describe the bug

When the max number of a stat increase was reached, it doesn't show an info that it can't increase further but reports that it was `rapidly increased`

### Reproduction

1. Pick an attack that increases stats
2. Keep using it till the max number (+6) is reached
3. Keep using it and read what the message says (see video)

### Expected behavior

It should tell the player that it can't be increased any further instead

### Screenshots / Videos

https://github.com/user-attachments/assets/6ca597f9-84fa-4334-8229-a2da2a5cbbe4

### Additional context

- Apparently it was introduced with the stats refactor
- Discord Threads:
    - https://discord.com/channels/1125469663833370665/1282189311101501463

**Comment by PigeonBar** [comment]
Just wanted to add that this also occurs for stat drops:

https://github.com/user-attachments/assets/492c7de7-30fc-4713-af94-8404f238aced
