### ISSUE TITLE
Where are the savestates?

### ISSUE THREAD

**Issue by k4li-admin** [pagefaultgames/pokerogue#454]
Hey, 

first time creating an issue so please excuse any mistakes.

Im currently trying to dockerize pokerogue, and i just want to know, where the savestates are. Is there a file i can reference, to have a persistant save state?

I would also be happy to contribute my dockerfile/container to the project if it works in the end.

Great project!!

**Comment by Dakurei** [comment]
I don't think it's necessary to do it a 3rd time 😅

(Look at #98 and #279)

**Comment by k4li-admin** [comment]
Oh sorry, i did search for docker but found nothing. Thanks for the fast reply tho!

**Comment by Dakurei** [comment]
No problem 👍
