### ISSUE TITLE
[Bug] Egg summary view does not refresh 

### ISSUE THREAD

**Issue by Solarer** [pagefaultgames/pokerogue#4556]
### Describe the bug

Hatched a bunch of eggs and entered summary view to see all at once (first egg was a Caterpie).
After a couple of battles, more eggs hatched and I entered the summary view again. Even though the first egg was a kapador, it still showed EV values, nature and Name of the Caterpie. Moving the cursor back and forth refreshed the view and correct values were displayed.

### Reproduction

See above

### Expected behavior

See above

**Comment by MokaStitcher** [comment]
Already fixed here #4507 
Will get propagated with the next update

**Comment by Solarer** [comment]
Sorry. Only searched the open issues for duplicates.
Thanks for the hard work
