### ISSUE TITLE
[Bug] Metal Burst causes game to crash if intended target faints

### ISSUE THREAD

**Issue by seanrmon** [pagefaultgames/pokerogue#4575]
### Describe the bug

Metal Burst does not seem to handle the case where the pokemon that uses Metal Burst takes damage, then that target gets KO'd before that pokémon's turn starts.

### Reproduction

[sessionData_metalburstcrash.txt](https://github.com/user-attachments/files/17261538/sessionData_metalburstcrash.txt)

Use Water Spout and Metal Burst. See video below.

### Expected behavior

Metal burst should just fail in this case

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/c525d268-3437-4fe2-bb89-4f4a005094fb)

https://github.com/user-attachments/assets/2f3fd6ca-d992-48bc-b7b3-80aed08c1918

### Additional context

This was seen on the beta branch but when trying the same set-up on main, the crash did not happen. So I believe this bug was recently introduced.

**Comment by PigeonBar** [comment]
https://github.com/user-attachments/assets/8a060792-484a-4b1f-82fd-38baa41954e1

Testing save file:

[20241004 Metal Burst Crash.prsv.txt](https://github.com/user-attachments/files/17265121/20241004.Metal.Burst.Crash.prsv.txt)

Additional testing notes:
- Crash does not seem to occur on main
- Crash does not seem to occur when using Counter or Mirror Coat
