### ISSUE TITLE
[Bug] Pollen Puff Damages Ally Before Healing

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#4594]
### Describe the bug

When used in a double battle against an ally, Pollen Puff damages the ally before healing it.

Link to Discord's Bug Report (pollen puff does not heal)
https://discord.com/channels/1125469663833370665/1289355443394842686

### Reproduction

Use Pollen Puff on an Ally

### Expected behavior

It should only heal when used against an ally in doubles.

### Screenshots / Videos

https://github.com/user-attachments/assets/74a1df55-dee1-413a-942b-d3778b50e7ca

**Comment by frutescens** [comment]
Might be a while before I can get to it, but the Heal Block-related changes are unrelated to this. Somehow the move's category change / handling changed during the time before the most-recent beta. Those are the notes from my quick research into it when the bug was first discovered.
