### ISSUE TITLE
[Bug] Imprison Crashes the Game when Used Against the Player with an Invalid Pokemon in the Second Slot

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#4605]
### Describe the bug

The game crashes when an Enemy Pokémon uses Imprison while the Player has an Invalid Pokémon for a Challenge occupying the second Party Slot.

### Reproduction

Double battle in challenges where you have an invalid Pokémon in the second Party Slot.
Encounter an opponent that uses Imprison.

### Expected behavior

It should restrict active Pokemon's moves without Crashing

### Screenshots / Videos

Fairy Monotype, Silvally is Normal

https://github.com/user-attachments/assets/cf134ffc-eebf-42c0-8762-99160ab1c96c

![Screenshot (384)](https://github.com/user-attachments/assets/bd88b862-8591-4ded-9a71-32b6b1e61167)

### Session export file

[ImprisonCrash.txt](https://github.com/user-attachments/files/17274359/ImprisonCrash.txt)

**Comment by frutescens** [comment]
Will forget the solution otherwise but I will add the fix to #4536 tomorrow or Friday

![image](https://github.com/user-attachments/assets/3545ccbd-99fd-4fc7-9841-a83636c6cff3)
