### ISSUE TITLE
[Bug] Game crash involving Ditto, Reviver Seed, and Sketch

### ISSUE THREAD

**Issue by Fubs** [pagefaultgames/pokerogue#4610]
### Describe the bug

I have a ditto with the impostor ability. The ditto is holding a reviver seed, knows sketch as one of its base moves (unused up until this point). Opposing team includes a G-Max charizard, an aegislash, a zacian, and a cinderace.

Ditto switches transforms into G-Max charizard, and KO's the opposing G-Max charizard. Then opponent sends in zacian. Zacian uses magical torque, which inflicts confusion on the ditto but does not KO it. Ditto KO's the zacian, and opponent switches in aegislash. Ditto KO's aegislash, and opponent switches in cinderace.

At this point, opponent's pokemon is cinderace, and my ditto (transformed into G-Max charizard) is still confused.

The first turn after cinderace comes out, ditto's confusion procs and it hurts itself. The opposing cinderace uses bolt strike and KO's the ditto. Ditto's reviver seed activates and ditto is revived. Ditto is now alive and back in its base form.

The second turn, ditto attempts to use sketch to copy bolt strike. The game writes this glitchy message:
```
Ditto sketched
!
```
And then after selecting "fight" on the next turn, the menu area becomes blank, but my cursor can still move aroud, as if the moves become invisible. Upon selecting a move though, the game crashes to a black screen.

### Reproduction

Set up this situation:
- A ditto that:
  - has the impostor ability
  - is transformed into G-Max charizard
  - is holding a reviver seed
  - is at low hp (enough to get one hit KO'd)
  - is confused

- A cinderace that:
  - knows bolt strike
  - is at low hp
  - is paralyzed
 
On the first turn: have ditto hurt itself from confusion and get KO'd by bolt strike. Then ditto will be revived back to its base form from the reviver seed. On the second turn: ditto uses sketch to copy bolt strike, and the game should glitch out as described in the previous section.

### Expected behavior

The revived ditto should be able to copy bolt strike with sketch without crashing the game.

### Screenshots / Videos

https://github.com/user-attachments/assets/812a8196-0a14-4059-99a4-8fe59f9b49c4

### Session export file

[session.txt](https://github.com/user-attachments/files/17284748/session.txt)

### User data export file

[data.txt](https://github.com/user-attachments/files/17284751/data.txt)

### Additional context

Browser/OS: Firefox on linux

**Comment by Snailman11** [comment]
Prob just need rev seed and sketch, if sketch is trying to sketch the move which KO'd it.
