### ISSUE TITLE
[Bug] Repeated Pokemon ID's in Daily Runs

### ISSUE THREAD

**Issue by PigeonBar** [pagefaultgames/pokerogue#4621]
### Describe the bug

Original report: https://discord.com/channels/1125469663833370665/1125894949020381285/1293243631729115146

In Daily Runs, the Wave 1 wild Pokemon can generate with the same ID as one of the three starting Pokemon. In this screenshot, the party contains the three starting Pokemon and then the Wave 1 wild Nidorino that I caught. Notice that two Pokemon have the same ID of 3378356891:

![20241009 Daily Run IDs](https://github.com/user-attachments/assets/dd313b63-f481-4f9d-9258-9c84a0de1e8c)

This occurs because of this `scene.resetSeed(1)` call, which causes the RNG state for generating the three starting Pokemon to be the same as the RNG state for generating the Wave 1 wild Pokemon:

https://github.com/pagefaultgames/pokerogue/blob/0a4c12387b5992e1f14f53a0f8e6b493a0390ad0/src/phases/title-phase.ts#L195-L199

### Reproduction

Start any daily run, and the Wave 1 wild Pokemon will sometimes have the same ID as one of the three starting Pokemon (depends on the RNG for the day).

### Expected behavior

Different Pokemon should not have the same ID.

### Session export file

[20241007 Daily Run.prsv.txt](https://github.com/user-attachments/files/17308220/20241007.Daily.Run.prsv.txt)

### Additional context

#4505 fixed this bug for non-Daily modes, but did not fix this bug for Daily runs.

**Comment by MokaStitcher** [comment]
Oh, I had checked for this when fixing the other duplicate issue, but assumed it was fine because they would be generated one after another without resetting the seed in between, my bad...
