### ISSUE TITLE
[Beta][P3] Enemy used PP flyout does not count down

### ISSUE THREAD

**Issue by MokaStitcher** [pagefaultgames/pokerogue#4622]
### Describe the bug

When an enemy uses a move for the first time the battle flyout updates and shows the move and correct PP, but every time the move is used after that the PP does not change

### Reproduction

Start any battle and stall while the opposing Pokemon uses its moves

### Expected behavior

The PP count show update for every move used

### Screenshots / Videos

Battle flyout after 4 turns on main:
<img width="750" alt="_pp_main" src="https://github.com/user-attachments/assets/74214f17-8e3d-4621-8c88-9f482d479fd2">

Battle flyout the same 4 turns on beta:
<img width="750" alt="_pp_beta" src="https://github.com/user-attachments/assets/7a596f16-ff8e-49e8-8dfd-00aa2d8d585c">

### Session export file

For the same battle as the screenshot, keep using dragon dance

[sessionData3_pp.txt](https://github.com/user-attachments/files/17309982/sessionData3_pp.txt)

### Additional context

I confirmed that this has been introduced with PR #3974, probably an issue with the `MoveUsedEvent` not being called in the same way as before

**Comment by Snailman11** [comment]
Discord's Report (10/6/24(beta) eternatus pp not going down while using moves (possible visual error))
https://discord.com/channels/1125469663833370665/1292618750104703087
