### ISSUE TITLE
[Bug] OHKO Move Type Hints Display a "falsex" when Targeting Immune Enemies

### ISSUE THREAD

**Issue by hopesgit** [pagefaultgames/pokerogue#4634]
### Describe the bug

When using Sheer Cold (this likely works with other OHKO moves), the type effectiveness hint displays an odd value

### Reproduction

In Display Settings, be sure to have Type Hints ON.
Bring an Ice-type Pokemon that knows Sheer Cold.
Target another Ice-type Pokemon with Sheer Cold.

### Expected behavior

I might expect a 0x instead of falsex. Or some other indicator that it won't have any effect.

### Screenshots / Videos

![Screenshot 2024-10-10 111929](https://github.com/user-attachments/assets/e46164a6-2c45-4e6a-9f6d-2f20b9e47291)

### Session export file

[sessionData_kenna_puppers.txt](https://github.com/user-attachments/files/17332081/sessionData_kenna_puppers.txt)

### User data export file

[data_kenna_puppers.txt](https://github.com/user-attachments/files/17332106/data_kenna_puppers.txt)

**Comment by Snailman11** [comment]
Discord's Bug report
