### ISSUE TITLE
[Bug] No visual updates after lvl decrease by event

### ISSUE THREAD

**Issue by Solarer** [pagefaultgames/pokerogue#4669]
### Describe the bug

I encountered a lady who could see my future and wanted to change my Pokemon team. I declined her offer. As a result, the levels of my Pokemon were reduced. I had a Miraidon in first position and its level was 104 (currently maxed out). While its level was also reduced (it started to gain exp and level ups again) the display in the battle screen still showed its current level to be 104.
There was no visual update.

### Reproduction

See above 

### Expected behavior

See above

**Comment by Snailman11** [comment]
First one on github
https://discord.com/channels/1125469663833370665/1289842295751053354
