### ISSUE TITLE
[Question] where are you guys setting the PersistentStats 

### ISSUE THREAD

**Issue by marcolbx** [pagefaultgames/pokerogue#4685]
### Is your feature request related to a problem? Please describe.

Im reading the code, however I do not find the code related to:

When a pokemon levels up, then it gets +2 AtK, +1Speed and so on.

### Describe the Feature

Its a question

**Comment by Tempo-anon** [comment]
I don't quite understand the question. Are you asking where a Pokemon's stats are set? Or for the UI that shows the increase in stats upon level up?

If you're asking for the first part of where a Pokemon's stats are calculated, I'd check `pokemon.ts` for `getStat` which is how the mainline games calculate stats too (it just uses a formula of the species' base stat along with current level and modifiers)

If it's about the popup that displays stat changes you are looking for [this line](https://github.com/pagefaultgames/pokerogue/blob/beta/src/ui/battle-message-ui-handler.ts#L176) in battle-message-ui-handler that's called from the `level-up-phase`

**Comment by marcolbx** [comment]
I found it!
