### ISSUE TITLE
[Bug] Status immunity abilities don't heal associated status if the Pokemon is inflicted with the status

### ISSUE THREAD

**Issue by YamiTheYin** [pagefaultgames/pokerogue#4686]
### Describe the bug

The abilities Limber, Insomnia, Immunity, Magma Armor, Water Veil, Vital Spirit, Water Bubble, Pastel Veil, & Thermal Exchange don't heal their corresponding non-volatile status if the ability holder has the status inflicted on it.
Additionally, the abilities Oblivious & Own Tempo don't heal their corresponding volatile status.

### Reproduction

Either use a Mold Breaker Pokemon and inflict the status on the Pokemon with the immunity ability or use a Neutralizing Gas Pokemon to inflict the status then exit the field so the ability is regained and activates.

### Expected behavior

The abilities above should heal the associated status immediately after it's inflicted or heal the status as soon as the ability is gained.
Pastel Veil when being ignored only heals poison on the Pokemon holding the ability not the ally, however gaining the ability will heal poison from both the ability holder and the ally. ([Showdown Description](https://dex.pokemonshowdown.com/abilities/pastelveil))

**Comment by Snailman11** [comment]
Closing this in favour of my own issue
https://github.com/pagefaultgames/pokerogue/issues/4972
-It has videos
