### ISSUE TITLE
[Bug] Nightmare does not work properly

### ISSUE THREAD

**Issue by muscode13** [pagefaultgames/pokerogue#4691]
### Describe the bug

Nightmare does not work properly. It does not trigger the turn it is applied and then the following turn it triggers twice in the middle of the move phase. This leads to the afflicted pokemon losing 50% of their health in one turn

### Reproduction

Have a sleeping Pokemon and use Nightmare on it. 

In the game the only way to do this is get a Hypno, use a memory mushroom on it to get Nightmare. 

### Expected behavior

Nightmare should trigger the turn it is applied, if the pokemon is asleep.
Nightmare should only trigger once in a turn.
Nightmare should happen after the Pokemon use moves, not in the middle.

Here is a Pokemon Showdown simulation of how it should work: https://replay.pokemonshowdown.com/gen9customgame-2226194365-m29ru2zbt5mq1twez6wgp0uw3uvvtq6pw

### Screenshots / Videos

https://github.com/user-attachments/assets/42fa38d0-58fb-4ad2-9e97-13a34b6119a1

### Session export file

[sessionData3.txt](https://github.com/user-attachments/files/17443341/sessionData3.txt)

### Additional context

On a side note, only Hypno can learn Nightmare in the game but Munna, Darkrai, and the Gastly line should be able to learn it [too](https://bulbapedia.bulbagarden.net/wiki/Nightmare_(move))

I believe it was removed in Gen 8, maybe if its too much trouble to code in a fix you could remove it? I don't think it would be missed.

**Comment by Snailman11** [comment]
Link to Discord's Bug Report (Nightmare does not work properly)
https://discord.com/channels/1125469663833370665/1297087407207874641
