### ISSUE TITLE
[Bug] Defeats from some Mystery Encounters are not displayed in Run History correctly

### ISSUE THREAD

**Issue by frutescens** [pagefaultgames/pokerogue#4706]
### Describe the bug

Defeats from some Mystery Encounters are not parsed correctly by the Run History UI. This issue looks through all 22 original Mystery Encounters and checks if their lose conditions are correctly parsed by the UI currently or not. 

### Affected Mystery Encounters
- [x] Trainer MEs <-- Covered by #4716 
- [x] Mysterious Chest <-- Covered by #4716 as well. 
- [ ] Fiery Fallout and Lost at Sea <-- Still drafting an idea

### Reproduction

To reproduce this bug, please refer to the labeled session data attached.

### Expected behavior

The trainer + trainer's team / wild Pokemon that defeated the player.

**Comment by frutescens** [comment]
### Mysterious Challenges
Status: Broken
[Run History File -> mysteriousChallenges.txt](https://github.com/user-attachments/files/17482935/mysteriousChallenges.txt)

**Comment by Snailman11** [comment]
Link to Discord's Bug Report (Run history trainer not showing up)
https://discord.com/channels/1125469663833370665/1298383872358092872
**-Bug Type Superfan**
