### ISSUE TITLE
[Bug] The game crashed after a long loading and impossible to open it anymore

### ISSUE THREAD

**Issue by JeremyBesson** [pagefaultgames/pokerogue#4740]
### Describe the bug

The game crashed with a loading interface. 
Then I open it again, a "please contact admin message" message is shown since this moment and it's impossible to use any button. 

### Reproduction

Login on my account 

### Expected behavior

Be able to open the game again 

### Screenshots / Videos

During the first crash: 
![image](https://github.com/user-attachments/assets/aacbf3f8-3306-44f9-81fb-16a737f05b3d)
Then this message: 
![image](https://github.com/user-attachments/assets/b6abf319-924a-414c-ac8a-dd4c7eb9641a)

### Additional context

I have this error message in js logs: 

failed to update active session: Error 1114 (HY000): The table 'activeClientSessions' is full
loading-scene-rJQpBHaq.js:834:47305
    loadSystem https://pokerogue.net/assets/loading-scene-rJQpBHaq.js:834

**Comment by MokaStitcher** [comment]
The server is currently down with no estimated end time at the moment.
Announcement of it getting back up will get posted in the official Discord server

**Comment by MokaStitcher** [comment]
server back up
