### ISSUE TITLE
[Bug] Encore and Disable do not Interact Correctly

### ISSUE THREAD

**Issue by Snailman11** [pagefaultgames/pokerogue#4745]
### Describe the bug

Using Disable on a Pokémon that has been Encored allows that Pokémon to select any not-Disabled move.

Torment and Encore allow a Pokemon to choose any not-Tormented move

Link to Discord's Bug Report (Encore Disable doesn’t work properly)
https://discord.com/channels/1125469663833370665/1234291385457311836

### Reproduction

Use Encore, then use Disable. Observe that the opposing Pokemon isn't struggling

### Expected behavior

They should be forced to Struggle when affected by both Encore and Disable

https://replay.pokemonshowdown.com/gen9customgame-2232270265-ytb6vvnkpnucliw0h47jq7bxpps1uy9pw

Torment Alternates Struggle if the target only has two moves

https://replay.pokemonshowdown.com/gen9customgame-2232301078-ygxd6gkbglyxt3b5og2cjscqarcnm94pw

### Screenshots / Videos

Opponent

https://github.com/user-attachments/assets/d9f246a2-4f3f-432c-ad42-01038561f71d

Player

https://github.com/user-attachments/assets/74b2126a-eda3-4ca4-a367-94b881a870e1

Torment

https://github.com/user-attachments/assets/82aeed75-ef8a-4427-bab0-a8e4963351db

### Additional context

In `command-phase.ts`, Encore gets ignored when the encored move is unusable (e.g., due to Disable)
![EncoreDisableCode](https://github.com/user-attachments/assets/17556bf0-359f-4ba6-9b84-1abfbf193c22)

-PigeonBar

**Comment by frutescens** [comment]
Looking into this bug and I think its related to how EncoreTag is not a move-restriction battler tag. Think it should be fixed with a change to do that. Will work on it soon.

**Comment by frutescens** [comment]
PR is in progress --> https://github.com/pagefaultgames/pokerogue/pull/4805
