### ISSUE TITLE
[Bug] Pokerus doesn't show up daily on local download version

### ISSUE THREAD

**Issue by jackfrancismurphy** [pagefaultgames/pokerogue#4772]
### Describe the bug

When I start up Pokerogue sometimes there is not a daily selection of pokemon with the Pokerus virus

### Reproduction

I am running on the locally downloaded version of Pokerogue

### Expected behavior

There should be an option daily of three Pokemon with the Pokerus virus, am I right in believing that?

**Comment by MokaStitcher** [comment]
Are you sure that is the case? By default the Pokemon you don't own are not shown in starter select, can you double check if you show them with the filters that there is no Pokérus?
