### ISSUE TITLE
[Bug] Battles against wild Aegislash display a message after defeat

### ISSUE THREAD

**Issue by PLMMJ-FH** [pagefaultgames/pokerogue#4774]
### Describe the bug

After defeating a wild Aegislash, the game will display "Wild Aegislash reverted to its original form!" as if it has used King's Shield. May be an Endless mode bug again, since this is from the same run with the double battle item thing.

### Reproduction

Fight a wild Aegislash. Defeat it.

### Expected behavior

No message should display unless it has a Reviver Seed and uses King's Shield.

### Screenshots / Videos

![What Aegishlash](https://github.com/user-attachments/assets/293e8760-08b6-4588-b6eb-343d1c8f5f0c)

**Comment by Snailman11** [comment]
It reverts because on faint, all form pokemon revert to their base form.

Whether this should be taking place at all when not the Player's Pokemon is a good question

**Comment by Snailman11** [comment]
Link to Discord's Post
(Aegislash form revert message plays after KO)
https://discord.com/channels/1125469663833370665/1291865920511279204

**Comment by Snailman11** [comment]
https://github.com/pagefaultgames/pokerogue/issues/4552
Could be related, crash involving wild pokemon that are in their not base form fainting at the same time as player
