### ISSUE TITLE
[Bug] Lycanroc dusk form evolution

### ISSUE THREAD

**Issue by Srikar441** [pagefaultgames/pokerogue#4822]
### Describe the bug

I am unable to evolve lycanroc into dusk form with the ability own tempo. I heard it's is a bug so please fix it.

### Reproduction

.

### Expected behavior

I expect the bug to be fixed and lycanroc to evolve in dusk form.

### Screenshots / Videos

.

### Session export file

.

### User data export file

.

### Additional context

.

**Comment by MokaStitcher** [comment]
Already fixed by PR #4762
Just wait for next update
