### ISSUE TITLE
[Bug] Parental Bond/Double Battles

### ISSUE THREAD

**Issue by ggarlitz** [pagefaultgames/pokerogue#4825]
### Describe the bug

It looks like there is an issue with Parental Bond in double battles. I'm not sure if it's an issue with all spread moves or just hyper voice, but when I use hyper voice on my Farigiraf with the Parental Bond Passive it only hits 1 time in double battles, seems to work fine for single battles. 

That behavior happens even when there's only one target remaining in double battles. With both Multi-lense(s) and Parental Bond it does hit (1 + (# of Multi lense(s))) times, but it should be hitting up to (2 x (1 + (# of Multi Lense(s)))) times. It also looks like every hit only has the multi lense damage debuff, rather than every other hit having both the multi lense and parental bond damage debuffs. 

Again I haven't tested this with any other spread moves, and all single target moves seem to behave as expected in both singles and doubles. I know Hyper Voice specifically has this issue though. I also haven't tested this on any Parental Bond Pokemon besides Farigarif, so it may be an issue with just Parental Bond as a Passive rather than both as a Passive and as an Ability.

### Reproduction

In Endless mode using Girafarig or Farigaraf that knows the move hyper voice and with the Parental Bond Passive Unlocked and in Use, get into a double battle and try using the move hyper voice.

### Expected behavior

When using the spread damage move hyper voice in a double battle with Parental Bond Farigiraf, I expected the number of times it hits the target(s) to be:

number of hits = hit up to a max of (2 x (1 + (# of Multi Lense(s)))) times, if applicable stop hitting before max if/when opponent(s) are fainted

with the damage calculation (not including stab, type boosting item, crit, stat, damage roll, or other multipliers not listed in the calculation) for odd hits being:
 
damage on hit = flat damage x Multi Lense(s) Debuff

and for even hits being: 
damage on hit = (flat damage x Multi Lense(s) Debuff) x Parental Bond Debuff

### Session export file

[sessionData_Awesomeking9.txt](https://github.com/user-attachments/files/17684393/sessionData_Awesomeking9.txt)

### User data export file

[data_Awesomeking9.txt](https://github.com/user-attachments/files/17684622/data_Awesomeking9.txt)

### Additional context

Probably worth double checking:
Other Parental Bond Pokemon outside the Girafarig line, whether they have it as a passive or ability.
Other spread moves besides Hyper Voice
Multi Lense interactions
Spread Moves in Double Battles where 1 side is fainted
Behavior in Other Modes besides Endless

**Comment by PigeonBar** [comment]
This is intended: Moves that target multiple Pokemon at once do not activate Parental Bond.
Source: [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Parental_Bond_(Ability))

**Comment by ggarlitz** [comment]
> This is intended: Moves that target multiple Pokemon at once do not activate Parental Bond. Source: [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Parental_Bond_(Ability))

I've never heard of that before, but that makes sense. 

It looks like there is still a minor bug associated with this though as per bulbapedia:
"if it can only hit a single Pokémon, such as in a Single Battle or if using a move that can hit multiple targets when only one target is in range, it will strike twice. If a move could hit multiple Pokémon but only hits one due to missing the other Pokémon, it will only strike once."

Based on this it sounds like parental bond should be activating for hyper voice in double battles where only one side has a remaining opponent, but it looks like it's still not activating in those cases.
