### ISSUE TITLE
Killing a pokemon does not trigger contact effects

### ISSUE THREAD

**Issue by PaulBeslin** [pagefaultgames/pokerogue#483]
Abilities such as Static do not get triggered when the attacking pokemon kills the target with a contact move. It is properly triggered when the contact move does not kill.

To reproduce, override the opponent move to be Static, set its trigger chance to 100, and kill it in one hit.

**Comment by ArminOsvath** [comment]
Fixed in: [494](https://github.com/pagefaultgames/pokerogue/pull/494)
