### ISSUE TITLE
Swap A and B option doesn't work with the keyboard, only the gamepad.

### ISSUE THREAD

**Issue by Jaizu** [pagefaultgames/pokerogue#487]
Tested in the following scenarios:
- [ ] Options Menu
- [ ] Main menu
- [ ] Starter choose screen
- [ ] Battle 

![chrome_ibjABsM8se](https://github.com/pagefaultgames/pokerogue/assets/18596778/fa581b6e-c8a2-47b7-af88-63f77abd0387)

Edit: Is is possible that it only affects game controllers and not they keyboard binding? If so, I should rename my issue.

**Comment by Kiriox94** [comment]
Indeed, it's only for the gamepad, and in my case it works very well.

**Comment by Jaizu** [comment]
It should affect both imo ^^

**Comment by Jaizu** [comment]
This should wait for #429

**Comment by Flashfyre** [comment]
If we make it affect both, I'd like to make it default to on.

**Comment by bennybroseph** [comment]
When I added the setting, it was never intended to affect both. This isn't a bug but rather a new feature suggestion.

**Comment by Greenlamp2** [comment]
Final call: no swap for keyboard, this issue can be closed.

**Comment by lolbinarycat** [comment]
this behavior is very confusing, especially since the Accept/Cancel mapping is the opposite of what retroarch does by default.

**Comment by Jaizu** [comment]
No, this is not completed, only gamepad is supported to swap A/B button, keyboard should have the option in some form too.

**Comment by bennybroseph** [comment]
That's intentional

**Comment by Greenlamp2** [comment]
i'm working on the full remaping of the gamepads, next will be the keyboard, don't worry, i've heard you
https://github.com/pagefaultgames/pokerogue/pull/685
