### ISSUE TITLE
[P1] Crash when replacing a field Pokemon with a catch if Imprison is active

### ISSUE THREAD

**Issue by jopenmolles** [pagefaultgames/pokerogue#4886]
### Describe the bug

After catching a Lampent in a double battle at wave 91 the game freezes when my Gyarados levels up. This does not happen when I defeat the lampent or catch the Gholdengo. Reloading does not help.

In the console the following errors appear:
```
index-yN4aaLV8.js:6492 TypeError: Cannot read properties of undefined (reading 'tags')
    at Zm.removeTag (loading-scene-BeiwXceh.js:836:32601)
    at loading-scene-BeiwXceh.js:283:209160
    at Array.forEach (<anonymous>)
    at OL.onRemove (loading-scene-BeiwXceh.js:283:209146)
    at loading-scene-BeiwXceh.js:839:353631
    at Array.forEach (<anonymous>)
    at MV.lapseTags (loading-scene-BeiwXceh.js:839:353617)
    at YF.start (loading-scene-BeiwXceh.js:821:27340)
    at ZF.shiftPhase (loading-scene-BeiwXceh.js:821:71749)
    at yF.end (loading-scene-BeiwXceh.js:283:180242)
```
```
loading-scene-BeiwXceh.js:836 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'tags')
    at Zm.removeTag (loading-scene-BeiwXceh.js:836:32601)
    at loading-scene-BeiwXceh.js:283:209160
    at Array.forEach (<anonymous>)
    at OL.onRemove (loading-scene-BeiwXceh.js:283:209146)
    at loading-scene-BeiwXceh.js:839:353631
    at Array.forEach (<anonymous>)
    at MV.lapseTags (loading-scene-BeiwXceh.js:839:353617)
    at YF.start (loading-scene-BeiwXceh.js:821:27340)
    at ZF.shiftPhase (loading-scene-BeiwXceh.js:821:71749)
    at yF.end (loading-scene-BeiwXceh.js:283:180242)
```

### Reproduction

1.  Defeat Gholdengo with Arcanine's Flamethrower
2. Throw 2 ultra balls at the Lampent 
3. Release Arcanine to add Lampent to the party
4. Wait for the exp to be shared between the party members
5. Game freezes and two errors appear in the console

### Expected behavior

After catching and leveling up continue to the shop

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/28c14a47-eac3-43c1-9ff1-0eaa889d9908)

### Session export file

[sessionData_jopenmolles.txt](https://github.com/user-attachments/files/17787933/sessionData_jopenmolles.txt)

### User data export file

[data_jopenmolles.txt](https://github.com/user-attachments/files/17787938/data_jopenmolles.txt)

**Comment by Snailman11** [comment]
Similar to
https://github.com/pagefaultgames/pokerogue/issues/4868

**Comment by MokaStitcher** [comment]
The issue seems to happen because the game tries to remove the Imprison tag from Lampent since it's on the field after replacing Arcanine with it. If you replace a Pokemon that's not in battle it doesn't happen

![image](https://github.com/user-attachments/assets/b30b4b63-9155-49dc-b43c-64948f61e1bf)

(also why is there no uppercase to the imprison arena tag, doesn't it have a proper locale field? 💀 )

**Comment by MokaStitcher** [comment]
> Similar to #4868

not sure this is the same since according to their description they didn't replace a pokemon that was in the field. But could be maybe, if they only had one alive pokemon it would put the new catch on the team

**Comment by jopenmolles** [comment]
> The issue seems to happen because the game tries to remove the Imprison tag from Lampent since it's on the field after replacing Arcanine with it. If you replace a Pokemon that's not in battle it doesn't happen

Indeed, when I defeat Gholdengo with Arcanine and damage Lampent with Staraptor and then switch them after being hit with Imprison before catching Lampent and replacing Arcanine for it, the game will just continue to work.

> not sure this is the same since according to their description they didn't replace a pokemon that was in the field

I did not mention it in my description, but I kept the Arcanine in the field while catching Lampent and always replaced him for Lampent.
