### ISSUE TITLE
Furfrou's alternative form Sprites are blurry

### ISSUE THREAD

**Issue by CandleClockwork** [pagefaultgames/pokerogue#489]
I've tested this with the Heart, Star and Diamond trim, and as the title says, both the front and back sprite of the non-standard, non-shiny forms of Furfrou show up as cloudy and artifact-y. A comparison between regular and non-regular to show:

![image](https://github.com/pagefaultgames/pokerogue/assets/22104403/bfeb42a4-e047-4418-a2e5-5201f0e7a56d)
![image](https://github.com/pagefaultgames/pokerogue/assets/22104403/64e0924d-e9d4-4160-b322-f35052f3a1bc)

And likewise, for the back-sprite:

![image](https://github.com/pagefaultgames/pokerogue/assets/22104403/87aa86ff-36c6-4394-96a6-3c978cbfbf9f)
![image](https://github.com/pagefaultgames/pokerogue/assets/22104403/c1fc0acf-1c34-41f7-a93e-943cb8437204)

I've tracked down the sprite sheets that were used for the repository:
https://www.smogon.com/forums/attachments/furfrou-normal-front-png.196215/
https://www.smogon.com/forums/attachments/furfrou-normal-back-png.196214/

And here's a comparison with the sprites pulled directly from the project's repo:
![image](https://github.com/pagefaultgames/pokerogue/assets/22104403/4e904c1d-4ecb-4441-9c2b-415366db59ee)
![image](https://github.com/pagefaultgames/pokerogue/assets/22104403/5516ea8c-eca6-486e-9a29-c0ad8fc3d19a)

Best I can do is provide the spritesheets, as I'm not entirely sure how shiny color palettes are handled in the code.

**Comment by Flashfyre** [comment]
Should be fixed now
