### ISSUE TITLE
CloudNine not indicated to show that is activated

### ISSUE THREAD

**Issue by ClearPL** [pagefaultgames/pokerogue#491]
I today have discovered some kind of weird issue with Sunny Day and Solarbeam. I was playing normally and one moment I have noticed that my Solar Beam was not launched immediately even tho Sunny Day was used 1-2 turns ago (in previous wave). I then reloaded game and confirmed that I was not seeing things.
By the damage taken I suppose the sun is probably in effect or in the current wave the weather have bugged because after reusing Sunny Day I received similar damage.

Very important is before this wave everything worked properly. And it's not the first time I used sunny day in this biome (it lowers damage from water moves).

Seed: PSBdm8Zph5iOpi65XkgWrjLa
Biome: 7
Wave: 126
From a console:
"enemyModifiers": [], "arena": { "biome": 7, "weather": { "weatherType": 1, "turnsLeft": 2 },

https://github.com/pagefaultgames/pokerogue/assets/33186959/d62cfb62-5ee9-4870-99e9-03a36c343101
-----

Sorry, I'm stupid. Just remembered that I fought against Golduck. It was long time since I played a game. Forgot about Cloud Nine ability.
But this is something to consider - in normal games as far as i remember there was always indicator about Cloud nine ability in effect. If it's hard or impossible to add it during the effecfts it deactivates, maybe you could just inform about ability at the entering at the field?

**Comment by ClearPL** [comment]
Also I just tested that also Morning Sun healed 1/2 of my health instead of 2/3 like it should in harsh sunlight. I'm not sure if it is correlated to this specific issue or it's general bug.

**Comment by ClearPL** [comment]
Via checking the source file and console output i have confirmed that it was Psyduck with ability Cloud Nine:
`[Abilities.DAMP, Abilities.CLOUD_NINE, Abilities.SWIFT_SWIM]`
`"species": 55,
      "formIndex": 0,
      "abilityIndex": 1,`

As that I edited post and subject.

**Comment by Tempo-anon** [comment]
Added an on summon message to cloud nine like air lock. Both of these should probably be localized though
