### ISSUE TITLE
[Bug] Can't work with ip address

### ISSUE THREAD

**Issue by cwycool** [pagefaultgames/pokerogue#4925]
### Describe the bug

I have set up a local server and I'm planning to use reverse proxy to expose it. I can't use it with 192.168.1.102:8000.

### Reproduction

When I access it using localhost:8000, it works fine. I can register, log in, and save the game. However, when I log in using 192.168.1.102:8000, it redirects back to the login screen after each login. How can I resolve this issue?

### Expected behavior

1. How can I resolve this issue? when I try to login It will keep refreshing on this page.
![2](https://github.com/user-attachments/assets/aae1db46-e3bf-4b2a-aaaa-86e21284b002)

### Screenshots / Videos

![1](https://github.com/user-attachments/assets/58d804fe-c9bd-49eb-bf53-7a3c488bae6e)

**Comment by Snailman11** [comment]
Could you screenshot your console in devtools when trying to log in to the website? (F12/Inspect Element -> Console tab)

**Comment by cwycool** [comment]
> Could you screenshot your console in devtools when trying to log in to the website? (F12/Inspect Element -> Console tab)

![1](https://github.com/user-attachments/assets/5cfdec06-5566-4d9e-a056-db719508d4ea)

What specific information do you need, you can let me know and I'll take a screenshot for you.

**Comment by Snailman11** [comment]
Your console tab, there should be small yellow boxes

**Comment by cwycool** [comment]
![3](https://github.com/user-attachments/assets/619e867d-f4c1-4301-843e-879a1c2293d2)
this?

**Comment by flx-sta** [comment]
So I can't really tell from your screenshot, as I'm can't read.... the language shown but it seems you are looking at your local IP via `http`
<img width="107" alt="image" src="https://github.com/user-attachments/assets/c74231f0-bec8-4d54-840c-06f442106ab3">


The Problem is, that we have no mechanic involved, that allows you set a cookie as `not safe`.

---

As a workaround you can adjust the `setCookie` and the `removeCookie` functions in `utils.ts` by removing the `Secure;` in the `document.cookie` string.

```ts

export function setCookie(cName: string, cValue: string): void {
  const expiration = new Date();
  expiration.setTime(new Date().getTime() + 3600000 * 24 * 30 * 3/*7*/);
  document.cookie = `${cName}=${cValue};Secure;SameSite=Strict;Domain=${window.location.hostname};Path=/;Expires=${expiration.toUTCString()}`;
  console.log(document.cookie);
}

export function removeCookie(cName: string): void {
  if (isBeta) {
    document.cookie = `${cName}=;SameSite=Strict;Domain=pokerogue.net;Path=/;Max-Age=-1`; // we need to remove the cookie from the main domain as well
  }

  document.cookie = `${cName}=;SameSite=Strict;Domain=${window.location.hostname};Path=/;Max-Age=-1`;
  document.cookie = `${cName}=;SameSite=Strict;Path=/;Max-Age=-1`; // legacy cookie without domain, for older cookies to prevent a login loop
}
```
