### ISSUE TITLE
account "doesnt exist"

### ISSUE THREAD

**Issue by dipdadronan** [pagefaultgames/pokerogue#493]
I, as well as many others that I've been in the forums, Reddit, and Discord, have encountered an issue that has logged us out of our accounts, and we cannot log back in with the game, stating that the account doesn't exist. If anyone has any advice, it would be appreciated

**Comment by Flashfyre** [comment]
Sessions expire. This is not a bug and normal website behaviour. If it says your account doesn't exist, you're entering it different than when you registered. Accounts do not change names nor disappear. I believe there is an issue with autofill password saving, but if it says your account doesn't exist, I'm fairly certain you're just entering it wrong.

**Comment by dipdadronan** [comment]
I’ve not entered it wrong as, I went through the process of making a new account as well, and the log in message for entering the wrong password is different than from what the message I was reviving. Additionally, I’m seeing posts from multiple users experiencing the same issue.

**Comment by dipdadronan** [comment]
Additionally, I am now not able to create an account using the same username as the test account I created, but I was able to make an account using the username of my first account, meaning that the account was actually removed.

**Comment by Flashfyre** [comment]
As far as I am aware, it is impossible for accounts to get removed or renamed on their own with the current logic. Are you sure it didn't get registered as something different? You can see your username on the summary of any mon in-game if you have any screenshots.

**Comment by dipdadronan** [comment]
I have a screenshot of my Google password manager, but I'm positive this had not been saved incorrectly, as I had logged in multiple times using it.

**Comment by Flashfyre** [comment]
If anyone with this problem has an exported save from the account they're locked out of, that might help narrow down the problem. The username must be different from what was entered on registration.

**Comment by legrand156** [comment]
cela ne change strictement rien

**Comment by Altesscss** [comment]
Hello.. i have use the F12 to have unlimited voucher i know this is bad but i dont play online juste in classic mod, but if i want to play in endless mode i can be banned for my voucher count ? If i can i want delete my old account to create a new with my same username but without any cheat and play normaly, ok i can create a new account but i dont want new username, so the dev can delete my account on ur server to make a new clear account please

**Comment by Altesscss** [comment]
Need help please
