### ISSUE TITLE
[Bug] Multi Lens not properly adding extra attack(s) to multi-hit moves.

### ISSUE THREAD

**Issue by AEMARR** [pagefaultgames/pokerogue#4930]
### Describe the bug

I have a Linoone holding a Multi Lens, and when it uses the move Pin Missile, Linoone is able to only hit with Pin Missile twice, despite base Pin Missile hitting a minimum of twice. I saw that the description of Multi Lens changed, so I assume it might work slightly differently than before, but no matter how it might work now, it should be hitting a minimum of 3 times, not 2.

### Reproduction

Equip a Multi Lens to a Linoone that knows Pin Missile. 
Use Pin Missile until you see the message "Hit 2 time(s)!"

### Expected behavior

I'm not sure which way is the intended way to work now, but I know its either supposed to double the number of hits an attack rolls, or add 1 hit per Multi Lens equipped.

### Screenshots / Videos

https://github.com/user-attachments/assets/34f7d792-b2f8-4a02-a11a-3efd4f00030b

### Session export file

[sessionData2_AEMARR.txt](https://github.com/user-attachments/files/17851244/sessionData2_AEMARR.txt)

### User data export file

[data_AEMARR.txt](https://github.com/user-attachments/files/17851246/data_AEMARR.txt)

### Additional context

This run is endless, and started multiple versions ago, though I don't know which.

**Comment by Snailman11** [comment]
![Uploading Screenshot_20241121-115308.png…]()
