### ISSUE TITLE
[Bug] Soothe Bells affecting Rare Candy friendship gain

### ISSUE THREAD

**Issue by star-krieg** [pagefaultgames/pokerogue#4948]
### Describe the bug

Rare Candies are affected by Soothe Bell friendship gain currently, which does not appear intended since the item describes Soothe Bells increase friendship gained per victory by 50%.

### Reproduction

1) Do a battle on this wave (You should be at Wave 779). KO the opponent with Lunala.
2) Reroll once without item lock to get a Rarer Candy.
3) Check friendship for those with and without soothe bells (I used Keldeo and Smeadinja in my example)
4) Transfer Soothe Bells from Lunala to Smeadinja (so you have a mon that can still gain friendship).
5) Use rarer candy and compare friendship gained by mons with and without soothe bells.
[sessionData3_starkrieg (3).txt](https://github.com/user-attachments/files/17954606/sessionData3_starkrieg.3.txt)

Action would depend on whether this is intended or not. If this is intended, Soothe Bell description needs to change. If this is unintended, friendship from rare candy should not be affected by Soothe Bells.

### Expected behavior

Rare Candy friendship gain should not be affected by Soothe Bell stacks (if the in-game description is correct). All mons should only gain a set amount of friendship from using the Rarer Candy.

### Screenshots / Videos

Smeadinja has 3 soothe bells. It gained 12 friendship (5 + floor(2.5*3)) = 5 + 7 = 12

Before: 
![unknown](https://github.com/user-attachments/assets/1e8edeb9-a427-432a-b992-92326e3fc2c2)
After:
![unknown](https://github.com/user-attachments/assets/adce93e6-d313-4e7b-b023-ab59dfb39c81)

Keldeo fusion gets 5 friendship (as expected)
Before:
![unknown](https://github.com/user-attachments/assets/625c07a1-b180-4382-a032-6b8c032e384a)
After:
![unknown](https://github.com/user-attachments/assets/68aaaff5-254b-4735-abc0-bf8ce424cd03)

### Session export file

[sessionData3_starkrieg (3).txt](https://github.com/user-attachments/files/17954617/sessionData3_starkrieg.3.txt)

**Comment by MokaStitcher** [comment]
If indeed this is not intended, the soothe bell also shouldn't affect candy friendship gain from the Expert Pokemon Breeder Encounter

**Comment by star-krieg** [comment]
Soothe Bell interaction with Rare Candies are intended. This would make the current item description inaccurate, so only the description needs to be fixed.

<img width="393" alt="image" src="https://github.com/user-attachments/assets/853c9501-a040-42df-8cd2-80e41674c647">
