### ISSUE TITLE
[Feature] Possibility for download as rom/gba-file etc.

### ISSUE THREAD

**Issue by Togetik** [pagefaultgames/pokerogue#4957]
### Is your feature request related to a problem? Please describe.

Your game is fire and i would love to play it offline too. There are multiple emulators and handheld-emu-systems that can operate a multitude of formats: from gba to rom to pc ports on a linux-base. Since 'tis the season i can dream, right?
(Yes, there is an app. But app-playing isn't handheld-console-playing)

### Describe the Feature

Downloadable game file as rom/gba...
so we can offline play on our local systems
(for the oldscool fans who want to play on a handheld)

### Additional context

Love your work!

**Comment by DayKev** [comment]
This isn't possible for many reasons. You can play on any mobile device that supports modern web browsers (ie: phone, tablet, Steam Deck, etc), but it's not a GBA/etc game. An offline mode is a wanted feature though.
