### ISSUE TITLE
[Bug] Baton Item not working

### ISSUE THREAD

**Issue by Togetik** [pagefaultgames/pokerogue#4977]
### Describe the bug

I got the baton as an Item. However, when i switch a stat-raised Pokemon either via normal switch or move-switch, the stats don't transfer. The Baton doesn't transfer either.

### Reproduction

Got a baton, put it on Archaludon. Had Archaludon raise multiple stats, then switched. Stats didn't move on, neither did the baton. Then tried with Zarude: raised stats, used U-Turn. No stats or items were carried over.

### Expected behavior

Expected raised stats from the first pokemon to appear on the switched-in pokemon, as well as the baton-item.

### Session export file

[sessionData1_Togetik(1).txt](https://github.com/user-attachments/files/18049979/sessionData1_Togetik.1.txt)

**Comment by Snailman11** [comment]
How did you switch your pokemon? Did you select the pass baton option?

**Comment by Togetik** [comment]
There was an option? Well this is awkward. I'll be sure to check this out next time. Just gotten used to the "usual" menu options I guess..
