### ISSUE TITLE
[Bug] Can't unfuse

### ISSUE THREAD

**Issue by Togetik** [pagefaultgames/pokerogue#4990]
### Describe the bug

I fused Mega Gyarados with a fainted Machamp. Now I can't unfuse them. Only option showing is the Mega-evo-trigger.
Mega-on or Mega-off changes appearance, but does not present the option to unfuse. Reloaded page and file, had pkmn faint, revive, level up and switch areas, no unfuse option appeared.
I had a schroedingers Gyarados for a while tho, as the fusion kept the healthbar of the Gyarados (1st pkmn) and the fnt-status of the Machamp (2nd pkmn). Could battle normally, after fainting in battle normally, the status cleared.

### Reproduction

Got a DNA-Splicer, used it on Mega Gyarados (1st; alive, no status condition) and Machamp (2nd; fainted). Fusion happened regularly, abilities combined as well as moves and types. Resulting Mega Gyamp was alive but with fnt-status. After the next battle i wanted to unfuse, but only the option to deactivate the Gyaradosite (Mega-evo) showed up. Switching this did not allow unfusing.

### Expected behavior

Expected the option to unfuse the two fused pkmn from the team selection menu after a wave. 

### Screenshots / Videos

![PR_fusion2](https://github.com/user-attachments/assets/d0cefbd3-e3ea-4721-9ea3-5d8cbc186ed2)
![PR_schroedingers mon](https://github.com/user-attachments/assets/045f032f-ccda-4e38-9397-474db622690b)
![PR_schroedingers_2](https://github.com/user-attachments/assets/b39107d7-c795-48a0-be61-ecf85aa56bd1)
![PR_fuse](https://github.com/user-attachments/assets/a740a59d-cf00-4420-802e-f0a65540acc9)

### Session export file

[sessionData2_Togetik(1).txt](https://github.com/user-attachments/files/18136513/sessionData2_Togetik.1.txt)

### User data export file

[data_Togetik(2).txt](https://github.com/user-attachments/files/18136515/data_Togetik.2.txt)

**Comment by Snailman11** [comment]
[BUG] Splicing together an alive and a fainted pkmn will result in the fusion being alive (at avaraged HP) but displying FNT status #2608
https://github.com/pagefaultgames/pokerogue/issues/2608
