### ISSUE TITLE
[Bug] Lunar Blessing game freeze/crash

### ISSUE THREAD

**Issue by Drackal** [pagefaultgames/pokerogue#4991]
### Describe the bug

Cresselia using Lunar Blessing consistently causes a game crash. Music continues, but gameplay is completely frozen, forcing a reload.

### Reproduction

Use Lunar Blessing. Every scenario I tested caused the crash, in both single and double battles.

### Expected behavior

not crashing

### Screenshots / Videos

seems to always freeze on this frame of the animation, after playing the sound effect
![image](https://github.com/user-attachments/assets/e27fdafd-9cb4-4477-9550-c0abf70d9501)

### Session export file

[sessionData1_AsterVoid.txt](https://github.com/user-attachments/files/18138766/sessionData1_AsterVoid.txt)

### User data export file

[data_AsterVoid.txt](https://github.com/user-attachments/files/18138768/data_AsterVoid.txt)

**Comment by Snailman11** [comment]
Please screenshot your console at the crash, then clear your cache

**Comment by Drackal** [comment]
![image](https://github.com/user-attachments/assets/9f6f4806-4af7-46f3-ad83-c05fba13bba0)

**Comment by Drackal** [comment]
crashes the same after clearing browser cache; looks like exactly the same error message in the console
![image](https://github.com/user-attachments/assets/ce5d951d-efaa-4e11-8ecb-037793a37cba)

**Comment by Drackal** [comment]
`TypeError: Cannot read properties of null (reading 'totalDuration')
    at cw.execute (loading-scene-NW4-1v2U.js:845:377250)
    at l.onRepeat (loading-scene-NW4-1v2U.js:845:387556)
    at Object.dispatchEvent (index-BJG1U-oy.js:6024:2070)
    at Object.onRepeat (index-BJG1U-oy.js:6004:3522)
    at Object.setStateFromEnd (index-BJG1U-oy.js:6004:2069)
    at Object.update (index-BJG1U-oy.js:6024:1531)
    at l.update (index-BJG1U-oy.js:6016:3800)
    at Object.step (index-BJG1U-oy.js:5900:2647)
    at Object.update (index-BJG1U-oy.js:5900:2476)
    at l.emit (index-BJG1U-oy.js:1:5204)
window.onerror @ index-BJG1U-oy.js:6492`

**Comment by Drackal** [comment]
Tested on my phone and lunar blessing works fine and doesn't crash there. Very possible that it's something about my ~10 year old computer running windows 8.1; it's not that uncommon for me to have problems running newer software, though this is the first time i've had any issues with pokerogue specifically.

**Comment by Drackal** [comment]
Just thought to try turning move animations off, and that does prevent the crash, with lunar blessing working as expected.

**Comment by Snailman11** [comment]
Likely a cache issue, please clear your cache. The steps to do so vary depending on the browser
