### ISSUE TITLE
Explosion doesn't self-KO if the attack misses

### ISSUE THREAD

**Issue by Mode8fx** [pagefaultgames/pokerogue#503]
The original behavior of Explosion is that the user will faint even if the attack misses. However, the user currently stays alive if it misses. I would assume this is also true for Self-Destruct.

**Comment by bennybroseph** [comment]
Reported in Discord [here](https://discord.com/channels/1125469663833370665/1236077661634302032)

**Comment by charliegiang** [comment]
this is fixed with #691
