### ISSUE TITLE
[Bug] Incorrect Transformation Items on Pokemon

### ISSUE THREAD

**Issue by Physic314** [pagefaultgames/pokerogue#5054]
### Describe the bug

Pokemon have the incorrect transformation items in party, however, they still work as intended and do not interfere with gameplay. As shown in the images, Kyurem has the Rusted Shield and the Icy Reins of Unity, instead of the Light and Dark stones. I had also not caught Glastrier prior to this bug occuring, so having the Icy Reins of Unity should not be possible either.

### Reproduction

I do not think this bug is reproducible as it most likely occurred due to an update and the item ID's changed when new ones were added.

### Expected behavior

I would expect that the items would not change.

### Screenshots / Videos

![Screenshot (3)](https://github.com/user-attachments/assets/17f9de3e-878d-4d5a-b8e5-da1d422b83da)
![Screenshot (4)](https://github.com/user-attachments/assets/3b0f8ba3-d445-4fcf-9426-22ba132863b1)

**Comment by Snailman11** [comment]
This will not be fixed and occured due to an update to their item tiers

https://discord.com/channels/1125469663833370665/1282191826450780300

**Comment by Snailman11** [comment]
Additionally, please try to make a descriptive title in the future.
