### ISSUE TITLE
Charcadet rare shiny will freeze on evolution page when applying Malicious Armor

### ISSUE THREAD

**Issue by Abhavikati** [pagefaultgames/pokerogue#517]
![charcadet](https://github.com/pagefaultgames/pokerogue/assets/54720133/afb22888-bca6-46c7-b14f-06c89e022989)

The page will freeze and pressing any buttons will do nothing

**Comment by bennybroseph** [comment]
[Have you check this post?](https://discord.com/channels/1125469663833370665/1236032576137728150)

**Comment by Abhavikati** [comment]
The link doesn't seem to work on my end

**Comment by Abhavikati** [comment]
> [Have you check this post?](https://discord.com/channels/1125469663833370665/1236032576137728150)

the link doesn't seem to be working on my end

**Comment by Abhavikati** [comment]
> [Have you check this post?](https://discord.com/channels/1125469663833370665/1236032576137728150)

my bad, I'm new to the game, didn't know this existed. Thank you I will give it a try and update as a comment on this
