### ISSUE TITLE
Game hard locks when hatching an Egg

### ISSUE THREAD

**Issue by Zanaphor** [pagefaultgames/pokerogue#518]
Looking in Inspect Element while it's frozen shows ID for 747 (Mareanie) so the game is hard locking when trying to hatch a Mareanie for some reason. 

Clearing cache and trying other browsers hasn't fixed the issue either.

EDIT: https://imgur.com/00q4E7E Included picture of console on the side

**Comment by frezgle** [comment]
Having the same issue today; console shows the same exact error as OP. Happens on two different devices and the common suggestions (reload, clearing cache) do not fix it.

**Comment by mathis-ait** [comment]
Having the same issue here with same error in console 
![image](https://github.com/pagefaultgames/pokerogue/assets/82377514/ca50b3a3-18f4-40f3-91f2-deb116a80b8d)

**Comment by Tempo-anon** [comment]
Mareanie is fixed now
