### ISSUE TITLE
Achievement names don't always fit

### ISSUE THREAD

**Issue by Flashfyre** [pagefaultgames/pokerogue#522]
Achievement bar display should be modified somehow to fit both the long names and the point counts. Shortening the names is not a solution.

**Comment by CodeTappert** [comment]
Fixed as part of https://github.com/pagefaultgames/pokerogue/pull/1150

**Comment by Dakurei** [comment]
Fixed in #1520
(we talk about achievement bar, not achievement ui)

**Comment by CodeTappert** [comment]
> Fixed in #1520 (we talk about achievement bar, not achievement ui)

This PR is what i mean sorry.
