### ISSUE TITLE
Gravity removes flying type in damage calculation

### ISSUE THREAD

**Issue by LaukkaE** [pagefaultgames/pokerogue#524]
When gravity is in effect, flying type is ignored in damage calculation, causing moves that should be super effective against flying type pokemon lose their advantage.

Gravity should not remove the flying type in damage calculation.

**Comment by flx-sta** [comment]
Still able to repro:
Used overrides:
```ts
const overrides = {
  OPP_SPECIES_OVERRIDE: Species.PIDGEOT,
  OPP_MOVESET_OVERRIDE: [Moves.SPLASH, Moves.SPLASH, Moves.SPLASH, Moves.SPLASH],
  STARTER_SPECIES_OVERRIDE: Species.PIKACHU,
  MOVESET_OVERRIDE: [Moves.GRAVITY, Moves.THUNDERBOLT],
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```
