### ISSUE TITLE
If a move has variable typing (Due to move itself or ability), other abilities will get tested against the moves base type

### ISSUE THREAD

**Issue by LaukkaE** [pagefaultgames/pokerogue#527]
This causes multiple issues, for example

Sunny day weather ball to ignore opponents Flash fire.

Tinted lens + any weather ball to get boosted against steel type (Due to normal type being not very effective against steel).

Filter& Solid rock to not reduce damage against a move that would become super-effective, if it wasnt before.

**Comment by Tempo-anon** [comment]
https://github.com/pagefaultgames/pokerogue/pull/1440 will fix this completely
