### ISSUE TITLE
Pokemon fused with itself doesn't have a cry

### ISSUE THREAD

**Issue by turtlesboulder** [pagefaultgames/pokerogue#540]
In the wild I encountered a shiny gliscor fused with another gliscor. When the encounter starts, it does not play its cry sound, nor when it breaks free of a pokeball. It does however, play its cry sound when it faints (the sound is fine, just gliscor's sound) Additionally, the fainting animation is not what I expected. Normally when a pokemon faints the sound plays and afterwards it drops off the screen. However with the fused gliscor it drops off the screen as the sound plays.

This is the error the console spits out when it attempts to play the cry:
[error.txt](https://github.com/pagefaultgames/pokerogue/files/15216146/error.txt)

Here is a video demonstrating what happens (it has sound):

https://github.com/pagefaultgames/pokerogue/assets/93344616/847ca1bd-0d9e-48fc-ad1a-9d71db9f4971

**Comment by bennybroseph** [comment]
Fixed in https://github.com/pagefaultgames/pokerogue/pull/615
