### ISSUE TITLE
Zygarde's form change conflicts with selecting starter forms

### ISSUE THREAD

**Issue by Madmadness65** [pagefaultgames/pokerogue#551]
It was brought to my attention that catching alternate Zygarde forms (10% and 50% Power Construct) results in only the 50% Aura Break Zygarde appearing to be the only selectable form when picking it as a starter. This is due to the `SpeciesFormChange` Zygarde has defined in pokemon-forms, as temporarily commenting it out lets you pick alternate Zygarde forms if you've caught any. The issue is, Zygarde needs those if it wants its Power Construct ability to work, but it also needs to switch forms to even get to Power Construct in the first place.

**Comment by Flashfyre** [comment]
This is also an issue for Rotom and Minior.

**Comment by Madmadness65** [comment]
> This is also an issue for Rotom and Minior.

True for Minior, but not Rotom. If alternate Rotom forms are caught, they can be switched between without issue.

**Comment by ConquestZ** [comment]
Yesterday, the legendary egg gotcha was for Zygarde and I hatched one with power construct. Is there any updates on when this issue that disallows the selection of power construct on a starter zygarde may be resolved?
