### ISSUE TITLE
Dachsbun's 'Well-Baked Body' does not work.

### ISSUE THREAD

**Issue by Iondwyn** [pagefaultgames/pokerogue#554]
Well-Baked Body does not work on the spell 'Inferno,' still took damage and did not receive the defensive increase.

**Comment by Tiduzz** [comment]
I just tested it with updated code, and it seemed to work as it should. Do you have the session data or proof of this?
![dachsbun](https://github.com/pagefaultgames/pokerogue/assets/42784723/79462775-bdd5-4e70-99f4-a36ea50b50fe)

**Comment by Iondwyn** [comment]
Ah, I hadn't thought of it, but it's likely an interaction with Infiltrator, since the opposing pokemon was a Chandelure. My apologies.

**Comment by Tiduzz** [comment]
Dw about it :)

According to bulbapedia at least, it should work regardless of infiltrator. I'm assuming the enemypokemon had mold breaker or something alike. If you do happen to see this 'bug' again, be sure to check the enemy ability!
