### ISSUE TITLE
sturdy protects from double hit moves

### ISSUE THREAD

**Issue by dipdadronan** [pagefaultgames/pokerogue#555]
Moves that attack twice and should normally kill through sturdy do not.

**Comment by Tiduzz** [comment]
I just tested it with double hit (which is a fixed number of attacks, 2) and with Bullet seed (which is 2-5). Either did indeed knock out the opponent. Are you sure it wasn't an endure move or endure token?

**Comment by spixi** [comment]
I also noted that issue with double health bar boss monsters with Sturdy and Double Kick. It is very frustrating, when you use Flamigo as a starter.

**Comment by flx-sta** [comment]
Cannot reproduce on `beta` (28c5dc6b59cd363c1dff55550bcaa620e7e29dda)
