### ISSUE TITLE
[Suggestion] Incentive players to keep their starters until the boss on daily runs

### ISSUE THREAD

**Issue by HapLifeMan** [pagefaultgames/pokerogue#561]
Hey, great job for PokéRogue!

I was wondering about a nice feature that could make the Daily Runs more enjoyable and different so players never always have the same team at the end of the runs by catching always the same powefull Pokémon.

The idea would be to incentive players to keep the random starters until the final boss, and reward them with some additionnal Egg Vouchers, or give a Legendary one or anything else if they still have them.

_Not to lock the starters and prevent them from being replaced, but just a bonus if they keep them._
_And/or we could imagine an "hard/difficult/extreme" Daily Run mode with locked starters (and items?)._

That could be very very nice and make it more challenging!
Interested to know your (and the community) input on this.

**Comment by hightowernl** [comment]
Sounds nice, or maybe get extra points for those Pokemon you beat the game with to unlock their passive/reduce cost. And only the first time you beat the game with those Pokemon. So it gives incentive to use different Pokemon the next time.

**Comment by HapLifeMan** [comment]
Looks like a good idea too, probably a mix of both ideas!

**Comment by PLMMJ-FH** [comment]
I like this idea

**Comment by Tempo-anon** [comment]
Most starters I take make it to the end due to their higher power from egg moves, passives, or extra luck. Not sure if a specific bonus is needed.
