### ISSUE TITLE
Stats lost(?) from unsplicing

### ISSUE THREAD

**Issue by ArbitraryCuriosity** [pagefaultgames/pokerogue#576]
Unsure if this replicates, but:

1. started endless fusion with Yveltal (-> it was randomly fused with Tympole)
2. Suppressed the Tympole evolutions (related issue -- I could not undo the temporary lock)
3. Unspliced from Tympole at level 40 (in order to keep Muddy Water but have an ordinary Yveltal)

I noticed that the resulting unspliced Yveltal's stats seemed to be lower than they should be. I started a normal run with vanilla Yveltal to compare; the normal run's Yveltal had higher stats than the endless-spliced run's Yveltal, despite being at a _lower_ level.

**Comment by Flashfyre** [comment]
This is intended in spliced endless. Unspliced mons have half base stats.
