### ISSUE TITLE
<Suggestion> Add a setting to skip "[Pokemon] leveled up to level XYZ"

### ISSUE THREAD

**Issue by Lumaura** [pagefaultgames/pokerogue#580]

**Comment by Tiduzz** [comment]
In game settings, there is a option to make it faster or skip this, no?

**Comment by TTkindboy** [comment]
A setting was added in yesterday's update to skip this.
![image](https://github.com/pagefaultgames/pokerogue/assets/64111041/c535ba48-4037-48c6-a3cc-9b91f14a4dbc)
