### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by ColinLug** [pagefaultgames/pokerogue#587]
I've been playing the challenge of the day and I caught the boss (on round 10) and an egg cracked open. I can't play since. I'm stuck on the loading screen. I've tried to log in from a different device but I'm stuck again on the loading screen (the green one) after logging in. Hope it could be fix if it's a common bug ! thanks for all

**Comment by ColinLug** [comment]
All right thanks. I'll try playing later !

**Comment by DarmokJaladd** [comment]
I was having the same issue. It has either fixed itself (so try that first), or when I downloaded and ran the PokeRogue Desktop app made by Admiral-Billy it fixed the issue. So idk if it was coincidence or if it was just a silly little work around I found. It also works on browser again :)

**Comment by ColinLug** [comment]
You're right, the problem is fixed. Thanks !
