### ISSUE TITLE
Can't create a save file

### ISSUE THREAD

**Issue by Sc2Prodigy** [pagefaultgames/pokerogue#588]
I just created an account, it first said user profile can't be created but then let me sign in. I can't start a single run as it crashes to a screen saying no save file has been found and boots me back to the main menu. I tried daily runs and same thing, can't even make it to see a battle. I have also tried making different accounts and different browsers. Same issue.

**Comment by Sc2Prodigy** [comment]
Now it randomly is working, no idea why.

**Comment by legrand156** [comment]
j'ai le même problème  et je ne peut pas me connecté a mais ancienne  sauvegarde pourtant j'ai notée mon identifiant et mot de passe sur ordinateur et mémo.
