### ISSUE TITLE
covet gives ur items to the opponent instead of stealing them

### ISSUE THREAD

**Issue by raato234** [pagefaultgames/pokerogue#589]
hi so i had mankey with covet and it gave all my items to the opponent instead of stealing them kinda whacky. and it was specifically boss batle and i allso had the claw that gives xtra 10% to steal items.

**Comment by Flashfyre** [comment]
Are you sure it wasn't something else? I've never heard of this happening to anybody.

**Comment by TempsRay** [comment]
Sounds like you were hitting a boss with pickpocket

**Comment by raato234** [comment]
Ps: if im just idiot im extremely sorry for wasting your time.

**Comment by TempsRay** [comment]
Are you sure it was a Herdier? I know Zigzagoon/Linoone gets pickpocket as a passive so if it's a boss hitting it can cause you to lose items.
