### ISSUE TITLE
Reviver seed not proccing off self damage.

### ISSUE THREAD

**Issue by DarmokJaladd** [pagefaultgames/pokerogue#591]
I used wood hammer on my rillaboom with reviver seed, it died from recoil and did not revive. Unsure if this is intended, but I wanted to mention it regardless.

**Comment by TempsRay** [comment]
Revival seed only procs if you get KO'd by a move by the opponent. It will not save you from weather, hazards, or recoil

**Comment by JoannaFalkowska** [comment]
> Revival seed only procs if you get KO'd by a move by the opponent. It will not save you from weather, hazards, or recoil

...Why though? Isn't this a bug? It doesn't make much sense why would it proc off direct hits but not off other things.

**Comment by Tempo-anon** [comment]
That's just the way it's implemented right now as a design choice. Lets you preserve your revival seed by fainting to a non direct attack
