### ISSUE TITLE
Evoultion Thunder Stone can be used on G-Max Pikachu

### ISSUE THREAD

**Issue by Graymare** [pagefaultgames/pokerogue#613]
Steps to Reproduce:
• Party contained Charjabug and G-Max Pikachu
• Was offered a Thunder Stone
• Applied Thunder Stone to G-Max Pikachu

Expectation:
"cannot use this item" message, or maybe a "would you like to release G-Max and evolve?" message.

Reality:
G-Max Pikachu consumed the Thunder Stone but nothing happened.  Changing forms back to PIkachu did not trigger Raichu evolution either.  Game continued as normal.  Unknown if this affects other alternate forms, or if Pika is just an edge case due to being a non-fully-evolved 'Mon that can use an evolution stone.  

Desired Resolution:
• Have G-Max Pikachu and any similar alt-forms reject Evolution Stones in the same way any other non-eligible Pokémon would, allowing the player to either choose an eligible party member or a different reward, or implement a "Would you like to end G-Max and evolve?" prompt.

**Comment by j-diefenbach** [comment]
I'll look into this and I believe there's also an issue where max mushroom can be transferred around the party and effectively be re-used

**Comment by j-diefenbach** [comment]
#208

**Comment by j-diefenbach** [comment]
Looks like there's no form check to prompt the 'won't have any effect' text, i've added it in but i'll do some more testing before making a PR

**Comment by j-diefenbach** [comment]
@bennybroseph this can be closed now

**Comment by CodeTappert** [comment]
Closing because fixed in https://github.com/pagefaultgames/pokerogue/pull/636
