### ISSUE TITLE
Can't login to pokerogue anymore

### ISSUE THREAD

**Issue by acantepie** [pagefaultgames/pokerogue#616]
Go this error when i try to login with valid credentials :

![image](https://github.com/pagefaultgames/pokerogue/assets/12775815/690931ef-0e4b-4c41-8d2d-b2a21bc9e1ae)

**Comment by bennybroseph** [comment]
https://discord.com/channels/1125469663833370665/1125469705172439122

**Comment by Shoan9** [comment]
how did you solve it
