### ISSUE TITLE
[Suggestion] Add victory screen after run win

### ISSUE THREAD

**Issue by Nafiz1** [pagefaultgames/pokerogue#621]
Add a victory screen after you win showing all your Pokémon, elite four win style.

**Comment by Flashfyre** [comment]
This is in the roadmap on the Discord

**Comment by hayuna** [comment]
Something like that? :)

<img width="970" alt="Screenshot 2024-07-04 at 19 46 45" src="https://github.com/pagefaultgames/pokerogue/assets/19636010/efdee95b-27c4-437e-9d90-85a09a11c6cc">

**Comment by Nafiz1** [comment]
@hayuna Yes exactly like that!

maybe make the pokemon stand out more?
![image](https://github.com/pagefaultgames/pokerogue/assets/41881743/15d792ab-c545-4a2f-a267-70f08afd5060)

**Comment by hayuna** [comment]
<img width="1620" alt="Screenshot 2024-07-05 at 13 34 04" src="https://github.com/pagefaultgames/pokerogue/assets/19636010/6053a997-7b9b-46ad-bcb4-878480636c24">

**Comment by torranx** [comment]
Closing with reference to https://github.com/pagefaultgames/pokerogue/pull/3303#issuecomment-2338974325
