### ISSUE TITLE
I would like to help add a Chinese language pack

### ISSUE THREAD

**Issue by 1596941391qq** [pagefaultgames/pokerogue#624]
This game now has many Chinese users, and I would like to help you add a Chinese language pack to enhance the gaming experience for Chinese-speaking users.

**Comment by justhil** [comment]
#485

**Comment by Janyz1005** [comment]
> 这款游戏现在有很多中国用户，我想帮大家添加一个中文语言包，以增强中文用户的游戏体验。

大佬加油

**Comment by 1596941391qq** [comment]
> > 这款游戏现在有很多中国用户，我想帮大家添加一个中文语言包，以增强中文用户的游戏体验。
> 
> 大佬加油

我们汉化好了，然后现在打算打包成electron，简化本地版进入

**Comment by justhil** [comment]
> > > 这款游戏现在有很多中国用户，我想帮大家添加一个中文语言包，以增强中文用户的游戏体验。
> > 
> > 
> > 大佬加油
> 
> 我们汉化好了，然后现在打算打包成electron，简化本地版进入

不是哥们隔壁我不早就提交了吗别重复做功啊做一下ui对其和字体适配呗

**Comment by 1596941391qq** [comment]
想玩本地离线汉化包的看我视频https://www.bilibili.com/video/BV13b421b7Wq/?spm_id_from=333.999.0.0，汉化内容丰富，换行和字体大小都有修改，而且不可能掉线

**Comment by CodeTappert** [comment]
There now exist zh_TW and zh_CN language options that are localized pretty well. 
If you want to add to that please create a PR with your changes. 
Or hop onto the discord to participate
