### ISSUE TITLE
Account broke

### ISSUE THREAD

**Issue by hightowernl** [pagefaultgames/pokerogue#629]
I think my account just broke this morning. Not 100% sure what happened, but a Pokemon of mine fainted after I beat the last Pokemon of a trainer. I had to reselect a Pokemon to switch in, which caused my trainer to show himself because the trainer battle ended. At the same time the Pokemon I selected was switched into battle while there is no battle so there were overlapping sprites of the trainer and the Pokemon. This went on for a few battles, even switching the Pokemon just kept the trainers sprite there. After a few battles I decided to refresh the page to hopefully clear the data of the trainers sprite into battle. But now the game won't even load. I deleted all cookies of Pokerogue which allows me to see the Login screen, but after pressing Login it just keeps loading until I get an error screen with long code throughout the window. 522 at the end. Hopefully a dev can see this and reload my account or smth? I had almost all Pokemon, 31 IVs in so many and so many shinies, I don't want to start over. Account name: DutchEZmoder

Thanks in advance

**Comment by hightowernl** [comment]
> the best solution for you is to upload your game data, at least if you have downloaded them.

Unfortunately I didn't, and I'm unable to download it now.

**Comment by OligarchButterfly** [comment]
The servers are down right now because so many people are trying to play. When it's back up for everyone you'll be fine.
