### ISSUE TITLE
Update learnsets for Indigo Disk

### ISSUE THREAD

**Issue by kittenchilly** [pagefaultgames/pokerogue#63]
Although a lot are accurate since they are updated for SV and BDSP (I notice changes so it has the removed moves as well), there are a few that aren't.
One I notice is the Snivy line, the levels are all off.

**Comment by kittenchilly** [comment]
It seems to be the new pokemon added in the indigo disk from gen 5 onward. They all have new learnsets since they weren't in BDSP.

**Comment by bennybroseph** [comment]
Working on this currently

**Comment by bennybroseph** [comment]
Gen 1 in this PR https://github.com/pagefaultgames/pokerogue/pull/449

**Comment by bennybroseph** [comment]
Gen 2 in this PR https://github.com/pagefaultgames/pokerogue/pull/469

**Comment by flx-sta** [comment]
@bennybroseph @kittenchilly 
Can this be considered done?
