### ISSUE TITLE
Pokerogue not logging in (some language issue)

### ISSUE THREAD

**Issue by 509Gameboy** [pagefaultgames/pokerogue#630]
![Bildschirmfoto 2024-05-08 um 13 42 22](https://github.com/pagefaultgames/pokerogue/assets/136295250/617bcb6b-2fe3-40b5-9700-3761970e3fc8)
Hello. on the new update my pokerogue Broke.
My Laptops Laguage is on german but my browser language is on English.
Today i tried to log in but it spat out this error.

Please help me i want to continue playing in english.

**Comment by OligarchButterfly** [comment]
The servers are down right now because so many people are trying to play. It's not the update.

**Comment by MasterAustin75** [comment]
when will they be back up

**Comment by CodeTappert** [comment]
Yeah server was just down. Closing this
