### ISSUE TITLE
Achievement not working

### ISSUE THREAD

**Issue by Diamnd08** [pagefaultgames/pokerogue#638]
So I finally hatched a shiny and I gained the achievement but I was not rewarded with anything, no ticket nothing? Why? What do I do?

**Comment by Flashfyre** [comment]
Rewards for achievements have never been a thing. The ticket there is an icon to represent the achievement.

**Comment by Diamnd08** [comment]
Ah, also I got a shiny misdreavous and it is purple instead of green and I have no idea if it is a rarer shiny or not
