### ISSUE TITLE
Pokemon sprites failing to load after fainting in Gym Leader battle

### ISSUE THREAD

**Issue by natoweg** [pagefaultgames/pokerogue#64]
When you KO the last Pokemon of a Gym Leader at the end of a biome and your Pokemon then faints due to a status effect (Toxic), your are prompted to select a new Pokemon from your party to switch in. After the subsequent heal and transition to a new biome, Pokemon battle sprites and move animations fail to render.

No sprites will render until the page is refreshed and the game is reloaded. Transitioning to a new biome after beating the next area boss does not fix.

Example:
![sprite_fail](https://github.com/pagefaultgames/pokerogue/assets/16001633/dac4b56f-e50f-4e2b-8cbf-91c2fc46f0b7)

**Comment by flx-sta** [comment]
Here is a video of the aftermath

https://github.com/pagefaultgames/pokerogue/assets/50131232/791857d6-6560-4c13-8a66-5ce5fce2b0c3

**Comment by JoshuaKeegan3** [comment]
Another example of this is destiny bond. Here is another example:

<img width="1433" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/37237625/4371c768-3f3d-4dd7-9e12-9e57a4290398">

**Comment by flx-sta** [comment]
Discord related links
- [#dev-corner -> Issue #64](https://discord.com/channels/1125469663833370665/1256481888986730527)
- [Bug Reports -> Fainting after winning trainer/gym battle causes graphical error](https://discord.com/channels/1125469663833370665/1243561436286812302)

**Comment by flx-sta** [comment]
Fixed through #3211
