### ISSUE TITLE
Dual Chop hits Pokemon using Fly

### ISSUE THREAD

**Issue by Joshima13** [pagefaultgames/pokerogue#656]
My Roaring Moon used Fly, after which the opponent Machoke hit it with Dual Chop. Fly has successfully avoided or been hit by other moves as normal (i.e. gust and twister), but I'm pretty sure Dual Chop isn't supposed to be able to hit while the target it in the sky
Edit: The exact same scenario just happened again

**Comment by lovegraveyard** [comment]
Does the Machoke have No Guard?

**Comment by Madmadness65** [comment]
No Guard lets a Pokemon hit a target even if it's in a semi-invulnerable state, so this is not a bug.

**Comment by Joshima13** [comment]
That would explain it, I didn't see the ability pop up, so I didn't think to check
