### ISSUE TITLE
Rest Sleep Turns Incorrect

### ISSUE THREAD

**Issue by GDonor** [pagefaultgames/pokerogue#678]
Sleep caused by Rest is not lasting the intended 2 turns.

**Comment by CodeTappert** [comment]
Could you explain a little more?

I just tested it. And my pokemon always wakes up exactly 3 turns after using Rest.

**Comment by GDonor** [comment]
From Bulapedia:

"Rest causes the user to fall asleep, restoring its HP to its maximum amount. The user is unable to use moves for 2 turns while asleep: the turn when Rest is used and the next turn."

The turn after you use Rest is the only turn the Pokemon should stay asleep, not 2 more consecutive turns.

**Comment by GDonor** [comment]
I realized my mistake re-reading how the move works, nevermind then
