### ISSUE TITLE
[Suggestion] Non-battle effects for Frisk, Compound Eyes and Super Luck?

### ISSUE THREAD

**Issue by Eridanus91** [pagefaultgames/pokerogue#679]
Frisk is completely useless right now, since the game tells you enemies held items anyway.

Compound Eyes and Super Luck in the main series have extra effect of increasing chance that an encounter has a held item on top of their  battle effects (Super Luck has gained that pretty recently, but still).

I am thinking, maybe have their effect do something with the post-battle items? Increase luck by 1 if it's in the battle at the end of wave? No idea, just throwing thoughts so Frisk isn't straight up useless with how the game is working right now.

**Comment by xdotsv** [comment]
frisk reveals enemy abilities in pokerogue
