### ISSUE TITLE
Critical hits and super effective dialogue out of order

### ISSUE THREAD

**Issue by j-diefenbach** [pagefaultgames/pokerogue#680]
Critical hits and super effective messages appear after damage has been applied, this also includes fainting, xp and moves being applied aswell as evolutions. Additionally if a pokemon dies to a multi-hit move e.g. a 3x hit on the 1st or 2nd hit it doesnt trigger the supereffective dialogue.

**Comment by DustinLin** [comment]
also seems like when a pokemon dies to a supereffective move, it doesn't trigger the supereffective dialogue (only show the fainted dialogue)

**Comment by j-diefenbach** [comment]
i might go about moving the supereffective and crit message calls but I want to do it properly / make sure I don't mess w anything else so I'll take a while

**Comment by DustinLin** [comment]
I think i have the supereffective and crit messages moved and working properly, but getting the multi-hit moves to render properly is a bit more tricky, haven't made any pull requests I want to get the second part figured out

**Comment by DustinLin** [comment]
I found another bug that's very similar, for a move like absorb, the subsequent dialogue also gets cuts upon fainting, I'm sure this has something to do with the `FaintPhase` overriding the queued messages

**Comment by j-diefenbach** [comment]
yeah i think the dialogue ordering as a whole is a mess since some dialogue-calling phases are called in the middle of a phase. someone in the discord mentioned seperating messages out somehow but i'm sure there's a better way to systematically order it instead. 
I think FaintPhase would exit and prevent messages from being called after the updateanddamage function as they normally do

**Comment by torranx** [comment]
any of you actively working on this? I've just forked the repo a while ago today and this is the first bug I'm trying to fix. also my first time participating (attempting to, at least lol) in opensourced projects like this.

**Comment by DustinLin** [comment]
hey all, yeah i've been working on it for the past couple days, as mentioned above I think iv'e fixed the critical and super effective hits dialogue but i sort of went down a rabbit hole b/c a lot of the dialogue is messed up, sorry i should have made it more clear from my initial message I was working on it

**Comment by DustinLin** [comment]
if you all can take a look at this solution I came up with and try it out, there is still some bugs that need to be fixed that I found when writing this, but this seems like a good starting point

**Comment by Dakurei** [comment]
Fixed in https://github.com/pagefaultgames/pokerogue/commit/7ac4900a3eceb64d48170350a4d5b1caf4e02410
