### ISSUE TITLE
Lycanrock dusk form evolution not possible

### ISSUE THREAD

**Issue by j-diefenbach** [pagefaultgames/pokerogue#681]
Rockruff doesn't evolve into lycanrock during dusk w appropriate level up, only evolves during day/night into midday/midnight forms.

**Comment by Madmadness65** [comment]
You need to catch an Own Tempo Rockruff (or a Dusk Lycanroc, both will make Own Tempo Rockruff available) to be able to evolve it into the Dusk form.

**Comment by j-diefenbach** [comment]
> You need to catch an Own Tempo Rockruff (or a Dusk Lycanroc, both will make Own Tempo Rockruff available) to be able to evolve it into the Dusk form.

It had own tempo, im going off of the discord post. Looks like there's an issue in pokemon-evolutions.ts line 1396. Currently it is 
`    new SpeciesFormEvolution(Species.LYCANROC, '', 'dusk', 25, null, new SpeciesEvolutionCondition(p =>  p.scene.getSpeciesFormIndex(p.species) === 1), null),`
There's no TimeOfDay.DUSK.
Working on replicating it but I'll come back to it tmr

**Comment by Madmadness65** [comment]
That evolution method is literally just "Evolve a form index 1 Rockruff (Own Tempo) at level 25", setting the time of day evolution requirement too was deemed too restrictive, so the form index is the only requirement for it.

**Comment by j-diefenbach** [comment]
not sure if i've read the code wrong but there seems to be no actual functionality for checking that form. When getSpeciesFormIndex(p.species) is called it checks for special IDs and ignoreArena, of which rockruff will ignore. Then it calls this.arena.getSpeciesFormIndex which again is pretty much just hardcoded. It looks like its mostly just returning cases e.g. lycanrock it returns the time of day. There's no rockruff switch case so I'll see if that can be added in, could just return 1 if it finds OwnTempo as an ability, with the current function itll just be returning 0 since it defaults

**Comment by j-diefenbach** [comment]
![image](https://github.com/pagefaultgames/pokerogue/assets/105332964/4d059bbc-0a60-49f9-897d-c222e4419e0b)
Have done some more testing currently rockruff evolves into day form even with own tempo. Have changed the code to directly check for own tempo rather than the form and doing more testing atm
