### ISSUE TITLE
Hazards are getting removed when returning to title and starting the battle again

### ISSUE THREAD

**Issue by Varauk** [pagefaultgames/pokerogue#684]
Usually, hazards like toxic spikes persist between encounters (unless a trainer battle starts). As seen in the clip, entering the next stage Dusclops gets poisened by existing toxic spikes as expected. But after quitting to title and starting the encounter again, the toxic spikes are gone.

Demo:

https://github.com/pagefaultgames/pokerogue/assets/35373497/95024d5a-8859-4c39-9b4a-2bb05415a5e4

**Comment by ch5rus** [comment]
Had this problem in a previous bug report, this one is described better so i'll close mine

**Comment by chacolah** [comment]
After poking through the files, issue seems to be that the data about the arena saved to session in game_data.ts only saves weather but not terrain, which seems obvious, but I do not know how to go about implementing a fix.

**Comment by happinyz** [comment]
> After poking through the files, issue seems to be that the data about the arena saved to session in game_data.ts only saves weather but not terrain, which seems obvious, but I do not know how to go about implementing a fix.

Thanks for the investigation! I can take a stab at a fix if you haven't started already.

**Comment by chacolah** [comment]
> > After poking through the files, issue seems to be that the data about the arena saved to session in game_data.ts only saves weather but not terrain, which seems obvious, but I do not know how to go about implementing a fix.
> 
> Thanks for the investigation! I can take a stab at a fix if you haven't started already.

I have not, so feel free. Don't forget to tag the issue if you do a PR!
