### ISSUE TITLE
Whirlpool DoT effect not working if using Multi-Lens (video proof)

### ISSUE THREAD

**Issue by Mertna** [pagefaultgames/pokerogue#690]
I'm not sure if it's due to multi-lens specifically but this issue started showing up as soon as I switched the item from another pokemon to the whirlpool user so I assume it's the problem here.
Nothing shows up in the console that links to this issue.

https://github.com/pagefaultgames/pokerogue/assets/122574158/946f3ca0-dd57-476e-be0e-4b363ba28537

**Comment by flx-sta** [comment]
Not able to reproduce on `beta` (4a04ef50c35b668f21a6fc627d30c064dce933eb)
