### ISSUE TITLE
Mareanie's Tier 3 shiny sprite causes an error when attempting to display it during gameplay.

### ISSUE THREAD

**Issue by DrSuavidade** [pagefaultgames/pokerogue#696]
since a week ago whenever i try to start a classic or endless run with my 2 tier 3 shiny pokemon the game always freezes after chosing the save. i can start a run in opera gx, but is extremelly laggy and when i come back to other browsers it shows that has a save, but when i try to load it it always freezes.

**Comment by DrSuavidade** [comment]
actually the issue is just with tier 3 shiny mareanie, other tier 3 shinies let me start runs

**Comment by j-diefenbach** [comment]
Have you tried changing to consistent animations / are you currently using mixed animations?

**Comment by DrSuavidade** [comment]
I tried both and keeps happening, but just when tier 3 mareanie is on the team

**Comment by Aero5789** [comment]
Hi I just want to say that I was also able to replicate this bug with the "blue" tier shiny of mareanie, as soon as you start the run the game just freezes and does not bring you to the first encounter, it just shows the backdrop and nothing else.

**Comment by andy0liang** [comment]
![Screenshot 2024-05-15 at 2 49 15 AM](https://github.com/pagefaultgames/pokerogue/assets/16409831/8517cc81-f9c3-44d4-a03c-7f7b4e4f97e8)
Seems like some JSON with color data (??) is missing for Mareanie, works for Toxapex (change 747.json to 748.json in url)

**Comment by flx-sta** [comment]
Tested on `beta` (4a04ef50c35b668f21a6fc627d30c064dce933eb) on Mac in FF, Chrome && Safari with all 3 shiny variants.

Not able to reproduce
