### ISSUE TITLE
Damage calculation of move "Electro Ball" doesn't consider paralysis?

### ISSUE THREAD

**Issue by BalaTiger** [pagefaultgames/pokerogue#701]
![QQ截图20240510095731](https://github.com/pagefaultgames/pokerogue/assets/52457902/0fca673f-9d89-4f4c-ab9d-9b09dbd750e2)
![QQ截图20240510095709](https://github.com/pagefaultgames/pokerogue/assets/52457902/11478f69-e0f0-40d6-ad08-4f56a882c204)
Here are stats of two sides in battle.
Rotom-Heat has a speed stat to 209.
Toxapex is Lv.115, and has a hasty nature and a speed IV to 21. If stat calculation here isn't different from Gamefreak's, then the speed stat of Toxapex shall not below 105.
Therefore, a Electro Ball used by Rotom-Heat is expected to reach a power of 60 normally, which is doubled when Toxapex is paralyzed.
However, what happened in game does not match what expected. I'm inclined to regard that as a bug:
https://github.com/pagefaultgames/pokerogue/assets/52457902/0105a9f7-2306-496b-b4d1-6dce5763e35d

**Comment by JakubHanko** [comment]
Fixed here https://github.com/pagefaultgames/pokerogue/pull/742
