### ISSUE TITLE
Tidy up clears opponents side of hazards instead of own side

### ISSUE THREAD

**Issue by j-diefenbach** [pagefaultgames/pokerogue#705]
Issue as title. Think this is due to tidy up being a self status move that cleans up only one side. All other hazard cleanup moves work as intended still

https://github.com/pagefaultgames/pokerogue/assets/105332964/df65da71-81eb-414f-8730-e180b2d478ac

https://github.com/pagefaultgames/pokerogue/assets/105332964/1fe11421-2039-49f6-b410-70ce4349a3ff

**Comment by td76099** [comment]
Addressed with #717
