### ISSUE TITLE
Sturdy does not work properly in double battles

### ISSUE THREAD

**Issue by umbresp** [pagefaultgames/pokerogue#708]
If two pokemon attack a pokemon with Sturdy it will endure both hits

**Comment by DustinLin** [comment]
Can't seem to reproduce, testing with a set up of geodude with sturdy and 2 opposing swampert with surf, endures the first surf but dies to the second

**Comment by DustinLin** [comment]
nvm, PR #604 resolves this

**Comment by DustinLin** [comment]
can someone close this issue? PR #604 is merged
