### ISSUE TITLE
Spliced Skeledirge/Feraligatr flashing colors back sprite animation

### ISSUE THREAD

**Issue by SoraHjort** [pagefaultgames/pokerogue#710]
I looked to see if something like this had been reported in the issues before posting, but I didn't see any. So, sorry if this is a duplicate.

Setup: DNA Splice Skeledirge with Feraligatr

Basically, Skeledirge's back sprite animation only has one frame with Feraligatr's color scheme. The rest of the frames are Skeledirge's normal palette. So it looks like the colors didn't get applied to every frame of the animation.

Front sprite's colors do not flash are are just Feraligatr's colors. So the issue lies with just the back sprite.

Video attached demonstrating, May require a slight flash warning.

https://github.com/pagefaultgames/pokerogue/assets/18604504/638e269a-92bc-4180-bc91-f824c149ec9f

random thoughts on the off chance it matters: 
- Browser is Vivaldi (chromium). 
- The fusion did happen while I had Sprite Set to mixed, but turning it back to Consistent didn't change anything.
- persists even after turning off fusion palette swaps.
- made a backup of the export data and session data in case either is requested.

**Comment by psychoDon525** [comment]
I have this exact same issue with Skeledirge and Swampert fusion. Maybe Skeledirge's backsprite has something weird going on?

**Comment by chaosgrimmon** [comment]
fixed
