### ISSUE TITLE
Didn't get any reward after beating Classic Mode (last Pokémon fainted after winning)

### ISSUE THREAD

**Issue by carlosramosmed** [pagefaultgames/pokerogue#713]
I defeated Eternatus in the last fight in the Classic (It even said its dialogue "Magnificent") with my last Pokémon, which was poisoned.
It died in the last turn due to the poison and I didn't get any rewards, in fact, it counted as if I lost the run, even though I had already defeated Eternatus.

**Comment by Flashfyre** [comment]
A warning about this was given in the Discord yesterday. If you refresh or crash directly after winning and don't progress to the title screen, you will not receive the rewards and unlocks.

**Comment by flx-sta** [comment]
Related to #222
