### ISSUE TITLE
Solar Beam text does not display when it is Sunny

### ISSUE THREAD

**Issue by kd8lvt** [pagefaultgames/pokerogue#72]
As the title says, the game skips rendering the "<pokemon> used Solar Beam!" text if the weather is Sunny.
Granted, I'm not sure if this is a "first turn of battle only" issue, or if this is always the case, but it legitimately caught me off guard >.>

Video of it in action, which was too beefy for Github: https://youtu.be/0H_Xj6r2wvg

**Comment by Flashfyre** [comment]
Known bug

**Comment by bennybroseph** [comment]
Looks like this was fixed

https://github.com/pagefaultgames/pokerogue/assets/13838608/1da0dc2f-5a38-46e5-b398-062e16faf6e5
