### ISSUE TITLE
Strange PokeBall Item Graphical Glitch

### ISSUE THREAD

**Issue by GDonor** [pagefaultgames/pokerogue#721]
![WTF](https://github.com/pagefaultgames/pokerogue/assets/129960488/2499ceec-c3e4-43b3-94c4-4b6a6c616077)

Game crashes then on item pick.

**Comment by j-diefenbach** [comment]
Do you have the save file or are able to recreate / reload the save? If so can you send it or try sending a ss of the console when this happens.

**Comment by GDonor** [comment]
I do not unfortunately.
