### ISSUE TITLE
Font size is too large, causing incomplete display when using Simplified Chinese

### ISSUE THREAD

**Issue by SchneeHertz** [pagefaultgames/pokerogue#732]
When using Simplified Chinese, the font size is too large, causing incomplete display or overflowing from the border.

![image](https://github.com/pagefaultgames/pokerogue/assets/39257008/127ab86e-8303-48f3-831a-d263f917a6b9)

**Comment by Madmadness65** [comment]
Yeah, it's due to the font the game uses not supporting Chinese characters, so the fallback font is too big for the textboxes.

**Comment by royess** [comment]
Same problem reported. Should we maybe consider including a new font that better support non-Latin characters?

**Comment by MrWaterT** [comment]
In #737, dynamic font loading is added.  
Just [add font file](https://github.com/MrWaterT/pokerogue/blob/30f4f45cf678268ab08128d1a5119370f1885e79/public/fonts/PokePT_Wansung.ttf) and [write a short reference](https://github.com/pagefaultgames/pokerogue/pull/737/files#diff-60258ac1f55717ab75876c0d8a946e2880a81c964b78b44ba15aa269861de544R82-R84).
(Font file should be size-adjustmented, text size-in-px is not localized for most texts)

How about using this method?
I don't know Chinese, but someone can search font and apply it.. like in #485.
[MuZaiPixel](https://github.com/DWNfonts/MuzaiPixel/blob/main/MZPXorig.ttf), right?

**Comment by davidyan-hub** [comment]
I did not have envirement to do this...
Who can modify the text.ts to change the font-family and font-size for chinese.

Code as below:

fontFamily: localStorage.getItem('prLang')==="zh_CN"?'simhei':'emerald',

styleOptions.fontFamily = localStorage.getItem('prLang')==="zh_CN"?'MuZaiPixel':'pkmnems'; 

and same judgement logic for changing font-size, let the size is smaller.

**Comment by CodeTappert** [comment]
![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/2bedb751-98d6-4cf6-a35f-a4fe4eb0c47a)
![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/63b663f0-0ecd-4f17-ac19-3e183b86dbf8)

I am not even gonna pretend which of those is simplified chinese. But it was fixed for both of them
