### ISSUE TITLE
Reviver seed/Eternatus

### ISSUE THREAD

**Issue by KonstantinosPls** [pagefaultgames/pokerogue#740]
On Endless mode when eternatus(250) kills my shiny Dialga with eternabeam it revives using the reviver seed but the game is instantly stuck there. Not frozen,music and animations still going on. Just cant end the text message. Tried changing the order and moveset for the flow to change but nothing happens.
![IMG_7437](https://github.com/pagefaultgames/pokerogue/assets/157883698/f80489ff-a387-4b0b-8769-01e16286dfa1)

**Comment by flx-sta** [comment]
@KonstantinosPls is this still an issue?

**Comment by flx-sta** [comment]
Stale. 
Feel free to re-open if it's still an issue
