### ISSUE TITLE
IV Screen Softlock after catching second slot pokemon in double battle

### ISSUE THREAD

**Issue by AbhishekRamjit** [pagefaultgames/pokerogue#757]
I ran into a double battle with a (rare) shiny lurantis in the second slot of the opponent team, if I catch it the game will always soft lock before leaving the battle. The iv display never goes away. It doesn't seem to be related to releasing a pokemon to add it to the party, I tried releasing a pokemon before catching the Lurantis and it still gets soft locked. The only thing that seems to work is not adding the Lurantis to my party.

https://github.com/pagefaultgames/pokerogue/assets/30081700/94da2617-9527-4044-8ad7-c253dc23f165

**Comment by j-diefenbach** [comment]
Have you turned consistent animations on?

**Comment by abhl** [comment]
My sprite set was on Mixed animated, I continued the run before your comment and other captures did not have the same issue so maybe it is related to Lurantis specifically.

**Comment by flx-sta** [comment]
Tested on `beta` (a0502fb0b569cc1a8d3ad1f1a9b36d63a4b4e2f3).
No longer able to reproduce it
