### ISSUE TITLE
Proctect not refreshing odds on failure.

### ISSUE THREAD

**Issue by Zilosis** [pagefaultgames/pokerogue#76]
Supposed to work like this:
 Protect (Failed) -> Protect (100%)
But works like this:
 Protect (Fail chance) -> Protect (Fail chance)

It probably only looks at how many times it was used regardless of it it failed or not.

I am unsure if this applies to other moves with similar effects: Endure, Detect, Spiky shield, Baneful bunker, etc.

**Comment by bennybroseph** [comment]
Fixed here https://github.com/pagefaultgames/pokerogue/commit/3a2f364b41caaa16fdc793caec548b41ca10d44f
