### ISSUE TITLE
Ordering of some battle texts is incorrect

### ISSUE THREAD

**Issue by happinyz** [pagefaultgames/pokerogue#788]
"It's super effective" and "A critical hit" texts current appear after a Pokemon has fainted and experience is distributed. These should come before. I think this might also happen with multihit moves ("Hit (x) times!"), but I don't have a demo atm

https://github.com/pagefaultgames/pokerogue/assets/59787978/84e75a8a-7a2c-446c-b68b-042d621845a4

**Comment by j-diefenbach** [comment]
duplicate, see #680 but nice to have some more examples lol
