### ISSUE TITLE
Summary text as images

### ISSUE THREAD

**Issue by rnicar245** [pagefaultgames/pokerogue#789]
Some of the text found in the summary are images. We should probably:
- Remove the text from the images and insert the text programatically
- Or create several images for each lang.

**Comment by CodeTappert** [comment]
I would prefer the first solution. Then it is easier to add new languages

**Comment by Adri1** [comment]
Furthermore, also for any HUD element like "Lv.", "Exp" on the battle screen,and stats names when you toggle current boosts.
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/81a9cbe6-9b6c-4a59-b467-2cacedb670ab)
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/62854128-bca8-49cd-9bbb-db9984c6b6d9)

Personnaly, I would prefer the second solution, create several images for each lang. It would give use a precise control, and prevent any font compatibility issues from a language to another, as currently exists in regular texts with Simplified Chinese.

**Comment by CodeTappert** [comment]
Well look how i changed the font size based on the language here:

https://github.com/pagefaultgames/pokerogue/pull/797

So we can make the "bad" text smaller if it is currently showing chinese

**Comment by Adri1** [comment]
Even without font issues, I personally still think it would be better to edit images.
Visually, it would help to keep the style, and not taking the risk of something visually incoherent and cranky

**Comment by CodeTappert** [comment]
> Even without font issues, I personally still think it would be better to edit images. Visually, it would help to keep the style, and not taking the risk of something visually incoherent and cranky

While this is true. It is a lot more work then to add a new language. 

There are already PRs for Korean, Japanese and Portugese (Brazil). And probably there will be more. 

Also this will increase file size a lot no? If we have every image for every language

**Comment by Adri1** [comment]
Translated elements can just be tiny tiles overlaid on the base HUD, not a whole version of the HUD per language. So highly doubt it would be heavy in any way.
I'm aware it might be more difficult for dev to implement, but on my opinion, it's better to take time to do this than choosing the easy path and ending with something for lower quality

**Comment by CodeTappert** [comment]
Okay. 

I already have made an issue for the type symbols (that creates the images we can later integrate).

https://github.com/pagefaultgames/pokerogue/issues/755

Maybe we can do something similar for the rest?

**Comment by Adri1** [comment]
I admit I'm not quite conviced it would fit for the HUD, what your proposion seem to be is bascally the 1st solution, but glorified. I would have the same issues, like not having the correct font (which might not exists at all in some precise cases) or fonts that do not support non-latin writing systems

**Comment by CodeTappert** [comment]
> I admit I'm not quite conviced it would fit for the HUD, what your proposion seem to be is bascally the 1st solution, but glorified. It would have the same issues, like not having the correct font (which might not exists at all in some precise cases) or fonts that do not support non-latin writing systems
> 
> As an example, in Italian "EXP" will have to be translated as "ESP", and in that case, I can't figure how what you are proposing can work. There is no font for it, so it has to be a handmade image tile ![image](https://private-user-images.githubusercontent.com/2070109/329876315-d82b7ef5-8108-47f3-85e7-56fea8099f00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NDM4MzMsIm5iZiI6MTcxNTU0MzUzMywicGF0aCI6Ii8yMDcwMTA5LzMyOTg3NjMxNS1kODJiN2VmNS04MTA4LTQ3ZjMtODVlNy01NmZlYTgwOTlmMDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTJUMTk1MjEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRkY2UyNzk0YjQ2YjY5NDRiZDZkMmJiMmI4OGU1YTgwNDQ5YmM5ZWY0MjA1YzhlZTdlMDhlYWEyYjU2YzdjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5MFHNpylpjgc7SoP8jamP6amogmrKY84RpBpbxinY48)
> 
> Same for HP, being "PV" in French or "PS" in Spanish, among others ![image](https://private-user-images.githubusercontent.com/2070109/329876476-591d8f8d-927e-4942-bffd-553e0b7d85dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NDM4MzMsIm5iZiI6MTcxNTU0MzUzMywicGF0aCI6Ii8yMDcwMTA5LzMyOTg3NjQ3Ni01OTFkOGY4ZC05MjdlLTQ5NDItYmZmZC01NTNlMGI3ZDg1ZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTJUMTk1MjEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjBlOGE4YWRhMTVhMDdlMzQwNDJhMzIzMjliNDdkNGU3NjUwZTM1ZGY4YmZjYWZiZDMwMmZmMzg4MDgyOWJjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m2eqg5kiZyp-26jQ6alCwzerp8vVY1r1uSfiWC6lGQk)

Sorry to ask this. But did you actually look at the code i have done?

For chinese there is a special font used since the font the western languages use does not have chinese symbols in it. 

The same could be done for japanese, korean etc. 

Also why couldnt the images for EXP and HP be generated that way? I am already giving the function the text it should put in the image. So for italian it can put ESP and for english EXP

**Comment by CodeTappert** [comment]
But if you think we should not use what  i have created its fine. I can close that issue. 

Just wanted to make sure we discussed this

**Comment by Adri1** [comment]
Yes I saw what you did and think it's fantastic, however it wont be fathful if we don't have the precise original font.
Unless Flashfyre allow liberties in the art style, but it's not mine to descide of course, I'm not giving my opinion.

>Also we would need a font to create the images (unless you want to handdraw them pixel by pixel...)`

I love doing this kind of pixel work, so it would not bother me to hand drawn words with letters of 6px tall, but I understand it's not everyone's kink

**Comment by CodeTappert** [comment]
I will close my issue, it is still linked here so if we decide to use it fine. But i dont think it should be its own issue no matter what
