### ISSUE TITLE
Zippy Zap Crash

### ISSUE THREAD

**Issue by Traxaner** [pagefaultgames/pokerogue#792]
The game crashes when trying to teach Kantonian Raichu Zippy Zap, which it can learn by level-up/memory mushroom.
Didn't find any mention of this on GitHub and am not on discord.

**Comment by Admiral-Billy** [comment]
Are you using my app version? There's a similar issue that was fixed in it in newer versions.

**Comment by Traxaner** [comment]
Yes I am, I downloaded it a couple days ago and did the data download for offline play before the coming accross the bug.

**Comment by Admiral-Billy** [comment]
Try downloading the latest version of the app from github, and I think that'll solve your issue!
