### ISSUE TITLE
Protect counter does not reset after throwing a Pokeball

### ISSUE THREAD

**Issue by happinyz** [pagefaultgames/pokerogue#803]
If protect (or Detect/King's shield/etc) is used turn one, and a Pokeball is thrown turn two, then protect has a chance to fail turn three. This should not be the case, as technically the protect counter should reset on turn two.

**Comment by bennybroseph** [comment]
Do you have a source for this? I'd rather not have to boot up Scarlet to check

**Comment by bennybroseph** [comment]
Ain't no way you made me boot up Scarlet just to find out it was false 😢 

https://github.com/pagefaultgames/pokerogue/assets/13838608/18253fd4-9629-495d-b2d1-202231279e33

**Comment by happinyz** [comment]
> Ain't no way you made me boot up Scarlet just to find out it was false 😢
> 
>  0513.1.mp4

oh shit mb I thought I had seen this interaction before, sorry
