### ISSUE TITLE
Multi-Lens ends an attack early if it misses a target during a Double Battle

### ISSUE THREAD

**Issue by Baphvincent** [pagefaultgames/pokerogue#806]
In a double battle, if you use fly on one Pokémon and earthquake on another and the earthquake Pokémon has a multi Lens, the move will only hit once. Not a big deal but was frustrating because it messes up my double battle strategy.

**Comment by Kreeperwide** [comment]
This actually happens with any Multi targeting move with Multi lens
If it misses any target, the extra hits of the multi lens hits do not apply
Happened to me with heat wave missing the second target

**Comment by innerthunder** [comment]
#2648 

Should be fixed now.
