### ISSUE TITLE
`account/info` api call again before the last `account/info` api call return.

### ISSUE THREAD

**Issue by jcc1997** [pagefaultgames/pokerogue#809]
![image](https://github.com/pagefaultgames/pokerogue/assets/17106928/72803d6d-306d-40ab-9b13-6a995ac2f4de)

maybe it should retry after last `account/info` call false return.

**Comment by flx-sta** [comment]
It no longer does that in `beta` (4a04ef50c35b668f21a6fc627d30c064dce933eb)
