### ISSUE TITLE
Using Minimize should cause vulnerability and bypassed accuracy check to various moves 

### ISSUE THREAD

**Issue by LaukkaE** [pagefaultgames/pokerogue#814]
BattlerTag "MINIMIZED" or similar should be added to track if a pokemon has used minimize, and then following moves should have double damage applied & accuracy check bypassed (except if the opposing pokemon is semi-invunerable).
![minimize](https://github.com/pagefaultgames/pokerogue/assets/73663099/1d01c461-e4c9-44ef-9e85-b41969c90f8a)

**Comment by andrew-wilcox** [comment]
Looking at this as a first contribution

**Comment by andrew-wilcox** [comment]
https://github.com/pagefaultgames/pokerogue/pull/824

this is handled once this is merged
