### ISSUE TITLE
Language Select box going off limits

### ISSUE THREAD

**Issue by Adri1** [pagefaultgames/pokerogue#819]
With the newly added Brazilian Portuguese, the language selection box starts to go out of the limits of the screen
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/aac40a7d-0c55-499e-9bbb-50910172e31f)

If we add one more language, the top of that list will go out of sight, like that when for example I include the Japanese locale I created:
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/2890b20e-e0ad-4bd9-bcbe-3460ecbc0261)

**Comment by CodeTappert** [comment]
Maybe add scrolling? Like there already is for the main settings?
