### ISSUE TITLE
Champion doesn't have a female alternative in trainer.ts

### ISSUE THREAD

**Issue by josericardo-fo** [pagefaultgames/pokerogue#820]
In portuguese, for example, champion has a male and female versions. "Campeão" for men and "Campeã" for women.

**Comment by Flashfyre** [comment]
We might need to start setting the 'female' flag on gym leaders, elites, and champions. Currently the flag is only used when the trainer can be either, but this can be used for gendered localization.

**Comment by Adri1** [comment]
It would be nice indeed to add this option and to all trainer classes not matter what. Because never know by advance the specs of potential future languages that might have elements with a gendered translation where other don't.

**Comment by josericardo-fo** [comment]
There are some trainers that have only one gender. For example, Hoopster is a Gen V trainer class that can only be male, and Nurse is female. I don't know if the sprites used in the game are from official games, if it is the case, there isn't need for a female and female counterpart of the classes I talked about.

**Comment by Adri1** [comment]
Yes you are right to make that precision indeed

**Comment by Eridanus91** [comment]
> It would be nice indeed to add this flag and to all trainer classes not matter what, even to the Elite Four just by precaution. Because you never know by advance the specs of potential future languages that might have elements with a gendered translation where other don't.

I don't think any of the big eight should have big problems, but if we do continue with ones beyond that, like with Brazilian Portuguese, some European languages might have to might have to get a bit unusual with wording (for example Slavic languages in past tense inflect verbs based on grammatical gender, which could be made irrelevant by using e.g. present tense, but would that work everywhere?) ~~inflection, bane of translation~~.
