### ISSUE TITLE
Offline mode can't complete wave 200 classic

### ISSUE THREAD

**Issue by Shayrai** [pagefaultgames/pokerogue#828]
I see a supposed fix was done in #799 but was moved to #808 but both have been closed. Is it just gonna be impossible for a while ( or ever ) to unlock endless on offline mode or is there plans for the fix to be merged soon? PRs were unclear and don't want the bug lost

**Comment by Nexllon** [comment]
I'm working on it!

**Comment by Shayrai** [comment]
Awesome thank you so much @Nexllon :D
