### ISSUE TITLE
Poison ticks at start of fight

### ISSUE THREAD

**Issue by CarsonVB** [pagefaultgames/pokerogue#830]
No moves have been made yet in this battle, but the poison from toxic spikes ticked.
I cannot further debug the issue due to https://github.com/pagefaultgames/pokerogue/issues/684
I assume the way the game handles turns makes the "1st" turn take place during the swap prompt, so the end of turn hook is called, perhaps other hazards tick as well?
![image](https://github.com/pagefaultgames/pokerogue/assets/59876651/0bcdb4da-b61c-402d-8b15-12ce4bca13a2)

**Comment by flx-sta** [comment]
Apparently fixed with #1844
