### ISSUE TITLE
Game freezes after status affect applied on U-Turn

### ISSUE THREAD

**Issue by kalebruscitti** [pagefaultgames/pokerogue#838]
Hi, I just encounted the following bug:

I had a flame body Talonflame in against a Jumpluff. The Jumpluff used U-Turn and thus fled the battle, however it got burned by flame body. Then the game simply hanged there. I waited a little more than a minute and nothing changed.

I am running the local copy, V1.0.4.

**Comment by flx-sta** [comment]
No longer crashes on `beta` (4a04ef50c35b668f21a6fc627d30c064dce933eb)
