### ISSUE TITLE
Sinistea (antique form) can't evolve with chipped pot ("it will have no effect")

### ISSUE THREAD

**Issue by j-diefenbach** [pagefaultgames/pokerogue#839]
Related to #636 as evolution items now check formIndex however sinistea antique form is index 1. The chipped pot can still spawn however attempting to use it gives the 'but it will have no effect' message
Cracked pot working as intended (using overrides to have phony form):

https://github.com/pagefaultgames/pokerogue/assets/105332964/3ada93bb-3721-47ef-a1ea-3baa3982a5c4

Using chipped pot on antique form which should prompt evolution (overriden to have antique form):

https://github.com/pagefaultgames/pokerogue/assets/105332964/26590c22-b675-44e9-9178-906085ac9ce8

I imagine this also effects poltchageist and its counterfeit/artisan forms

**Comment by bennybroseph** [comment]
Good catch. Not something to revert the commit over though as this edge case is not as bad as what the commit fixed. If you already have a solution in mind for this, I'm open to suggestions.

**Comment by j-diefenbach** [comment]
Yeah i think using pokemon.GetFormKey() !== SpeciesFormKey.GIGANTAMAX will cover literally all the possibly cases where evo items can be used on non-base-form pokemon but we could also throw on the rest of the SpeciesFormKey cases
