### ISSUE TITLE
No Starter Points

### ISSUE THREAD

**Issue by giantratdatmakesalldarulez** [pagefaultgames/pokerogue#846]
I had just finished a round that got me to wave 70 something when I finally got wiped. I went to go start a new round but for some reason couldn't interact with the pokemon. I couldn't start a new game, but it also wouldn't even let me make any changes to the pokemon at all. I'm completely locked from doing basically anything in the game
![image_2024-05-13_194414572](https://github.com/pagefaultgames/pokerogue/assets/114633498/e55eaf3a-80be-4ac6-9256-f82ee8c4fce0)

**Comment by giantratdatmakesalldarulez** [comment]
I was able to start a new round on mobile so hopefully the problem is fixed on my end

**Comment by giantratdatmakesalldarulez** [comment]
Ok finished that round and I still can't interact with my pokemon on desktop. I can interact with them on mobile but not on desktop

**Comment by TempsRay** [comment]
Can you move the cursors over the pokemon? Have you tried pressing Z/spacebar to select them instead of enter?

**Comment by hassanoza22** [comment]
Try to open the game in incognito mode (so it redownloads your data from the server) and see if it works there. Might be a corrupted localstorage.

**Comment by giantratdatmakesalldarulez** [comment]
I tried doing that and I still can't interact with the pokemon even in the incognito tab. I even tried on a new browser. So far it doesn't work anywhere except on mobile

**Comment by giantratdatmakesalldarulez** [comment]
I tried doing that and I still can't interact with the pokemon even in the incognito tab. I even tried on a new browser. So far it doesn't work anywhere except on mobile. I'm able to cycle natures and abilities but that's it

**Comment by Tempo-anon** [comment]
Closing because it's been 3 weeks. Let us know if issue persists
