### ISSUE TITLE
Visual bug: ditto type doesn't update with transformation immediately (takes one turn to update)

### ISSUE THREAD

**Issue by j-diefenbach** [pagefaultgames/pokerogue#847]
Opposing ditto still shows normal type after transforming into ghost type (sinistea), ghost type move is super effective after transformation so type change still works as normal.
This also occurs on player's own ditto.
Wild ditto not updating immediately after transformation:
![ScreenRecording2024-05-14at12 34 12-ezgif com-video-to-gif-converter](https://github.com/pagefaultgames/pokerogue/assets/105332964/a6d74e84-3b39-46bd-a818-a7a185750c32)

Player's ditto behaviour and in party / after switching:
![ScreenRecording2024-05-14at12 36 52-ezgif com-video-to-gif-converter](https://github.com/pagefaultgames/pokerogue/assets/105332964/2e6d0ded-268a-4149-823f-3018e3cb679f)
![ScreenRecording2024-05-14at12 38 26-ezgif com-video-to-gif-converter (1)](https://github.com/pagefaultgames/pokerogue/assets/105332964/c97a1818-9780-4126-981d-e2963261f454)

It seems to update after one move so this may just be an enhancement point rather than an issue. The rest of ditto's behaviour / display seems as normal

**Comment by Snailman11** [comment]
Grand Transform Aggregated Issues (Fusion Transform Softlock, Delayed Visual, Form Not Saved)
https://discord.com/channels/1125469663833370665/1267976989957029900/1267976989957029900
