### ISSUE TITLE
Screen is whiter when press on start 

### ISSUE THREAD

**Issue by maximehuran** [pagefaultgames/pokerogue#854]
https://private-user-images.githubusercontent.com/11380627/330327265-a8656ebf-c906-4f01-9523-22cf7b7abc0c.mov?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODMwMDMsIm5iZiI6MTcxNTY4MjcwMywicGF0aCI6Ii8xMTM4MDYyNy8zMzAzMjcyNjUtYTg2NTZlYmYtYzkwNi00ZjAxLTk1MjMtMjJjZjdiN2FiYzBjLm1vdj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEwMzE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNDZjYWI2NWZjYThmNTViYWI3YmRjMmE3YTliMGEwYmQ5OGM3NjI3MzgwNmEzM2MyOGUwMjc5YjkxMTZlZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m_W_Y_dEtdkt_qfE6JhaUZ2EzmHZq1d5-WmXsHnWbRY

When I launch the website from Ayn Odin 2, then I press the start button which opens the menu, the app is whiter.
It looks like a focus or something else is set and change the contrast of the image. Sometimes in other context it is darker.

See also : https://github.com/Admiral-Billy/Pokerogue-App/issues/34

**Comment by maximehuran** [comment]
I had made the same behaviour tonight on Firefox only. Not in chrome.

**Comment by flx-sta** [comment]
@maximehuran Can you still reproduce this?
Can you also add a `(Steam Deck)` to the title?
