### ISSUE TITLE
Ingrain does not work with a ghost type pokemon, and Infestation does not work against ghost type pokemon

### ISSUE THREAD

**Issue by LaukkaE** [pagefaultgames/pokerogue#856]
IngrainTag extends TrappedTag, and TrappedTag cannot be applied to a ghost type, so Ingrain will not get applied if ghost-type (Phantump, Trevenant or any other ghost type, fused or not) tries to use it.

In addition, Infestation cannot be applied to a ghost type pokemon, meaning they will not take residual damage.

**Comment by Xavion3** [comment]
I'm like 99% sure that PR doesn't actually fix this. It lets phantump and trevenant use it, but it looks like it does that by just letting them be trapped by anything, and also doesn't do anything if a ghost type other than those two uses ingrain.

Also looking at this, does ingrain actually provide the anti-forced switch effect right now?

**Comment by Tempo-anon** [comment]
Fixed for real in https://github.com/pagefaultgames/pokerogue/pull/1030
