### ISSUE TITLE
It seems like Outrage + Multihit keeps going on and on?

### ISSUE THREAD

**Issue by HighMans** [pagefaultgames/pokerogue#859]
I count 6 instances on this fight of outrage being used.

https://github.com/pagefaultgames/pokerogue/assets/42877729/c1a3d5be-bd8d-49c0-881c-f270765f7cb8

**Comment by HighMans** [comment]
Here it's happening 9x in a row.

https://github.com/pagefaultgames/pokerogue/assets/42877729/94e770a7-a1a9-461c-ac5f-5f59f9e0ad46

**Comment by innerthunder** [comment]
#2662 

Should be fixed now.

**Comment by flx-sta** [comment]
@innerthunder this is on you
