### ISSUE TITLE
[Suggestion] Delta-esque touch controls, the current ones are difficult to use

### ISSUE THREAD

**Issue by ch5rus** [pagefaultgames/pokerogue#862]
For example:
![image](https://github.com/pagefaultgames/pokerogue/assets/159018522/955c5dee-4bfa-4480-8336-452e4ac78c83)
![image](https://github.com/pagefaultgames/pokerogue/assets/159018522/01c83f0a-c461-436c-8681-5b261bfdf874)
Not these exact ones, but could be nice for mobile players.

**Comment by bennybroseph** [comment]
I would agree that something like this could be cool for aesthetics, but to say that this would make them function any differently is a reach. It's just a png overlay.

**Comment by ch5rus** [comment]
Yeah, exactly. It would mostly be placebo, but the current controls are quite small, so it could help.

**Comment by torranx** [comment]
Closing this, the customization issue should be covered by https://github.com/pagefaultgames/pokerogue/pull/3256. With regards to aesthetics, I don't think there are plans.
