### ISSUE TITLE
No CORS Header present on api.pokerogue to pokerogue.net?

### ISSUE THREAD

**Issue by karl-police** [pagefaultgames/pokerogue#878]
```
Access to fetch at 'https://api.pokerogue.net/account/info' from origin 'https://pokerogue.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

well I mean...

**Comment by danieland** [comment]
I'm 99% sure this is not a CORS issue, when the API gets beaten down with loads of traffic, CloudFlare shows an error page (maybe 522 I forget) - and that error page doesn't have pokerogue.net allowed for CORS (of course) - only way around this I see (other than server stability down the line) is to add some sort of retry around this call, preferably with linear or exponential backoff, but as mentioned - almost certain it's not a CORS issue
