### ISSUE TITLE
[Suggestion] Add a “black border” achievement/reward

### ISSUE THREAD

**Issue by FuecocoBoi09** [pagefaultgames/pokerogue#880]
(Terminology taken from BTD6 Community) Add a reward or achievement for completing Classic Mode without having to retry last battle or save scum. 
Proof of change in-game: https://www.youtube.com/watch?v=i-qB0PF8clE (Video by ISAB)

**Comment by j-diefenbach** [comment]
Might be a bit hard to implement / check properly since you could always just refresh and it will restart the battle
