### ISSUE TITLE
Game freezing on clear

### ISSUE THREAD

**Issue by Boongalu** [pagefaultgames/pokerogue#889]
I have reloaded the save various times to go through different randomization paths to avoid the freeze and nothing I have done works. Everytime I beat Eternatus the game does not move forward or register a clear in offline mode.

**Comment by Nexllon** [comment]
It's a recently fixed issue, you gotta update your game

**Comment by Boongalu** [comment]
Tried to update it yesterday for the fix but didn't work. Reloaded a few times after updating and it worked now. Thank you.
