### ISSUE TITLE
Rest failing when used while paralyzed

### ISSUE THREAD

**Issue by Korolebi** [pagefaultgames/pokerogue#89]
Move _Rest_ does not work while paralyzed

**Steps to replicate**:
1. Pokemon who knows rest is paralyzed and is not at 100% health
2. Attempt to use rest

**Expected result**:
Health is set to 100% and Status condition is changed from _PAR_ to _SLP_
^This is how the move works in the traditional games

**Actual result**:
No heal or status change and "But it failed!" dialogue appears

**Reproducibility**:
100%

**Severity**: 
Minor/Edge Case (Possibly slightly more severe if this behavior occurs with other statuses, but can only confirm for Paralysis at this time)

------------------------------------------------------------

Information on Game State Below at the time of report

------------------------------------------------------------

Progress: 
Wave 80, Classic Mode, Lake Biome (Noticed the same behavior in another biome too but I can't recall which)

Items owned during battle:
Map, 4x Super EXP Charm, 3x EXP All, 8x EXP Charm, Golden Pokeball, Mega Bracelet, Lock Capsule, 3x Super Lure

Mon used: 
Snorlax, Lvl 64, Impish Nature, Thick Fat, female

Moveset: 
Body Slam, Covet, Sleep Talk, Rest

Held Items: 
Reviver Seed, Soul Dew, Silk Scarf, Apicot Berry, Leppa Berry, 2x Sitrus Berry

**Comment by Korolebi** [comment]
Can now confirm that it also fails while burned

**Comment by Flashfyre** [comment]
This should be fixed, can you confirm?

**Comment by Korolebi** [comment]
Can confirm it seems to work as intended now
