### ISSUE TITLE
game freezes while opening egg

### ISSUE THREAD

**Issue by yawai1** [pagefaultgames/pokerogue#891]
in the middle of egg opening animation my game always freezes I have tried many things reload saves, did different runs, restarted browser, restarted computer but the exact same egg always freezes the game. 

I have many eggs that I open before the egg that freezes my game, many opening animations before, but every time I get too said egg my game will always freeze.

I open over ten eggs before just fine until I end up at the exact same egg that wont open.

the game will always load me before I opened any eggs so after one battle I will always start opening eggs until I end up at the frozen egg.

I don't know if this is a problem on my side as I haven't seen anyone talk about it so I have waited a day too see maybe if something might have changed but it still happens and freezes.

**Comment by Umberwolf** [comment]
Same here. Been trying to open an egg too, but the game keeps freezing. If it helps the browser I've been using is Firefox. Either way hopes this problem gets resolved soon.

**Comment by TempsRay** [comment]
Did you try changing your sprite animation settings? Open up the console with F12 and post the console logs

**Comment by PLMMJ-FH** [comment]
Haven't run into this issue but my best guess is that the data for the mon in the egg somehow corrupted, and because of the game's anti-save scum, it still tries to load the corrupt data and freezes again.

**Comment by TempsRay** [comment]
> Haven't run into this issue but my best guess is that the data for the mon in the egg somehow corrupted, and because of the game's anti-save scum, it still tries to load the corrupt data and freezes again.

That's not how any of that works. Please don't spread misinformation if you aren't sure about something.

**Comment by Umberwolf** [comment]
@TempsRay Turns out it was the sprite animation. Though still unsure why turning off the sprite animations had it working or why the animated sprites would cause the freeze.

**Comment by yawai1** [comment]
this is correct when I reload then change my sprites from mixed animated to consistent and opened my eggs again it suddenly wouldn't freeze anymore, weird.

but either way, thank you all for the helps   :D
