### ISSUE TITLE
Candies can break the level cap

### ISSUE THREAD

**Issue by PLMMJ-FH** [pagefaultgames/pokerogue#893]
Using a Rare or Rarer Candy can break the level cap. I thought it was just a bug with stopping their use at max level not working with Rarer Candies, but my team was all maxed and I used a Rare on my Staraptor and it leveled past the cap too.
![UsingRarerCandyAtLevelCapBreaksPokerogue](https://github.com/pagefaultgames/pokerogue/assets/159862724/40dcd8b4-78b5-496a-8d8d-642e57528a36)
![RegCandiesDoItToo](https://github.com/pagefaultgames/pokerogue/assets/159862724/21b08f69-a387-4b2c-bbaa-0134c7883334)

I don't know whether this is a bug or a feature, it doesn't feel to me like a bug because how could you miss this, but also it does because it breaks the level cap.

**Comment by Flashfyre** [comment]
It's not a bug, it's a feature
