### ISSUE TITLE
Gym leader mon has an empty item slot?

### ISSUE THREAD

**Issue by PLMMJ-FH** [pagefaultgames/pokerogue#896]
Got to the wave 110 gym leader, Grant's lead Armaldo seemingly has an empty item slot. Anyone explain?
![armaldoberry](https://github.com/pagefaultgames/pokerogue/assets/159862724/0fd516bf-3194-4cb8-b70b-f6a0fe7a82f9)

**Comment by TempsRay** [comment]
From left to right: Leppa berry, Lansat berry, Petaya berry, vitamin, Apicot berry

**Comment by PLMMJ-FH** [comment]
I just got an Apicot berry in the shop, it just blended in
