### ISSUE TITLE
Suggestion: Make higher tier Pokeballs more available late game.

### ISSUE THREAD

**Issue by PLMMJ-FH** [pagefaultgames/pokerogue#899]
By "late game" I mean in the late 110's level area. I had a level 117 mon against a level 102 Lokix that was on practically zero health, and it Would. Not. Stay. In. My. Ultra Balls. It made me burn through all my balls and still couldn't catch it. I feel this would be much easier with Rogue Balls being more accessible as I did not get offered a single one in this hours long (ongoing) playthrough.

**Comment by Smewkie** [comment]
Just want to state that this game does not feature the base game mechanic of catch rate being modified as a Pokemon gets higher in levels, as it would make catching things past level 100 ridiculous.

**Comment by PLMMJ-FH** [comment]
OK this is a real problem. I had a Gyarados many levels lower, poisoned, on its last sliver of health. Not even one shake with an Ultra Ball. Late game catching is a bit odd dudes.

**Comment by Tempo-anon** [comment]
This is a balance suggestion that should be sent to the balance team
