### ISSUE TITLE
Snow Storm causes HP to go up? Min HP over Max HP bug

### ISSUE THREAD

**Issue by karl-police** [pagefaultgames/pokerogue#909]
Not sure how this happened.

![image](https://github.com/pagefaultgames/pokerogue/assets/12023782/e2f24980-1278-4c81-8a78-9f13dd46d81c)

Thing is, after this, something happened, the HP was still over the Max HP after that ``/`` in ``min / max`` formatted display.

So this still persisted but the value wasn't ``104 / 92`` anymore, it turned to ``99 / 92``.

**Comment by karl-police** [comment]
It's caused by snow storm.

**Comment by TempsRay** [comment]
Caused by a [commit that got reverted](https://github.com/pagefaultgames/pokerogue/commit/3c8d919ef8e1e69a063710e4d98cb27a0350d208)
