### ISSUE TITLE
Fury Swipes' multiple hit animations still play out if the opponent is immune

### ISSUE THREAD

**Issue by PLMMJ-FH** [pagefaultgames/pokerogue#921]
So this Linoone got a 5 hit Fury Swipes on my Gholdengo, and all 5 swiping animations played even though Gholdengo is immune. No text boxes popped up other than at the end "But it doesn't affect Gholdengo..." and "Hit 5 time(s)!" in that orderNot sure if this works for other moves.

**Comment by MarshRey** [comment]
In original Pokemon games the fury swipes animation would not play when hitting a Pokemon that is immune. But in Pokerogue all animation play through regardless of immunities so this is working as intended. 

You can see how this works with shadow ball vs normal types. In normal pokemon it would just tell the player that this move doesn't affect that pokemon but in Pokerogue the animation still plays and then delivers the message that the move does not affect the opposing pokemon.
