### ISSUE TITLE
Zigzagoon stolen item.

### ISSUE THREAD

**Issue by Zabosch** [pagefaultgames/pokerogue#922]
Is it intended that stolen items doesnt return after winning the battle?

**Comment by Madmadness65** [comment]
Yes, it is intentional that items stolen by enemy Pokémon through Thief/Covet, Magician, and Pickpocket can be permanently lost, just the same as stealing from enemy Pokémon in the same ways is permanent too.

**Comment by Zabosch** [comment]
Thanks!
