### ISSUE TITLE
The RNG with Dynamic Punch confusion is broken

### ISSUE THREAD

**Issue by PLMMJ-FH** [pagefaultgames/pokerogue#925]
So every time I have run into a Dynamic Punch using mon, whether that be Chuck's Poliwrath or a boss Machamp (that's not all of them), it hits every single time, and I hit myself in confusion every. single. time. The accuracy thing with Machamp specifically could be No Guard, but for all the other mons, and the confusion hax, leads me to believe that RNG is broken

**Comment by j-diefenbach** [comment]
I had a similar issue with aerial ace, every single hit about 6 or 7 caused a flinch, wasn't able to confirm further because PP ran out. I have had it not flinch before but during this battle every time i used it I got a flinch, even if alternating between other moves.

**Comment by Tempo-anon** [comment]
Confusion was indeed bugged (2/3 instead of 1/3) but there should be nothing wrong with dynamic punch
