### ISSUE TITLE
Skorupi's legs clip out of view on the egg hatched screen

### ISSUE THREAD

**Issue by PLMMJ-FH** [pagefaultgames/pokerogue#926]
I hatched a Skorupi and in some frames of the animation, its leg tips become invisible.
![Skorupispriteclip](https://github.com/pagefaultgames/pokerogue/assets/159862724/f543167b-6248-4381-8499-0266f54c196b)

**Comment by innerthunder** [comment]
@pom-eranian is this still a thing

**Comment by pom-eranian** [comment]
Yes, I'm adding the fix to my next PR.
