### ISSUE TITLE
Arena hazards are incorrectly ignored by the Pokemon that set them

### ISSUE THREAD

**Issue by Stagfox** [pagefaultgames/pokerogue#935]
Not sure if it's intended but arena trap doesn't work against teleport, Skorupi also not absorbing poison spikes.

Edit: Block also does not stop teleport.

**Comment by PLMMJ-FH** [comment]
What Pokemon is using Teleport? If it's a Ghost type, or if it's not grounded, i.e. 

- Flying type
- Levitate
- Air Balloon (IDT this is in the game yet)
- Telekinesis or Magnet Rise

It will not be Arena Trapped.
If Skorupi is any of these things either, the spikes will not be there.

**Comment by Stagfox** [comment]
Sorry I should have clarified these are two separate instances, Abra's are teleporting away from Trapinch w/ arena trap and stonejourner with block, Abra was grounded. The Skorupi situation was Opposing Skorupi toxic spiked, I caught and switched to him and he would not absorb the toxic spikes no matter how many times I would switch back out to him.

**Comment by Snailman11** [comment]
https://github.com/pagefaultgames/pokerogue/blob/39abac65be26c2004ea1ca9a686cc8d7b35efb65/src/data/arena-tag.ts#L1208

Link to Discord Post (Toxic Spikes not being Absorbed)
https://discord.com/channels/1125469663833370665/1267643732878954538

Catch and Switch in

https://github.com/user-attachments/assets/e113b7be-545e-47bf-87c7-fdbad337faf1

Switch in after

https://github.com/user-attachments/assets/466fd0c9-f741-4c9f-a116-7423818a8561

-This occurs whenever the source of Toxic Spikes is switched in on a Toxic Spikes Pile that it has started.
I believe that this must mean that the source is checked , and then  Toxic Spikes are not removed, if the sourceid matches the mon switching in.

**Comment by Snailman11** [comment]
Probably all Arena Hazards

https://github.com/user-attachments/assets/7c08e910-b315-40a2-b5bf-3872569c02b6
