### ISSUE TITLE
E-max Eternatus perma-frozen 

### ISSUE THREAD

**Issue by MatsushimaDesu** [pagefaultgames/pokerogue#939]
My lapras' ice beam froze it on place, and never managed to unfreeze (maybe has something to do with lum berry/corviknight's unnerve interaction). This went on for ~20 turns.

![image](https://github.com/pagefaultgames/pokerogue/assets/63380960/c39d3c57-02e8-40ce-b7a7-c639bf7db1e5)

**Comment by flx-sta** [comment]
Tested on `beta` (4a04ef50c35b668f21a6fc627d30c064dce933eb) and it's still present.
It doesn't seem to be connected to the berry and `UNNERVE` ability.

Eternatus (without E-MAX) suffers from the same issue

**Comment by Snailman11** [comment]
Removing Flamethrower and it dethaws post Early August 2024 update
