### ISSUE TITLE
Effect Spore + multi hitting moves

### ISSUE THREAD

**Issue by hightowernl** [pagefaultgames/pokerogue#950]
Multi hitting moves continue to hit even if you are put to sleep because of Effect Spore, sleep walking and muscle memory I guess.

But in the regular games you stop everything and don't finish the sequence.

**Comment by DustinLin** [comment]
Able to reproduce on `main`

https://github.com/pagefaultgames/pokerogue/assets/39450497/920c5aa3-9418-47a6-b43f-532825e56e86

**Comment by DustinLin** [comment]
i'll try to take a look at this, but hopefully after PR #783 and #924 are merged

**Comment by DustinLin** [comment]
testing on `beta` this seems to have been fixed, issue should be closed


https://github.com/user-attachments/assets/08160d4d-c60f-4f69-bea6-bc385f3e150e
