### ISSUE TITLE
Blastoise multiple forms softlock

### ISSUE THREAD

**Issue by ClownDoll** [pagefaultgames/pokerogue#957]
I had a Blastoise I gave a max mushroom, and it g-maxed. Later, I gave it a Blastoisinite. I then deactivated the max mushroom, and the Blastoise reverted to its normal form. When I exited to title screen and then attempted to continue the run, it is softlocked on the transformation screen, as if the game realized it should mega evolve the Blastoise. However, does not complete the transformation and just shows the Blastoise.

**Comment by ClownDoll** [comment]
Also, I've never used this site before and know nothing about coding, so sorry if I've done something improperly here.

**Comment by dillonkkoval** [comment]
I also ran into this issue, it looks like there are missing animation files for blastoise variant shinies: 
![blastoise-variant-img-missing](https://github.com/pagefaultgames/pokerogue/assets/16768505/d3ca4b7c-9c73-4cf9-b7e6-fde358f4ae2e)

**Comment by Tempo-anon** [comment]
Blastoise sprite issues have been resolved
