### ISSUE TITLE
Add trainer class localizations for doubles

### ISSUE THREAD

**Issue by CodeTappert** [pagefaultgames/pokerogue#959]
We have already added them for single trainers here:
https://github.com/pagefaultgames/pokerogue/issues/745

But while playing i found that the doubles have their own trainer class names (i thought they just use the individual ones)...

Well i will add this

**Comment by CodeTappert** [comment]
https://cdn.discordapp.com/attachments/1176874654015684739/1240597901688836127/image.png?ex=66472454&is=6645d2d4&hm=936a006b3ad70c769e4dc2a2125fd5ded9fae623d13110db4e45842c923092f8&

**Comment by CodeTappert** [comment]
![image](https://github.com/pagefaultgames/pokerogue/assets/38758606/343c8311-f5bd-4b54-81c0-eae22879609c)

**Comment by CodeTappert** [comment]
This is the problem right now. It just takes he placeholder, removes spaces and replaces them with _ and makes all lowercase. 

Then it looks like the above (because it can not find a trainerclass for this)

**Comment by Adri1** [comment]
While we are back on this topic, I noticed some translations that are ignored by the game
For example, I created translations for the French names of the Rivals, but they are ignored by the game and keep displaying the English name instead.
