### ISSUE TITLE
Weather sandstrom damages localization does not work

### ISSUE THREAD

**Issue by Adri1** [pagefaultgames/pokerogue#972]
The message about damages made by the sandstorm seem to not work in localized languages, and is by default replaced by the English version.
Checking if is it does the same with the hail could also be nice

https://github.com/pagefaultgames/pokerogue/blob/ff086ca4926bb090ac54a043ec02faddfbce753a/src/locales/fr/weather.ts#L18C1-L18C110

**Comment by CodeTappert** [comment]
Fixed in https://github.com/pagefaultgames/pokerogue/pull/1017
