### ISSUE TITLE
Stats screen Specials and Speed are sticking out

### ISSUE THREAD

**Issue by Adri1** [pagefaultgames/pokerogue#973]
In the summary, the stats on the right column (Sp Atk, Sp Def, Speed) are not centered, causing the text to stick out (or about to stick out in other languages) to the left while leaving too much room on the right
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/382f8e6a-dfb3-4d91-bf6e-72cda504cdb5)

And in legacy UI, it can be even worse, because too narrow :
![image](https://github.com/pagefaultgames/pokerogue/assets/2070109/d9d7faad-d9dd-4c2d-b724-405c521f3bf1)

**Comment by josericardo-fo** [comment]
We have the same problem with ptBR

**Comment by Dakurei** [comment]
Fixed in https://github.com/pagefaultgames/pokerogue/commit/56acd164569f42f49103a6b65f2e883a5f190b19
