### ISSUE TITLE
Ace Trainer Female Localization does not work

### ISSUE THREAD

**Issue by Adri1** [pagefaultgames/pokerogue#974]
The male version is shown instead
(@CodeTappert , allow me to poke you)

https://github.com/pagefaultgames/pokerogue/blob/ff086ca4926bb090ac54a043ec02faddfbce753a/src/locales/fr/trainers.ts#L18

**Comment by CodeTappert** [comment]
This is a fundemental problem in the code. 
The female version is not used because it is never told to do so. I fixed it for the Ace Trainer Class now but maybe you should have a look and see where it is also missing

**Comment by CodeTappert** [comment]
This was fixed
