### ISSUE TITLE
Second Pokémon in a splice doesn't get ribbon for classic completion

### ISSUE THREAD

**Issue by travbp** [pagefaultgames/pokerogue#985]
Just finished a run where I had two splice mons, one Mantine/Garchomp and one Gholdengo/Hydreigon.

Prevolutions for Garchomp and Hydreigon didn't get ribbons after beating classic, but Gholdengo got one (Mantine already has one).

**Comment by Flashfyre** [comment]
Not a bug, this is just how it works. If the reward for something splice-based can't be evenly split, it only counts for the main component.
