### ISSUE TITLE
Body Slam does not ignore evasion for minimize

### ISSUE THREAD

**Issue by DustinLin** [pagefaultgames/pokerogue#988]
As per [bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Body_Slam_(move))

Gen VI onward: "If the target has used [Minimize](https://bulbapedia.bulbagarden.net/wiki/Minimize_(move)), Body Slam now deals double its regular damage and bypasses [accuracy](https://bulbapedia.bulbagarden.net/wiki/Stat#Accuracy) checks to always hit, unless the target is in the [semi-invulnerable turn](https://bulbapedia.bulbagarden.net/wiki/Semi-invulnerable_turn) of a move such as [Dig](https://bulbapedia.bulbagarden.net/wiki/Dig_(move)) or [Fly](https://bulbapedia.bulbagarden.net/wiki/Fly_(move))."

-----
Note that in the clip I already used OS to be able to hit 

https://github.com/pagefaultgames/pokerogue/assets/39450497/4d6adfa4-097e-418d-b076-134dcb9a96cd

**Comment by TempsRay** [comment]
Hm. Interesting. Body slam should have the requisite tag as implemented [here](https://github.com/pagefaultgames/pokerogue/pull/824)

**Comment by LaukkaE** [comment]
Odor Sleuth is (N) move, and currently does nothing. (No idea why it doesnt show up as such). Thus you are missing because you are trying to hit a ghost type with a normal move.
Odor Sleuth will be implemented in #812

**Comment by LaukkaE** [comment]
I think what happened here is that you were testing on branch #812 (The Odor sleuth implementation) before it was merged with the recent changes to minimize. (#824)

**Comment by DustinLin** [comment]
yeah i think yall are right, thanks for pointing it out!
