### ISSUE TITLE
Berry pouch description (25%) is incongruous with code functionality (33%)

### ISSUE THREAD

**Issue by TempsRay** [pagefaultgames/pokerogue#992]
The description says it has an additive 25% chance to proc but the actual code has it as 33%. The max stack for this item is 3 so with the max stack (3) it has a 100% of activating. The real question is whether the description should be the correct one or the implementation

**Comment by shayebeadling** [comment]
yup judging by the code, you're right. If I had to guess, it used to stack to 4 so the description was correct at some point, then the max stack was dropped to 3 without checking how the chance was being calculated.

**Comment by TempsRay** [comment]
Updated desc to 33%
