### ISSUE TITLE
Download does not account for vitamins

### ISSUE THREAD

**Issue by Tempo-anon** [pagefaultgames/pokerogue#993]
![](https://cdn.discordapp.com/attachments/1240694435952463932/1240694436413968454/image.png?ex=66477e3c&is=66462cbc&hm=afc49657adbaabe1a3b75208aeacf7d83728e3f26e25626421a94b0bb67309a0&) ![](https://media.discordapp.net/attachments/1240694435952463932/1240694436929994822/image.png?ex=66477e3c&is=66462cbc&hm=7cd99f077fea83f224bc38e1e9aa0f6bedeef01edd8dd6e8d7540f74133fe830&=&format=webp&quality=lossless&width=1080&height=585)

**Comment by TempsRay** [comment]
not merged in yet

**Comment by EvasiveAce** [comment]
Issue can be closed now.
